# 将User_FeatureVectors聚成40类

### 读取所有用户向量

In [17]:
import pandas as pd
import numpy as np
# Path of the file to read
User_filepath = "lastfm_User_Glovemean_FeatureVectors.csv"#可以选择
FeatureVectors = {}
Userfeatures_noid = []
User_id = []
data = pd.read_csv(User_filepath, header=0,sep=' ')
data_user = data.iloc[:,0]
User_id = data_user
data_feature = data.iloc[:,1:]
data_feature
# with open(User_filepath, "r") as f:
#     # f.readline() # skip the header
#     for line in f:
#         line = line.split("\t")
#         vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
#         FeatureVectors[int(line[0])] = np.array(vec).astype(float)
#         Userfeatures_noid.append(np.array(vec).astype(float))
#         User_id.append(int(line[0]))
# Userfeatures_noid = pd.DataFrame(Userfeatures_noid)
# Userfeatures_noid

,u0,u1,u2,u3,u4,u5,u6,u7,u8,u9,...,u15,u16,u17,u18,u19,u20,u21,u22,u23,u24
0,0.146516,-0.035242,-0.131514,0.083956,0.086915,0.030891,0.187623,-0.029845,0.020943,-0.094302,...,0.055610,0.026923,-0.078993,0.021650,-0.031373,0.022851,0.047545,-0.056427,0.031172,0.005416
1,0.232363,-0.081555,-0.248638,0.027093,0.095547,-0.101298,-0.084566,-0.090268,-0.071834,0.040172,...,-0.000021,-0.011883,0.037535,0.044342,-0.017238,-0.004193,-0.038553,-0.014560,-0.027404,-0.009196
2,0.381102,0.028847,0.005632,0.007148,0.054034,-0.037941,-0.020789,-0.013469,-0.012093,0.049300,...,-0.000951,0.011067,-0.015101,-0.007707,0.001102,0.059045,0.009473,0.027300,-0.004653,0.004550
3,0.501056,0.012766,0.024526,-0.012577,-0.021955,-0.083902,-0.030951,0.041419,0.084193,0.121142,...,0.010787,0.000394,-0.002209,0.022088,-0.003369,-0.003611,0.010476,-0.016955,0.001728,-0.011246
4,0.205974,-0.094238,-0.280693,-0.112118,0.095212,-0.180953,-0.035970,-0.009452,-0.083246,0.024759,...,-0.018163,-0.012631,0.000735,-0.075945,0.053570,-0.103092,0.118748,0.049006,0.156359,0.039533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1887,0.334910,-0.060034,-0.046841,-0.021949,0.031356,-0.115047,-0.005808,0.020633,0.003952,-0.061204,...,0.001726,-0.002547,-0.026334,0.040394,0.002703,-0.024378,-0.015015,-0.016494,-0.023620,-0.004378
1888,0.394615,-0.106214,0.047338,-0.091694,-0.255788,0.204071,-0.065478,-0.001207,-0.017908,-0.004826,...,0.037049,-0.030204,-0.037304,0.024258,0.002283,0.009137,0.001110,-0.003936,-0.019321,0.023620
1889,0.383800,-0.019713,0.005815,0.021731,0.291234,0.071020,-0.125398,0.076468,-0.000342,0.087650,...,0.010982,-0.008682,-0.015261,0.003954,0.012496,0.041983,0.006839,0.014767,-0.024760,0.030195
1890,0.130486,-0.019064,-0.101496,0.003898,0.115576,0.008739,0.104791,-0.011906,0.080871,-0.003296,...,0.100098,-0.005045,-0.015133,0.026074,0.001952,0.003328,0.057320,-0.014684,0.006163,-0.002116
1891,0.001512,-0.000254,-0.001659,0.000457,0.000626,-0.000722,-0.000681,-0.000820,0.000123,-0.000522,...,0.000086,0.003376,0.002199,-0.000081,-0.003294,0.002052,0.000178,-0.000414,0.003493,0.005965

### 生成聚类向量

In [8]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
# 假设 user_vectors 是用户向量的集合，每个向量形状为 (n_features,)
Userfeatures_noid = data_feature
n_clusters = 40# 指定聚类的数量
kmeans = KMeans(n_clusters=n_clusters)
kmeans.fit(Userfeatures_noid)
centers = kmeans.cluster_centers_
for i in range(len(centers)):
    print("Class {}: {}".format(i+1, centers[i]))


# 计算轮廓系数
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")

Class 1: [ 5.53074430e-01  4.91345378e-02  1.58463921e-01  7.94551691e-02
 -4.62283008e-02 -4.64668919e-02  1.99349845e-02  9.42487821e-03
  5.26057494e-02  1.60759629e-01 -4.32954982e-02  1.43203602e-02
 -6.23154436e-02  4.96597932e-02  2.32215293e-02  9.79450942e-03
 -7.33595542e-03  1.14229797e-04  1.66534220e-02  3.67673193e-03
 -1.63646617e-03  5.04520974e-03 -9.66018321e-03 -7.04274403e-03
 -4.82262066e-03]
Class 2: [ 0.26625822 -0.10894141 -0.33202756 -0.11903151  0.10825593 -0.19979914
 -0.03703313 -0.02449502 -0.08516617  0.04749749  0.04675683  0.03709353
 -0.0028214   0.03050912 -0.01689019 -0.01911964 -0.01812028  0.04313291
  0.05429742 -0.00371683  0.00047516 -0.01255096 -0.01237637 -0.02635562
 -0.02321324]
Class 3: [ 2.05762092e-01  4.96275805e-01 -8.92006679e-02 -2.92299027e-02
 -1.10956126e-02  1.69709030e-02 -8.59357551e-03 -2.19098499e-02
  1.56293845e-02  9.65404728e-03 -1.05304008e-02  8.44042214e-03
  2.15631228e-02  2.88832360e-03 -1.32046009e-02  3.53581113e-03
  1.66065374e-03 -3.53671446e-05  1.02943482e-02 -4.76898703e-03
 -4.07722202e-03 -9.08206403e-04  5.79325504e-03 -1.75028158e-03
  2.46408462e-03]
Class 4: [ 0.18684404 -0.04845574 -0.19956081 -0.06628961  0.04881029 -0.12902406
 -0.0125806   0.08399182  0.04084208 -0.01055052 -0.01243312  0.0152995
 -0.00951383 -0.02678004  0.00689124  0.01835147  0.00222139  0.0101881
  0.0217542  -0.01618586 -0.0044256   0.01223149  0.01759395 -0.04150083
  0.00650136]
Class 5: [ 0.12810097 -0.02189054 -0.17196963  0.00608097  0.05628785  0.01275411
  0.22835742 -0.05640567 -0.01475897  0.05346013  0.10727243 -0.15320244
 -0.06768188  0.04387416 -0.04562805 -0.02733747 -0.05871744  0.07574881
  0.07483672 -0.04121201  0.03092294  0.05925078  0.01166443  0.03698182
 -0.02108182]
Class 6: [ 0.10431668 -0.03443427 -0.30878807  0.40679703 -0.07297976 -0.01887397
 -0.12163333 -0.02758115 -0.03996219  0.01831077 -0.00542112 -0.01968337
  0.02253532  0.00831451  0.00913487 -0.02818251 -0.00447212  0.02666488
  0.0394025  -0.02284873 -0.00287004 -0.01644059  0.01481673  0.01160604
 -0.00071432]
Class 7: [ 0.25446518 -0.07041139 -0.16884271 -0.03820591  0.20285928  0.04511678
  0.15188633 -0.22824578 -0.05878178 -0.01142079 -0.41345133 -0.18118584
 -0.10093461 -0.19182001  0.10262501  0.01080244  0.0500276  -0.06839954
 -0.05620228 -0.01587122 -0.00697185  0.01409253  0.01007478  0.04836456
  0.01338078]
Class 8: [ 0.54991155  0.06513381  0.22143123  0.13149392  0.00928459 -0.22949669
  0.0901376  -0.02437029 -0.07109347 -0.13105999 -0.01536178 -0.08514545
  0.06193579 -0.01460042 -0.09546913 -0.01425484  0.02416817 -0.0670573
  0.02977096 -0.03816111 -0.00745529  0.01366419 -0.04109306 -0.04243231
 -0.01915252]
Class 9: [ 0.36267158  0.02255754  0.05440537  0.04943913  0.01498619 -0.07454856
  0.0341085  -0.0132169  -0.00088492 -0.01597329 -0.0379046  -0.0307373
 -0.00252597  0.00914767 -0.01891107  0.00608176  0.00514601 -0.00597627
  0.01852364 -0.00939606 -0.00304786  0.01218824 -0.00754071 -0.01429627
 -0.00580183]
Class 10: [ 0.26274735  0.00298317 -0.06940058  0.02134641  0.01528373  0.03463913
  0.05760273  0.00666136  0.01519508  0.00680625 -0.02406991 -0.0024039
 -0.00877305  0.00399485  0.01296702  0.01662874  0.0021571   0.00485466
  0.00845451  0.00678419 -0.00992516  0.01132187  0.0033829  -0.00544564
 -0.00139541]
Class 11: [ 0.20600864  0.08836917  0.00399889  0.04493081  0.20437216  0.17237158
 -0.03040286  0.25523279 -0.19743112  0.09200319 -0.03203148 -0.00609656
  0.01982611  0.02196702 -0.00972553 -0.00550971 -0.01575768  0.02457373
 -0.00758635  0.00996905  0.00282587  0.00241988 -0.02001764 -0.0039407
  0.02574814]
Class 12: [ 4.67945217e-01 -1.18835869e-01 -1.98347132e-01 -1.23473229e-01
 -3.87488524e-02 -5.90187036e-02 -2.75155708e-02  9.53147083e-02
  7.53819234e-02  3.37681741e-02  6.37851643e-03  3.11570897e-04
 -2.10542505e-02 -1.28157646e-02  2.06351547e-02 -1.57217293e-02
 -1.60501929e-03 -9.66162381e-03 -9.41588892e-04 -9.55289561e-03
 -2.01226589e-02 -5.31821227e-03 -6.63155761e-03 -2.39750937e-02
 -3.77661636e-04]
Class 13: [ 0.18225223 -0.06322469 -0.16493991 -0.08449483  0.05425568 -0.16144595
 -0.03793122  0.06489361  0.00415484 -0.0585058  -0.0626265  -0.02713468
  0.02437028  0.05710978 -0.00471795 -0.06603244 -0.02105799 -0.05199937
  0.22047395  0.34500061  0.00105095 -0.07382974 -0.00698085 -0.0020788
  0.02083603]
Class 14: [ 0.38018846 -0.08368629 -0.0446637  -0.04606946 -0.08244547  0.08807203
 -0.00688314  0.00577371  0.01475592 -0.01716053 -0.01971835 -0.02482316
 -0.00728331  0.0115595  -0.00264711  0.00218636  0.00847467  0.00750137
  0.00624502 -0.00369103 -0.00751614  0.00129518  0.00324217 -0.00322288
 -0.00423422]
Class 15: [ 0.09114811 -0.00629436 -0.08985412  0.05115503  0.02984506  0.06753442
  0.18049252  0.02885621  0.0223833  -0.06236855 -0.01061505  0.09710199
 -0.02684203  0.01558159  0.00819091  0.00428727  0.01625497 -0.0282444
  0.03185015 -0.01139017  0.01173238  0.02091927  0.00541323  0.00499593
  0.00065841]
Class 16: [ 0.2982007  -0.04784832 -0.09265608 -0.01709871  0.09655791 -0.01320811
  0.08975996 -0.11653703 -0.03326925 -0.00139541 -0.19730295 -0.09086533
 -0.04289038 -0.07760183  0.04335461  0.01477109  0.02598295 -0.03415295
 -0.00617292 -0.01619917 -0.005298    0.01359693 -0.00705354  0.00873738
  0.00101432]
Class 17: [ 0.19908998 -0.03725478 -0.06198243 -0.03431075 -0.03263861  0.01759761
  0.00508457  0.06829473  0.03473204 -0.09534105 -0.04993213 -0.02735379
  0.00646969  0.10077534  0.00852067 -0.03319434 -0.01642669  0.0200995
 -0.03154609 -0.01606405  0.02604331  0.00981503  0.0072805   0.01701778
 -0.01257013]
Class 18: [ 0.10318656  0.05320242 -0.09777383 -0.004511    0.04430171  0.05347416
  0.19905378 -0.0483148   0.0753644   0.09196924 -0.02648288 -0.0409463
  0.34427427  0.00549537  0.14114229  0.07296196 -0.02519097  0.00299882
  0.02482909 -0.00883324  0.01569901  0.02446899 -0.01621454  0.00360895
 -0.00375477]
Class 19: [ 0.1213784  -0.03238933 -0.1571212   0.12399554 -0.01508905  0.003534
  0.08266813  0.05220449  0.04613129 -0.04761779 -0.0004571   0.0164005
 -0.05818587  0.00246845 -0.0506473   0.15770756 -0.01830006 -0.01164068
 -0.03331651  0.03975628  0.01928905  0.02147779 -0.05218404 -0.00602957
 -0.02888765]
Class 20: [ 0.53403309 -0.07635877  0.04114039 -0.00474706 -0.05255958  0.0647701
 -0.02105032 -0.02103399  0.04966456  0.0764746  -0.01502849 -0.00797937
 -0.03576123  0.01154105  0.00644198  0.0174508   0.00107924 -0.00569669
  0.02422238  0.00108663 -0.01430875  0.00695311 -0.00425814 -0.00828547
 -0.00258338]
Class 21: [ 0.34375125  0.3149698   0.07232535  0.06410641 -0.02490139 -0.10625566
  0.09375067 -0.00203827 -0.0841751  -0.13201301  0.16396089 -0.11960886
 -0.10836224 -0.00243732  0.25651961  0.04712212  0.02410218 -0.01869643
 -0.03491845  0.02975556 -0.0253032  -0.02862049 -0.01120255 -0.02839884
  0.05377283]
Class 22: [ 0.26065633  0.00743868  0.09368082  0.06091612  0.00166858 -0.11856412
  0.04223102  0.02858282 -0.00036171 -0.11772109 -0.03637272 -0.06217835
  0.05965361  0.03635192 -0.15196324  0.10294636 -0.00533006  0.00525844
  0.08688694 -0.08322282 -0.10355254 -0.10027122  0.10509833  0.07883304
  0.18645687]
Class 23: [ 0.2234617   0.27144591 -0.06310814  0.00635764  0.01017322  0.00548386
  0.01332448  0.01172672  0.00488684  0.02086913 -0.00508706 -0.00360451
  0.0022754   0.00209294  0.00157865  0.00611961 -0.0026651   0.01360446
  0.00496362  0.00424934  0.00136254  0.01961421 -0.00433914 -0.00375269
  0.01180924]
Class 24: [ 0.44858295 -0.07363761 -0.13311653 -0.04490809  0.09242212 -0.12833512
 -0.057615   -0.02950608  0.0007358   0.07663819  0.03453987  0.05158034
 -0.008741    0.03975155  0.00144133 -0.00823416 -0.00877386  0.00416262
  0.01628898  0.00463686 -0.00053457 -0.00658323 -0.00568622 -0.02651492
 -0.01093104]
Class 25: [ 0.59097814 -0.12913807  0.0494857  -0.08147927 -0.2294346   0.20437999
 -0.0525508  -0.00826534  0.01102388  0.01203464  0.01656959 -0.0264725
 -0.00488285 -0.05779044 -0.00632246  0.01805518  0.00355559 -0.00425076
  0.03745435 -0.00975423 -0.00464585  0.01165266 -0.00109733  0.00496532
 -0.00255358]
Class 26: [ 1.86372001e-01  6.80680281e-01 -1.29714401e-01 -6.64192668e-02
 -3.81343448e-02  2.39435849e-02 -4.73095777e-02 -4.84407118e-02
  1.20432471e-02 -1.06993483e-02 -3.12111864e-02  1.56605896e-02
 -1.70581126e-02 -1.52123266e-02 -7.91540377e-02 -1.93051739e-02
  7.34987140e-05  1.29829387e-02  3.03098776e-03  1.16634695e-03
  2.20937292e-02  8.24290175e-03 -1.96207716e-02 -2.03231705e-02
  2.78260781e-02]
Class 27: [ 0.15763442  0.22215375 -0.02280701  0.01730226  0.09522704  0.0980659
 -0.02259454  0.16171374 -0.13160223  0.08278534 -0.01277111 -0.02534663
 -0.00836602  0.05308764 -0.00645975  0.03806359  0.03648972 -0.10683727
  0.02831899 -0.02302135 -0.06428003 -0.01451001  0.08026391  0.02738357
 -0.15709662]
Class 28: [ 0.23792905 -0.12059016 -0.45239333  0.0176095   0.08307851 -0.23296753
 -0.09088199  0.01375266 -0.06671407  0.05463965  0.05134384  0.02219778
 -0.00187802 -0.00228102 -0.01377803 -0.01923144 -0.03861191  0.07824208
  0.10166405 -0.06528818 -0.01355806 -0.05418957 -0.03481686 -0.02416977
 -0.01316238]
Class 29: [ 0.05549428 -0.00060511 -0.03161281  0.0163383   0.0091425  -0.00362788
  0.00865219  0.00458672 -0.00229529 -0.00879979 -0.00801845 -0.0031221
  0.003635    0.01173791 -0.00373357  0.00740204 -0.00133596  0.00553478
  0.01099099  0.00481849  0.00030727  0.00911963  0.0082527  -0.00370383
  0.00216224]
Class 30: [ 0.55282435 -0.0503405   0.11208249  0.05625701  0.20208185  0.02584597
 -0.12051204 -0.11160136  0.12169521  0.07082355  0.06162711  0.04223183
 -0.028597    0.08398705 -0.00696854  0.01737324 -0.00977621 -0.02223082
  0.01292941  0.00892375 -0.01354683  0.01685039  0.00663784  0.01023411
 -0.00347495]
Class 31: [ 0.29040767 -0.14493385 -0.45750804 -0.18551284  0.15940593 -0.24762276
  0.00549069 -0.04060316 -0.10830112  0.08801664  0.08460644  0.00846787
 -0.01980659  0.023687   -0.04727698 -0.04199568 -0.03587572  0.08140727
  0.07090512 -0.02901967  0.01744831 -0.00150595 -0.00486615 -0.02676882
 -0.04391426]
Class 32: [ 0.24693732 -0.07073674 -0.19880458 -0.03102299  0.05464577 -0.11524336
 -0.02639438 -0.03022664 -0.05680492  0.02605956  0.00849113  0.02189161
 -0.00040677  0.04082945 -0.00998412 -0.00127953 -0.00633112  0.02354632
  0.02838936 -0.00660552  0.00875958 -0.01461853 -0.00497    -0.02532298
 -0.00755899]
Class 33: [ 0.28831702 -0.09247384 -0.21849251 -0.05306144  0.02508882  0.05578472
  0.13409939 -0.04504966  0.01650517  0.06744251  0.00305901 -0.07274367
 -0.02272022 -0.01622362 -0.03640527 -0.00806998  0.00301035 -0.00310673
 -0.03219637  0.01455681 -0.02120055 -0.01027279  0.00624416 -0.01534991
  0.00953695]
Class 34: [ 0.31707229  0.07756946  0.02871472  0.04445873  0.1306279   0.05153391
 -0.05952786 -0.00359692  0.04550153  0.02402568  0.00321467 -0.00486792
 -0.0006243   0.0276113  -0.0089787   0.00584866  0.0108716   0.00118848
  0.00962126  0.00193964  0.00811892  0.01027969 -0.00469702 -0.00058842
  0.00049135]
Class 35: [ 0.14505228 -0.03118216 -0.10529606 -0.03711311  0.04923864 -0.09995055
 -0.01435858 -0.02147519 -0.06166495  0.02524871  0.03681825  0.07984279
  0.02557129  0.02504498 -0.00738131 -0.00845427  0.00542541 -0.00881297
 -0.10245992  0.07493342 -0.09861735  0.14992799  0.04797685  0.25009976
  0.04480389]
Class 36: [ 0.30163988 -0.02825955  0.00912331 -0.00296154  0.00414503 -0.03717384
  0.0028227   0.03642208  0.00219781  0.01324709 -0.01452236  0.00059967
  0.0040705   0.02132219 -0.01337937  0.01770022  0.05172526 -0.01470935
 -0.0296049   0.01485434  0.21338484 -0.01933727  0.15496526 -0.00666226
  0.02575534]
Class 37: [ 0.32401772 -0.00645242  0.05534373  0.07443572  0.05204237  0.08632579
  0.1181204   0.08432677 -0.02726848 -0.05551626 -0.05306446  0.13558307
 -0.03604798 -0.05291788  0.04093995 -0.04648293 -0.04544514  0.14748914
 -0.01442058  0.02077127 -0.01649605 -0.03466417  0.03470417 -0.00488784
 -0.03909018]
Class 38: [ 0.25944114 -0.01610851  0.03271881  0.06027132  0.37296368  0.17724522
 -0.1767888  -0.01411706  0.0526863   0.01376426  0.0674056  -0.00573672
  0.00115176  0.06362961 -0.01077917  0.02134117 -0.00445763 -0.03705548
  0.00953866 -0.00089376  0.02029095  0.0116034   0.00163003 -0.01188967
  0.03192982]
Class 39: [ 1.16994368e-01 -3.41827593e-02 -1.78302384e-01  1.06774847e-01
  2.32441937e-02  1.29726085e-01  3.16770273e-01  3.19525511e-02
  7.18863016e-02 -4.61652729e-02 -3.35265483e-03  1.25670000e-01
 -1.07712761e-01  4.39083320e-02 -4.84612441e-02  1.36842007e-02
  3.49121321e-02 -1.09130046e-01 -1.33856510e-02  1.51745512e-02
  1.76125166e-02  1.31910273e-07 -4.56710527e-02 -1.97087173e-02
  4.46247760e-03]
Class 40: [ 0.3834965   0.33131181  0.06386802  0.04723808 -0.00050548 -0.10254665
  0.02294175 -0.04585524 -0.01781506 -0.03202305 -0.02852426 -0.02650705
  0.03123559 -0.03191969 -0.09045959 -0.02233406  0.01582675 -0.02196968
  0.00859974 -0.00684469  0.04595904  0.03723248 -0.05365551 -0.03404519
  0.00990732]
轮廓系数：0.1530020218502776

### 生成用户聚类结果信息

In [11]:
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")
print("label",  kmeans.labels_)
print("num_label",  len(kmeans.labels_))
print(kmeans.labels_[1])

轮廓系数：0.1530020218502776
label [14 31  8 ... 37  9 28]
num_label 1892
31

### 同步存储聚类后的用户向量 和 映射关系

In [21]:
# 因为聚类了所以不用考虑原来用户id，类别顺序就是新的id
filename = "./lastfm_40clusters.dat"
with open(filename, 'w', newline='') as f:
    for i in range(centers.shape[0]):
        new_line = str(i) + '\t' + ';'.join(str(centers[i, :]).strip('[').strip(']').split()) + '\n'
        f.write(new_line)
print("done")

#label需要类别顺序与用户id对应，而不是与用户向量的index对应
label_dict = {}
User_id = data_user
User_id = User_id.astype(str)
for i in range(len(kmeans.labels_)):
    label_dict[User_id[i]] = int(kmeans.labels_[i])
import json
filename = "./lastfm_{}clusters_labels.json".format(n_clusters)
with open(filename, 'w') as f:
    json.dump(label_dict, f)
print("done")

done
done

## 生成关系矩阵

### 读取聚类向量

In [4]:
classfeatures = []
import numpy as np
import pandas as pd
n_clusters = 40
filename = "./lastfm_{}clusters.dat".format(n_clusters)
with open("./lastfm_{}clusters.dat".format(n_clusters), "r") as f:
    # f.readline()# 跳过第一行
    for line in f:
        line = line.split("\t")
        vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
        classfeatures.append(np.array(vec).astype(float))
classfeatures = pd.DataFrame(classfeatures)
classfeatures

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.553074,0.049135,0.158464,0.079455,-0.046228,-0.046467,0.019935,0.009425,0.052606,0.160760,...,0.009795,-0.007336,0.000114,0.016653,0.003677,-0.001636,5.045210e-03,-0.009660,-0.007043,-0.004823
1,0.266258,-0.108941,-0.332028,-0.119032,0.108256,-0.199799,-0.037033,-0.024495,-0.085166,0.047497,...,-0.019120,-0.018120,0.043133,0.054297,-0.003717,0.000475,-1.255096e-02,-0.012376,-0.026356,-0.023213
2,0.205762,0.496276,-0.089201,-0.029230,-0.011096,0.016971,-0.008594,-0.021910,0.015629,0.009654,...,0.003536,0.001661,-0.000035,0.010294,-0.004769,-0.004077,-9.082064e-04,0.005793,-0.001750,0.002464
3,0.186844,-0.048456,-0.199561,-0.066290,0.048810,-0.129024,-0.012581,0.083992,0.040842,-0.010551,...,0.018351,0.002221,0.010188,0.021754,-0.016186,-0.004426,1.223149e-02,0.017594,-0.041501,0.006501
4,0.128101,-0.021891,-0.171970,0.006081,0.056288,0.012754,0.228357,-0.056406,-0.014759,0.053460,...,-0.027337,-0.058717,0.075749,0.074837,-0.041212,0.030923,5.925078e-02,0.011664,0.036982,-0.021082
5,0.104317,-0.034434,-0.308788,0.406797,-0.072980,-0.018874,-0.121633,-0.027581,-0.039962,0.018311,...,-0.028183,-0.004472,0.026665,0.039403,-0.022849,-0.002870,-1.644059e-02,0.014817,0.011606,-0.000714
6,0.254465,-0.070411,-0.168843,-0.038206,0.202859,0.045117,0.151886,-0.228246,-0.058782,-0.011421,...,0.010802,0.050028,-0.068400,-0.056202,-0.015871,-0.006972,1.409253e-02,0.010075,0.048365,0.013381
7,0.549912,0.065134,0.221431,0.131494,0.009285,-0.229497,0.090138,-0.024370,-0.071093,-0.131060,...,-0.014255,0.024168,-0.067057,0.029771,-0.038161,-0.007455,1.366419e-02,-0.041093,-0.042432,-0.019153
8,0.362672,0.022558,0.054405,0.049439,0.014986,-0.074549,0.034108,-0.013217,-0.000885,-0.015973,...,0.006082,0.005146,-0.005976,0.018524,-0.009396,-0.003048,1.218824e-02,-0.007541,-0.014296,-0.005802
9,0.262747,0.002983,-0.069401,0.021346,0.015284,0.034639,0.057603,0.006661,0.015195,0.006806,...,0.016629,0.002157,0.004855,0.008455,0.006784,-0.009925,1.132187e-02,0.003383,-0.005446,-0.001395
10,0.206009,0.088369,0.003999,0.044931,0.204372,0.172372,-0.030403,0.255233,-0.197431,0.092003,...,-0.005510,-0.015758,0.024574,-0.007586,0.009969,0.002826,2.419880e-03,-0.020018,-0.003941,0.025748
11,0.467945,-0.118836,-0.198347,-0.123473,-0.038749,-0.059019,-0.027516,0.095315,0.075382,0.033768,...,-0.015722,-0.001605,-0.009662,-0.000942,-0.009553,-0.020123,-5.318212e-03,-0.006632,-0.023975,-0.000378
12,0.182252,-0.063225,-0.164940,-0.084495,0.054256,-0.161446,-0.037931,0.064894,0.004155,-0.058506,...,-0.066032,-0.021058,-0.051999,0.220474,0.345001,0.001051,-7.382974e-02,-0.006981,-0.002079,0.020836
13,0.380188,-0.083686,-0.044664,-0.046069,-0.082445,0.088072,-0.006883,0.005774,0.014756,-0.017161,...,0.002186,0.008475,0.007501,0.006245,-0.003691,-0.007516,1.295180e-03,0.003242,-0.003223,-0.004234
14,0.091148,-0.006294,-0.089854,0.051155,0.029845,0.067534,0.180493,0.028856,0.022383,-0.062369,...,0.004287,0.016255,-0.028244,0.031850,-0.011390,0.011732,2.091927e-02,0.005413,0.004996,0.000658
15,0.298201,-0.047848,-0.092656,-0.017099,0.096558,-0.013208,0.089760,-0.116537,-0.033269,-0.001395,...,0.014771,0.025983,-0.034153,-0.006173,-0.016199,-0.005298,1.359693e-02,-0.007054,0.008737,0.001014
16,0.199090,-0.037255,-0.061982,-0.034311,-0.032639,0.017598,0.005085,0.068295,0.034732,-0.095341,...,-0.033194,-0.016427,0.020099,-0.031546,-0.016064,0.026043,9.815030e-03,0.007280,0.017018,-0.012570
17,0.103187,0.053202,-0.097774,-0.004511,0.044302,0.053474,0.199054,-0.048315,0.075364,0.091969,...,0.072962,-0.025191,0.002999,0.024829,-0.008833,0.015699,2.446899e-02,-0.016215,0.003609,-0.003755
18,0.121378,-0.032389,-0.157121,0.123996,-0.015089,0.003534,0.082668,0.052204,0.046131,-0.047618,...,0.157708,-0.018300,-0.011641,-0.033317,0.039756,0.019289,2.147779e-02,-0.052184,-0.006030,-0.028888
19,0.534033,-0.076359,0.041140,-0.004747,-0.052560,0.064770,-0.021050,-0.021034,0.049665,0.076475,...,0.017451,0.001079,-0.005697,0.024222,0.001087,-0.014309,6.953110e-03,-0.004258,-0.008285,-0.002583
20,0.343751,0.314970,0.072325,0.064106,-0.024901,-0.106256,0.093751,-0.002038,-0.084175,-0.132013,...,0.047122,0.024102,-0.018696,-0.034918,0.029756,-0.025303,-2.862049e-02,-0.011203,-0.028399,0.053773
21,0.260656,0.007439,0.093681,0.060916,0.001669,-0.118564,0.042231,0.028583,-0.000362,-0.117721,...,0.102946,-0.005330,0.005258,0.086887,-0.083223,-0.103553,-1.002712e-01,0.105098,0.078833,0.186457
22,0.223462,0.271446,-0.063108,0.006358,0.010173,0.005484,0.013324,0.011727,0.004887,0.020869,...,0.006120,-0.002665,0.013604,0.004964,0.004249,0.001363,1.961421e-02,-0.004339,-0.003753,0.011809
23,0.448583,-0.073638,-0.133117,-0.044908,0.092422,-0.128335,-0.057615,-0.029506,0.000736,0.076638,...,-0.008234,-0.008774,0.004163,0.016289,0.004637,-0.000535,-6.583230e-03,-0.005686,-0.026515,-0.010931
24,0.590978,-0.129138,0.049486,-0.081479,-0.229435,0.204380,-0.052551,-0.008265,0.011024,0.012035,...,0.018055,0.003556,-0.004251,0.037454,-0.009754,-0.004646,1.165266e-02,-0.001097,0.004965,-0.002554
25,0.186372,0.680680,-0.129714,-0.066419,-0.038134,0.023944,-0.047310,-0.048441,0.012043,-0.010699,...,-0.019305,0.000073,0.012983,0.003031,0.001166,0.022094,8.242902e-03,-0.019621,-0.020323,0.027826
26,0.157634,0.222154,-0.022807,0.017302,0.095227,0.098066,-0.022595,0.161714,-0.131602,0.082785,...,0.038064,0.036490,-0.106837,0.028319,-0.023021,-0.064280,-1.451001e-02,0.080264,0.027384,-0.157097
27,0.237929,-0.120590,-0.452393,0.017610,0.083079,-0.232968,-0.090882,0.013753,-0.066714,0.054640,...,-0.019231,-0.038612,0.078242,0.101664,-0.065288,-0.013558,-5.418957e-02,-0.034817,-0.024170,-0.013162
28,0.055494,-0.000605,-0.031613,0.016338,0.009142,-0.003628,0.008652,0.004587,-0.002295,-0.008800,...,0.007402,-0.001336,0.005535,0.010991,0.004818,0.000307,9.119630e-03,0.008253,-0.003704,0.002162
29,0.552824,-0.050341,0.112082,0.056257,0.202082,0.025846,-0.120512,-0.111601,0.121695,0.070824,...,0.017373,-0.009776,-0.022231,0.012929,0.008924,-0.013547,1.685039e-02,0.006638,0.010234,-0.003475
30,0.290408,-0.144934,-0.457508,-0.185513,0.159406,-0.247623,0.005491,-0.040603,-0.108301,0.088017,...,-0.041996,-0.035876,0.081407,0.070905,-0.029020,0.017448,-1.505950e-03,-0.004866,-0.026769,-0.043914
31,0.246937,-0.070737,-0.198805,-0.031023,0.054646,-0.115243,-0.026394,-0.030227,-0.056805,0.026060,...,-0.001280,-0.006331,0.023546,0.028389,-0.006606,0.008760,-1.461853e-02,-0.004970,-0.025323,-0.007559
32,0.288317,-0.092474,-0.218493,-0.053061,0.025089,0.055785,0.134099,-0.045050,0.016505,0.067443,...,-0.008070,0.003010,-0.003107,-0.032196,0.014557,-0.021201,-1.027279e-02,0.006244,-0.015350,0.009537
33,0.317072,0.077569,0.028715,0.044459,0.130628,0.051534,-0.059528,-0.003597,0.045502,0.024026,...,0.005849,0.010872,0.001188,0.009621,0.001940,0.008119,1.027969e-02,-0.004697,-0.000588,0.000491
34,0.145052,-0.031182,-0.105296,-0.037113,0.049239,-0.099951,-0.014359,-0.021475,-0.061665,0.025249,...,-0.008454,0.005425,-0.008813,-0.102460,0.074933,-0.098617,1.499280e-01,0.047977,0.250100,0.044804
35,0.301640,-0.028260,0.009123,-0.002962,0.004145,-0.037174,0.002823,0.036422,0.002198,0.013247,...,0.017700,0.051725,-0.014709,-0.029605,0.014854,0.213385,-1.933727e-02,0.154965,-0.006662,0.025755
36,0.324018,-0.006452,0.055344,0.074436,0.052042,0.086326,0.118120,0.084327,-0.027268,-0.055516,...,-0.046483,-0.045445,0.147489,-0.014421,0.020771,-0.016496,-3.466417e-02,0.034704,-0.004888,-0.039090
37,0.259441,-0.016109,0.032719,0.060271,0.372964,0.177245,-0.176789,-0.014117,0.052686,0.013764,...,0.021341,-0.004458,-0.037055,0.009539,-0.000894,0.020291,1.160340e-02,0.001630,-0.011890,0.031930
38,0.116994,-0.034183,-0.178302,0.106775,0.023244,0.129726,0.316770,0.031953,0.071886,-0.046165,...,0.013684,0.034912,-0.109130,-0.013386,0.015175,0.017613,1.319103e-07,-0.045671,-0.019709,0.004462
39,0.383497,0.331312,0.063868,0.047238,-0.000505,-0.102547,0.022942,-0.045855,-0.017815,-0.032023,...,-0.022334,0.015827,-0.021970,0.008600,-0.006845,0.045959,3.723248e-02,-0.053656,-0.034045,0.009907

### 生成W

In [5]:
import numpy as np
classfeatures = np.array(classfeatures)
n = len(classfeatures)
sparsityLevel = int(n/3)
W = np.zeros(shape=(n, n))

for i in range(n):
    sSim = 0
    for j in range(n):
        sim = np.dot(classfeatures[i], classfeatures[j])
        W[i][j] = sim
        sSim += sim
    W[i] /= sSim
SparseW = W

#小于阈值的置为0
if sparsityLevel > 0 and sparsityLevel < n:
    for i in range(n):
        similarity = sorted(W[i], reverse=True)
        threshold = similarity[sparsityLevel]
        for j in range(n):
            if W[i][j] <= threshold:
                SparseW[i][j] = 0
        SparseW[i] /= sum(SparseW[i])

for i in range(n):
    SparseW[i][i] = 0
    if sum(SparseW[i]) != 0:
        SparseW[i][i] = np.linalg.norm(SparseW[i]) ** 2 / sum(SparseW[i])
    else:
        SparseW[i][i] = 1
    SparseW[i] /= sum(SparseW[i])
print("SparseW --Opt", SparseW)

#存储为json格式
import json
filename = "./lastfm_SparseW.json"
with open(filename, 'w') as f:
    json.dump(SparseW.T.tolist(), f)
print("save SparseW.json")
# W = np.load('./NYC/SparseW.npy')

SparseW --Opt [[0.08059744 0.         0.         ... 0.         0.         0.07278624]
 [0.         0.08853541 0.         ... 0.         0.         0.        ]
 [0.06080789 0.         0.10121386 ... 0.         0.         0.11711784]
 ...
 [0.07575284 0.         0.         ... 0.08757806 0.         0.        ]
 [0.         0.         0.         ... 0.         0.08177436 0.        ]
 [0.08831731 0.         0.08809426 ... 0.         0.         0.0816727 ]]
save SparseW.json