In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
import numpy as np
from scipy.sparse import csr_matrix
import csv
import random
import pickle
import json
import pandas as pd

In [9]:
import pandas as pd
def get_first_value(s):
    lst = eval(s)
    return lst[0]
event_file = r"./processed_events_shuffled.dat"
data = pd.read_csv(event_file, sep='\t', header=None, names=['user', 'timestamp', 'armpool'])
data= data.iloc[1:,:]

data["picked_item"] = data['armpool'].apply(get_first_value)
data

,user,timestamp,armpool,picked_item
1,46,1283292000000,"[295, 7288, 11206, 13034, 9964, 5604, 11315, 1...",295
2,1326,1228086000000,"[288, 4104, 12805, 14978, 14340, 13225, 16644,...",288
3,1535,1272664800000,"[7123, 8876, 10576, 4442, 7556, 12113, 10208, ...",7123
4,650,1191189600000,"[3902, 803, 11498, 5605, 15562, 3650, 1583, 17...",3902
5,1769,1246399200000,"[1243, 2832, 870, 14087, 699, 18391, 14142, 10...",1243
...,...,...,...,...
96729,411,1214863200000,"[475, 8363, 13785, 17907, 14570, 6233, 15262, ...",475
96730,357,1243807200000,"[6388, 18574, 6771, 11131, 4622, 1337, 5256, 1...",6388
96731,1822,1277935200000,"[9155, 9200, 17404, 17234, 1309, 3347, 8926, 6...",9155
96732,1217,1291158000000,"[707, 18609, 6835, 8788, 2637, 13456, 12002, 9...",707
96733,510,1212271200000,"[1925, 6552, 10567, 18511, 5014, 4340, 11536, ...",1925

In [13]:
data2 = data[["user","picked_item"]]
data2= data2.reset_index(drop=True)
data2

       user  picked_item
0        46          295
1      1326          288
2      1535         7123
3       650         3902
4      1769         1243
...     ...          ...
96728   411          475
96729   357         6388
96730  1822         9155
96731  1217          707
96732   510         1925

[96733 rows x 2 columns]

In [20]:
import numpy as np
FeatureVectors = {}
with open('./Arm_FeatureVectors_2.dat', "r") as f:
    for line in f:
        line = line.split("\t")
        vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
        FeatureVectors[int(line[0])] = np.array(vec).astype(np.float)
# FeatureVectors

d:\SoftwareFamily\Anaconda\envs\nlplab\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys

{52: array([ 0.10568702, -0.06818229, -0.41204546,  0.35458666, -0.04224088,
         0.01919637,  0.10927453,  0.0839815 ,  0.11687149, -0.01779011,
         0.05488165,  0.03145848, -0.10723706, -0.02694798, -0.10281454,
         0.09930332,  0.0893081 , -0.15731957, -0.14839965,  0.11303263,
         0.00412588,  0.10442615, -0.17321055, -0.12906204, -0.01506565]),
 63: array([ 0.0875718 , -0.03493151, -0.16046736,  0.03671298,  0.09810837,
         0.14123745,  0.37590639, -0.01531431,  0.0578995 , -0.13208602,
        -0.19649849,  0.13972472, -0.15252865, -0.04887264,  0.03046871,
        -0.04110974,  0.05374018, -0.15685045,  0.02506383, -0.06176694,
        -0.00740979,  0.08900594, -0.04204989,  0.03754526,  0.08987929]),
 73: array([ 0.1302909 , -0.03727091, -0.16032599,  0.10376093,  0.00551067,
         0.03821518,  0.2346223 ,  0.10629966,  0.13732067, -0.04119535,
        -0.01649755,  0.17309532, -0.16922014,  0.0339166 , -0.06441467,
         0.20138471,  0.00197677, -0.1289072 , -0.04308587,  0.02228167,
         0.06008973,  0.07274773, -0.17498776, -0.00915107, -0.00276711]),
 94: array([ 0.04867704, -0.02940165, -0.21672062,  0.172376  , -0.0047464 ,
         0.0115125 ,  0.12704749,  0.02784222,  0.04588648, -0.0327223 ,
         0.05739746, -0.03214098, -0.15282878,  0.02689343, -0.16144706,
         0.27991186, -0.07650173,  0.02881679, -0.00996726,  0.03175863,
         0.14587028,  0.11489841, -0.17974915,  0.02235834, -0.14368784]),
 96: array([ 0.48923093, -0.01021771,  0.21330598,  0.14363296,  0.04752489,
        -0.30078521,  0.10249179, -0.00601601, -0.08967761, -0.21564422,
        -0.1037373 , -0.11545178,  0.11426022, -0.05215972, -0.22773032,
         0.08697741,  0.00078447, -0.07798434,  0.12136972, -0.12802369,
        -0.12945098, -0.07474507,  0.09106067,  0.02759781,  0.14030868]),
 995: array([ 0.17902419, -0.06958534, -0.16719359, -0.08194358,  0.19578163,
        -0.04841418,  0.02886336, -0.30079631, -0.18073766, -0.05049786,
        -0.52190202, -0.15921321, -0.13305417, -0.20805454,  0.15227418,
         0.03692707,  0.03419727, -0.10267684,  0.02124742, -0.06754142,
         0.06073362,  0.05214242, -0.01436281,  0.07493549, -0.01266268]),
 3894: array([ 0.13509902, -0.02670351, -0.03955046,  0.0323234 ,  0.32882859,
         0.19633419,  0.03570788, -0.12476599,  0.03403217, -0.16117249,
        -0.37441713, -0.03952444, -0.11881349, -0.27341559,  0.20197483,
        -0.00741856, -0.02760072,  0.07948466, -0.05440844,  0.01413756,
        -0.0113743 , -0.06569624,  0.11244744,  0.12641146, -0.08086933]),
 6160: array([ 0.05287734, -0.01022614, -0.09220758,  0.04009173,  0.05421527,
         0.13386655,  0.34882617,  0.06777479,  0.0517547 , -0.1647627 ,
        -0.02471038,  0.35923676, -0.07894563,  0.05393019,  0.04247575,
        -0.11213171,  0.08634848, -0.12349141,  0.18797734, -0.14695214,
         0.04337133,  0.01681041, -0.03916938,  0.06575825,  0.06545153]),
 6177: array([ 0.09597116, -0.04244998, -0.22642367,  0.03753704,  0.06979777,
         0.11194397,  0.42173885,  0.02437205,  0.07788741, -0.06466554,
         0.09923605,  0.01294302, -0.19772887,  0.05815445, -0.04942177,
         0.00298384,  0.0609983 , -0.0541989 ,  0.12931873, -0.05616376,
         0.04530017,  0.1287625 , -0.13803793,  0.04166863,  0.02906048]),
 9322: array([ 0.14073165, -0.02344962, -0.05351146,  0.00047987,  0.11637051,
         0.00580661,  0.09174751, -0.16182542, -0.04181159, -0.06248526,
        -0.37397424, -0.18740051, -0.07684993, -0.22823873,  0.06998173,
         0.00927026,  0.04597411, -0.09680197, -0.01261955, -0.0344891 ,
         0.01725822,  0.03709458, -0.00621308,  0.05365342, -0.01548513]),
 101: array([ 0.03046278, -0.00955765, -0.07670829,  0.05007695,  0.00877245,
         0.00714293,  0.06322187,  0.04841327,  0.032513  , -0.04463554,
        -0.00033558,  0.09428901, -0.02357409, -0.00906013,  0.00685818,
        -0.0063187 ,  0.01834188, -0.04125037,  0.03263044, -0.00069547,
         0.00981893,  0.00945583,  0.01218135, -0.01708727, -0.00978991]),
 102: array([ 0.04854141, -0.01479786, -0.10167649,  0.04423682,  0.04015188,
         0.1064058 ,  0.26535753,  0.03617599,  0.04484514, -0.07551034,
         0.00196652,  0.15070655, -0.05383846,  0.03245961, -0.01704627,
        -0.02302667,  0.04267493, -0.07440513, -0.00799879, -0.00749177,
        -0.00068811, -0.05028666, -0.01024998, -0.00215928,  0.01005962]),
 106: array([ 0.02655659, -0.00109441, -0.03749059,  0.02815429,  0.02823245,
         0.0768387 ,  0.17507221,  0.04941379,  0.02157644, -0.1024357 ,
        -0.01274613,  0.21188056, -0.03829565,  0.02687116,  0.04872242,
        -0.04950456,  0.04125817, -0.04173007,  0.08970121, -0.05659064,
         0.03035741, -0.05057471,  0.02462823,  0.0464557 , -0.01369842]),
 108: array([ 0.05751107, -0.0225898 , -0.12752246, -0.00507182,  0.03800747,
        -0.01675745,  0.1071065 ,  0.12030132,  0.08018156, -0.04506039,
         0.03997423,  0.13399961, -0.03792208, -0.05487098,  0.01120805,
        -0.01022554,  0.03856388, -0.07883308, -0.00400908,  0.0311469 ,
         0.0429189 , -0.06531778,  0.01050844,  0.00939965, -0.07187997]),
 122: array([ 0.03274503, -0.0042232 , -0.05499616,  0.05261989,  0.01129539,
         0.07257127,  0.13286446,  0.05737277,  0.0251749 , -0.08295439,
         0.00211494,  0.13442346, -0.04530113,  0.01500161,  0.02598458,
         0.04402907,  0.01699641, -0.02344557, -0.02646883,  0.03970285,
         0.02056379, -0.06195913,  0.01394758, -0.01039725, -0.08566933]),
 128: array([ 0.01260492, -0.0009851 , -0.02149047,  0.01688126,  0.01717329,
         0.04020761,  0.10931225,  0.02908058,  0.01809675, -0.07314261,
        -0.02028374,  0.16208534, -0.03155907,  0.01818056,  0.02700656,
        -0.04096459,  0.03048162, -0.05250866,  0.08202447, -0.06968533,
         0.01904162,  0.0221781 , -0.03577362,  0.03191278,  0.04142213]),
 130: array([ 0.03346212, -0.00116064, -0.04879413,  0.05068932,  0.02773395,
         0.09122118,  0.19055475,  0.06428434,  0.02141375, -0.12970273,
        -0.02579369,  0.26591074, -0.03927835,  0.02507308,  0.07431001,
        -0.05350838,  0.04878049, -0.04005583,  0.09553035, -0.06090767,
         0.02013834, -0.06060594,  0.02790602,  0.05370455, -0.01553103]),
 134: array([ 0.03674101, -0.00174517, -0.05290363,  0.03888109,  0.03920424,
         0.10629465,  0.24220272,  0.06536608,  0.0295431 , -0.13676453,
        -0.01689414,  0.28098537, -0.05246429,  0.03643275,  0.06208622,
        -0.06858946,  0.05203916, -0.05599228,  0.11317975, -0.07727877,
         0.03068769, -0.07038207,  0.03277663,  0.05798709, -0.01080038]),
 137: array([ 0.02498982, -0.01390542, -0.08224138,  0.06982479,  0.00462427,
         0.06638336,  0.13979326,  0.01414505,  0.02699054, -0.04058269,
         0.01268165,  0.10194229, -0.04513795,  0.01495976, -0.03687453,
        -0.02986181,  0.03111625, -0.08678115, -0.0035598 ,  0.00874094,
         0.03723182, -0.03740825, -0.02909259, -0.00519457, -0.01094253]),
 51: array([ 2.39324213e-01, -7.73503709e-02, -1.58405844e-01, -6.91899855e-02,
         1.84401772e-01, -5.06107814e-03,  6.85557577e-02, -2.76446686e-01,
        -1.41229106e-01, -7.94677671e-02, -5.40238904e-01, -1.87090639e-01,
        -1.25477902e-01, -2.23307994e-01,  1.47113443e-01,  3.76762620e-02,
         1.17616619e-01, -7.36578796e-02, -8.53033286e-05, -4.77073255e-02,
         2.33109993e-02,  6.04887256e-02, -6.17427246e-03,  6.87294348e-02,
        -9.19661639e-03]),
 53: array([ 0.19957978, -0.08643299, -0.35928346,  0.16775542,  0.01193707,
         0.23923638,  0.54276914, -0.001624  ,  0.1190635 , -0.00490431,
         0.0187779 ,  0.10857209, -0.16449915,  0.08730413, -0.15693359,
         0.02937715,  0.04834419, -0.1906278 , -0.11888388,  0.05297794,
        -0.05202517,  0.03549913, -0.11587457, -0.11749452,  0.1032986 ]),
 64: array([ 0.12208898, -0.06967588, -0.35969582,  0.14445335,  0.05609478,
         0.2018499 ,  0.5466672 , -0.01449112,  0.1016531 , -0.00778698,
         0.0723305 ,  0.03259048, -0.1242117 ,  0.06009268, -0.19005482,
        -0.02020891,  0.03027708, -0.19255706, -0.14237372,  0.05570963,
        -0.02888938,  0.00923553, -0.10663552, -0.09996696,  0.0730388 ]),
 70: array([ 0.34673296, -0.11439578, -0.32738672,  0.05848224,  0.04665807,
         0.22045115,  0.56701527, -0.00652848,  0.12301187,  0.02844549,
        -0.02339037,  0.10163948, -0.23464098,  0.11959528, -0.10783443,
        -0.03967775,  0.06216772, -0.08684279,  0.03592559, -0.04597471,
        -0.02073179,  0.05782561, -0.08966165, -0.04315038,  0.07025082]),
 72: array([ 0.29180361, -0.0870387 , -0.26029882, -0.05579534,  0.21218115,
         0.07575802,  0.29817923, -0.29613517, -0.07505826,  0.03588828,
        -0.49927121, -0.2619704 , -0.10748509, -0.18372596,  0.10138594,
         0.02672505,  0.10729553, -0.08331161, -0.08718326,  0.00828629,
        -0.03148792,  0.0179722 ,  0.01699213,  0.03956909,  0.03660627]),
 80: array([ 1.08412352e-01, -5.80705094e-02, -3.20367894e-01,  8.30320963e-02,
         7.00188960e-02,  1.24437536e-01,  4.47216170e-01, -5.32039873e-02,
         5.54747494e-02,  5.25041728e-02,  1.16474448e-01, -1.39108800e-01,
        -1.67618140e-01,  6.91025994e-02, -2.35084494e-01, -7.92398187e-03,
        -2.53665743e-04,  1.68665438e-02, -1.72025951e-03, -1.26461495e-02,
         6.35335329e-02,  8.42048206e-02, -9.64837947e-02, -1.91664316e-02,
        -4.58609690e-02]),
 99: array([ 0.51806781, -0.06126456,  0.05496137,  0.03121001,  0.12342011,
        -0.12720681,  0.07182208, -0.22997059, -0.11854308,  0.02936995,
        -0.47082223, -0.14657611, -0.12632791, -0.16948238,  0.09952988,
         0.025601  ,  0.10259158, -0.05690249,  0.04757269, -0.0581551 ,
         0.04207972,  0.07806024, -0.02702374,  0.06287265, -0.050435  ]),
 151: array([ 0.0589604 , -0.02289786, -0.11527131,  0.03611552,  0.08007111,
         0.10545398,  0.293809  ,  0.00411246,  0.04744257, -0.1805046 ,
        -0.19674373,  0.21967602, -0.14946051, -0.04642527,  0.06765125,
        -0.03017815,  0.06543686, -0.16774484,  0.09403956, -0.09955639,
         0.03860499,  0.13310381, -0.05823012,  0.07354852,  0.07193019]),
 152: array([ 0.44307764,  0.20681192,  0.19456673,  0.13347463, -0.01799888,
        -0.15355355,  0.17460126,  0.01924151, -0.15151035, -0.19004373,
         0.32034581, -0.18123204, -0.17608877, -0.00776646,  0.46897119,
         0.06149311,  0.05899562, -0.00353103, -0.04299265,  0.03621808,
        -0.0418036 , -0.06595765, -0.02684919, -0.01159536,  0.06735892]),
 153: array([ 0.1388464 , -0.06370422, -0.22887319, -0.06793981,  0.11201407,
         0.07280563,  0.28706067, -0.2149022 , -0.04696408,  0.17588372,
        -0.1310208 , -0.14933388,  0.13032787,  0.04152332,  0.03395578,
         0.03179334,  0.06592239, -0.05291327, -0.19433884,  0.0847989 ,
        -0.0629861 , -0.07944398, -0.00129002, -0.03917197,  0.09632046]),
 154: array([ 7.81800171e-01, -1.05596463e-01,  1.48234533e-01,  4.81434009e-02,
        -2.19187801e-01,  1.58159146e-01,  1.61026804e-01,  1.20414869e-02,
         1.09644697e-01,  2.53080855e-01, -5.16981756e-02,  4.87170432e-04,
        -1.56820193e-01,  5.53181483e-02,  6.19747829e-02,  3.86266683e-02,
        -4.91329144e-03,  1.41378230e-03,  4.97825526e-03,  4.24297163e-02,
        -6.79373500e-02, -5.06028942e-02,  1.77664105e-02, -1.11980601e-02,
         1.02387513e-02]),
 156: array([ 0.51720977, -0.06141064,  0.13768257,  0.05386967, -0.15284549,
         0.07060652,  0.12045583, -0.00821527,  0.18807694,  0.45648689,
        -0.10710919,  0.01364301, -0.20833817,  0.15126414,  0.08111594,
         0.02606352, -0.0785922 , -0.0340765 , -0.0390788 ,  0.02412349,
        -0.07384792, -0.05060651,  0.02660228,  0.00097574,  0.07423878]),
 157: array([ 0.2653131 , -0.12085406, -0.31956759, -0.13143927,  0.17087433,
        -0.19692472, -0.03846231, -0.24094061, -0.28598346, -0.02474755,
        -0.13298895,  0.0041394 , -0.03182711,  0.12499916, -0.04077397,
         0.08933915, -0.03024551,  0.08756403,  0.1339395 , -0.09109061,
         0.04496922, -0.04203001, -0.07198857, -0.05016214, -0.0391924 ]),
 162: array([ 0.4490466 ,  0.01222816,  0.18188889,  0.19837399,  0.17499199,
         0.10307716,  0.28203055,  0.23041277, -0.13830488, -0.19901341,
        -0.09894524,  0.35739137, -0.03938068, -0.14355443,  0.06507092,
        -0.14722049, -0.10126381,  0.37739457, -0.04381998,  0.04845881,
        -0.07656606, -0.05464909,  0.07893203, -0.02826822, -0.1017739 ]),
 163: array([ 0.59754451,  0.07144792,  0.3154808 ,  0.2027948 ,  0.00099576,
        -0.25930627,  0.19458426, -0.00464259, -0.15331363, -0.22532062,
         0.18619396, -0.15145305, -0.02304978, -0.03325675,  0.16286099,
         0.01047854,  0.02673252, -0.06756808,  0.01790364, -0.00881657,
        -0.02588443, -0.00438122, -0.03217815, -0.02549859, -0.02300522]),
 164: array([ 1.56137564e-04, -8.53071870e-05, -2.03515508e-04, -2.16708852e-04,
         4.17652627e-05, -2.01303866e-04, -1.73995631e-04, -1.22209456e-04,
        -3.14594875e-04, -5.87692699e-04, -3.03437502e-04, -3.96187126e-05,
         2.73564501e-04,  1.61623979e-03,  8.13643942e-05, -5.43406187e-04,
         8.50107046e-05,  4.11721729e-04, -7.84174798e-04, -1.03512947e-04,
         2.88124492e-04,  2.43873662e-04, -4.48264972e-04,  5.82372485e-04,
        -3.29533717e-04]),
 165: array([ 0.11880009, -0.07758911, -0.33099046, -0.02238259,  0.12886346,
         0.13340181,  0.54173813, -0.13457768, -0.00199011,  0.13754658,
         0.13909214, -0.20308479, -0.07296762,  0.08459298, -0.26610646,
        -0.0601606 , -0.05904763,  0.04449238, -0.07648316, -0.0071471 ,
        -0.03474395, -0.08643017,  0.01230197, -0.02884864,  0.03388328]),
 167: array([ 0.3429446 , -0.13114367, -0.29965933, -0.14552226,  0.04864482,
        -0.02304286,  0.1243567 , -0.14617462, -0.10169077,  0.17548253,
         0.06252585, -0.08928476, -0.07320167,  0.11734021, -0.10710577,
        -0.03051124,  0.01701909,  0.16213846,  0.10123897, -0.02246789,
         0.02561864,  0.02958931, -0.01181575, -0.00508001, -0.06028809]),
 170: array([ 0.72865423, -0.17719512,  0.09161079, -0.12077459, -0.31039553,
         0.32129946, -0.10971066, -0.02339423, -0.0332271 ,  0.03490841,
         0.05541908,  0.04398325,  0.00893905, -0.08517114, -0.00867639,
         0.02725986,  0.05860638,  0.06658248,  0.04384196,  0.01515863,
        -0.00812618, -0.00645345, -0.01790289,  0.01790848,  0.00104771]),
 171: array([ 0.72104459, -0.12332325,  0.20148446, -0.02465222, -0.31543186,
         0.16912313, -0.04065262, -0.00382909,  0.04162561,  0.12770581,
        -0.00376685, -0.00813689, -0.03634027, -0.04592967, -0.00404678,
         0.0374375 ,  0.02306558, -0.01923033,  0.05968988, -0.01080936,
        -0.02361076,  0.03518164, -0.00692958,  0.00217085,  0.00271904]),
 173: array([ 7.69665994e-01, -1.19320909e-01,  1.80996848e-01, -7.15943264e-03,
        -2.72916485e-01,  1.45364544e-01, -1.66332949e-02,  5.96807226e-03,
         1.11659412e-01,  2.70903278e-01, -7.73647662e-02,  6.25339717e-03,
        -1.32462215e-01,  4.30343723e-02,  7.62244452e-02,  5.37124243e-02,
         3.99779232e-02,  2.47596617e-02,  7.22192383e-02,  3.66635876e-03,
        -4.59405991e-02,  1.48998073e-02, -8.76209353e-03, -4.43016702e-04,
         2.16666212e-02]),
 174: array([ 0.05245351, -0.01770232, -0.11796681,  0.01323054,  0.04686609,
         0.07330866,  0.3071899 , -0.04314675,  0.00432553,  0.00573014,
         0.1947442 , -0.20107204, -0.12541018,  0.05828796,  0.02202938,
        -0.04564197, -0.07765292,  0.03694013,  0.13331426, -0.07387436,
         0.0076204 ,  0.06974584, -0.00745472,  0.09651045,  0.03351624]),
 175: array([ 0.09322616, -0.03199081, -0.21115404,  0.09414358,  0.06393866,
         0.1521058 ,  0.47807041,  0.02132967,  0.06873386, -0.09999935,
         0.07454346,  0.15286902, -0.22174813,  0.07797977,  0.04464731,
        -0.06669635, -0.01477588, -0.09411428,  0.24057383, -0.16561124,
         0.05528727,  0.17227436, -0.10624567,  0.08906076,  0.09088973]),
 180: array([ 0.40993839, -0.09315015, -0.15456715, -0.09575   ,  0.18435076,
        -0.26059104, -0.03947246, -0.21831626, -0.26136972, -0.04880612,
        -0.21591874,  0.02459773,  0.00279603, -0.05047137,  0.01708333,
         0.0102318 ,  0.03782069, -0.0815962 ,  0.0116536 , -0.04117604,
         0.07117681,  0.01605431, -0.07775573, -0.04195457, -0.03141613]),
 181: array([ 0.13613932,  0.70555647, -0.17369551, -0.09119598, -0.03620644,
         0.04660553, -0.05436161, -0.04264341,  0.06196539,  0.01326504,
        -0.03826101,  0.0442272 ,  0.03447943, -0.03718812, -0.05373928,
        -0.02697094,  0.03606567,  0.07789119, -0.012336  ,  0.01287367,
         0.02509228,  0.02454426, -0.04661043,  0.04070733,  0.05424831]),
 183: array([ 0.09339343, -0.05008721, -0.18140583, -0.01942147,  0.06433811,
        -0.00331135,  0.1660275 , -0.04754334, -0.01896471,  0.01443641,
         0.00135727, -0.09341502, -0.07767861,  0.05045334, -0.16164441,
         0.24811096, -0.06814945,  0.10068828,  0.00526764,  0.02607866,
         0.02831563, -0.06279598, -0.07052649,  0.01095944, -0.06163066]),
 184: array([ 0.41214696, -0.16603626, -0.25778198, -0.20408613, -0.02481377,
        -0.10418047, -0.10892169, -0.00609987, -0.07064497, -0.1112201 ,
        -0.13334348,  0.0270699 , -0.01022849,  0.27017241,  0.05416187,
         0.0302371 , -0.01506471, -0.01466289, -0.02977443, -0.04703377,
        -0.05564664, -0.04937998, -0.05027676, -0.20121676, -0.00081585]),
 185: array([ 6.61621857e-01, -3.11316837e-02,  2.63638382e-01,  1.24461791e-01,
        -1.49665062e-02, -2.06760390e-01,  6.03518335e-02, -5.89724861e-02,
        -6.78176492e-02,  8.94819775e-02,  3.04615756e-03,  5.16459080e-02,
         3.56546799e-02,  8.99192727e-02, -6.30886084e-02, -1.82810386e-02,
         2.29693799e-01,  8.28719045e-02, -9.83334713e-03,  2.74192232e-02,
        -2.66420709e-02,  1.44639219e-02, -6.82076404e-02, -8.26089599e-05,
        -5.96212214e-02]),
 188: array([ 0.19658038,  0.76964618, -0.1234094 , -0.05198684, -0.05040106,
         0.00122927,  0.01487351, -0.0363826 , -0.08445063, -0.13446457,
         0.20446341, -0.12724423, -0.16619919,  0.00619102,  0.29991333,
         0.05942761,  0.02311724, -0.02638857, -0.03011077,  0.02664102,
        -0.08854824, -0.11148694,  0.05493301, -0.02114014,  0.03771079]),
 192: array([ 0.56009252, -0.08637582,  0.01624134, -0.0020507 ,  0.08041151,
        -0.30782969,  0.01010808, -0.09365889, -0.18326015, -0.19434121,
        -0.14416783, -0.04813507,  0.08254622,  0.1700148 , -0.08955747,
        -0.00229525,  0.00307879, -0.06188733,  0.02237832, -0.06611495,
        -0.05444904, -0.03239174, -0.06625106, -0.16876537, -0.05028643]),
 193: array([ 0.2728963 , -0.0585379 , -0.12195087, -0.050052  ,  0.21355461,
        -0.05901154,  0.06442149, -0.31167008, -0.16748431, -0.07195327,
        -0.59927746, -0.21759951, -0.14627661, -0.29174194,  0.1700478 ,
         0.03806516,  0.06532782, -0.14953195, -0.0169457 , -0.08867748,
         0.04685213,  0.05194894, -0.01580016,  0.06657368, -0.00356477]),
 217: array([ 7.23748432e-01, -1.55843787e-01,  6.27743761e-02, -1.36067716e-01,
        -3.53539099e-01,  3.00658687e-01, -1.02389560e-01, -5.08356527e-03,
         3.57435217e-03, -4.42528461e-05, -3.94309886e-03, -2.45091448e-02,
        -6.20612031e-03, -5.33329549e-02, -1.48741725e-02,  4.18451834e-02,
        -2.18207007e-02, -3.43203355e-02,  6.39589926e-02, -1.13605453e-02,
        -1.34472048e-02,  2.55477542e-02,  1.22792322e-02, -1.17943144e-02,
        -1.38352460e-02]),
 463: array([ 0.43355035, -0.11749574, -0.1555013 , -0.10322214,  0.0849019 ,
        -0.21337234, -0.05441156, -0.17202832, -0.21033312,  0.09359695,
        -0.05818153,  0.15421019, -0.02882115,  0.23344183,  0.02164388,

In [21]:
data2["vector"] = data2["picked_item"].apply(lambda x: FeatureVectors[int(x)])

data2

       user  picked_item                                             vector
0        46          295  [0.198105271095, -0.120441564893, -0.513285157...
1      1326          288  [0.264864077083, -0.151376289625, -0.591367725...
2      1535         7123  [0.026714469914, -0.0102648091517, -0.05784553...
3       650         3902  [0.335463886333, -0.132924508804, -0.230038553...
4      1769         1243  [0.303273924208, -0.152522102457, -0.367109724...
...     ...          ...                                                ...
96728   411          475  [0.0740732304714, -0.0518889850447, -0.4298387...
96729   357         6388  [0.0682554059354, -0.0538198237039, -0.4372134...
96730  1822         9155  [0.0124508073157, -0.00227429826354, -0.003006...
96731  1217          707  [0.29812985971, 0.781472297137, -0.09547337719...
96732   510         1925  [0.25096783412, -0.0630546147527, -0.069006850...

[96733 rows x 3 columns]

In [36]:
mean_vectors  = data2.groupby("user")["vector"].mean()
result_df = pd.DataFrame({'user': mean_vectors.index, 'mean_vector': mean_vectors.values})
result_df

# user_vectors

      user                                        mean_vector
0        1  [0.14651610408492, -0.03524186513439, -0.13151...
1       10  [0.2323631672838095, -0.08155480954594285, -0....
2      100  [0.38110215476591164, 0.028847463113691175, 0....
3     1000  [0.5010557456564286, 0.012765960823234642, 0.0...
4     1001  [0.20597415220017776, -0.09423752447720299, -0...
...    ...                                                ...
1887   995  [0.33490970290478894, -0.06003423397522645, -0...
1888   996  [0.394614651284, -0.10621367388695, 0.04733795...
1889   997  [0.38380028034067065, -0.019712678101738424, 0...
1890   998  [0.13048619508163245, -0.019063641214482705, -...
1891   999  [0.00151197399274, -0.000253994902072, -0.0016...

[1892 rows x 2 columns]

In [37]:
result_df[['u{}'.format(i) for i in range(len(result_df['mean_vector'][0]))]] = result_df['mean_vector'].apply(pd.Series)
result_df = result_df.drop('mean_vector', axis=1)
result_df

,user,u0,u1,u2,u3,u4,u5,u6,u7,u8,...,u15,u16,u17,u18,u19,u20,u21,u22,u23,u24
0,1,0.146516,-0.035242,-0.131514,0.083956,0.086915,0.030891,0.187623,-0.029845,0.020943,...,0.055610,0.026923,-0.078993,0.021650,-0.031373,0.022851,0.047545,-0.056427,0.031172,0.005416
1,10,0.232363,-0.081555,-0.248638,0.027093,0.095547,-0.101298,-0.084566,-0.090268,-0.071834,...,-0.000021,-0.011883,0.037535,0.044342,-0.017238,-0.004193,-0.038553,-0.014560,-0.027404,-0.009196
2,100,0.381102,0.028847,0.005632,0.007148,0.054034,-0.037941,-0.020789,-0.013469,-0.012093,...,-0.000951,0.011067,-0.015101,-0.007707,0.001102,0.059045,0.009473,0.027300,-0.004653,0.004550
3,1000,0.501056,0.012766,0.024526,-0.012577,-0.021955,-0.083902,-0.030951,0.041419,0.084193,...,0.010787,0.000394,-0.002209,0.022088,-0.003369,-0.003611,0.010476,-0.016955,0.001728,-0.011246
4,1001,0.205974,-0.094238,-0.280693,-0.112118,0.095212,-0.180953,-0.035970,-0.009452,-0.083246,...,-0.018163,-0.012631,0.000735,-0.075945,0.053570,-0.103092,0.118748,0.049006,0.156359,0.039533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1887,995,0.334910,-0.060034,-0.046841,-0.021949,0.031356,-0.115047,-0.005808,0.020633,0.003952,...,0.001726,-0.002547,-0.026334,0.040394,0.002703,-0.024378,-0.015015,-0.016494,-0.023620,-0.004378
1888,996,0.394615,-0.106214,0.047338,-0.091694,-0.255788,0.204071,-0.065478,-0.001207,-0.017908,...,0.037049,-0.030204,-0.037304,0.024258,0.002283,0.009137,0.001110,-0.003936,-0.019321,0.023620
1889,997,0.383800,-0.019713,0.005815,0.021731,0.291234,0.071020,-0.125398,0.076468,-0.000342,...,0.010982,-0.008682,-0.015261,0.003954,0.012496,0.041983,0.006839,0.014767,-0.024760,0.030195
1890,998,0.130486,-0.019064,-0.101496,0.003898,0.115576,0.008739,0.104791,-0.011906,0.080871,...,0.100098,-0.005045,-0.015133,0.026074,0.001952,0.003328,0.057320,-0.014684,0.006163,-0.002116
1891,999,0.001512,-0.000254,-0.001659,0.000457,0.000626,-0.000722,-0.000681,-0.000820,0.000123,...,0.000086,0.003376,0.002199,-0.000081,-0.003294,0.002052,0.000178,-0.000414,0.003493,0.005965

In [ ]:
result_df.to_csv('./lastfm_User_Glovemean_FeatureVectors.csv', sep=' ', index=False, header=True)

In [ ]:
#数据读入预处理
import pandas as pd
event_file = r"./Arm_FeatureVectors_2.dat"
data = pd.read_csv('data.txt', sep='\t', header=None, names=['user', 'timestamp', 'armpool'])

# user_id_list, user_documents_list, user_documents_dict = data_process_user(event_file) # 返回前一周的user列表，元素是venue id

# # 初始化 TfidfVectorizer
# vectorizer = TfidfVectorizer()
# # 计算 TF-IDF
# tfidf_matrix = vectorizer.fit_transform(user_documents_list) # 每一行代表一个文章，每一列代表一个单词
# #将稀疏矩阵转化为密集矩阵再转化为array
# dense_matrix = np.asarray(csr_matrix.todense(tfidf_matrix))
# # 创建 PCA 对象，指定降维后的维度为 25
# pca = PCA(n_components=25)
# # 对数据矩阵进行拟合和转换
# X_projected = pca.fit_transform(dense_matrix)
# #将降维后的向量与user id 匹配
# filename = 'User_FeatureVectors.dat'
# with open(filename, 'w', newline='') as f:
#     for i in range(X_projected.shape[0]):
#         new_line = str(user_id_list[i]) + '\t' + ';'.join(str(X_projected[i, :]).strip('[').strip(']').split()) + '\n'
#         f.write(new_line)

# 读取没有列名的CSV文件
data = pd.read_csv("./POI_Glove_FeatureVectors.csv", header=0, sep=' ')
FeatureVectors = {}
for index, row in data.iterrows():
    key = int(row[0])
    value = row[1:].tolist()
    FeatureVectors[key] = np.array(value)
# cat_id_map_dict = {}

# with open("./dataset/foursquare/cat_id_map_dict.json", 'r') as f:
#     cat_id_map_dict = json.load(f)
with open("./cat_id_map_dict.json", 'r') as f:
    cat_id_map_dict = json.load(f)

users = []
userfeatures = []
for user in user_documents_dict:
    list = user_documents_dict[user]
    newlist =  [cat_id_map_dict.get(item) for item in list]
    featurelist = [FeatureVectors.get(item) for item in newlist]
    featuremean = np.mean(featurelist,axis = 0)
    users.append(user)
    userfeatures.append(featuremean)
users_glove_feature = pd.DataFrame({'uid': users, 'featuremean': userfeatures})
# 展开userfeatures列
users_glove_feature_expanded = users_glove_feature["featuremean"].apply(pd.Series)
users_glove_feature_expanded.columns = [f"u{i}" for i in range(len(users_glove_feature_expanded.columns))]
# 合并展开后的列和原始列
result_df = pd.concat([users_glove_feature.drop("featuremean", axis=1), users_glove_feature_expanded], axis=1)
result_df