In [5]:
import torchtext
import re
import numpy as np
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
import pandas as pd

categories_week = np.array(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])
categories_day = np.array(['morning', 'noon', 'afternoon', 'night', 'rest'])

embedding = torchtext.vocab.GloVe(name='840B', dim=300)
category_embedding = [] #np.zeros(shape=(35, 300), dtype=np.float32)
keys = []
for i, text1 in enumerate(categories_week):
    for j, text2 in enumerate(categories_day):
        text = text1 + ' ' + text2
        clean_text = re.sub(r'[^\w\s]','',text)
        token = word_tokenize(clean_text)
        print(token)
        key = text1[:3] + ' ' + text2
        keys.append(key)
        category_embedding.append(embedding.get_vecs_by_tokens(token).numpy().mean(axis=0))
category_df = pd.DataFrame(category_embedding)
category_df.index = keys
category_df

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\89660\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

['Monday', 'morning']
['Monday', 'noon']
['Monday', 'afternoon']
['Monday', 'night']
['Monday', 'rest']
['Tuesday', 'morning']
['Tuesday', 'noon']
['Tuesday', 'afternoon']
['Tuesday', 'night']
['Tuesday', 'rest']
['Wednesday', 'morning']
['Wednesday', 'noon']
['Wednesday', 'afternoon']
['Wednesday', 'night']
['Wednesday', 'rest']
['Thursday', 'morning']
['Thursday', 'noon']
['Thursday', 'afternoon']
['Thursday', 'night']
['Thursday', 'rest']
['Friday', 'morning']
['Friday', 'noon']
['Friday', 'afternoon']
['Friday', 'night']
['Friday', 'rest']
['Saturday', 'morning']
['Saturday', 'noon']
['Saturday', 'afternoon']
['Saturday', 'night']
['Saturday', 'rest']
['Sunday', 'morning']
['Sunday', 'noon']
['Sunday', 'afternoon']
['Sunday', 'night']
['Sunday', 'rest']

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
Mon morning,0.105511,0.591770,0.146040,0.415545,-0.471540,-0.125739,-0.278390,-0.200495,-0.024554,2.87255,...,0.244820,-0.087701,0.571835,-0.354570,-0.317945,-0.337165,0.073606,0.011046,-0.391135,-0.140610
Mon noon,0.158376,0.528650,0.457560,0.428620,-0.271824,-0.038635,-0.003960,-0.031315,0.103331,2.54070,...,0.481330,-0.056364,0.339795,-0.387220,-0.317350,-0.344525,0.044839,0.108829,-0.356755,0.051075
Mon afternoon,0.305836,0.498325,0.293875,0.447710,-0.336044,-0.118920,-0.204525,-0.150691,-0.049168,2.93295,...,0.435405,-0.112886,0.434045,-0.369885,-0.280170,-0.300265,0.113341,0.073890,-0.387610,-0.180675
Mon night,0.140516,0.392570,0.319425,0.292174,-0.309738,-0.205435,-0.108681,-0.232965,-0.037190,2.81365,...,0.187070,-0.060350,0.430750,-0.248420,-0.250919,-0.119340,-0.042319,0.120375,-0.241515,-0.216470
Mon rest,-0.006936,0.303600,0.201214,0.356960,-0.365870,-0.127860,-0.303595,0.012845,0.147080,2.68170,...,0.092925,-0.150260,0.212895,-0.389125,-0.190675,-0.333850,-0.007532,-0.030810,-0.304670,-0.146160
Tue morning,0.174642,0.563970,0.200340,0.451905,-0.476590,-0.101299,-0.217990,-0.228365,-0.083295,2.91660,...,0.244315,-0.113826,0.530340,-0.406585,-0.374925,-0.319225,0.100875,-0.091679,-0.398560,-0.129625
Tue noon,0.227507,0.500850,0.511860,0.464980,-0.276874,-0.014195,0.056440,-0.059185,0.044590,2.58475,...,0.480825,-0.082489,0.298300,-0.439235,-0.374330,-0.326585,0.072108,0.006105,-0.364180,0.062060
Tue afternoon,0.374967,0.470525,0.348175,0.484070,-0.341094,-0.094480,-0.144125,-0.178561,-0.107909,2.97700,...,0.434900,-0.139011,0.392550,-0.421900,-0.337150,-0.282325,0.140610,-0.028835,-0.395035,-0.169690
Tue night,0.209646,0.364770,0.373725,0.328534,-0.314788,-0.180995,-0.048281,-0.260835,-0.095931,2.85770,...,0.186565,-0.086475,0.389255,-0.300435,-0.307899,-0.101400,-0.015050,0.017650,-0.248940,-0.205485
Tue rest,0.062195,0.275800,0.255514,0.393320,-0.370920,-0.103420,-0.243195,-0.015025,0.088340,2.72575,...,0.092420,-0.176385,0.171400,-0.441140,-0.247655,-0.315910,0.019738,-0.133535,-0.312095,-0.135175
Wed morning,0.151258,0.535750,0.218060,0.449435,-0.440660,-0.093654,-0.220610,-0.176580,-0.111220,2.91675,...,0.294200,-0.105291,0.513285,-0.400205,-0.383845,-0.322305,0.094035,-0.065658,-0.322233,-0.107845
Wed noon,0.204123,0.472630,0.529580,0.462510,-0.240944,-0.006550,0.053820,-0.007400,0.016665,2.58490,...,0.530710,-0.073955,0.281245,-0.432855,-0.383250,-0.329665,0.065269,0.032126,-0.287853,0.083840
Wed afternoon,0.351583,0.442305,0.365895,0.481600,-0.305164,-0.086835,-0.146745,-0.126776,-0.135834,2.97715,...,0.484785,-0.130476,0.375495,-0.415520,-0.346070,-0.285405,0.133770,-0.002814,-0.318708,-0.147910
Wed night,0.186264,0.336550,0.391445,0.326064,-0.278858,-0.173350,-0.050901,-0.209050,-0.123856,2.85785,...,0.236450,-0.077940,0.372200,-0.294055,-0.316819,-0.104480,-0.021890,0.043671,-0.172613,-0.183705
Wed rest,0.038812,0.247580,0.273234,0.390850,-0.334990,-0.095775,-0.245815,0.036760,0.060415,2.72590,...,0.142305,-0.167850,0.154345,-0.434760,-0.256575,-0.318990,0.012898,-0.107514,-0.235768,-0.113395
Thu morning,0.181780,0.583375,0.202835,0.435145,-0.459000,-0.156965,-0.236595,-0.232180,-0.086885,2.91900,...,0.260965,-0.110061,0.498245,-0.430300,-0.376780,-0.336340,0.092201,-0.025807,-0.340010,-0.120915
Thu noon,0.234645,0.520255,0.514355,0.448220,-0.259284,-0.069860,0.037835,-0.063000,0.041000,2.58715,...,0.497475,-0.078725,0.266205,-0.462950,-0.376185,-0.343700,0.063434,0.071976,-0.305630,0.070770
Thu afternoon,0.382105,0.489930,0.350670,0.467310,-0.323504,-0.150145,-0.162730,-0.182376,-0.111499,2.97940,...,0.451550,-0.135246,0.360455,-0.445615,-0.339005,-0.299440,0.131935,0.037036,-0.336485,-0.160980
Thu night,0.216785,0.384175,0.376220,0.311774,-0.297198,-0.236660,-0.066886,-0.264650,-0.099520,2.86010,...,0.203215,-0.082710,0.357160,-0.324150,-0.309754,-0.118515,-0.023725,0.083521,-0.190390,-0.196775
Thu rest,0.069333,0.295205,0.258009,0.376560,-0.353330,-0.159085,-0.261800,-0.018840,0.084750,2.72815,...,0.109070,-0.172620,0.139305,-0.464855,-0.249510,-0.333025,0.011063,-0.067664,-0.253545,-0.126465
Fri morning,0.146173,0.484400,0.081900,0.423505,-0.337025,-0.151015,-0.232330,-0.183455,-0.041830,2.80990,...,0.115701,-0.055315,0.500105,-0.389890,-0.308115,-0.373145,0.096332,0.004858,-0.303396,-0.128495
Fri noon,0.199038,0.421280,0.393420,0.436580,-0.137309,-0.063910,0.042100,-0.014275,0.086055,2.47805,...,0.352212,-0.023979,0.268065,-0.422540,-0.307520,-0.380505,0.067566,0.102642,-0.269017,0.063190
Fri afternoon,0.346497,0.390955,0.229735,0.455670,-0.201529,-0.144195,-0.158465,-0.133651,-0.066445,2.87030,...,0.306286,-0.080501,0.362315,-0.405205,-0.270339,-0.336245,0.136067,0.067702,-0.299872,-0.168560
Fri night,0.181177,0.285200,0.255285,0.300133,-0.175223,-0.230710,-0.062621,-0.215925,-0.054466,2.75100,...,0.057951,-0.027965,0.359020,-0.283740,-0.241089,-0.155320,-0.019593,0.114187,-0.153776,-0.204355
Fri rest,0.033726,0.196230,0.137074,0.364920,-0.231355,-0.153135,-0.257535,0.029885,0.129805,2.61905,...,-0.036193,-0.117875,0.141165,-0.424445,-0.180845,-0.369830,0.015194,-0.036998,-0.216931,-0.134045
Sat morning,0.288265,0.477720,0.138865,0.452100,-0.396785,-0.134595,-0.242040,-0.059080,-0.126755,2.89665,...,0.319290,-0.077666,0.346840,-0.368135,-0.212980,-0.333665,0.122080,0.064711,-0.333860,-0.123475
Sat noon,0.341130,0.414600,0.450385,0.465175,-0.197069,-0.047490,0.032390,0.110101,0.001130,2.56480,...,0.555800,-0.046329,0.114800,-0.400785,-0.212385,-0.341025,0.093314,0.162495,-0.299480,0.068210
Sat afternoon,0.488590,0.384275,0.286700,0.484265,-0.261289,-0.127775,-0.168175,-0.009275,-0.151369,2.95705,...,0.509875,-0.102851,0.209050,-0.383450,-0.175205,-0.296765,0.161815,0.127555,-0.330335,-0.163540
Sat night,0.323270,0.278520,0.312250,0.328728,-0.234983,-0.214290,-0.072331,-0.091550,-0.139390,2.83775,...,0.261540,-0.050315,0.205755,-0.261985,-0.145954,-0.115840,0.006155,0.174040,-0.184240,-0.199335
Sat rest,0.175818,0.189550,0.194039,0.393515,-0.291115,-0.136715,-0.267245,0.154261,0.044880,2.70580,...,0.167395,-0.140225,-0.012100,-0.402690,-0.085710,-0.330350,0.040942,0.022855,-0.247395,-0.129025
Sun morning,0.185995,0.476030,0.188855,0.454660,-0.420675,-0.122929,-0.205835,0.069550,-0.113155,2.89095,...,0.343270,-0.141845,0.380870,-0.423605,-0.260720,-0.326965,0.094929,0.048186,-0.241138,-0.226110
Sun noon,0.238860,0.412910,0.500375,0.467735,-0.220959,-0.035825,0.068595,0.238730,0.014730,2.55910,...,0.579780,-0.110509,0.148830,-0.456255,-0.260125,-0.334325,0.066162,0.145970,-0.206758,-0.034425
Sun afternoon,0.386320,0.382585,0.336690,0.486825,-0.285179,-0.116110,-0.131970,0.119354,-0.137769,2.95135,...,0.533855,-0.167031,0.243080,-0.438920,-0.222944,-0.290065,0.134664,0.111030,-0.237613,-0.266175
Sun night,0.221000,0.276830,0.362240,0.331289,-0.258873,-0.202625,-0.036126,0.037080,-0.125791,2.83205,...,0.285520,-0.114495,0.239785,-0.317455,-0.193694,-0.109140,-0.020996,0.157515,-0.091518,-0.301970
Sun rest,0.073548,0.187860,0.244029,0.396075,-0.315005,-0.125050,-0.231040,0.282890,0.058480,2.70010,...,0.191375,-0.204405,0.021930,-0.458160,-0.133450,-0.323650,0.013791,0.006330,-0.154673,-0.231660

In [8]:
from sklearn.decomposition import PCA
n_components  = 30
pca = PCA(n_components=n_components)
item_df_for_pca = category_df
pca.fit(item_df_for_pca)
item_pca = pca.transform(item_df_for_pca)
item_pca

array([[-2.89241970e-01,  1.77991062e-01, -1.25704598e+00, ...,
         1.67638063e-08, -3.72529030e-09,  4.28408384e-08],
       [-1.27574253e+00, -1.30538702e+00,  2.19365463e-01, ...,
        -1.06170774e-07, -7.45058060e-09, -1.49011612e-07],
       [-5.68808198e-01,  1.91298842e-01, -8.78683805e-01, ...,
        -8.94069672e-08,  5.96046448e-08,  2.98023224e-08],
       ...,
       [-4.51690555e-01,  5.10784805e-01,  1.15717269e-01, ...,
        -1.34110451e-07,  2.60770321e-08, -1.07102096e-07],
       [ 2.97008306e-01,  1.33169866e+00,  1.27111328e+00, ...,
         0.00000000e+00, -2.23517418e-08, -1.04308128e-07],
       [ 2.11321712e+00, -5.36241174e-01,  6.43473148e-01, ...,
        -1.09896064e-07, -4.47034836e-08, -8.10250640e-08]], dtype=float32)

In [10]:
item_pca_df = pd.DataFrame(item_pca)
item_pca_df.index = keys
index_item_pca_df = item_pca_df.reset_index()#.rename(columns={"index":"timeId"})
index_item_pca_df.columns = ["timename"] + ["i"+str(i) for i in range(30)]
index_item_pca_df

,timename,i0,i1,i2,i3,i4,i5,i6,i7,i8,...,i20,i21,i22,i23,i24,i25,i26,i27,i28,i29
0,Mon morning,-0.289242,0.177991,-1.257046,0.308005,-0.784546,0.230671,0.048224,0.379949,0.008805,...,4.470348e-08,-4.842877e-08,-1.490116e-08,8.195639e-08,-2.235174e-08,7.450581e-09,-7.450581e-09,1.676381e-08,-3.725290e-09,4.284084e-08
1,Mon noon,-1.275743,-1.305387,0.219365,-0.394094,-0.361410,0.071475,0.204380,0.412947,0.017999,...,1.471490e-07,2.235174e-08,-1.173466e-07,1.043081e-07,-1.154840e-07,1.117587e-08,3.725290e-08,-1.061708e-07,-7.450581e-09,-1.490116e-07
2,Mon afternoon,-0.568808,0.191299,-0.878684,0.042353,0.563139,0.035360,0.320633,0.456135,0.035351,...,7.450581e-09,2.421439e-08,-1.750886e-07,1.071021e-07,8.940697e-08,2.980232e-08,-1.043081e-07,-8.940697e-08,5.960464e-08,2.980232e-08
3,Mon night,0.179891,1.012212,0.276712,-0.888235,-0.413733,-0.011168,0.221098,0.435291,0.021257,...,2.980232e-08,9.313226e-08,-1.788139e-07,9.685755e-08,4.097819e-08,-2.235174e-08,-5.215406e-08,6.705523e-08,-2.108573e-08,3.725290e-08
4,Mon rest,1.996099,-0.855727,-0.350928,-0.171364,-0.134088,0.110433,0.186585,0.418915,0.028518,...,2.086163e-07,-9.406358e-08,-8.940697e-08,2.458692e-07,1.117587e-08,3.119931e-08,-5.960464e-08,-2.235174e-08,5.960464e-08,1.005828e-07
5,Tue morning,-0.316007,0.173510,-1.302857,0.065851,-0.479508,-0.045616,-0.278990,-0.030383,-0.204603,...,-7.450581e-09,-1.396984e-07,9.685755e-08,1.769513e-08,-5.774200e-08,-4.470348e-08,1.285225e-07,7.636845e-08,-7.823110e-08,5.960464e-08
6,Tue noon,-1.302508,-1.309868,0.173554,-0.636248,-0.056371,-0.204812,-0.122833,0.002616,-0.195409,...,1.110020e-07,-8.009374e-08,4.051253e-08,-1.490116e-08,-1.341105e-07,0.000000e+00,1.657754e-07,-9.313226e-09,-6.891787e-08,-6.332994e-08
7,Tue afternoon,-0.595573,0.186818,-0.924495,-0.199801,0.868178,-0.240927,-0.006581,0.045803,-0.178057,...,-5.215406e-08,-1.266599e-07,-1.862645e-09,7.450581e-09,6.332994e-08,0.000000e+00,2.607703e-08,-8.195639e-08,4.470348e-08,8.195639e-08
8,Tue night,0.153126,1.007732,0.230901,-1.130389,-0.108694,-0.287455,-0.106115,0.024959,-0.192150,...,1.490116e-08,1.862645e-08,2.235174e-08,8.568168e-08,4.097819e-08,-1.011649e-07,1.117587e-07,1.192093e-07,-6.332994e-08,4.749745e-08
9,Tue rest,1.969334,-0.860208,-0.396739,-0.413518,0.170951,-0.165854,-0.140629,0.008584,-0.184890,...,1.639128e-07,-2.700835e-07,-2.607703e-08,1.713634e-07,1.490116e-08,2.281740e-08,1.788139e-07,7.450581e-08,1.490116e-08,1.117587e-07
10,Wed morning,-0.316858,0.216317,-1.260428,0.157854,-0.474163,-0.050387,-0.292914,-0.203165,-0.128948,...,-5.215406e-08,-4.470348e-08,2.048910e-08,4.097819e-08,3.725290e-09,-2.235174e-08,1.341105e-07,1.024455e-07,7.450581e-09,2.048910e-08
11,Wed noon,-1.303358,-1.267062,0.215983,-0.544245,-0.051026,-0.209582,-0.136757,-0.170167,-0.119754,...,7.776543e-08,3.352761e-08,-4.097819e-08,5.960464e-08,-8.195639e-08,-2.048910e-08,1.695007e-07,7.450581e-09,-2.421439e-08,-7.450581e-08
12,Wed afternoon,-0.596424,0.229624,-0.882066,-0.107798,0.873523,-0.245697,-0.020505,-0.126979,-0.102403,...,-1.378357e-07,-3.725290e-09,-1.378357e-07,8.940697e-08,1.117587e-07,-2.607703e-08,3.911555e-08,-2.980232e-08,7.450581e-08,6.705523e-08
13,Wed night,0.152275,1.050538,0.273330,-1.038386,-0.103349,-0.292226,-0.120039,-0.147823,-0.116496,...,-9.685755e-08,8.195639e-08,-1.341105e-07,7.450581e-08,9.313226e-08,-7.776543e-08,1.117587e-07,1.415610e-07,9.313226e-09,8.195639e-08
14,Wed rest,1.968482,-0.817402,-0.354310,-0.321515,0.176296,-0.170625,-0.154553,-0.164199,-0.109235,...,9.685755e-08,-2.160668e-07,-5.774200e-08,1.676381e-07,2.980232e-08,1.490116e-08,2.980232e-08,6.705523e-08,1.639128e-07,1.080334e-07
15,Thu morning,-0.377886,0.240236,-1.172698,0.165976,-0.528412,0.059350,-0.292192,-0.138349,0.320916,...,-5.215406e-08,-1.676381e-08,8.568168e-08,-5.890615e-08,9.313226e-09,4.470348e-08,9.685755e-08,1.266599e-07,0.000000e+00,4.842877e-08
16,Thu noon,-1.364386,-1.243142,0.303712,-0.536124,-0.105276,-0.099846,-0.136035,-0.105351,0.330110,...,6.542541e-08,-1.862645e-08,2.235174e-08,-5.960464e-08,-1.043081e-07,4.284084e-08,7.078052e-08,-7.450581e-08,-5.587935e-08,-1.303852e-07
17,Thu afternoon,-0.657452,0.253544,-0.794337,-0.099676,0.819273,-0.135961,-0.019783,-0.062163,0.347462,...,-6.705523e-08,4.889444e-09,-7.124618e-08,-7.450581e-09,1.043081e-07,2.980232e-08,-4.470348e-08,5.215406e-08,2.980232e-08,1.490116e-08
18,Thu night,0.091247,1.074457,0.361059,-1.030264,-0.157599,-0.182489,-0.119317,-0.083007,0.333368,...,-8.940697e-08,1.788139e-07,-1.490116e-08,7.450581e-09,1.080334e-07,-5.401671e-08,2.607703e-08,8.195639e-08,2.421439e-08,5.587935e-08
19,Thu rest,1.907455,-0.793482,-0.266581,-0.313393,0.122046,-0.060888,-0.153831,-0.099383,0.340629,...,1.005828e-07,-5.401671e-08,3.725290e-09,1.490116e-07,4.470348e-08,3.539026e-08,3.725290e-08,0.000000e+00,5.960464e-08,1.341105e-07
20,Fri morning,-0.264766,0.408839,-0.794426,0.445445,-0.612383,0.623835,0.276756,-0.267613,-0.046031,...,-1.080334e-07,-1.117587e-07,-1.303852e-08,-1.676381e-07,3.166497e-08,0.000000e+00,2.235174e-08,8.940697e-08,-4.470348e-08,1.136214e-07
21,Fri noon,-1.251266,-1.074539,0.681985,-0.256655,-0.189247,0.464639,0.432912,-0.234615,-0.036837,...,0.000000e+00,-1.490116e-08,-1.862645e-08,-1.490116e-07,-2.235174e-08,1.862645e-08,8.940697e-08,9.313226e-09,-5.681068e-08,-4.470348e-08
22,Fri afternoon,-0.544332,0.422147,-0.416064,0.179793,0.735302,0.428524,0.549165,-0.191427,-0.019485,...,-1.490116e-07,-2.235174e-08,-9.080395e-08,-1.229346e-07,1.378357e-07,5.587935e-08,-5.960464e-08,-1.117587e-08,7.450581e-09,1.303852e-07
23,Fri night,0.204367,1.243060,0.739332,-0.750796,-0.241570,0.381996,0.449630,-0.212271,-0.033578,...,-1.490116e-07,1.303852e-07,-8.195639e-08,-8.940697e-08,1.415610e-07,-1.043081e-07,1.862645e-09,1.639128e-07,-5.960464e-08,1.676381e-07
24,Fri rest,2.020575,-0.624879,0.111692,-0.033925,0.038075,0.503597,0.415117,-0.228647,-0.026318,...,3.725290e-08,-1.974404e-07,-5.308539e-08,-3.352761e-08,7.450581e-08,3.725290e-08,-7.450581e-08,6.705523e-08,7.450581e-08,1.639128e-07
25,Sat morning,-0.346887,0.623025,0.037592,1.011134,-0.266883,0.539060,-0.532426,0.043413,-0.038744,...,1.490116e-08,-1.303852e-08,1.527369e-07,-1.080334e-07,-1.713634e-07,-3.166497e-08,-6.705523e-08,-4.586764e-08,0.000000e+00,-1.247972e-07
26,Sat noon,-1.333387,-0.860354,1.514003,0.309034,0.156253,0.379864,-0.376270,0.076411,-0.029550,...,1.303852e-07,9.313226e-10,6.612390e-08,-8.940697e-08,-2.421439e-07,-1.490116e-08,-2.235174e-08,-1.378357e-07,-1.117587e-08,-2.235174e-07
27,Sat afternoon,-0.626453,0.636332,0.415953,0.745482,1.080802,0.343749,-0.260017,0.119599,-0.012198,...,-5.960464e-08,-2.793968e-09,-1.117587e-08,-1.082662e-07,-4.470348e-08,-2.142042e-08,-1.490116e-07,-1.788139e-07,8.940697e-08,-1.303852e-07
28,Sat night,0.122246,1.457246,1.571349,-0.185106,0.103930,0.297221,-0.359552,0.098755,-0.026292,...,-8.940697e-08,1.266599e-07,-1.490116e-08,-7.450581e-08,-8.568168e-08,-4.470348e-08,-3.725290e-08,-3.352761e-08,0.000000e+00,-1.043081e-07
29,Sat rest,1.938454,-0.410694,0.943709,0.531765,0.383575,0.418822,-0.394065,0.082379,-0.019031,...,1.676381e-07,-1.490116e-07,3.725290e-08,1.490116e-08,-1.154840e-07,1.266599e-07,-1.192093e-07,-3.725290e-09,1.266599e-07,-5.401671e-08
30,Sun morning,-0.172124,0.497477,-0.262644,1.546440,-0.763036,-0.353697,0.035820,-0.068741,-0.006462,...,-2.980232e-08,-5.494803e-08,2.086163e-07,-1.117587e-07,-9.313226e-08,-1.061708e-07,-2.235174e-08,-3.725290e-09,0.000000e+00,-9.406358e-08
31,Sun noon,-1.158625,-0.985901,1.213767,0.844341,-0.339900,-0.512893,0.191976,-0.035743,0.002732,...,1.601875e-07,-3.201421e-08,1.897570e-07,0.000000e+00,-2.346933e-07,-8.940697e-08,-2.980232e-08,-7.450581e-08,-7.939525e-08,-1.713634e-07
32,Sun afternoon,-0.451691,0.510785,0.115717,1.280788,0.584650,-0.549007,0.308229,0.007445,0.020084,...,-4.470348e-08,1.583248e-08,7.450581e-08,-5.960464e-08,-2.980232e-08,-7.171184e-08,-1.043081e-07,-1.341105e-07,2.607703e-08,-1.071021e-07
33,Sun night,0.297008,1.331699,1.271113,0.350200,-0.392223,-0.595535,0.208694,-0.013399,0.005990,...,-2.235174e-08,1.750886e-07,1.117587e-07,0.000000e+00,7.450581e-09,-1.639128e-07,-1.490116e-08,0.000000e+00,-2.235174e-08,-1.043081e-07
34,Sun rest,2.113217,-0.536241,0.643473,1.067071,-0.112577,-0.473935,0.174181,-0.029775,0.013251,...,1.471490e-07,-5.960464e-08,1.490116e-07,1.341105e-07,-3.725290e-08,-2.235174e-08,-5.215406e-08,-1.098961e-07,-4.470348e-08,-8.102506e-08

In [ ]:
index_item_pca_df.to_csv('./timeVectors_{}.csv'.format(n_components), sep=' ', index=False, header=True)