In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt #绘图工具
import seaborn as sns
import warnings
import random
import time
import torch
from sklearn.utils import shuffle
warnings.filterwarnings("ignore")
#设置jupyter显示多行结果
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all' #默认为'last'
# #显示所有列
pd.set_option('display.max_columns', None) #原来中间会有部分列的显示被省略
# #显示所有行
# pd.set_option('display.max_rows', None)
#设置value的显示长度为100，默认为50
pd.set_option('max_colwidth',100)
plt.rcParams['font.sans-serif'] = ['SimHei']  #显示中文
plt.rcParams['axes.unicode_minus']=False #用来正常显示负号

In [2]:
rootpath = "./KuaiRec 2.0/"

# 1. Process User Feature

In [4]:
user_features = pd.read_csv(rootpath + "data/user_features.csv")
user_features

,user_id,user_active_degree,is_lowactive_period,is_live_streamer,is_video_author,follow_user_num,follow_user_num_range,fans_user_num,fans_user_num_range,friend_user_num,friend_user_num_range,register_days,register_days_range,onehot_feat0,onehot_feat1,onehot_feat2,onehot_feat3,onehot_feat4,onehot_feat5,onehot_feat6,onehot_feat7,onehot_feat8,onehot_feat9,onehot_feat10,onehot_feat11,onehot_feat12,onehot_feat13,onehot_feat14,onehot_feat15,onehot_feat16,onehot_feat17
0,0,high_active,0,0,0,5,"(0,10]",0,0,0,0,107,61-90,0,1,17,638,2.0,0,1,6,184,6,3,0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,full_active,0,0,0,386,"(250,500]",4,"[1,10)",2,"[1,5)",327,181-365,0,3,25,1021,0.0,0,1,6,186,6,2,0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,full_active,0,0,0,27,"(10,50]",0,0,0,0,116,91-180,0,6,8,402,0.0,0,0,2,51,2,3,0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,full_active,0,0,0,16,"(10,50]",0,0,0,0,105,61-90,0,1,8,281,0.0,0,0,34,251,3,2,0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,full_active,0,0,0,122,"(100,150]",4,"[1,10)",0,0,225,181-365,0,1,8,316,1.0,0,1,46,99,4,2,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7171,7171,full_active,0,0,1,52,"(50,100]",1,"[1,10)",0,0,283,181-365,0,3,8,302,1.0,0,1,15,259,1,4,0,1.0,0.0,0.0,0.0,0.0,0.0
7172,7172,full_active,0,0,0,45,"(10,50]",2,"[1,10)",2,"[1,5)",109,91-180,0,3,25,1025,0.0,0,1,35,11,2,0,0,1.0,0.0,0.0,0.0,0.0,0.0
7173,7173,full_active,0,0,0,615,500+,3,"[1,10)",2,"[1,5)",167,91-180,0,6,8,240,1.0,0,0,2,51,2,2,0,1.0,0.0,0.0,0.0,0.0,0.0
7174,7174,full_active,0,0,0,959,500+,0,0,0,0,241,181-365,1,6,25,1029,0.0,0,1,20,107,3,2,0,0.0,0.0,0.0,0.0,0.0,0.0
7175,7175,full_active,0,0,1,98,"(100,150]",35,"[10,100)",33,"[30,60)",167,91-180,0,6,8,290,1.0,0,1,19,132,5,2,0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
#数据总缺失情况查阅
(user_features.isna().sum()/user_features.shape[0]).sort_values(ascending=False)

onehot_feat4             0.028010
onehot_feat12            0.010730
onehot_feat14            0.010452
onehot_feat13            0.010452
onehot_feat17            0.010312
onehot_feat16            0.010312
onehot_feat15            0.010312
onehot_feat3             0.000000
onehot_feat11            0.000000
onehot_feat10            0.000000
onehot_feat9             0.000000
onehot_feat8             0.000000
onehot_feat7             0.000000
onehot_feat6             0.000000
onehot_feat5             0.000000
user_id                  0.000000
user_active_degree       0.000000
onehot_feat1             0.000000
onehot_feat0             0.000000
register_days_range      0.000000
register_days            0.000000
friend_user_num_range    0.000000
friend_user_num          0.000000
fans_user_num_range      0.000000
fans_user_num            0.000000
follow_user_num_range    0.000000
follow_user_num          0.000000
is_video_author          0.000000
is_live_streamer         0.000000
is_lowactive_period      0.000000
onehot_feat2             0.000000
dtype: float64

In [6]:
# 都是onehot缺失值，用0填补
user_features = user_features.fillna(0)
# 填补完再次查看是否有缺失值
(user_features.isna().sum()/user_features.shape[0]).sort_values(ascending=False)

user_id                  0.0
onehot_feat3             0.0
onehot_feat16            0.0
onehot_feat15            0.0
onehot_feat14            0.0
onehot_feat13            0.0
onehot_feat12            0.0
onehot_feat11            0.0
onehot_feat10            0.0
onehot_feat9             0.0
onehot_feat8             0.0
onehot_feat7             0.0
onehot_feat6             0.0
onehot_feat5             0.0
onehot_feat4             0.0
onehot_feat2             0.0
user_active_degree       0.0
onehot_feat1             0.0
onehot_feat0             0.0
register_days_range      0.0
register_days            0.0
friend_user_num_range    0.0
friend_user_num          0.0
fans_user_num_range      0.0
fans_user_num            0.0
follow_user_num_range    0.0
follow_user_num          0.0
is_video_author          0.0
is_live_streamer         0.0
is_lowactive_period      0.0
onehot_feat17            0.0
dtype: float64

## User feature

### sparse_feature: 
["user_active_degree","follow_user_num_range","fans_user_num_range","friend_user_num_range","register_days_range"] 需要进行labelencoder到0-n-1  
["onehot_feat" + str(i) for i in range(1,12)]

上述进行onehot展开

["onehot_feat0"] + ["onehot_feat" + str(i) for i in range(12,18)] + ["is_lowactive_period","is_live_streamer","is_video_author"]二值向量直接拼上去即可
### dense_feature: 
["follow_user_num","fans_user_num","friend_user_num","register_days"] 需要进行minmax归一化

In [7]:
user_sparse_feature_1 = ["user_active_degree","follow_user_num_range","fans_user_num_range","friend_user_num_range","register_days_range"]
user_sparse_feature_2 = ["onehot_feat" + str(i) for i in range(1,12)]
user_sparse_feature_3 = ["onehot_feat0"] + ["onehot_feat" + str(i) for i in range(12,18)] + ["is_lowactive_period","is_live_streamer","is_video_author"]
user_dense_feature = ["follow_user_num","fans_user_num","friend_user_num","register_days"]

In [8]:
# Label Encoding for sparse features,and do simple Transformation for dense features
from sklearn import preprocessing
for feat in user_sparse_feature_1:
    lbe = preprocessing.LabelEncoder()
    user_features[feat] = lbe.fit_transform(user_features[feat])

mms = preprocessing.MinMaxScaler(feature_range=(0, 1))
user_features[user_dense_feature] = mms.fit_transform(user_features[user_dense_feature])

user_features

,user_id,user_active_degree,is_lowactive_period,is_live_streamer,is_video_author,follow_user_num,follow_user_num_range,fans_user_num,fans_user_num_range,friend_user_num,friend_user_num_range,register_days,register_days_range,onehot_feat0,onehot_feat1,onehot_feat2,onehot_feat3,onehot_feat4,onehot_feat5,onehot_feat6,onehot_feat7,onehot_feat8,onehot_feat9,onehot_feat10,onehot_feat11,onehot_feat12,onehot_feat13,onehot_feat14,onehot_feat15,onehot_feat16,onehot_feat17
0,0,2,0,0,0,0.002381,0,0.000000,0,0.000000,0,0.047661,4,0,1,17,638,2.0,0,1,6,184,6,3,0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1,0,0,0,0.183810,4,0.000351,1,0.001404,2,0.145657,1,0,3,25,1021,0.0,0,1,6,186,6,2,0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,1,0,0,0,0.012857,1,0.000000,0,0.000000,0,0.051670,6,0,6,8,402,0.0,0,0,2,51,2,3,0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,1,0,0,0,0.007619,1,0.000000,0,0.000000,0,0.046771,4,0,1,8,281,0.0,0,0,34,251,3,2,0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,1,0,0,0,0.058095,2,0.000351,1,0.000000,0,0.100223,1,0,1,8,316,1.0,0,1,46,99,4,2,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7171,7171,1,0,0,1,0.024762,5,0.000088,1,0.000000,0,0.126058,1,0,3,8,302,1.0,0,1,15,259,1,4,0,1.0,0.0,0.0,0.0,0.0,0.0
7172,7172,1,0,0,0,0.021429,1,0.000175,1,0.001404,2,0.048552,6,0,3,25,1025,0.0,0,1,35,11,2,0,0,1.0,0.0,0.0,0.0,0.0,0.0
7173,7173,1,0,0,0,0.292857,7,0.000263,1,0.001404,2,0.074388,6,0,6,8,240,1.0,0,0,2,51,2,2,0,1.0,0.0,0.0,0.0,0.0,0.0
7174,7174,1,0,0,0,0.456667,7,0.000000,0,0.000000,0,0.107350,1,1,6,25,1029,0.0,0,1,20,107,3,2,0,0.0,0.0,0.0,0.0,0.0,0.0
7175,7175,1,0,0,1,0.046667,2,0.003070,2,0.023158,4,0.074388,6,0,6,8,290,1.0,0,1,19,132,5,2,0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
# onehot sparse feature
user_features = pd.get_dummies(user_features, columns=user_sparse_feature_1+user_sparse_feature_2)
user_features

,user_id,is_lowactive_period,is_live_streamer,is_video_author,follow_user_num,fans_user_num,friend_user_num,register_days,onehot_feat0,onehot_feat12,onehot_feat13,onehot_feat14,onehot_feat15,onehot_feat16,onehot_feat17,user_active_degree_0,user_active_degree_1,user_active_degree_2,user_active_degree_3,follow_user_num_range_0,follow_user_num_range_1,follow_user_num_range_2,follow_user_num_range_3,follow_user_num_range_4,follow_user_num_range_5,follow_user_num_range_6,follow_user_num_range_7,fans_user_num_range_0,fans_user_num_range_1,fans_user_num_range_2,fans_user_num_range_3,fans_user_num_range_4,fans_user_num_range_5,fans_user_num_range_6,friend_user_num_range_0,friend_user_num_range_1,friend_user_num_range_2,friend_user_num_range_3,friend_user_num_range_4,friend_user_num_range_5,friend_user_num_range_6,register_days_range_0,register_days_range_1,register_days_range_2,register_days_range_3,register_days_range_4,register_days_range_5,register_days_range_6,onehot_feat1_0,onehot_feat1_1,onehot_feat1_2,onehot_feat1_3,onehot_feat1_4,onehot_feat1_5,onehot_feat1_6,onehot_feat1_7,onehot_feat2_0,onehot_feat2_1,onehot_feat2_2,onehot_feat2_3,onehot_feat2_4,onehot_feat2_5,onehot_feat2_6,onehot_feat2_7,onehot_feat2_8,onehot_feat2_9,onehot_feat2_10,onehot_feat2_11,onehot_feat2_12,onehot_feat2_13,onehot_feat2_14,onehot_feat2_15,onehot_feat2_16,onehot_feat2_17,onehot_feat2_18,onehot_feat2_19,onehot_feat2_20,onehot_feat2_21,onehot_feat2_22,onehot_feat2_23,onehot_feat2_24,onehot_feat2_25,onehot_feat2_26,onehot_feat2_27,onehot_feat2_28,onehot_feat2_29,onehot_feat3_0,onehot_feat3_1,onehot_feat3_2,onehot_feat3_3,onehot_feat3_4,onehot_feat3_5,onehot_feat3_6,onehot_feat3_7,onehot_feat3_8,onehot_feat3_9,onehot_feat3_10,onehot_feat3_11,onehot_feat3_12,onehot_feat3_13,onehot_feat3_14,onehot_feat3_15,onehot_feat3_16,onehot_feat3_17,onehot_feat3_18,onehot_feat3_19,onehot_feat3_20,onehot_feat3_21,onehot_feat3_22,onehot_feat3_23,onehot_feat3_24,onehot_feat3_25,onehot_feat3_26,onehot_feat3_27,onehot_feat3_28,onehot_feat3_29,onehot_feat3_30,onehot_feat3_31,onehot_feat3_32,onehot_feat3_33,onehot_feat3_34,onehot_feat3_35,onehot_feat3_36,onehot_feat3_37,onehot_feat3_38,onehot_feat3_39,onehot_feat3_40,onehot_feat3_41,onehot_feat3_42,onehot_feat3_43,onehot_feat3_44,onehot_feat3_45,onehot_feat3_46,onehot_feat3_47,onehot_feat3_48,onehot_feat3_49,onehot_feat3_50,onehot_feat3_51,onehot_feat3_52,onehot_feat3_53,onehot_feat3_54,onehot_feat3_55,onehot_feat3_56,onehot_feat3_57,onehot_feat3_58,onehot_feat3_59,onehot_feat3_60,onehot_feat3_61,onehot_feat3_62,onehot_feat3_63,onehot_feat3_64,onehot_feat3_65,onehot_feat3_66,onehot_feat3_67,onehot_feat3_68,onehot_feat3_69,onehot_feat3_70,onehot_feat3_71,onehot_feat3_72,onehot_feat3_73,onehot_feat3_74,onehot_feat3_75,onehot_feat3_76,onehot_feat3_77,onehot_feat3_78,onehot_feat3_79,onehot_feat3_80,onehot_feat3_81,onehot_feat3_82,onehot_feat3_83,onehot_feat3_84,onehot_feat3_85,onehot_feat3_86,onehot_feat3_87,onehot_feat3_88,onehot_feat3_89,onehot_feat3_90,onehot_feat3_91,onehot_feat3_92,onehot_feat3_93,onehot_feat3_94,onehot_feat3_95,onehot_feat3_96,onehot_feat3_97,onehot_feat3_98,onehot_feat3_99,onehot_feat3_100,onehot_feat3_101,onehot_feat3_102,onehot_feat3_103,onehot_feat3_104,onehot_feat3_105,onehot_feat3_106,onehot_feat3_107,onehot_feat3_108,onehot_feat3_109,onehot_feat3_110,onehot_feat3_111,onehot_feat3_112,onehot_feat3_113,onehot_feat3_114,onehot_feat3_115,onehot_feat3_116,onehot_feat3_117,onehot_feat3_118,onehot_feat3_119,onehot_feat3_120,onehot_feat3_121,onehot_feat3_122,onehot_feat3_123,onehot_feat3_124,onehot_feat3_125,onehot_feat3_126,onehot_feat3_127,onehot_feat3_128,onehot_feat3_129,onehot_feat3_130,onehot_feat3_131,onehot_feat3_132,onehot_feat3_133,onehot_feat3_134,onehot_feat3_135,onehot_feat3_136,onehot_feat3_137,onehot_feat3_138,onehot_feat3_139,onehot_feat3_140,onehot_feat3_141,onehot_feat3_142,onehot_feat3_143,onehot_feat3_144,onehot_feat3_145,onehot_feat3_146,onehot_feat3_147,onehot_feat3_148,onehot_feat3_149,onehot_feat3_150,onehot_feat3_151,onehot_feat3_152,onehot_feat3_153,onehot_feat3_154,onehot_feat3_155,onehot_feat3_156,onehot_feat3_157,onehot_feat3_158,onehot_feat3_159,onehot_feat3_160,onehot_feat3_161,onehot_feat3_162,onehot_feat3_163,onehot_feat3_164,onehot_feat3_165,onehot_feat3_166,onehot_feat3_167,onehot_feat3_168,onehot_feat3_169,onehot_feat3_170,onehot_feat3_171,onehot_feat3_172,onehot_feat3_173,onehot_feat3_174,onehot_feat3_175,onehot_feat3_176,onehot_feat3_177,onehot_feat3_178,onehot_feat3_179,onehot_feat3_180,onehot_feat3_181,onehot_feat3_182,onehot_feat3_183,onehot_feat3_184,onehot_feat3_185,onehot_feat3_186,onehot_feat3_187,onehot_feat3_188,onehot_feat3_189,onehot_feat3_190,onehot_feat3_191,onehot_feat3_192,onehot_feat3_193,onehot_feat3_194,onehot_feat3_195,onehot_feat3_196,onehot_feat3_197,onehot_feat3_198,onehot_feat3_199,onehot_feat3_200,onehot_feat3_201,onehot_feat3_202,onehot_feat3_203,onehot_feat3_204,onehot_feat3_205,onehot_feat3_206,onehot_feat3_207,onehot_feat3_208,onehot_feat3_209,onehot_feat3_210,onehot_feat3_211,onehot_feat3_212,onehot_feat3_213,onehot_feat3_214,onehot_feat3_215,onehot_feat3_216,onehot_feat3_217,onehot_feat3_218,onehot_feat3_219,onehot_feat3_220,onehot_feat3_221,onehot_feat3_222,onehot_feat3_223,onehot_feat3_224,onehot_feat3_225,onehot_feat3_226,onehot_feat3_227,onehot_feat3_228,onehot_feat3_229,onehot_feat3_230,onehot_feat3_231,onehot_feat3_232,onehot_feat3_233,onehot_feat3_234,onehot_feat3_235,onehot_feat3_236,onehot_feat3_237,onehot_feat3_238,onehot_feat3_239,onehot_feat3_240,onehot_feat3_241,onehot_feat3_242,onehot_feat3_243,onehot_feat3_244,onehot_feat3_245,onehot_feat3_246,onehot_feat3_247,onehot_feat3_248,onehot_feat3_249,onehot_feat3_250,onehot_feat3_251,onehot_feat3_252,onehot_feat3_253,onehot_feat3_254,onehot_feat3_255,onehot_feat3_256,onehot_feat3_257,onehot_feat3_258,onehot_feat3_259,onehot_feat3_260,onehot_feat3_261,onehot_feat3_262,onehot_feat3_263,onehot_feat3_264,onehot_feat3_265,onehot_feat3_266,onehot_feat3_267,onehot_feat3_268,onehot_feat3_269,onehot_feat3_270,onehot_feat3_271,onehot_feat3_272,onehot_feat3_273,onehot_feat3_274,onehot_feat3_275,onehot_feat3_276,onehot_feat3_277,onehot_feat3_278,onehot_feat3_279,onehot_feat3_280,onehot_feat3_281,onehot_feat3_282,onehot_feat3_283,onehot_feat3_284,onehot_feat3_285,onehot_feat3_286,onehot_feat3_287,onehot_feat3_288,onehot_feat3_289,onehot_feat3_290,onehot_feat3_291,onehot_feat3_292,onehot_feat3_293,onehot_feat3_294,onehot_feat3_295,onehot_feat3_296,onehot_feat3_297,onehot_feat3_298,onehot_feat3_299,onehot_feat3_300,onehot_feat3_301,onehot_feat3_302,onehot_feat3_303,onehot_feat3_304,onehot_feat3_305,onehot_feat3_306,onehot_feat3_307,onehot_feat3_308,onehot_feat3_309,onehot_feat3_310,onehot_feat3_311,onehot_feat3_312,onehot_feat3_313,onehot_feat3_314,onehot_feat3_315,onehot_feat3_316,onehot_feat3_317,onehot_feat3_318,onehot_feat3_319,onehot_feat3_320,onehot_feat3_321,onehot_feat3_322,onehot_feat3_323,onehot_feat3_324,onehot_feat3_325,onehot_feat3_326,onehot_feat3_327,onehot_feat3_328,onehot_feat3_329,onehot_feat3_330,onehot_feat3_331,onehot_feat3_332,onehot_feat3_333,onehot_feat3_334,onehot_feat3_335,onehot_feat3_336,onehot_feat3_337,onehot_feat3_338,onehot_feat3_339,onehot_feat3_340,onehot_feat3_341,onehot_feat3_342,onehot_feat3_343,onehot_feat3_344,onehot_feat3_345,onehot_feat3_346,onehot_feat3_347,onehot_feat3_348,onehot_feat3_349,onehot_feat3_350,onehot_feat3_351,onehot_feat3_352,onehot_feat3_353,onehot_feat3_354,onehot_feat3_355,onehot_feat3_356,onehot_feat3_357,onehot_feat3_358,onehot_feat3_359,onehot_feat3_360,onehot_feat3_361,onehot_feat3_362,onehot_feat3_363,onehot_feat3_364,onehot_feat3_365,onehot_feat3_366,onehot_feat3_367,onehot_feat3_368,onehot_feat3_369,onehot_feat3_370,onehot_feat3_371,onehot_feat3_372,onehot_feat3_373,onehot_feat3_374,onehot_feat3_375,onehot_feat3_376,onehot_feat3_377,onehot_feat3_378,onehot_feat3_379,onehot_feat3_380,onehot_feat3_381,onehot_feat3_382,onehot_feat3_383,onehot_feat3_384,onehot_feat3_385,onehot_feat3_386,onehot_feat3_387,onehot_feat3_388,onehot_feat3_389,onehot_feat3_390,onehot_feat3_391,onehot_feat3_392,onehot_feat3_393,onehot_feat3_394,onehot_feat3_395,onehot_feat3_396,onehot_feat3_397,onehot_feat3_398,onehot_feat3_399,onehot_feat3_400,onehot_feat3_401,onehot_feat3_402,onehot_feat3_403,onehot_feat3_404,onehot_feat3_405,onehot_feat3_406,onehot_feat3_407,onehot_feat3_408,onehot_feat3_409,onehot_feat3_410,onehot_feat3_411,onehot_feat3_412,onehot_feat3_413,onehot_feat3_414,onehot_feat3_415,onehot_feat3_416,onehot_feat3_417,onehot_feat3_418,onehot_feat3_419,onehot_feat3_420,onehot_feat3_421,onehot_feat3_422,onehot_feat3_423,onehot_feat3_424,onehot_feat3_425,onehot_feat3_426,onehot_feat3_427,onehot_feat3_428,onehot_feat3_429,onehot_feat3_430,onehot_feat3_431,onehot_feat3_432,onehot_feat3_433,onehot_feat3_434,onehot_feat3_435,onehot_feat3_436,onehot_feat3_437,onehot_feat3_438,onehot_feat3_439,onehot_feat3_440,onehot_feat3_441,onehot_feat3_442,onehot_feat3_443,onehot_feat3_444,onehot_feat3_445,onehot_feat3_446,onehot_feat3_447,onehot_feat3_448,onehot_feat3_449,onehot_feat3_450,onehot_feat3_451,onehot_feat3_452,onehot_feat3_453,onehot_feat3_454,onehot_feat3_455,onehot_feat3_456,onehot_feat3_457,onehot_feat3_458,onehot_feat3_459,onehot_feat3_460,onehot_feat3_461,onehot_feat3_462,onehot_feat3_463,onehot_feat3_464,onehot_feat3_465,onehot_feat3_466,onehot_feat3_467,onehot_feat3_468,onehot_feat3_469,onehot_feat3_470,onehot_feat3_471,onehot_feat3_472,onehot_feat3_473,onehot_feat3_474,onehot_feat3_475,onehot_feat3_476,onehot_feat3_477,onehot_feat3_478,onehot_feat3_479,onehot_feat3_480,onehot_feat3_481,onehot_feat3_482,onehot_feat3_483,onehot_feat3_484,onehot_feat3_485,onehot_feat3_486,onehot_feat3_487,onehot_feat3_488,onehot_feat3_489,onehot_feat3_490,onehot_feat3_491,onehot_feat3_492,onehot_feat3_493,onehot_feat3_494,onehot_feat3_495,onehot_feat3_496,onehot_feat3_497,onehot_feat3_498,onehot_feat3_499,onehot_feat3_500,onehot_feat3_501,onehot_feat3_502,onehot_feat3_503,onehot_feat3_504,onehot_feat3_505,onehot_feat3_506,onehot_feat3_507,onehot_feat3_508,onehot_feat3_509,onehot_feat3_510,onehot_feat3_511,onehot_feat3_512,onehot_feat3_513,onehot_feat3_514,onehot_feat3_515,onehot_feat3_516,onehot_feat3_517,onehot_feat3_518,onehot_feat3_519,onehot_feat3_520,onehot_feat3_521,onehot_feat3_522,onehot_feat3_523,onehot_feat3_524,onehot_feat3_525,onehot_feat3_526,onehot_feat3_527,onehot_feat3_528,onehot_feat3_529,onehot_feat3_530,onehot_feat3_531,onehot_feat3_532,onehot_feat3_533,onehot_feat3_534,onehot_feat3_535,onehot_feat3_536,onehot_feat3_537,onehot_feat3_538,onehot_feat3_539,onehot_feat3_540,onehot_feat3_541,onehot_feat3_542,onehot_feat3_543,onehot_feat3_544,onehot_feat3_545,onehot_feat3_546,onehot_feat3_547,onehot_feat3_548,onehot_feat3_549,onehot_feat3_550,onehot_feat3_551,onehot_feat3_552,onehot_feat3_553,onehot_feat3_554,onehot_feat3_555,onehot_feat3_556,onehot_feat3_557,onehot_feat3_558,onehot_feat3_559,onehot_feat3_560,onehot_feat3_561,onehot_feat3_562,onehot_feat3_563,onehot_feat3_564,onehot_feat3_565,onehot_feat3_566,onehot_feat3_567,onehot_feat3_568,onehot_feat3_569,onehot_feat3_570,onehot_feat3_571,onehot_feat3_572,onehot_feat3_573,onehot_feat3_574,onehot_feat3_575,onehot_feat3_576,onehot_feat3_577,onehot_feat3_578,onehot_feat3_579,onehot_feat3_580,onehot_feat3_581,onehot_feat3_582,onehot_feat3_583,onehot_feat3_584,onehot_feat3_585,onehot_feat3_586,onehot_feat3_587,onehot_feat3_588,onehot_feat3_589,onehot_feat3_590,onehot_feat3_591,onehot_feat3_592,onehot_feat3_593,onehot_feat3_594,onehot_feat3_595,onehot_feat3_596,onehot_feat3_597,onehot_feat3_598,onehot_feat3_599,onehot_feat3_600,onehot_feat3_601,onehot_feat3_602,onehot_feat3_603,onehot_feat3_604,onehot_feat3_605,onehot_feat3_606,onehot_feat3_607,onehot_feat3_608,onehot_feat3_609,onehot_feat3_610,onehot_feat3_611,onehot_feat3_612,onehot_feat3_613,onehot_feat3_614,onehot_feat3_615,onehot_feat3_616,onehot_feat3_617,onehot_feat3_618,onehot_feat3_619,onehot_feat3_620,onehot_feat3_621,onehot_feat3_622,onehot_feat3_623,onehot_feat3_624,onehot_feat3_625,onehot_feat3_626,onehot_feat3_627,onehot_feat3_628,onehot_feat3_629,onehot_feat3_630,onehot_feat3_631,onehot_feat3_632,onehot_feat3_633,onehot_feat3_634,onehot_feat3_635,onehot_feat3_636,onehot_feat3_637,onehot_feat3_638,onehot_feat3_639,onehot_feat3_640,onehot_feat3_641,onehot_feat3_642,onehot_feat3_643,onehot_feat3_644,onehot_feat3_645,onehot_feat3_646,onehot_feat3_647,onehot_feat3_648,onehot_feat3_649,onehot_feat3_650,onehot_feat3_651,onehot_feat3_652,onehot_feat3_653,onehot_feat3_654,onehot_feat3_655,onehot_feat3_656,onehot_feat3_657,onehot_feat3_658,onehot_feat3_659,onehot_feat3_660,onehot_feat3_661,onehot_feat3_662,onehot_feat3_663,onehot_feat3_664,onehot_feat3_665,onehot_feat3_666,onehot_feat3_667,onehot_feat3_668,onehot_feat3_669,onehot_feat3_670,onehot_feat3_671,onehot_feat3_672,onehot_feat3_673,onehot_feat3_674,onehot_feat3_675,onehot_feat3_676,onehot_feat3_677,onehot_feat3_678,onehot_feat3_679,onehot_feat3_680,onehot_feat3_681,onehot_feat3_682,onehot_feat3_683,onehot_feat3_684,onehot_feat3_685,onehot_feat3_686,onehot_feat3_687,onehot_feat3_688,onehot_feat3_689,onehot_feat3_690,onehot_feat3_691,onehot_feat3_692,onehot_feat3_693,onehot_feat3_694,onehot_feat3_695,onehot_feat3_696,onehot_feat3_697,onehot_feat3_698,onehot_feat3_699,onehot_feat3_700,onehot_feat3_701,onehot_feat3_702,onehot_feat3_703,onehot_feat3_704,onehot_feat3_705,onehot_feat3_706,onehot_feat3_707,onehot_feat3_708,onehot_feat3_709,onehot_feat3_710,onehot_feat3_711,onehot_feat3_712,onehot_feat3_713,onehot_feat3_714,onehot_feat3_715,onehot_feat3_716,onehot_feat3_717,onehot_feat3_718,onehot_feat3_719,onehot_feat3_720,onehot_feat3_721,onehot_feat3_722,onehot_feat3_723,onehot_feat3_724,onehot_feat3_725,onehot_feat3_726,onehot_feat3_727,onehot_feat3_728,onehot_feat3_729,onehot_feat3_730,onehot_feat3_731,onehot_feat3_732,onehot_feat3_733,onehot_feat3_734,onehot_feat3_735,onehot_feat3_736,onehot_feat3_737,onehot_feat3_738,onehot_feat3_739,onehot_feat3_740,onehot_feat3_741,onehot_feat3_742,onehot_feat3_743,onehot_feat3_744,onehot_feat3_745,onehot_feat3_746,onehot_feat3_747,onehot_feat3_748,onehot_feat3_749,onehot_feat3_750,onehot_feat3_751,onehot_feat3_752,onehot_feat3_753,onehot_feat3_754,onehot_feat3_755,onehot_feat3_756,onehot_feat3_757,onehot_feat3_758,onehot_feat3_759,onehot_feat3_760,onehot_feat3_761,onehot_feat3_762,onehot_feat3_763,onehot_feat3_764,onehot_feat3_765,onehot_feat3_766,onehot_feat3_767,onehot_feat3_768,onehot_feat3_769,onehot_feat3_770,onehot_feat3_771,onehot_feat3_772,onehot_feat3_773,onehot_feat3_774,onehot_feat3_775,onehot_feat3_776,onehot_feat3_777,onehot_feat3_778,onehot_feat3_779,onehot_feat3_780,onehot_feat3_781,onehot_feat3_782,onehot_feat3_783,onehot_feat3_784,onehot_feat3_785,onehot_feat3_786,onehot_feat3_787,onehot_feat3_788,onehot_feat3_789,onehot_feat3_790,onehot_feat3_791,onehot_feat3_792,onehot_feat3_793,onehot_feat3_794,onehot_feat3_795,onehot_feat3_796,onehot_feat3_797,onehot_feat3_798,onehot_feat3_799,onehot_feat3_800,onehot_feat3_801,onehot_feat3_802,onehot_feat3_803,onehot_feat3_804,onehot_feat3_805,onehot_feat3_806,onehot_feat3_807,onehot_feat3_808,onehot_feat3_809,onehot_feat3_810,onehot_feat3_811,onehot_feat3_812,onehot_feat3_813,onehot_feat3_814,onehot_feat3_815,onehot_feat3_816,onehot_feat3_817,onehot_feat3_818,onehot_feat3_819,onehot_feat3_820,onehot_feat3_821,onehot_feat3_822,onehot_feat3_823,onehot_feat3_824,onehot_feat3_825,onehot_feat3_826,onehot_feat3_827,onehot_feat3_828,onehot_feat3_829,onehot_feat3_830,onehot_feat3_831,onehot_feat3_832,onehot_feat3_833,onehot_feat3_834,onehot_feat3_835,onehot_feat3_836,onehot_feat3_837,onehot_feat3_838,onehot_feat3_839,onehot_feat3_840,onehot_feat3_841,onehot_feat3_842,onehot_feat3_843,onehot_feat3_844,onehot_feat3_845,onehot_feat3_846,onehot_feat3_847,onehot_feat3_848,onehot_feat3_849,onehot_feat3_850,onehot_feat3_851,onehot_feat3_852,onehot_feat3_853,onehot_feat3_854,onehot_feat3_855,onehot_feat3_856,onehot_feat3_857,onehot_feat3_858,onehot_feat3_859,onehot_feat3_860,onehot_feat3_861,onehot_feat3_862,onehot_feat3_863,onehot_feat3_864,onehot_feat3_865,onehot_feat3_866,onehot_feat3_867,onehot_feat3_868,onehot_feat3_869,onehot_feat3_870,onehot_feat3_871,onehot_feat3_872,onehot_feat3_873,onehot_feat3_874,onehot_feat3_875,onehot_feat3_876,onehot_feat3_877,onehot_feat3_878,onehot_feat3_879,onehot_feat3_880,onehot_feat3_881,onehot_feat3_882,onehot_feat3_883,onehot_feat3_884,onehot_feat3_885,onehot_feat3_886,onehot_feat3_887,onehot_feat3_888,onehot_feat3_889,onehot_feat3_890,onehot_feat3_891,onehot_feat3_892,onehot_feat3_893,onehot_feat3_894,onehot_feat3_895,onehot_feat3_896,onehot_feat3_897,onehot_feat3_898,onehot_feat3_899,onehot_feat3_900,onehot_feat3_901,onehot_feat3_902,onehot_feat3_903,onehot_feat3_904,onehot_feat3_905,onehot_feat3_906,onehot_feat3_907,onehot_feat3_908,onehot_feat3_909,onehot_feat3_910,onehot_feat3_911,onehot_feat3_912,onehot_feat3_913,onehot_feat3_914,onehot_feat3_915,onehot_feat3_916,onehot_feat3_917,onehot_feat3_918,onehot_feat3_919,onehot_feat3_920,onehot_feat3_921,onehot_feat3_922,onehot_feat3_923,onehot_feat3_924,onehot_feat3_925,onehot_feat3_926,onehot_feat3_927,onehot_feat3_928,onehot_feat3_929,onehot_feat3_930,onehot_feat3_931,onehot_feat3_932,onehot_feat3_933,onehot_feat3_934,onehot_feat3_935,onehot_feat3_936,onehot_feat3_937,onehot_feat3_938,onehot_feat3_939,onehot_feat3_940,onehot_feat3_941,onehot_feat3_942,onehot_feat3_943,onehot_feat3_944,onehot_feat3_945,onehot_feat3_946,onehot_feat3_947,onehot_feat3_948,onehot_feat3_949,onehot_feat3_950,onehot_feat3_951,onehot_feat3_952,onehot_feat3_953,onehot_feat3_954,onehot_feat3_955,onehot_feat3_956,onehot_feat3_957,onehot_feat3_958,onehot_feat3_959,onehot_feat3_960,onehot_feat3_961,onehot_feat3_962,onehot_feat3_963,onehot_feat3_964,onehot_feat3_965,onehot_feat3_966,onehot_feat3_967,onehot_feat3_968,onehot_feat3_969,onehot_feat3_970,onehot_feat3_971,onehot_feat3_972,onehot_feat3_973,onehot_feat3_974,onehot_feat3_975,onehot_feat3_976,onehot_feat3_977,onehot_feat3_978,onehot_feat3_979,onehot_feat3_980,onehot_feat3_981,onehot_feat3_982,onehot_feat3_983,onehot_feat3_984,onehot_feat3_985,onehot_feat3_986,onehot_feat3_987,onehot_feat3_988,onehot_feat3_989,onehot_feat3_990,onehot_feat3_991,onehot_feat3_992,onehot_feat3_993,onehot_feat3_994,onehot_feat3_995,onehot_feat3_996,onehot_feat3_997,onehot_feat3_998,onehot_feat3_999,onehot_feat3_1000,onehot_feat3_1001,onehot_feat3_1002,onehot_feat3_1003,onehot_feat3_1004,onehot_feat3_1005,onehot_feat3_1006,onehot_feat3_1007,onehot_feat3_1008,onehot_feat3_1009,onehot_feat3_1010,onehot_feat3_1011,onehot_feat3_1012,onehot_feat3_1013,onehot_feat3_1014,onehot_feat3_1015,onehot_feat3_1016,onehot_feat3_1017,onehot_feat3_1018,onehot_feat3_1019,onehot_feat3_1020,onehot_feat3_1021,onehot_feat3_1022,onehot_feat3_1023,onehot_feat3_1024,onehot_feat3_1025,onehot_feat3_1026,onehot_feat3_1027,onehot_feat3_1028,onehot_feat3_1029,onehot_feat3_1030,onehot_feat3_1031,onehot_feat3_1032,onehot_feat3_1033,onehot_feat3_1034,onehot_feat3_1035,onehot_feat3_1036,onehot_feat3_1037,onehot_feat3_1038,onehot_feat3_1039,onehot_feat3_1040,onehot_feat3_1041,onehot_feat3_1042,onehot_feat3_1043,onehot_feat3_1044,onehot_feat3_1045,onehot_feat3_1046,onehot_feat3_1047,onehot_feat3_1048,onehot_feat3_1049,onehot_feat3_1050,onehot_feat3_1051,onehot_feat3_1052,onehot_feat3_1053,onehot_feat3_1054,onehot_feat3_1055,onehot_feat3_1056,onehot_feat3_1057,onehot_feat3_1058,onehot_feat3_1059,onehot_feat3_1060,onehot_feat3_1061,onehot_feat3_1062,onehot_feat3_1063,onehot_feat3_1064,onehot_feat3_1065,onehot_feat3_1066,onehot_feat3_1067,onehot_feat3_1068,onehot_feat3_1069,onehot_feat3_1070,onehot_feat3_1071,onehot_feat3_1072,onehot_feat3_1073,onehot_feat3_1074,onehot_feat3_1075,onehot_feat4_0.0,onehot_feat4_1.0,onehot_feat4_2.0,onehot_feat4_3.0,onehot_feat4_4.0,onehot_feat4_5.0,onehot_feat4_6.0,onehot_feat4_7.0,onehot_feat4_8.0,onehot_feat4_9.0,onehot_feat

In [10]:
user_features_columns = user_features.columns.tolist()
user_features_columns

['user_id',
 'is_lowactive_period',
 'is_live_streamer',
 'is_video_author',
 'follow_user_num',
 'fans_user_num',
 'friend_user_num',
 'register_days',
 'onehot_feat0',
 'onehot_feat12',
 'onehot_feat13',
 'onehot_feat14',
 'onehot_feat15',
 'onehot_feat16',
 'onehot_feat17',
 'user_active_degree_0',
 'user_active_degree_1',
 'user_active_degree_2',
 'user_active_degree_3',
 'follow_user_num_range_0',
 'follow_user_num_range_1',
 'follow_user_num_range_2',
 'follow_user_num_range_3',
 'follow_user_num_range_4',
 'follow_user_num_range_5',
 'follow_user_num_range_6',
 'follow_user_num_range_7',
 'fans_user_num_range_0',
 'fans_user_num_range_1',
 'fans_user_num_range_2',
 'fans_user_num_range_3',
 'fans_user_num_range_4',
 'fans_user_num_range_5',
 'fans_user_num_range_6',
 'friend_user_num_range_0',
 'friend_user_num_range_1',
 'friend_user_num_range_2',
 'friend_user_num_range_3',
 'friend_user_num_range_4',
 'friend_user_num_range_5',
 'friend_user_num_range_6',
 'register_days_range_0',
 'register_days_range_1',
 'register_days_range_2',
 'register_days_range_3',
 'register_days_range_4',
 'register_days_range_5',
 'register_days_range_6',
 'onehot_feat1_0',
 'onehot_feat1_1',
 'onehot_feat1_2',
 'onehot_feat1_3',
 'onehot_feat1_4',
 'onehot_feat1_5',
 'onehot_feat1_6',
 'onehot_feat1_7',
 'onehot_feat2_0',
 'onehot_feat2_1',
 'onehot_feat2_2',
 'onehot_feat2_3',
 'onehot_feat2_4',
 'onehot_feat2_5',
 'onehot_feat2_6',
 'onehot_feat2_7',
 'onehot_feat2_8',
 'onehot_feat2_9',
 'onehot_feat2_10',
 'onehot_feat2_11',
 'onehot_feat2_12',
 'onehot_feat2_13',
 'onehot_feat2_14',
 'onehot_feat2_15',
 'onehot_feat2_16',
 'onehot_feat2_17',
 'onehot_feat2_18',
 'onehot_feat2_19',
 'onehot_feat2_20',
 'onehot_feat2_21',
 'onehot_feat2_22',
 'onehot_feat2_23',
 'onehot_feat2_24',
 'onehot_feat2_25',
 'onehot_feat2_26',
 'onehot_feat2_27',
 'onehot_feat2_28',
 'onehot_feat2_29',
 'onehot_feat3_0',
 'onehot_feat3_1',
 'onehot_feat3_2',
 'onehot_feat3_3',
 'onehot_feat3_4',
 'onehot_feat3_5',
 'onehot_feat3_6',
 'onehot_feat3_7',
 'onehot_feat3_8',
 'onehot_feat3_9',
 'onehot_feat3_10',
 'onehot_feat3_11',
 'onehot_feat3_12',
 'onehot_feat3_13',
 'onehot_feat3_14',
 'onehot_feat3_15',
 'onehot_feat3_16',
 'onehot_feat3_17',
 'onehot_feat3_18',
 'onehot_feat3_19',
 'onehot_feat3_20',
 'onehot_feat3_21',
 'onehot_feat3_22',
 'onehot_feat3_23',
 'onehot_feat3_24',
 'onehot_feat3_25',
 'onehot_feat3_26',
 'onehot_feat3_27',
 'onehot_feat3_28',
 'onehot_feat3_29',
 'onehot_feat3_30',
 'onehot_feat3_31',
 'onehot_feat3_32',
 'onehot_feat3_33',
 'onehot_feat3_34',
 'onehot_feat3_35',
 'onehot_feat3_36',
 'onehot_feat3_37',
 'onehot_feat3_38',
 'onehot_feat3_39',
 'onehot_feat3_40',
 'onehot_feat3_41',
 'onehot_feat3_42',
 'onehot_feat3_43',
 'onehot_feat3_44',
 'onehot_feat3_45',
 'onehot_feat3_46',
 'onehot_feat3_47',
 'onehot_feat3_48',
 'onehot_feat3_49',
 'onehot_feat3_50',
 'onehot_feat3_51',
 'onehot_feat3_52',
 'onehot_feat3_53',
 'onehot_feat3_54',
 'onehot_feat3_55',
 'onehot_feat3_56',
 'onehot_feat3_57',
 'onehot_feat3_58',
 'onehot_feat3_59',
 'onehot_feat3_60',
 'onehot_feat3_61',
 'onehot_feat3_62',
 'onehot_feat3_63',
 'onehot_feat3_64',
 'onehot_feat3_65',
 'onehot_feat3_66',
 'onehot_feat3_67',
 'onehot_feat3_68',
 'onehot_feat3_69',
 'onehot_feat3_70',
 'onehot_feat3_71',
 'onehot_feat3_72',
 'onehot_feat3_73',
 'onehot_feat3_74',
 'onehot_feat3_75',
 'onehot_feat3_76',
 'onehot_feat3_77',
 'onehot_feat3_78',
 'onehot_feat3_79',
 'onehot_feat3_80',
 'onehot_feat3_81',
 'onehot_feat3_82',
 'onehot_feat3_83',
 'onehot_feat3_84',
 'onehot_feat3_85',
 'onehot_feat3_86',
 'onehot_feat3_87',
 'onehot_feat3_88',
 'onehot_feat3_89',
 'onehot_feat3_90',
 'onehot_feat3_91',
 'onehot_feat3_92',
 'onehot_feat3_93',
 'onehot_feat3_94',
 'onehot_feat3_95',
 'onehot_feat3_96',
 'onehot_feat3_97',
 'onehot_feat3_98',
 'onehot_feat3_99',
 'onehot_feat3_100',
 'onehot_feat3_101',
 'onehot_feat3_102',
 'onehot_feat3_103',
 'onehot_feat3_104',
 'onehot_feat3_105',
 'onehot_feat3_106',
 'onehot_feat3_107',
 'onehot_feat3_108',
 'onehot_feat3_109',
 'onehot_feat3_110',
 'onehot_feat3_111',
 'onehot_feat3_112',
 'onehot_feat3_113',
 'onehot_feat3_114',
 'onehot_feat3_115',
 'onehot_feat3_116',
 'onehot_feat3_117',
 'onehot_feat3_118',
 'onehot_feat3_119',
 'onehot_feat3_120',
 'onehot_feat3_121',
 'onehot_feat3_122',
 'onehot_feat3_123',
 'onehot_feat3_124',
 'onehot_feat3_125',
 'onehot_feat3_126',
 'onehot_feat3_127',
 'onehot_feat3_128',
 'onehot_feat3_129',
 'onehot_feat3_130',
 'onehot_feat3_131',
 'onehot_feat3_132',
 'onehot_feat3_133',
 'onehot_feat3_134',
 'onehot_feat3_135',
 'onehot_feat3_136',
 'onehot_feat3_137',
 'onehot_feat3_138',
 'onehot_feat3_139',
 'onehot_feat3_140',
 'onehot_feat3_141',
 'onehot_feat3_142',
 'onehot_feat3_143',
 'onehot_feat3_144',
 'onehot_feat3_145',
 'onehot_feat3_146',
 'onehot_feat3_147',
 'onehot_feat3_148',
 'onehot_feat3_149',
 'onehot_feat3_150',
 'onehot_feat3_151',
 'onehot_feat3_152',
 'onehot_feat3_153',
 'onehot_feat3_154',
 'onehot_feat3_155',
 'onehot_feat3_156',
 'onehot_feat3_157',
 'onehot_feat3_158',
 'onehot_feat3_159',
 'onehot_feat3_160',
 'onehot_feat3_161',
 'onehot_feat3_162',
 'onehot_feat3_163',
 'onehot_feat3_164',
 'onehot_feat3_165',
 'onehot_feat3_166',
 'onehot_feat3_167',
 'onehot_feat3_168',
 'onehot_feat3_169',
 'onehot_feat3_170',
 'onehot_feat3_171',
 'onehot_feat3_172',
 'onehot_feat3_173',
 'onehot_feat3_174',
 'onehot_feat3_175',
 'onehot_feat3_176',
 'onehot_feat3_177',
 'onehot_feat3_178',
 'onehot_feat3_179',
 'onehot_feat3_180',
 'onehot_feat3_181',
 'onehot_feat3_182',
 'onehot_feat3_183',
 'onehot_feat3_184',
 'onehot_feat3_185',
 'onehot_feat3_186',
 'onehot_feat3_187',
 'onehot_feat3_188',
 'onehot_feat3_189',
 'onehot_feat3_190',
 'onehot_feat3_191',
 'onehot_feat3_192',
 'onehot_feat3_193',
 'onehot_feat3_194',
 'onehot_feat3_195',
 'onehot_feat3_196',
 'onehot_feat3_197',
 'onehot_feat3_198',
 'onehot_feat3_199',
 'onehot_feat3_200',
 'onehot_feat3_201',
 'onehot_feat3_202',
 'onehot_feat3_203',
 'onehot_feat3_204',
 'onehot_feat3_205',
 'onehot_feat3_206',
 'onehot_feat3_207',
 'onehot_feat3_208',
 'onehot_feat3_209',
 'onehot_feat3_210',
 'onehot_feat3_211',
 'onehot_feat3_212',
 'onehot_feat3_213',
 'onehot_feat3_214',
 'onehot_feat3_215',
 'onehot_feat3_216',
 'onehot_feat3_217',
 'onehot_feat3_218',
 'onehot_feat3_219',
 'onehot_feat3_220',
 'onehot_feat3_221',
 'onehot_feat3_222',
 'onehot_feat3_223',
 'onehot_feat3_224',
 'onehot_feat3_225',
 'onehot_feat3_226',
 'onehot_feat3_227',
 'onehot_feat3_228',
 'onehot_feat3_229',
 'onehot_feat3_230',
 'onehot_feat3_231',
 'onehot_feat3_232',
 'onehot_feat3_233',
 'onehot_feat3_234',
 'onehot_feat3_235',
 'onehot_feat3_236',
 'onehot_feat3_237',
 'onehot_feat3_238',
 'onehot_feat3_239',
 'onehot_feat3_240',
 'onehot_feat3_241',
 'onehot_feat3_242',
 'onehot_feat3_243',
 'onehot_feat3_244',
 'onehot_feat3_245',
 'onehot_feat3_246',
 'onehot_feat3_247',
 'onehot_feat3_248',
 'onehot_feat3_249',
 'onehot_feat3_250',
 'onehot_feat3_251',
 'onehot_feat3_252',
 'onehot_feat3_253',
 'onehot_feat3_254',
 'onehot_feat3_255',
 'onehot_feat3_256',
 'onehot_feat3_257',
 'onehot_feat3_258',
 'onehot_feat3_259',
 'onehot_feat3_260',
 'onehot_feat3_261',
 'onehot_feat3_262',
 'onehot_feat3_263',
 'onehot_feat3_264',
 'onehot_feat3_265',
 'onehot_feat3_266',
 'onehot_feat3_267',
 'onehot_feat3_268',
 'onehot_feat3_269',
 'onehot_feat3_270',
 'onehot_feat3_271',
 'onehot_feat3_272',
 'onehot_feat3_273',
 'onehot_feat3_274',
 'onehot_feat3_275',
 'onehot_feat3_276',
 'onehot_feat3_277',
 'onehot_feat3_278',
 'onehot_feat3_279',
 'onehot_feat3_280',
 'onehot_feat3_281',
 'onehot_feat3_282',
 'onehot_feat3_283',
 'onehot_feat3_284',
 'onehot_feat3_285',
 'onehot_feat3_286',
 'onehot_feat3_287',
 'onehot_feat3_288',
 'onehot_feat3_289',
 'onehot_feat3_290',
 'onehot_feat3_291',
 'onehot_feat3_292',
 'onehot_feat3_293',
 'onehot_feat3_294',
 'onehot_feat3_295',
 'onehot_feat3_296',
 'onehot_feat3_297',
 'onehot_feat3_298',
 'onehot_feat3_299',
 'onehot_feat3_300',
 'onehot_feat3_301',
 'onehot_feat3_302',
 'onehot_feat3_303',
 'onehot_feat3_304',
 'onehot_feat3_305',
 'onehot_feat3_306',
 'onehot_feat3_307',
 'onehot_feat3_308',
 'onehot_feat3_309',
 'onehot_feat3_310',
 'onehot_feat3_311',
 'onehot_feat3_312',
 'onehot_feat3_313',
 'onehot_feat3_314',
 'onehot_feat3_315',
 'onehot_feat3_316',
 'onehot_feat3_317',
 'onehot_feat3_318',
 'onehot_feat3_319',
 'onehot_feat3_320',
 'onehot_feat3_321',
 'onehot_feat3_322',
 'onehot_feat3_323',
 'onehot_feat3_324',
 'onehot_feat3_325',
 'onehot_feat3_326',
 'onehot_feat3_327',
 'onehot_feat3_328',
 'onehot_feat3_329',
 'onehot_feat3_330',
 'onehot_feat3_331',
 'onehot_feat3_332',
 'onehot_feat3_333',
 'onehot_feat3_334',
 'onehot_feat3_335',
 'onehot_feat3_336',
 'onehot_feat3_337',
 'onehot_feat3_338',
 'onehot_feat3_339',
 'onehot_feat3_340',
 'onehot_feat3_341',
 'onehot_feat3_342',
 'onehot_feat3_343',
 'onehot_feat3_344',
 'onehot_feat3_345',
 'onehot_feat3_346',
 'onehot_feat3_347',
 'onehot_feat3_348',
 'onehot_feat3_349',
 'onehot_feat3_350',
 'onehot_feat3_351',
 'onehot_feat3_352',
 'onehot_feat3_353',
 'onehot_feat3_354',
 'onehot_feat3_355',
 'onehot_feat3_356',
 'onehot_feat3_357',
 'onehot_feat3_358',
 'onehot_feat3_359',
 'onehot_feat3_360',
 'onehot_feat3_361',
 'onehot_feat3_362',
 'onehot_feat3_363',
 'onehot_feat3_364',
 'onehot_feat3_365',
 'onehot_feat3_366',
 'onehot_feat3_367',
 'onehot_feat3_368',
 'onehot_feat3_369',
 'onehot_feat3_370',
 'onehot_feat3_371',
 'onehot_feat3_372',
 'onehot_feat3_373',
 'onehot_feat3_374',
 'onehot_feat3_375',
 'onehot_feat3_376',
 'onehot_feat3_377',
 'onehot_feat3_378',
 'onehot_feat3_379',
 'onehot_feat3_380',
 'onehot_feat3_381',
 'onehot_feat3_382',
 'onehot_feat3_383',
 'onehot_feat3_384',
 'onehot_feat3_385',
 'onehot_feat3_386',
 'onehot_feat3_387',
 'onehot_feat3_388',
 'onehot_feat3_389',
 'onehot_feat3_390',
 'onehot_feat3_391',
 'onehot_feat3_392',
 'onehot_feat3_393',
 'onehot_feat3_394',
 'onehot_feat3_395',
 'onehot_feat3_396',
 'onehot_feat3_397',
 'onehot_feat3_398',
 'onehot_feat3_399',
 'onehot_feat3_400',
 'onehot_feat3_401',
 'onehot_feat3_402',
 'onehot_feat3_403',
 'onehot_feat3_404',
 'onehot_feat3_405',
 'onehot_feat3_406',
 'onehot_feat3_407',
 'onehot_feat3_408',
 'onehot_feat3_409',
 'onehot_feat3_410',
 'onehot_feat3_411',
 'onehot_feat3_412',
 'onehot_feat3_413',
 'onehot_feat3_414',
 'onehot_feat3_415',
 'onehot_feat3_416',
 'onehot_feat3_417',
 'onehot_feat3_418',
 'onehot_feat3_419',
 'onehot_feat3_420',
 'onehot_feat3_421',
 'onehot_feat3_422',
 'onehot_feat3_423',
 'onehot_feat3_424',
 'onehot_feat3_425',
 'onehot_feat3_426',
 'onehot_feat3_427',
 'onehot_feat3_428',
 'onehot_feat3_429',
 'onehot_feat3_430',
 'onehot_feat3_431',
 'onehot_feat3_432',
 'onehot_feat3_433',
 'onehot_feat3_434',
 'onehot_feat3_435',
 'onehot_feat3_436',
 'onehot_feat3_437',
 'onehot_feat3_438',
 'onehot_feat3_439',
 'onehot_feat3_440',
 'onehot_feat3_441',
 'onehot_feat3_442',
 'onehot_feat3_443',
 'onehot_feat3_444',
 'onehot_feat3_445',
 'onehot_feat3_446',
 'onehot_feat3_447',
 'onehot_feat3_448',
 'onehot_feat3_449',
 'onehot_feat3_450',
 'onehot_feat3_451',
 'onehot_feat3_452',
 'onehot_feat3_453',
 'onehot_feat3_454',
 'onehot_feat3_455',
 'onehot_feat3_456',
 'onehot_feat3_457',
 'onehot_feat3_458',
 'onehot_feat3_459',
 'onehot_feat3_460',
 'onehot_feat3_461',
 'onehot_feat3_462',
 'onehot_feat3_463',
 'onehot_feat3_464',
 'onehot_feat3_465',
 'onehot_feat3_466',
 'onehot_feat3_467',
 'onehot_feat3_468',
 'onehot_feat3_469',
 'onehot_feat3_470',
 'onehot_feat3_471',
 'onehot_feat3_472',
 'onehot_feat3_473',
 'onehot_feat3_474',
 'onehot_feat3_475',
 'onehot_feat3_476',
 'onehot_feat3_477',
 'onehot_feat3_478',
 'onehot_feat3_479',
 'onehot_feat3_480',
 'onehot_feat3_481',
 'onehot_feat3_482',
 'onehot_feat3_483',
 'onehot_feat3_484',
 'onehot_feat3_485',
 'onehot_feat3_486',
 'onehot_feat3_487',
 'onehot_feat3_488',
 'onehot_feat3_489',
 'onehot_feat3_490',
 'onehot_feat3_491',
 'onehot_feat3_492',
 'onehot_feat3_493',
 'onehot_feat3_494',
 'onehot_feat3_495',
 'onehot_feat3_496',
 'onehot_feat3_497',
 'onehot_feat3_498',
 'onehot_feat3_499',
 'onehot_feat3_500',
 'onehot_feat3_501',
 'onehot_feat3_502',
 'onehot_feat3_503',
 'onehot_feat3_504',
 'onehot_feat3_505',
 'onehot_feat3_506',
 'onehot_feat3_507',
 'onehot_feat3_508',
 'onehot_feat3_509',
 'onehot_feat3_510',
 'onehot_feat3_511',
 'onehot_feat3_512',
 'onehot_feat3_513',
 'onehot_feat3_514',
 'onehot_feat3_515',
 'onehot_feat3_516',
 'onehot_feat3_517',
 'onehot_feat3_518',
 'onehot_feat3_519',
 'onehot_feat3_520',
 'onehot_feat3_521',
 'onehot_feat3_522',
 'onehot_feat3_523',
 'onehot_feat3_524',
 'onehot_feat3_525',
 'onehot_feat3_526',
 'onehot_feat3_527',
 'onehot_feat3_528',
 'onehot_feat3_529',
 'onehot_feat3_530',
 'onehot_feat3_531',
 'onehot_feat3_532',
 'onehot_feat3_533',
 'onehot_feat3_534',
 'onehot_feat3_535',
 'onehot_feat3_536',
 'onehot_feat3_537',
 'onehot_feat3_538',
 'onehot_feat3_539',
 'onehot_feat3_540',
 'onehot_feat3_541',
 'onehot_feat3_542',
 'onehot_feat3_543',
 'onehot_feat3_544',
 'onehot_feat3_545',
 'onehot_feat3_546',
 'onehot_feat3_547',
 'onehot_feat3_548',
 'onehot_feat3_549',
 'onehot_feat3_550',
 'onehot_feat3_551',
 'onehot_feat3_552',
 'onehot_feat3_553',
 'onehot_feat3_554',
 'onehot_feat3_555',
 'onehot_feat3_556',
 'onehot_feat3_557',
 'onehot_feat3_558',
 'onehot_feat3_559',
 'onehot_feat3_560',
 'onehot_feat3_561',
 'onehot_feat3_562',
 'onehot_feat3_563',
 'onehot_feat3_564',
 'onehot_feat3_565',
 'onehot_feat3_566',
 'onehot_feat3_567',
 'onehot_feat3_568',
 'onehot_feat3_569',
 'onehot_feat3_570',
 'onehot_feat3_571',
 'onehot_feat3_572',
 'onehot_feat3_573',
 'onehot_feat3_574',
 'onehot_feat3_575',
 'onehot_feat3_576',
 'onehot_feat3_577',
 'onehot_feat3_578',
 'onehot_feat3_579',
 'onehot_feat3_580',
 'onehot_feat3_581',
 'onehot_feat3_582',
 'onehot_feat3_583',
 'onehot_feat3_584',
 'onehot_feat3_585',
 'onehot_feat3_586',
 'onehot_feat3_587',
 'onehot_feat3_588',
 'onehot_feat3_589',
 'onehot_feat3_590',
 'onehot_feat3_591',
 'onehot_feat3_592',
 'onehot_feat3_593',
 'onehot_feat3_594',
 'onehot_feat3_595',
 'onehot_feat3_596',
 'onehot_feat3_597',
 'onehot_feat3_598',
 'onehot_feat3_599',
 'onehot_feat3_600',
 'onehot_feat3_601',
 'onehot_feat3_602',
 'onehot_feat3_603',
 'onehot_feat3_604',
 'onehot_feat3_605',
 'onehot_feat3_606',
 'onehot_feat3_607',
 'onehot_feat3_608',
 'onehot_feat3_609',
 'onehot_feat3_610',
 'onehot_feat3_611',
 'onehot_feat3_612',
 'onehot_feat3_613',
 'onehot_feat3_614',
 'onehot_feat3_615',
 'onehot_feat3_616',
 'onehot_feat3_617',
 'onehot_feat3_618',
 'onehot_feat3_619',
 'onehot_feat3_620',
 'onehot_feat3_621',
 'onehot_feat3_622',
 'onehot_feat3_623',
 'onehot_feat3_624',
 'onehot_feat3_625',
 'onehot_feat3_626',
 'onehot_feat3_627',
 'onehot_feat3_628',
 'onehot_feat3_629',
 'onehot_feat3_630',
 'onehot_feat3_631',
 'onehot_feat3_632',
 'onehot_feat3_633',
 'onehot_feat3_634',
 'onehot_feat3_635',
 'onehot_feat3_636',
 'onehot_feat3_637',
 'onehot_feat3_638',
 'onehot_feat3_639',
 'onehot_feat3_640',
 'onehot_feat3_641',
 'onehot_feat3_642',
 'onehot_feat3_643',
 'onehot_feat3_644',
 'onehot_feat3_645',
 'onehot_feat3_646',
 'onehot_feat3_647',
 'onehot_feat3_648',
 'onehot_feat3_649',
 'onehot_feat3_650',
 'onehot_feat3_651',
 'onehot_feat3_652',
 'onehot_feat3_653',
 'onehot_feat3_654',
 'onehot_feat3_655',
 'onehot_feat3_656',
 'onehot_feat3_657',
 'onehot_feat3_658',
 'onehot_feat3_659',
 'onehot_feat3_660',
 'onehot_feat3_661',
 'onehot_feat3_662',
 'onehot_feat3_663',
 'onehot_feat3_664',
 'onehot_feat3_665',
 'onehot_feat3_666',
 'onehot_feat3_667',
 'onehot_feat3_668',
 'onehot_feat3_669',
 'onehot_feat3_670',
 'onehot_feat3_671',
 'onehot_feat3_672',
 'onehot_feat3_673',
 'onehot_feat3_674',
 'onehot_feat3_675',
 'onehot_feat3_676',
 'onehot_feat3_677',
 'onehot_feat3_678',
 'onehot_feat3_679',
 'onehot_feat3_680',
 'onehot_feat3_681',
 'onehot_feat3_682',
 'onehot_feat3_683',
 'onehot_feat3_684',
 'onehot_feat3_685',
 'onehot_feat3_686',
 'onehot_feat3_687',
 'onehot_feat3_688',
 'onehot_feat3_689',
 'onehot_feat3_690',
 'onehot_feat3_691',
 'onehot_feat3_692',
 'onehot_feat3_693',
 'onehot_feat3_694',
 'onehot_feat3_695',
 'onehot_feat3_696',
 'onehot_feat3_697',
 'onehot_feat3_698',
 'onehot_feat3_699',
 'onehot_feat3_700',
 'onehot_feat3_701',
 'onehot_feat3_702',
 'onehot_feat3_703',
 'onehot_feat3_704',
 'onehot_feat3_705',
 'onehot_feat3_706',
 'onehot_feat3_707',
 'onehot_feat3_708',
 'onehot_feat3_709',
 'onehot_feat3_710',
 'onehot_feat3_711',
 'onehot_feat3_712',
 'onehot_feat3_713',
 'onehot_feat3_714',
 'onehot_feat3_715',
 'onehot_feat3_716',
 'onehot_feat3_717',
 'onehot_feat3_718',
 'onehot_feat3_719',
 'onehot_feat3_720',
 'onehot_feat3_721',
 'onehot_feat3_722',
 'onehot_feat3_723',
 'onehot_feat3_724',
 'onehot_feat3_725',
 'onehot_feat3_726',
 'onehot_feat3_727',
 'onehot_feat3_728',
 'onehot_feat3_729',
 'onehot_feat3_730',
 'onehot_feat3_731',
 'onehot_feat3_732',
 'onehot_feat3_733',
 'onehot_feat3_734',
 'onehot_feat3_735',
 'onehot_feat3_736',
 'onehot_feat3_737',
 'onehot_feat3_738',
 'onehot_feat3_739',
 'onehot_feat3_740',
 'onehot_feat3_741',
 'onehot_feat3_742',
 'onehot_feat3_743',
 'onehot_feat3_744',
 'onehot_feat3_745',
 'onehot_feat3_746',
 'onehot_feat3_747',
 'onehot_feat3_748',
 'onehot_feat3_749',
 'onehot_feat3_750',
 'onehot_feat3_751',
 'onehot_feat3_752',
 'onehot_feat3_753',
 'onehot_feat3_754',
 'onehot_feat3_755',
 'onehot_feat3_756',
 'onehot_feat3_757',
 'onehot_feat3_758',
 'onehot_feat3_759',
 'onehot_feat3_760',
 'onehot_feat3_761',
 'onehot_feat3_762',
 'onehot_feat3_763',
 'onehot_feat3_764',
 'onehot_feat3_765',
 'onehot_feat3_766',
 'onehot_feat3_767',
 'onehot_feat3_768',
 'onehot_feat3_769',
 'onehot_feat3_770',
 'onehot_feat3_771',
 'onehot_feat3_772',
 'onehot_feat3_773',
 'onehot_feat3_774',
 'onehot_feat3_775',
 'onehot_feat3_776',
 'onehot_feat3_777',
 'onehot_feat3_778',
 'onehot_feat3_779',
 'onehot_feat3_780',
 'onehot_feat3_781',
 'onehot_feat3_782',
 'onehot_feat3_783',
 'onehot_feat3_784',
 'onehot_feat3_785',
 'onehot_feat3_786',
 'onehot_feat3_787',
 'onehot_feat3_788',
 'onehot_feat3_789',
 'onehot_feat3_790',
 'onehot_feat3_791',
 'onehot_feat3_792',
 'onehot_feat3_793',
 'onehot_feat3_794',
 'onehot_feat3_795',
 'onehot_feat3_796',
 'onehot_feat3_797',
 'onehot_feat3_798',
 'onehot_feat3_799',
 'onehot_feat3_800',
 'onehot_feat3_801',
 'onehot_feat3_802',
 'onehot_feat3_803',
 'onehot_feat3_804',
 'onehot_feat3_805',
 'onehot_feat3_806',
 'onehot_feat3_807',
 'onehot_feat3_808',
 'onehot_feat3_809',
 'onehot_feat3_810',
 'onehot_feat3_811',
 'onehot_feat3_812',
 'onehot_feat3_813',
 'onehot_feat3_814',
 'onehot_feat3_815',
 'onehot_feat3_816',
 'onehot_feat3_817',
 'onehot_feat3_818',
 'onehot_feat3_819',
 'onehot_feat3_820',
 'onehot_feat3_821',
 'onehot_feat3_822',
 'onehot_feat3_823',
 'onehot_feat3_824',
 'onehot_feat3_825',
 'onehot_feat3_826',
 'onehot_feat3_827',
 'onehot_feat3_828',
 'onehot_feat3_829',
 'onehot_feat3_830',
 'onehot_feat3_831',
 'onehot_feat3_832',
 'onehot_feat3_833',
 'onehot_feat3_834',
 'onehot_feat3_835',
 'onehot_feat3_836',
 'onehot_feat3_837',
 'onehot_feat3_838',
 'onehot_feat3_839',
 'onehot_feat3_840',
 'onehot_feat3_841',
 'onehot_feat3_842',
 'onehot_feat3_843',
 'onehot_feat3_844',
 'onehot_feat3_845',
 'onehot_feat3_846',
 'onehot_feat3_847',
 'onehot_feat3_848',
 'onehot_feat3_849',
 'onehot_feat3_850',
 'onehot_feat3_851',
 'onehot_feat3_852',
 'onehot_feat3_853',
 'onehot_feat3_854',
 'onehot_feat3_855',
 'onehot_feat3_856',
 'onehot_feat3_857',
 'onehot_feat3_858',
 'onehot_feat3_859',
 'onehot_feat3_860',
 'onehot_feat3_861',
 'onehot_feat3_862',
 'onehot_feat3_863',
 'onehot_feat3_864',
 'onehot_feat3_865',

### PCA降维 到25维

In [11]:
from sklearn.decomposition import PCA
user_features_for_pca = user_features[user_features_columns[1:]]
user_features_for_pca
pca = PCA(n_components=25)
pca.fit(user_features_for_pca)
user_features_pca = pca.transform(user_features_for_pca)
user_features_for_pca.shape
user_features_pca.shape

,is_lowactive_period,is_live_streamer,is_video_author,follow_user_num,fans_user_num,friend_user_num,register_days,onehot_feat0,onehot_feat12,onehot_feat13,onehot_feat14,onehot_feat15,onehot_feat16,onehot_feat17,user_active_degree_0,user_active_degree_1,user_active_degree_2,user_active_degree_3,follow_user_num_range_0,follow_user_num_range_1,follow_user_num_range_2,follow_user_num_range_3,follow_user_num_range_4,follow_user_num_range_5,follow_user_num_range_6,follow_user_num_range_7,fans_user_num_range_0,fans_user_num_range_1,fans_user_num_range_2,fans_user_num_range_3,fans_user_num_range_4,fans_user_num_range_5,fans_user_num_range_6,friend_user_num_range_0,friend_user_num_range_1,friend_user_num_range_2,friend_user_num_range_3,friend_user_num_range_4,friend_user_num_range_5,friend_user_num_range_6,register_days_range_0,register_days_range_1,register_days_range_2,register_days_range_3,register_days_range_4,register_days_range_5,register_days_range_6,onehot_feat1_0,onehot_feat1_1,onehot_feat1_2,onehot_feat1_3,onehot_feat1_4,onehot_feat1_5,onehot_feat1_6,onehot_feat1_7,onehot_feat2_0,onehot_feat2_1,onehot_feat2_2,onehot_feat2_3,onehot_feat2_4,onehot_feat2_5,onehot_feat2_6,onehot_feat2_7,onehot_feat2_8,onehot_feat2_9,onehot_feat2_10,onehot_feat2_11,onehot_feat2_12,onehot_feat2_13,onehot_feat2_14,onehot_feat2_15,onehot_feat2_16,onehot_feat2_17,onehot_feat2_18,onehot_feat2_19,onehot_feat2_20,onehot_feat2_21,onehot_feat2_22,onehot_feat2_23,onehot_feat2_24,onehot_feat2_25,onehot_feat2_26,onehot_feat2_27,onehot_feat2_28,onehot_feat2_29,onehot_feat3_0,onehot_feat3_1,onehot_feat3_2,onehot_feat3_3,onehot_feat3_4,onehot_feat3_5,onehot_feat3_6,onehot_feat3_7,onehot_feat3_8,onehot_feat3_9,onehot_feat3_10,onehot_feat3_11,onehot_feat3_12,onehot_feat3_13,onehot_feat3_14,onehot_feat3_15,onehot_feat3_16,onehot_feat3_17,onehot_feat3_18,onehot_feat3_19,onehot_feat3_20,onehot_feat3_21,onehot_feat3_22,onehot_feat3_23,onehot_feat3_24,onehot_feat3_25,onehot_feat3_26,onehot_feat3_27,onehot_feat3_28,onehot_feat3_29,onehot_feat3_30,onehot_feat3_31,onehot_feat3_32,onehot_feat3_33,onehot_feat3_34,onehot_feat3_35,onehot_feat3_36,onehot_feat3_37,onehot_feat3_38,onehot_feat3_39,onehot_feat3_40,onehot_feat3_41,onehot_feat3_42,onehot_feat3_43,onehot_feat3_44,onehot_feat3_45,onehot_feat3_46,onehot_feat3_47,onehot_feat3_48,onehot_feat3_49,onehot_feat3_50,onehot_feat3_51,onehot_feat3_52,onehot_feat3_53,onehot_feat3_54,onehot_feat3_55,onehot_feat3_56,onehot_feat3_57,onehot_feat3_58,onehot_feat3_59,onehot_feat3_60,onehot_feat3_61,onehot_feat3_62,onehot_feat3_63,onehot_feat3_64,onehot_feat3_65,onehot_feat3_66,onehot_feat3_67,onehot_feat3_68,onehot_feat3_69,onehot_feat3_70,onehot_feat3_71,onehot_feat3_72,onehot_feat3_73,onehot_feat3_74,onehot_feat3_75,onehot_feat3_76,onehot_feat3_77,onehot_feat3_78,onehot_feat3_79,onehot_feat3_80,onehot_feat3_81,onehot_feat3_82,onehot_feat3_83,onehot_feat3_84,onehot_feat3_85,onehot_feat3_86,onehot_feat3_87,onehot_feat3_88,onehot_feat3_89,onehot_feat3_90,onehot_feat3_91,onehot_feat3_92,onehot_feat3_93,onehot_feat3_94,onehot_feat3_95,onehot_feat3_96,onehot_feat3_97,onehot_feat3_98,onehot_feat3_99,onehot_feat3_100,onehot_feat3_101,onehot_feat3_102,onehot_feat3_103,onehot_feat3_104,onehot_feat3_105,onehot_feat3_106,onehot_feat3_107,onehot_feat3_108,onehot_feat3_109,onehot_feat3_110,onehot_feat3_111,onehot_feat3_112,onehot_feat3_113,onehot_feat3_114,onehot_feat3_115,onehot_feat3_116,onehot_feat3_117,onehot_feat3_118,onehot_feat3_119,onehot_feat3_120,onehot_feat3_121,onehot_feat3_122,onehot_feat3_123,onehot_feat3_124,onehot_feat3_125,onehot_feat3_126,onehot_feat3_127,onehot_feat3_128,onehot_feat3_129,onehot_feat3_130,onehot_feat3_131,onehot_feat3_132,onehot_feat3_133,onehot_feat3_134,onehot_feat3_135,onehot_feat3_136,onehot_feat3_137,onehot_feat3_138,onehot_feat3_139,onehot_feat3_140,onehot_feat3_141,onehot_feat3_142,onehot_feat3_143,onehot_feat3_144,onehot_feat3_145,onehot_feat3_146,onehot_feat3_147,onehot_feat3_148,onehot_feat3_149,onehot_feat3_150,onehot_feat3_151,onehot_feat3_152,onehot_feat3_153,onehot_feat3_154,onehot_feat3_155,onehot_feat3_156,onehot_feat3_157,onehot_feat3_158,onehot_feat3_159,onehot_feat3_160,onehot_feat3_161,onehot_feat3_162,onehot_feat3_163,onehot_feat3_164,onehot_feat3_165,onehot_feat3_166,onehot_feat3_167,onehot_feat3_168,onehot_feat3_169,onehot_feat3_170,onehot_feat3_171,onehot_feat3_172,onehot_feat3_173,onehot_feat3_174,onehot_feat3_175,onehot_feat3_176,onehot_feat3_177,onehot_feat3_178,onehot_feat3_179,onehot_feat3_180,onehot_feat3_181,onehot_feat3_182,onehot_feat3_183,onehot_feat3_184,onehot_feat3_185,onehot_feat3_186,onehot_feat3_187,onehot_feat3_188,onehot_feat3_189,onehot_feat3_190,onehot_feat3_191,onehot_feat3_192,onehot_feat3_193,onehot_feat3_194,onehot_feat3_195,onehot_feat3_196,onehot_feat3_197,onehot_feat3_198,onehot_feat3_199,onehot_feat3_200,onehot_feat3_201,onehot_feat3_202,onehot_feat3_203,onehot_feat3_204,onehot_feat3_205,onehot_feat3_206,onehot_feat3_207,onehot_feat3_208,onehot_feat3_209,onehot_feat3_210,onehot_feat3_211,onehot_feat3_212,onehot_feat3_213,onehot_feat3_214,onehot_feat3_215,onehot_feat3_216,onehot_feat3_217,onehot_feat3_218,onehot_feat3_219,onehot_feat3_220,onehot_feat3_221,onehot_feat3_222,onehot_feat3_223,onehot_feat3_224,onehot_feat3_225,onehot_feat3_226,onehot_feat3_227,onehot_feat3_228,onehot_feat3_229,onehot_feat3_230,onehot_feat3_231,onehot_feat3_232,onehot_feat3_233,onehot_feat3_234,onehot_feat3_235,onehot_feat3_236,onehot_feat3_237,onehot_feat3_238,onehot_feat3_239,onehot_feat3_240,onehot_feat3_241,onehot_feat3_242,onehot_feat3_243,onehot_feat3_244,onehot_feat3_245,onehot_feat3_246,onehot_feat3_247,onehot_feat3_248,onehot_feat3_249,onehot_feat3_250,onehot_feat3_251,onehot_feat3_252,onehot_feat3_253,onehot_feat3_254,onehot_feat3_255,onehot_feat3_256,onehot_feat3_257,onehot_feat3_258,onehot_feat3_259,onehot_feat3_260,onehot_feat3_261,onehot_feat3_262,onehot_feat3_263,onehot_feat3_264,onehot_feat3_265,onehot_feat3_266,onehot_feat3_267,onehot_feat3_268,onehot_feat3_269,onehot_feat3_270,onehot_feat3_271,onehot_feat3_272,onehot_feat3_273,onehot_feat3_274,onehot_feat3_275,onehot_feat3_276,onehot_feat3_277,onehot_feat3_278,onehot_feat3_279,onehot_feat3_280,onehot_feat3_281,onehot_feat3_282,onehot_feat3_283,onehot_feat3_284,onehot_feat3_285,onehot_feat3_286,onehot_feat3_287,onehot_feat3_288,onehot_feat3_289,onehot_feat3_290,onehot_feat3_291,onehot_feat3_292,onehot_feat3_293,onehot_feat3_294,onehot_feat3_295,onehot_feat3_296,onehot_feat3_297,onehot_feat3_298,onehot_feat3_299,onehot_feat3_300,onehot_feat3_301,onehot_feat3_302,onehot_feat3_303,onehot_feat3_304,onehot_feat3_305,onehot_feat3_306,onehot_feat3_307,onehot_feat3_308,onehot_feat3_309,onehot_feat3_310,onehot_feat3_311,onehot_feat3_312,onehot_feat3_313,onehot_feat3_314,onehot_feat3_315,onehot_feat3_316,onehot_feat3_317,onehot_feat3_318,onehot_feat3_319,onehot_feat3_320,onehot_feat3_321,onehot_feat3_322,onehot_feat3_323,onehot_feat3_324,onehot_feat3_325,onehot_feat3_326,onehot_feat3_327,onehot_feat3_328,onehot_feat3_329,onehot_feat3_330,onehot_feat3_331,onehot_feat3_332,onehot_feat3_333,onehot_feat3_334,onehot_feat3_335,onehot_feat3_336,onehot_feat3_337,onehot_feat3_338,onehot_feat3_339,onehot_feat3_340,onehot_feat3_341,onehot_feat3_342,onehot_feat3_343,onehot_feat3_344,onehot_feat3_345,onehot_feat3_346,onehot_feat3_347,onehot_feat3_348,onehot_feat3_349,onehot_feat3_350,onehot_feat3_351,onehot_feat3_352,onehot_feat3_353,onehot_feat3_354,onehot_feat3_355,onehot_feat3_356,onehot_feat3_357,onehot_feat3_358,onehot_feat3_359,onehot_feat3_360,onehot_feat3_361,onehot_feat3_362,onehot_feat3_363,onehot_feat3_364,onehot_feat3_365,onehot_feat3_366,onehot_feat3_367,onehot_feat3_368,onehot_feat3_369,onehot_feat3_370,onehot_feat3_371,onehot_feat3_372,onehot_feat3_373,onehot_feat3_374,onehot_feat3_375,onehot_feat3_376,onehot_feat3_377,onehot_feat3_378,onehot_feat3_379,onehot_feat3_380,onehot_feat3_381,onehot_feat3_382,onehot_feat3_383,onehot_feat3_384,onehot_feat3_385,onehot_feat3_386,onehot_feat3_387,onehot_feat3_388,onehot_feat3_389,onehot_feat3_390,onehot_feat3_391,onehot_feat3_392,onehot_feat3_393,onehot_feat3_394,onehot_feat3_395,onehot_feat3_396,onehot_feat3_397,onehot_feat3_398,onehot_feat3_399,onehot_feat3_400,onehot_feat3_401,onehot_feat3_402,onehot_feat3_403,onehot_feat3_404,onehot_feat3_405,onehot_feat3_406,onehot_feat3_407,onehot_feat3_408,onehot_feat3_409,onehot_feat3_410,onehot_feat3_411,onehot_feat3_412,onehot_feat3_413,onehot_feat3_414,onehot_feat3_415,onehot_feat3_416,onehot_feat3_417,onehot_feat3_418,onehot_feat3_419,onehot_feat3_420,onehot_feat3_421,onehot_feat3_422,onehot_feat3_423,onehot_feat3_424,onehot_feat3_425,onehot_feat3_426,onehot_feat3_427,onehot_feat3_428,onehot_feat3_429,onehot_feat3_430,onehot_feat3_431,onehot_feat3_432,onehot_feat3_433,onehot_feat3_434,onehot_feat3_435,onehot_feat3_436,onehot_feat3_437,onehot_feat3_438,onehot_feat3_439,onehot_feat3_440,onehot_feat3_441,onehot_feat3_442,onehot_feat3_443,onehot_feat3_444,onehot_feat3_445,onehot_feat3_446,onehot_feat3_447,onehot_feat3_448,onehot_feat3_449,onehot_feat3_450,onehot_feat3_451,onehot_feat3_452,onehot_feat3_453,onehot_feat3_454,onehot_feat3_455,onehot_feat3_456,onehot_feat3_457,onehot_feat3_458,onehot_feat3_459,onehot_feat3_460,onehot_feat3_461,onehot_feat3_462,onehot_feat3_463,onehot_feat3_464,onehot_feat3_465,onehot_feat3_466,onehot_feat3_467,onehot_feat3_468,onehot_feat3_469,onehot_feat3_470,onehot_feat3_471,onehot_feat3_472,onehot_feat3_473,onehot_feat3_474,onehot_feat3_475,onehot_feat3_476,onehot_feat3_477,onehot_feat3_478,onehot_feat3_479,onehot_feat3_480,onehot_feat3_481,onehot_feat3_482,onehot_feat3_483,onehot_feat3_484,onehot_feat3_485,onehot_feat3_486,onehot_feat3_487,onehot_feat3_488,onehot_feat3_489,onehot_feat3_490,onehot_feat3_491,onehot_feat3_492,onehot_feat3_493,onehot_feat3_494,onehot_feat3_495,onehot_feat3_496,onehot_feat3_497,onehot_feat3_498,onehot_feat3_499,onehot_feat3_500,onehot_feat3_501,onehot_feat3_502,onehot_feat3_503,onehot_feat3_504,onehot_feat3_505,onehot_feat3_506,onehot_feat3_507,onehot_feat3_508,onehot_feat3_509,onehot_feat3_510,onehot_feat3_511,onehot_feat3_512,onehot_feat3_513,onehot_feat3_514,onehot_feat3_515,onehot_feat3_516,onehot_feat3_517,onehot_feat3_518,onehot_feat3_519,onehot_feat3_520,onehot_feat3_521,onehot_feat3_522,onehot_feat3_523,onehot_feat3_524,onehot_feat3_525,onehot_feat3_526,onehot_feat3_527,onehot_feat3_528,onehot_feat3_529,onehot_feat3_530,onehot_feat3_531,onehot_feat3_532,onehot_feat3_533,onehot_feat3_534,onehot_feat3_535,onehot_feat3_536,onehot_feat3_537,onehot_feat3_538,onehot_feat3_539,onehot_feat3_540,onehot_feat3_541,onehot_feat3_542,onehot_feat3_543,onehot_feat3_544,onehot_feat3_545,onehot_feat3_546,onehot_feat3_547,onehot_feat3_548,onehot_feat3_549,onehot_feat3_550,onehot_feat3_551,onehot_feat3_552,onehot_feat3_553,onehot_feat3_554,onehot_feat3_555,onehot_feat3_556,onehot_feat3_557,onehot_feat3_558,onehot_feat3_559,onehot_feat3_560,onehot_feat3_561,onehot_feat3_562,onehot_feat3_563,onehot_feat3_564,onehot_feat3_565,onehot_feat3_566,onehot_feat3_567,onehot_feat3_568,onehot_feat3_569,onehot_feat3_570,onehot_feat3_571,onehot_feat3_572,onehot_feat3_573,onehot_feat3_574,onehot_feat3_575,onehot_feat3_576,onehot_feat3_577,onehot_feat3_578,onehot_feat3_579,onehot_feat3_580,onehot_feat3_581,onehot_feat3_582,onehot_feat3_583,onehot_feat3_584,onehot_feat3_585,onehot_feat3_586,onehot_feat3_587,onehot_feat3_588,onehot_feat3_589,onehot_feat3_590,onehot_feat3_591,onehot_feat3_592,onehot_feat3_593,onehot_feat3_594,onehot_feat3_595,onehot_feat3_596,onehot_feat3_597,onehot_feat3_598,onehot_feat3_599,onehot_feat3_600,onehot_feat3_601,onehot_feat3_602,onehot_feat3_603,onehot_feat3_604,onehot_feat3_605,onehot_feat3_606,onehot_feat3_607,onehot_feat3_608,onehot_feat3_609,onehot_feat3_610,onehot_feat3_611,onehot_feat3_612,onehot_feat3_613,onehot_feat3_614,onehot_feat3_615,onehot_feat3_616,onehot_feat3_617,onehot_feat3_618,onehot_feat3_619,onehot_feat3_620,onehot_feat3_621,onehot_feat3_622,onehot_feat3_623,onehot_feat3_624,onehot_feat3_625,onehot_feat3_626,onehot_feat3_627,onehot_feat3_628,onehot_feat3_629,onehot_feat3_630,onehot_feat3_631,onehot_feat3_632,onehot_feat3_633,onehot_feat3_634,onehot_feat3_635,onehot_feat3_636,onehot_feat3_637,onehot_feat3_638,onehot_feat3_639,onehot_feat3_640,onehot_feat3_641,onehot_feat3_642,onehot_feat3_643,onehot_feat3_644,onehot_feat3_645,onehot_feat3_646,onehot_feat3_647,onehot_feat3_648,onehot_feat3_649,onehot_feat3_650,onehot_feat3_651,onehot_feat3_652,onehot_feat3_653,onehot_feat3_654,onehot_feat3_655,onehot_feat3_656,onehot_feat3_657,onehot_feat3_658,onehot_feat3_659,onehot_feat3_660,onehot_feat3_661,onehot_feat3_662,onehot_feat3_663,onehot_feat3_664,onehot_feat3_665,onehot_feat3_666,onehot_feat3_667,onehot_feat3_668,onehot_feat3_669,onehot_feat3_670,onehot_feat3_671,onehot_feat3_672,onehot_feat3_673,onehot_feat3_674,onehot_feat3_675,onehot_feat3_676,onehot_feat3_677,onehot_feat3_678,onehot_feat3_679,onehot_feat3_680,onehot_feat3_681,onehot_feat3_682,onehot_feat3_683,onehot_feat3_684,onehot_feat3_685,onehot_feat3_686,onehot_feat3_687,onehot_feat3_688,onehot_feat3_689,onehot_feat3_690,onehot_feat3_691,onehot_feat3_692,onehot_feat3_693,onehot_feat3_694,onehot_feat3_695,onehot_feat3_696,onehot_feat3_697,onehot_feat3_698,onehot_feat3_699,onehot_feat3_700,onehot_feat3_701,onehot_feat3_702,onehot_feat3_703,onehot_feat3_704,onehot_feat3_705,onehot_feat3_706,onehot_feat3_707,onehot_feat3_708,onehot_feat3_709,onehot_feat3_710,onehot_feat3_711,onehot_feat3_712,onehot_feat3_713,onehot_feat3_714,onehot_feat3_715,onehot_feat3_716,onehot_feat3_717,onehot_feat3_718,onehot_feat3_719,onehot_feat3_720,onehot_feat3_721,onehot_feat3_722,onehot_feat3_723,onehot_feat3_724,onehot_feat3_725,onehot_feat3_726,onehot_feat3_727,onehot_feat3_728,onehot_feat3_729,onehot_feat3_730,onehot_feat3_731,onehot_feat3_732,onehot_feat3_733,onehot_feat3_734,onehot_feat3_735,onehot_feat3_736,onehot_feat3_737,onehot_feat3_738,onehot_feat3_739,onehot_feat3_740,onehot_feat3_741,onehot_feat3_742,onehot_feat3_743,onehot_feat3_744,onehot_feat3_745,onehot_feat3_746,onehot_feat3_747,onehot_feat3_748,onehot_feat3_749,onehot_feat3_750,onehot_feat3_751,onehot_feat3_752,onehot_feat3_753,onehot_feat3_754,onehot_feat3_755,onehot_feat3_756,onehot_feat3_757,onehot_feat3_758,onehot_feat3_759,onehot_feat3_760,onehot_feat3_761,onehot_feat3_762,onehot_feat3_763,onehot_feat3_764,onehot_feat3_765,onehot_feat3_766,onehot_feat3_767,onehot_feat3_768,onehot_feat3_769,onehot_feat3_770,onehot_feat3_771,onehot_feat3_772,onehot_feat3_773,onehot_feat3_774,onehot_feat3_775,onehot_feat3_776,onehot_feat3_777,onehot_feat3_778,onehot_feat3_779,onehot_feat3_780,onehot_feat3_781,onehot_feat3_782,onehot_feat3_783,onehot_feat3_784,onehot_feat3_785,onehot_feat3_786,onehot_feat3_787,onehot_feat3_788,onehot_feat3_789,onehot_feat3_790,onehot_feat3_791,onehot_feat3_792,onehot_feat3_793,onehot_feat3_794,onehot_feat3_795,onehot_feat3_796,onehot_feat3_797,onehot_feat3_798,onehot_feat3_799,onehot_feat3_800,onehot_feat3_801,onehot_feat3_802,onehot_feat3_803,onehot_feat3_804,onehot_feat3_805,onehot_feat3_806,onehot_feat3_807,onehot_feat3_808,onehot_feat3_809,onehot_feat3_810,onehot_feat3_811,onehot_feat3_812,onehot_feat3_813,onehot_feat3_814,onehot_feat3_815,onehot_feat3_816,onehot_feat3_817,onehot_feat3_818,onehot_feat3_819,onehot_feat3_820,onehot_feat3_821,onehot_feat3_822,onehot_feat3_823,onehot_feat3_824,onehot_feat3_825,onehot_feat3_826,onehot_feat3_827,onehot_feat3_828,onehot_feat3_829,onehot_feat3_830,onehot_feat3_831,onehot_feat3_832,onehot_feat3_833,onehot_feat3_834,onehot_feat3_835,onehot_feat3_836,onehot_feat3_837,onehot_feat3_838,onehot_feat3_839,onehot_feat3_840,onehot_feat3_841,onehot_feat3_842,onehot_feat3_843,onehot_feat3_844,onehot_feat3_845,onehot_feat3_846,onehot_feat3_847,onehot_feat3_848,onehot_feat3_849,onehot_feat3_850,onehot_feat3_851,onehot_feat3_852,onehot_feat3_853,onehot_feat3_854,onehot_feat3_855,onehot_feat3_856,onehot_feat3_857,onehot_feat3_858,onehot_feat3_859,onehot_feat3_860,onehot_feat3_861,onehot_feat3_862,onehot_feat3_863,onehot_feat3_864,onehot_feat3_865,onehot_feat3_866,onehot_feat3_867,onehot_feat3_868,onehot_feat3_869,onehot_feat3_870,onehot_feat3_871,onehot_feat3_872,onehot_feat3_873,onehot_feat3_874,onehot_feat3_875,onehot_feat3_876,onehot_feat3_877,onehot_feat3_878,onehot_feat3_879,onehot_feat3_880,onehot_feat3_881,onehot_feat3_882,onehot_feat3_883,onehot_feat3_884,onehot_feat3_885,onehot_feat3_886,onehot_feat3_887,onehot_feat3_888,onehot_feat3_889,onehot_feat3_890,onehot_feat3_891,onehot_feat3_892,onehot_feat3_893,onehot_feat3_894,onehot_feat3_895,onehot_feat3_896,onehot_feat3_897,onehot_feat3_898,onehot_feat3_899,onehot_feat3_900,onehot_feat3_901,onehot_feat3_902,onehot_feat3_903,onehot_feat3_904,onehot_feat3_905,onehot_feat3_906,onehot_feat3_907,onehot_feat3_908,onehot_feat3_909,onehot_feat3_910,onehot_feat3_911,onehot_feat3_912,onehot_feat3_913,onehot_feat3_914,onehot_feat3_915,onehot_feat3_916,onehot_feat3_917,onehot_feat3_918,onehot_feat3_919,onehot_feat3_920,onehot_feat3_921,onehot_feat3_922,onehot_feat3_923,onehot_feat3_924,onehot_feat3_925,onehot_feat3_926,onehot_feat3_927,onehot_feat3_928,onehot_feat3_929,onehot_feat3_930,onehot_feat3_931,onehot_feat3_932,onehot_feat3_933,onehot_feat3_934,onehot_feat3_935,onehot_feat3_936,onehot_feat3_937,onehot_feat3_938,onehot_feat3_939,onehot_feat3_940,onehot_feat3_941,onehot_feat3_942,onehot_feat3_943,onehot_feat3_944,onehot_feat3_945,onehot_feat3_946,onehot_feat3_947,onehot_feat3_948,onehot_feat3_949,onehot_feat3_950,onehot_feat3_951,onehot_feat3_952,onehot_feat3_953,onehot_feat3_954,onehot_feat3_955,onehot_feat3_956,onehot_feat3_957,onehot_feat3_958,onehot_feat3_959,onehot_feat3_960,onehot_feat3_961,onehot_feat3_962,onehot_feat3_963,onehot_feat3_964,onehot_feat3_965,onehot_feat3_966,onehot_feat3_967,onehot_feat3_968,onehot_feat3_969,onehot_feat3_970,onehot_feat3_971,onehot_feat3_972,onehot_feat3_973,onehot_feat3_974,onehot_feat3_975,onehot_feat3_976,onehot_feat3_977,onehot_feat3_978,onehot_feat3_979,onehot_feat3_980,onehot_feat3_981,onehot_feat3_982,onehot_feat3_983,onehot_feat3_984,onehot_feat3_985,onehot_feat3_986,onehot_feat3_987,onehot_feat3_988,onehot_feat3_989,onehot_feat3_990,onehot_feat3_991,onehot_feat3_992,onehot_feat3_993,onehot_feat3_994,onehot_feat3_995,onehot_feat3_996,onehot_feat3_997,onehot_feat3_998,onehot_feat3_999,onehot_feat3_1000,onehot_feat3_1001,onehot_feat3_1002,onehot_feat3_1003,onehot_feat3_1004,onehot_feat3_1005,onehot_feat3_1006,onehot_feat3_1007,onehot_feat3_1008,onehot_feat3_1009,onehot_feat3_1010,onehot_feat3_1011,onehot_feat3_1012,onehot_feat3_1013,onehot_feat3_1014,onehot_feat3_1015,onehot_feat3_1016,onehot_feat3_1017,onehot_feat3_1018,onehot_feat3_1019,onehot_feat3_1020,onehot_feat3_1021,onehot_feat3_1022,onehot_feat3_1023,onehot_feat3_1024,onehot_feat3_1025,onehot_feat3_1026,onehot_feat3_1027,onehot_feat3_1028,onehot_feat3_1029,onehot_feat3_1030,onehot_feat3_1031,onehot_feat3_1032,onehot_feat3_1033,onehot_feat3_1034,onehot_feat3_1035,onehot_feat3_1036,onehot_feat3_1037,onehot_feat3_1038,onehot_feat3_1039,onehot_feat3_1040,onehot_feat3_1041,onehot_feat3_1042,onehot_feat3_1043,onehot_feat3_1044,onehot_feat3_1045,onehot_feat3_1046,onehot_feat3_1047,onehot_feat3_1048,onehot_feat3_1049,onehot_feat3_1050,onehot_feat3_1051,onehot_feat3_1052,onehot_feat3_1053,onehot_feat3_1054,onehot_feat3_1055,onehot_feat3_1056,onehot_feat3_1057,onehot_feat3_1058,onehot_feat3_1059,onehot_feat3_1060,onehot_feat3_1061,onehot_feat3_1062,onehot_feat3_1063,onehot_feat3_1064,onehot_feat3_1065,onehot_feat3_1066,onehot_feat3_1067,onehot_feat3_1068,onehot_feat3_1069,onehot_feat3_1070,onehot_feat3_1071,onehot_feat3_1072,onehot_feat3_1073,onehot_feat3_1074,onehot_feat3_1075,onehot_feat4_0.0,onehot_feat4_1.0,onehot_feat4_2.0,onehot_feat4_3.0,onehot_feat4_4.0,onehot_feat4_5.0,onehot_feat4_6.0,onehot_feat4_7.0,onehot_feat4_8.0,onehot_feat4_9.0,onehot_feat4_10.0,o

PCA(n_components=25)

(7176, 1588)

(7176, 25)

In [12]:
new_user_data = pd.concat([user_features["user_id"], pd.DataFrame(user_features_pca)], axis=1)
new_user_data.columns = ["user_id"] + ["u"+str(i) for i in range(25)]
new_user_data

,user_id,u0,u1,u2,u3,u4,u5,u6,u7,u8,u9,u10,u11,u12,u13,u14,u15,u16,u17,u18,u19,u20,u21,u22,u23,u24
0,0,-1.674993,0.152371,-0.554478,0.847241,-0.487899,0.379005,0.038020,0.683137,-0.043919,0.463972,0.332833,-0.018468,0.682566,1.298489,0.160487,0.025993,-0.487937,-0.513339,-0.060585,0.092976,0.162210,-0.263889,-0.347352,0.251206,0.208874
1,1,0.353917,-1.110304,1.185043,0.134926,-0.119457,0.115978,-0.387008,0.258563,-0.518948,-0.095652,0.766431,-0.539570,0.089456,-0.006165,0.100268,0.734863,0.624212,-0.383560,-0.332877,-0.399949,0.062644,-0.418552,0.275639,0.188519,0.255468
2,2,-0.333553,1.103801,0.204809,0.232690,0.007381,0.132940,0.401279,-1.488611,-0.436226,0.569142,-0.651119,0.032094,-0.106102,-0.029214,0.112358,0.290853,0.251065,-0.164117,-0.360368,-0.423455,0.713594,0.097480,-0.051655,0.547016,0.350105
3,3,-0.658980,1.172114,0.762873,-0.289276,0.313181,-0.195914,-0.190670,-1.212718,-0.201246,0.093425,-0.309374,0.495787,0.410965,0.412080,-0.560811,-0.352097,0.541714,0.023365,-0.017354,0.213095,-0.118452,-0.016572,0.376097,-0.159158,-0.124515
4,4,-0.263066,-0.781668,-0.032065,-1.030237,-0.041411,-0.860592,-0.677270,-0.097401,-0.318732,0.046551,-0.447186,0.200679,0.159075,-0.143633,0.107536,0.197960,-0.430306,0.372218,0.136370,0.498894,-0.193749,-0.210194,-0.270706,0.178125,-0.176187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7171,7171,0.404764,-0.846309,-0.645774,-0.188909,-0.138761,-0.583587,0.241269,-0.113076,-0.145269,0.295969,-0.890268,-0.350043,0.555424,-0.607487,0.392625,0.117326,-0.257680,-0.230332,0.268963,-0.653390,-0.647309,-0.405664,-0.040272,-0.325261,0.631514
7172,7172,0.138108,-0.873551,0.685209,0.142144,-0.605445,1.214768,0.451691,-0.694564,-0.120286,-0.455424,0.075029,-0.243325,-0.008977,-0.933601,-0.189219,0.429813,0.601006,-0.507452,-0.075559,-0.744555,0.350266,-0.340947,-0.065165,0.382320,0.235505
7173,7173,1.334196,0.262405,-0.146614,-1.131377,0.207926,0.824497,-0.787195,-0.134796,-0.132404,0.463317,-0.477721,-0.016490,0.220773,-0.522641,-0.074776,0.033094,0.299075,-0.276668,0.104060,-0.676064,0.904495,0.089272,-0.141311,0.509480,0.112142
7174,7174,-0.423911,-0.368874,0.673537,0.627725,1.059992,-0.631193,-0.119376,0.054937,0.098089,-0.610454,-0.362799,-0.476146,-0.129339,0.257187,-0.328869,0.313102,0.809837,0.353500,0.113543,-0.264847,0.908311,0.635354,0.354454,-0.537803,-0.327043
7175,7175,0.382793,-0.503213,-0.848771,-0.150371,1.014602,0.563848,-1.034925,-0.713395,-0.231569,0.193781,-0.025160,0.293778,-0.406577,-0.051408,1.171221,0.051566,0.178112,0.117024,0.219552,0.146996,0.222483,0.134586,0.070334,-0.041519,-0.160424

In [13]:
new_user_data.to_csv("./user_feature_pca.csv", sep=" ", index=False)

# 2. Process Item Feature

In [7]:
item_daily_features = pd.read_csv(rootpath + "data/item_daily_features.csv")
item_daily_features

,video_id,date,author_id,video_type,upload_dt,upload_type,visible_status,video_duration,video_width,video_height,music_id,video_tag_id,video_tag_name,show_cnt,show_user_num,play_cnt,play_user_num,play_duration,complete_play_cnt,complete_play_user_num,valid_play_cnt,valid_play_user_num,long_time_play_cnt,long_time_play_user_num,short_time_play_cnt,short_time_play_user_num,play_progress,comment_stay_duration,like_cnt,like_user_num,click_like_cnt,double_click_cnt,cancel_like_cnt,cancel_like_user_num,comment_cnt,comment_user_num,direct_comment_cnt,reply_comment_cnt,delete_comment_cnt,delete_comment_user_num,comment_like_cnt,comment_like_user_num,follow_cnt,follow_user_num,cancel_follow_cnt,cancel_follow_user_num,share_cnt,share_user_num,download_cnt,download_user_num,report_cnt,report_user_num,reduce_similar_cnt,reduce_similar_user_num,collect_cnt,collect_user_num,cancel_collect_cnt,cancel_collect_user_num
0,0,20200705,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,3350323409,841,建筑,14665,11372,10141,7485,88729488,5657,4834,5503,4775,5503,4775,1939,1481,0.799860,6629173,573,569,315,257,87,85,11,11,8,3,0,0,112,61,284,284,0,0,2,2,8,8,0,0,3,3,NaN,NaN,NaN,NaN
1,0,20200706,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,3350323409,841,建筑,10883,8513,7321,5490,64264607,4162,3522,4039,3468,4039,3468,1340,1040,0.805253,3997498,302,301,159,142,47,47,7,7,6,1,0,0,60,32,201,200,0,0,1,1,2,2,0,0,5,5,NaN,NaN,NaN,NaN
2,0,20200707,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,3350323409,841,建筑,7842,6281,4757,3724,41338741,2734,2403,2640,2376,2640,2376,866,683,0.808821,3314323,205,205,121,84,52,50,4,3,3,1,0,0,59,26,131,131,0,0,1,1,2,2,0,0,0,0,NaN,NaN,NaN,NaN
3,0,20200708,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,3350323409,841,建筑,8916,7229,5172,3961,45281254,2950,2525,2865,2498,2865,2498,977,765,0.801680,4235579,297,293,178,119,60,59,4,4,2,2,0,0,91,46,179,179,0,0,2,2,3,3,0,0,3,3,NaN,NaN,NaN,NaN
4,0,20200709,3309,NORMAL,2020-03-30,ShortImport,public,5966.0,720,1280,3350323409,841,建筑,8502,6658,5392,3946,46952744,3058,2566,2946,2533,2945,2532,1046,752,0.805359,3862095,307,305,166,141,57,56,5,2,0,5,0,0,76,47,186,186,0,0,0,0,2,2,2,1,1,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343336,10723,20200905,236,NORMAL,2020-09-05,ShortImport,public,4833.0,720,1280,4428603493,11,生活,277,173,214,157,1681908,117,106,114,104,114,104,83,66,0.596591,337534,24,24,6,18,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0
343337,10724,20200905,5271,NORMAL,2020-09-05,LongImport,public,54720.0,720,1280,1090207430,2,音乐,1100,1017,965,856,56090732,535,523,754,721,657,637,113,99,0.574591,1249884,264,261,224,39,14,13,29,27,29,0,0,0,3,3,8,8,0,0,1,1,1,1,0,0,0,0,0.0,0.0,0.0,0.0
343338,10725,20200905,1924,NORMAL,2020-09-05,ShortImport,public,15800.0,576,1024,4429406509,15,才艺,16996,16345,15487,14672,323787284,8149,8015,9317,9171,7949,7871,4342,4139,0.577613,1963153,851,845,574,275,19,19,36,28,34,2,0,0,1,1,12,12,0,0,3,2,5,5,0,0,4,4,0.0,0.0,0.0,0.0
343339,10726,20200905,7604,NORMAL,2020-09-05,ShortImport,public,5132.0,528,960,68154,19,情感,7644,7568,7859,7480,128835301,5480,5395,5382,5319,5382,5319,1648,1580,0.818123,192695,44,44,18,25,1,1,0,0,0,0,0,0,0,0,2,2,0,0,1,1,2,2,0,0,1,1,0.0,0.0,0.0,0.0
343340,10727,20200905,7464,NORMAL,2020-09-05,ShortCamera,public,5666.0,720,1556,1090827283,5,穿搭,563,479,233,208,917740,69,65,63,61,63,61,134,125,0.210369,7643,7,7,1,6,3,3,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0

In [8]:
item_daily_features.video_tag_name

0         建筑
1         建筑
2         建筑
3         建筑
4         建筑
          ..
343336    生活
343337    音乐
343338    才艺
343339    情感
343340    穿搭
Name: video_tag_name, Length: 343341, dtype: object

In [9]:
#数据总缺失情况查阅
(item_daily_features.isna().sum()/item_daily_features.shape[0]).sort_values(ascending=False)

cancel_collect_user_num     0.202956
cancel_collect_cnt          0.202956
collect_user_num            0.202956
collect_cnt                 0.202956
video_tag_name              0.094466
video_duration              0.030867
reply_comment_cnt           0.000000
comment_like_cnt            0.000000
delete_comment_user_num     0.000000
delete_comment_cnt          0.000000
comment_cnt                 0.000000
direct_comment_cnt          0.000000
comment_user_num            0.000000
follow_cnt                  0.000000
cancel_like_user_num        0.000000
cancel_like_cnt             0.000000
comment_like_user_num       0.000000
cancel_follow_user_num      0.000000
follow_user_num             0.000000
cancel_follow_cnt           0.000000
click_like_cnt              0.000000
share_cnt                   0.000000
share_user_num              0.000000
download_cnt                0.000000
download_user_num           0.000000
report_cnt                  0.000000
report_user_num             0.000000
reduce_similar_cnt          0.000000
reduce_similar_user_num     0.000000
double_click_cnt            0.000000
video_id                    0.000000
date                        0.000000
play_cnt                    0.000000
author_id                   0.000000
video_type                  0.000000
upload_dt                   0.000000
upload_type                 0.000000
visible_status              0.000000
video_width                 0.000000
video_height                0.000000
music_id                    0.000000
video_tag_id                0.000000
show_cnt                    0.000000
show_user_num               0.000000
play_user_num               0.000000
like_cnt                    0.000000
play_duration               0.000000
complete_play_cnt           0.000000
complete_play_user_num      0.000000
valid_play_cnt              0.000000
valid_play_user_num         0.000000
long_time_play_cnt          0.000000
long_time_play_user_num     0.000000
short_time_play_cnt         0.000000
short_time_play_user_num    0.000000
play_progress               0.000000
comment_stay_duration       0.000000
like_user_num               0.000000
dtype: float64

In [10]:
item_daily_features.columns

Index(['video_id', 'date', 'author_id', 'video_type', 'upload_dt',
       'upload_type', 'visible_status', 'video_duration', 'video_width',
       'video_height', 'music_id', 'video_tag_id', 'video_tag_name',
       'show_cnt', 'show_user_num', 'play_cnt', 'play_user_num',
       'play_duration', 'complete_play_cnt', 'complete_play_user_num',
       'valid_play_cnt', 'valid_play_user_num', 'long_time_play_cnt',
       'long_time_play_user_num', 'short_time_play_cnt',
       'short_time_play_user_num', 'play_progress', 'comment_stay_duration',
       'like_cnt', 'like_user_num', 'click_like_cnt', 'double_click_cnt',
       'cancel_like_cnt', 'cancel_like_user_num', 'comment_cnt',
       'comment_user_num', 'direct_comment_cnt', 'reply_comment_cnt',
       'delete_comment_cnt', 'delete_comment_user_num', 'comment_like_cnt',
       'comment_like_user_num', 'follow_cnt', 'follow_user_num',
       'cancel_follow_cnt', 'cancel_follow_user_num', 'share_cnt',
       'share_user_num', 'download_cnt', 'download_user_num', 'report_cnt',
       'report_user_num', 'reduce_similar_cnt', 'reduce_similar_user_num',
       'collect_cnt', 'collect_user_num', 'cancel_collect_cnt',
       'cancel_collect_user_num'],
      dtype='object')

## Item Daily feature

对缺失较多的['collect_cnt', 'collect_user_num', 'cancel_collect_cnt','cancel_collect_user_num']特征直接丢弃  
video_duration缺失值用均值填充  
video_tag_id和video_tag_name重复，用video_tag_id即可，video_tag_name可以用来可视化  

### sparse_feature: 
['author_id','video_tag_id','upload_type','visible_status','music_id'] 需要进行labelencoder到0-n-1  
['author_id','music_id']重复度很小，可以考虑不用加进去

上述进行onehot展开

["video_type"] 转为二值向量直接拼上去即可
### dense_feature: 
['video_duration','video_width','video_height','show_cnt', 'show_user_num', 'play_cnt', 'play_user_num','play_duration', 'complete_play_cnt', 'complete_play_user_num','valid_play_cnt', 'valid_play_user_num', 'long_time_play_cnt','long_time_play_user_num', 'short_time_play_cnt','short_time_play_user_num', 'play_progress', 'comment_stay_duration','like_cnt', 'like_user_num', 'click_like_cnt', 'double_click_cnt','cancel_like_cnt', 'cancel_like_user_num', 'comment_cnt','comment_user_num', 'direct_comment_cnt', 'reply_comment_cnt','delete_comment_cnt', 'delete_comment_user_num', 'comment_like_cnt','comment_like_user_num', 'follow_cnt', 'follow_user_num','cancel_follow_cnt', 'cancel_follow_user_num', 'share_cnt','share_user_num', 'download_cnt', 'download_user_num', 'report_cnt','report_user_num', 'reduce_similar_cnt', 'reduce_similar_user_num'] 需要进行minmax归一化

In [11]:
item_daily_features['video_duration'] = item_daily_features['video_duration'].fillna(item_daily_features['video_duration'].mean())

In [12]:
item_sparse_feature_1 = ['video_tag_id','upload_type','visible_status'] 
item_sparse_feature_2 = ["video_type"]
item_dense_feature = ['video_duration','video_width','video_height','show_cnt', 'show_user_num', 'play_cnt', 'play_user_num','play_duration', 'complete_play_cnt', 'complete_play_user_num','valid_play_cnt', 'valid_play_user_num', 'long_time_play_cnt','long_time_play_user_num', 'short_time_play_cnt','short_time_play_user_num', 'play_progress', 'comment_stay_duration','like_cnt', 'like_user_num', 'click_like_cnt', 'double_click_cnt','cancel_like_cnt', 'cancel_like_user_num', 'comment_cnt','comment_user_num', 'direct_comment_cnt', 'reply_comment_cnt','delete_comment_cnt', 'delete_comment_user_num', 'comment_like_cnt','comment_like_user_num', 'follow_cnt', 'follow_user_num','cancel_follow_cnt', 'cancel_follow_user_num', 'share_cnt','share_user_num', 'download_cnt', 'download_user_num', 'report_cnt','report_user_num', 'reduce_similar_cnt', 'reduce_similar_user_num']

In [13]:
# Label Encoding for sparse features,and do simple Transformation for dense features
from sklearn import preprocessing
for feat in item_sparse_feature_1 + item_sparse_feature_2:
    lbe = preprocessing.LabelEncoder()
    item_daily_features[feat] = lbe.fit_transform(item_daily_features[feat])

mms = preprocessing.MinMaxScaler(feature_range=(0, 1))
item_daily_features[item_dense_feature] = mms.fit_transform(item_daily_features[item_dense_feature])

item_daily_features

,video_id,date,author_id,video_type,upload_dt,upload_type,visible_status,video_duration,video_width,video_height,music_id,video_tag_id,video_tag_name,show_cnt,show_user_num,play_cnt,play_user_num,play_duration,complete_play_cnt,complete_play_user_num,valid_play_cnt,valid_play_user_num,long_time_play_cnt,long_time_play_user_num,short_time_play_cnt,short_time_play_user_num,play_progress,comment_stay_duration,like_cnt,like_user_num,click_like_cnt,double_click_cnt,cancel_like_cnt,cancel_like_user_num,comment_cnt,comment_user_num,direct_comment_cnt,reply_comment_cnt,delete_comment_cnt,delete_comment_user_num,comment_like_cnt,comment_like_user_num,follow_cnt,follow_user_num,cancel_follow_cnt,cancel_follow_user_num,share_cnt,share_user_num,download_cnt,download_user_num,report_cnt,report_user_num,reduce_similar_cnt,reduce_similar_user_num,collect_cnt,collect_user_num,cancel_collect_cnt,cancel_collect_user_num
0,0,20200705,3309,1,2020-03-30,15,2,0.018813,0.163399,0.355030,3350323409,169,建筑,0.000348,0.000292,0.000246,0.000201,4.467997e-05,0.000224,0.000199,0.000189,0.000169,0.000208,0.000185,0.000186,0.000162,0.799860,3.179897e-05,0.000214,0.000215,1.850155e-04,0.000266,0.000372,0.000407,0.000060,0.000064,0.000046,0.00003,0.0,0.0,0.000164,0.000199,0.000575,0.000576,0.0,0.0,0.000007,0.000007,0.000060,0.000060,0.000000,0.000000,0.000087,0.000089,NaN,NaN,NaN,NaN
1,0,20200706,3309,1,2020-03-30,15,2,0.018813,0.163399,0.355030,3350323409,169,建筑,0.000258,0.000219,0.000178,0.000147,3.236061e-05,0.000165,0.000145,0.000138,0.000123,0.000152,0.000134,0.000128,0.000114,0.805253,1.917529e-05,0.000113,0.000114,9.338878e-05,0.000147,0.000201,0.000225,0.000038,0.000041,0.000034,0.00001,0.0,0.0,0.000088,0.000104,0.000407,0.000406,0.0,0.0,0.000003,0.000004,0.000015,0.000015,0.000000,0.000000,0.000145,0.000148,NaN,NaN,NaN,NaN
2,0,20200707,3309,1,2020-03-30,15,2,0.018813,0.163399,0.355030,3350323409,169,建筑,0.000186,0.000161,0.000116,0.000100,2.081623e-05,0.000108,0.000099,0.000090,0.000084,0.000100,0.000092,0.000083,0.000075,0.808821,1.589822e-05,0.000077,0.000077,7.106945e-05,0.000087,0.000223,0.000239,0.000022,0.000017,0.000017,0.00001,0.0,0.0,0.000086,0.000085,0.000265,0.000266,0.0,0.0,0.000003,0.000004,0.000015,0.000015,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
3,0,20200708,3309,1,2020-03-30,15,2,0.018813,0.163399,0.355030,3350323409,169,建筑,0.000211,0.000186,0.000126,0.000106,2.280150e-05,0.000117,0.000104,0.000098,0.000088,0.000108,0.000097,0.000094,0.000084,0.801680,2.031732e-05,0.000111,0.000110,1.045484e-04,0.000123,0.000257,0.000282,0.000022,0.000023,0.000011,0.00002,0.0,0.0,0.000133,0.000150,0.000363,0.000363,0.0,0.0,0.000007,0.000007,0.000022,0.000022,0.000000,0.000000,0.000087,0.000089,NaN,NaN,NaN,NaN
4,0,20200709,3309,1,2020-03-30,15,2,0.018813,0.163399,0.355030,3350323409,169,建筑,0.000202,0.000171,0.000131,0.000106,2.364318e-05,0.000121,0.000106,0.000101,0.000090,0.000111,0.000098,0.000100,0.000082,0.805359,1.852579e-05,0.000115,0.000115,9.750023e-05,0.000146,0.000244,0.000268,0.000027,0.000012,0.000000,0.00005,0.0,0.0,0.000111,0.000153,0.000377,0.000377,0.0,0.0,0.000000,0.000000,0.000015,0.000015,0.010101,0.005682,0.000029,0.000030,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343336,10723,20200905,236,1,2020-09-05,15,2,0.015216,0.163399,0.355030,4428603493,12,生活,0.000007,0.000004,0.000005,0.000004,8.469292e-07,0.000005,0.000004,0.000004,0.000004,0.000004,0.000004,0.000008,0.000007,0.596591,1.619091e-06,0.000009,0.000009,3.524105e-06,0.000019,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.000001,0.000003,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
343337,10724,20200905,5271,1,2020-09-05,7,2,0.173587,0.163399,0.355030,1090207430,3,音乐,0.000026,0.000026,0.000023,0.000023,2.824464e-05,0.000021,0.000022,0.000026,0.000026,0.000025,0.000025,0.000011,0.000011,0.574591,5.995473e-06,0.000099,0.000098,1.315666e-04,0.000040,0.000060,0.000062,0.000159,0.000157,0.000166,0.00000,0.0,0.0,0.000004,0.000010,0.000016,0.000016,0.0,0.0,0.000003,0.000004,0.000007,0.000007,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
343338,10725,20200905,1924,1,2020-09-05,15,2,0.050032,0.111111,0.260355,4429406509,16,才艺,0.000403,0.000420,0.000376,0.000394,1.630439e-04,0.000323,0.000330,0.000319,0.000325,0.000300,0.000305,0.000416,0.000453,0.577613,9.416898e-06,0.000318,0.000319,3.371394e-04,0.000285,0.000081,0.000091,0.000197,0.000163,0.000194,0.00002,0.0,0.0,0.000001,0.000003,0.000024,0.000024,0.0,0.0,0.000010,0.000007,0.000037,0.000037,0.000000,0.000000,0.000116,0.000119,0.0,0.0,0.0,0.0
343339,10726,20200905,7604,1,2020-09-05,15,2,0.016165,0.093682,0.236686,68154,20,情感,0.000181,0.000194,0.000191,0.000201,6.487536e-05,0.000217,0.000222,0.000184,0.000188,0.000203,0.000206,0.000158,0.000173,0.818123,9.243239e-07,0.000016,0.000017,1.057231e-05,0.000026,0.000004,0.000005,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.000004,0.000004,0.0,0.0,0.000003,0.000004,0.000015,0.000015,0.000000,0.000000,0.000029,0.000030,0.0,0.0,0.0,0.0
343340,10727,20200905,7464,1,2020-09-05,14,2,0.017860,0.163399,0.457101,1090827283,6,穿搭,0.000013,0.000012,0.000006,0.000006,4.621304e-07,0.000003,0.000003,0.000002,0.000002,0.000002,0.000002,0.000013,0.000014,0.210369,3.666212e-08,0.000003,0.000003,5.873508e-07,0.000006,0.000013,0.000014,0.000000,0.000000,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.000002,0.000002,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0

In [14]:
# onehot sparse feature
item_daily_features_onehot = pd.get_dummies(item_daily_features[item_sparse_feature_1], columns=item_sparse_feature_1)
item_daily_features_onehot

,video_tag_id_0,video_tag_id_1,video_tag_id_2,video_tag_id_3,video_tag_id_4,video_tag_id_5,video_tag_id_6,video_tag_id_7,video_tag_id_8,video_tag_id_9,video_tag_id_10,video_tag_id_11,video_tag_id_12,video_tag_id_13,video_tag_id_14,video_tag_id_15,video_tag_id_16,video_tag_id_17,video_tag_id_18,video_tag_id_19,video_tag_id_20,video_tag_id_21,video_tag_id_22,video_tag_id_23,video_tag_id_24,video_tag_id_25,video_tag_id_26,video_tag_id_27,video_tag_id_28,video_tag_id_29,video_tag_id_30,video_tag_id_31,video_tag_id_32,video_tag_id_33,video_tag_id_34,video_tag_id_35,video_tag_id_36,video_tag_id_37,video_tag_id_38,video_tag_id_39,video_tag_id_40,video_tag_id_41,video_tag_id_42,video_tag_id_43,video_tag_id_44,video_tag_id_45,video_tag_id_46,video_tag_id_47,video_tag_id_48,video_tag_id_49,video_tag_id_50,video_tag_id_51,video_tag_id_52,video_tag_id_53,video_tag_id_54,video_tag_id_55,video_tag_id_56,video_tag_id_57,video_tag_id_58,video_tag_id_59,video_tag_id_60,video_tag_id_61,video_tag_id_62,video_tag_id_63,video_tag_id_64,video_tag_id_65,video_tag_id_66,video_tag_id_67,video_tag_id_68,video_tag_id_69,video_tag_id_70,video_tag_id_71,video_tag_id_72,video_tag_id_73,video_tag_id_74,video_tag_id_75,video_tag_id_76,video_tag_id_77,video_tag_id_78,video_tag_id_79,video_tag_id_80,video_tag_id_81,video_tag_id_82,video_tag_id_83,video_tag_id_84,video_tag_id_85,video_tag_id_86,video_tag_id_87,video_tag_id_88,video_tag_id_89,video_tag_id_90,video_tag_id_91,video_tag_id_92,video_tag_id_93,video_tag_id_94,video_tag_id_95,video_tag_id_96,video_tag_id_97,video_tag_id_98,video_tag_id_99,video_tag_id_100,video_tag_id_101,video_tag_id_102,video_tag_id_103,video_tag_id_104,video_tag_id_105,video_tag_id_106,video_tag_id_107,video_tag_id_108,video_tag_id_109,video_tag_id_110,video_tag_id_111,video_tag_id_112,video_tag_id_113,video_tag_id_114,video_tag_id_115,video_tag_id_116,video_tag_id_117,video_tag_id_118,video_tag_id_119,video_tag_id_120,video_tag_id_121,video_tag_id_122,video_tag_id_123,video_tag_id_124,video_tag_id_125,video_tag_id_126,video_tag_id_127,video_tag_id_128,video_tag_id_129,video_tag_id_130,video_tag_id_131,video_tag_id_132,video_tag_id_133,video_tag_id_134,video_tag_id_135,video_tag_id_136,video_tag_id_137,video_tag_id_138,video_tag_id_139,video_tag_id_140,video_tag_id_141,video_tag_id_142,video_tag_id_143,video_tag_id_144,video_tag_id_145,video_tag_id_146,video_tag_id_147,video_tag_id_148,video_tag_id_149,video_tag_id_150,video_tag_id_151,video_tag_id_152,video_tag_id_153,video_tag_id_154,video_tag_id_155,video_tag_id_156,video_tag_id_157,video_tag_id_158,video_tag_id_159,video_tag_id_160,video_tag_id_161,video_tag_id_162,video_tag_id_163,video_tag_id_164,video_tag_id_165,video_tag_id_166,video_tag_id_167,video_tag_id_168,video_tag_id_169,video_tag_id_170,video_tag_id_171,video_tag_id_172,video_tag_id_173,video_tag_id_174,video_tag_id_175,video_tag_id_176,video_tag_id_177,video_tag_id_178,video_tag_id_179,video_tag_id_180,video_tag_id_181,video_tag_id_182,video_tag_id_183,video_tag_id_184,video_tag_id_185,video_tag_id_186,video_tag_id_187,video_tag_id_188,video_tag_id_189,video_tag_id_190,video_tag_id_191,video_tag_id_192,video_tag_id_193,video_tag_id_194,video_tag_id_195,video_tag_id_196,video_tag_id_197,video_tag_id_198,video_tag_id_199,video_tag_id_200,video_tag_id_201,video_tag_id_202,video_tag_id_203,video_tag_id_204,video_tag_id_205,video_tag_id_206,video_tag_id_207,video_tag_id_208,video_tag_id_209,video_tag_id_210,video_tag_id_211,video_tag_id_212,video_tag_id_213,video_tag_id_214,video_tag_id_215,video_tag_id_216,video_tag_id_217,video_tag_id_218,video_tag_id_219,video_tag_id_220,video_tag_id_221,video_tag_id_222,video_tag_id_223,video_tag_id_224,video_tag_id_225,video_tag_id_226,video_tag_id_227,video_tag_id_228,video_tag_id_229,video_tag_id_230,video_tag_id_231,video_tag_id_232,video_tag_id_233,video_tag_id_234,video_tag_id_235,video_tag_id_236,video_tag_id_237,video_tag_id_238,video_tag_id_239,video_tag_id_240,video_tag_id_241,video_tag_id_242,video_tag_id_243,video_tag_id_244,video_tag_id_245,video_tag_id_246,video_tag_id_247,video_tag_id_248,video_tag_id_249,video_tag_id_250,video_tag_id_251,video_tag_id_252,video_tag_id_253,video_tag_id_254,video_tag_id_255,video_tag_id_256,video_tag_id_257,video_tag_id_258,video_tag_id_259,video_tag_id_260,video_tag_id_261,video_tag_id_262,video_tag_id_263,video_tag_id_264,video_tag_id_265,video_tag_id_266,video_tag_id_267,video_tag_id_268,video_tag_id_269,video_tag_id_270,video_tag_id_271,video_tag_id_272,video_tag_id_273,video_tag_id_274,video_tag_id_275,video_tag_id_276,video_tag_id_277,video_tag_id_278,video_tag_id_279,video_tag_id_280,video_tag_id_281,video_tag_id_282,video_tag_id_283,video_tag_id_284,video_tag_id_285,video_tag_id_286,video_tag_id_287,video_tag_id_288,video_tag_id_289,video_tag_id_290,video_tag_id_291,video_tag_id_292,video_tag_id_293,video_tag_id_294,video_tag_id_295,video_tag_id_296,video_tag_id_297,video_tag_id_298,video_tag_id_299,video_tag_id_300,video_tag_id_301,video_tag_id_302,video_tag_id_303,video_tag_id_304,video_tag_id_305,video_tag_id_306,video_tag_id_307,video_tag_id_308,video_tag_id_309,video_tag_id_310,video_tag_id_311,video_tag_id_312,video_tag_id_313,video_tag_id_314,video_tag_id_315,video_tag_id_316,video_tag_id_317,video_tag_id_318,video_tag_id_319,video_tag_id_320,video_tag_id_321,video_tag_id_322,video_tag_id_323,video_tag_id_324,video_tag_id_325,video_tag_id_326,video_tag_id_327,video_tag_id_328,video_tag_id_329,video_tag_id_330,video_tag_id_331,video_tag_id_332,video_tag_id_333,video_tag_id_334,video_tag_id_335,video_tag_id_336,video_tag_id_337,video_tag_id_338,video_tag_id_339,video_tag_id_340,video_tag_id_341,video_tag_id_342,video_tag_id_343,video_tag_id_344,video_tag_id_345,video_tag_id_346,video_tag_id_347,video_tag_id_348,video_tag_id_349,video_tag_id_350,video_tag_id_351,video_tag_id_352,video_tag_id_353,video_tag_id_354,video_tag_id_355,video_tag_id_356,video_tag_id_357,video_tag_id_358,video_tag_id_359,video_tag_id_360,video_tag_id_361,video_tag_id_362,video_tag_id_363,video_tag_id_364,video_tag_id_365,video_tag_id_366,video_tag_id_367,video_tag_id_368,video_tag_id_369,video_tag_id_370,video_tag_id_371,video_tag_id_372,video_tag_id_373,video_tag_id_374,video_tag_id_375,video_tag_id_376,video_tag_id_377,video_tag_id_378,video_tag_id_379,video_tag_id_380,video_tag_id_381,video_tag_id_382,video_tag_id_383,video_tag_id_384,video_tag_id_385,video_tag_id_386,video_tag_id_387,video_tag_id_388,video_tag_id_389,video_tag_id_390,video_tag_id_391,video_tag_id_392,video_tag_id_393,video_tag_id_394,video_tag_id_395,video_tag_id_396,video_tag_id_397,video_tag_id_398,video_tag_id_399,video_tag_id_400,video_tag_id_401,video_tag_id_402,video_tag_id_403,video_tag_id_404,video_tag_id_405,video_tag_id_406,video_tag_id_407,video_tag_id_408,video_tag_id_409,video_tag_id_410,video_tag_id_411,video_tag_id_412,video_tag_id_413,video_tag_id_414,video_tag_id_415,video_tag_id_416,video_tag_id_417,video_tag_id_418,video_tag_id_419,video_tag_id_420,video_tag_id_421,video_tag_id_422,video_tag_id_423,video_tag_id_424,video_tag_id_425,video_tag_id_426,video_tag_id_427,video_tag_id_428,video_tag_id_429,video_tag_id_430,video_tag_id_431,video_tag_id_432,video_tag_id_433,video_tag_id_434,video_tag_id_435,video_tag_id_436,video_tag_id_437,video_tag_id_438,video_tag_id_439,video_tag_id_440,video_tag_id_441,video_tag_id_442,video_tag_id_443,video_tag_id_444,video_tag_id_445,video_tag_id_446,video_tag_id_447,video_tag_id_448,video_tag_id_449,video_tag_id_450,video_tag_id_451,video_tag_id_452,video_tag_id_453,video_tag_id_454,video_tag_id_455,video_tag_id_456,video_tag_id_457,video_tag_id_458,video_tag_id_459,video_tag_id_460,video_tag_id_461,video_tag_id_462,video_tag_id_463,video_tag_id_464,video_tag_id_465,video_tag_id_466,video_tag_id_467,video_tag_id_468,video_tag_id_469,video_tag_id_470,video_tag_id_471,video_tag_id_472,video_tag_id_473,video_tag_id_474,video_tag_id_475,video_tag_id_476,video_tag_id_477,video_tag_id_478,video_tag_id_479,video_tag_id_480,video_tag_id_481,video_tag_id_482,video_tag_id_483,video_tag_id_484,video_tag_id_485,video_tag_id_486,video_tag_id_487,video_tag_id_488,video_tag_id_489,video_tag_id_490,video_tag_id_491,video_tag_id_492,video_tag_id_493,video_tag_id_494,video_tag_id_495,video_tag_id_496,video_tag_id_497,video_tag_id_498,video_tag_id_499,video_tag_id_500,video_tag_id_501,video_tag_id_502,video_tag_id_503,video_tag_id_504,video_tag_id_505,video_tag_id_506,video_tag_id_507,video_tag_id_508,video_tag_id_509,video_tag_id_510,video_tag_id_511,video_tag_id_512,video_tag_id_513,video_tag_id_514,video_tag_id_515,video_tag_id_516,video_tag_id_517,video_tag_id_518,video_tag_id_519,video_tag_id_520,video_tag_id_521,video_tag_id_522,video_tag_id_523,video_tag_id_524,video_tag_id_525,video_tag_id_526,video_tag_id_527,video_tag_id_528,video_tag_id_529,video_tag_id_530,video_tag_id_531,video_tag_id_532,video_tag_id_533,video_tag_id_534,video_tag_id_535,video_tag_id_536,video_tag_id_537,video_tag_id_538,video_tag_id_539,video_tag_id_540,video_tag_id_541,video_tag_id_542,video_tag_id_543,video_tag_id_544,video_tag_id_545,video_tag_id_546,video_tag_id_547,video_tag_id_548,video_tag_id_549,video_tag_id_550,video_tag_id_551,video_tag_id_552,video_tag_id_553,video_tag_id_554,video_tag_id_555,video_tag_id_556,video_tag_id_557,video_tag_id_558,video_tag_id_559,video_tag_id_560,video_tag_id_561,upload_type_0,upload_type_1,upload_type_2,upload_type_3,upload_type_4,upload_type_5,upload_type_6,upload_type_7,upload_type_8,upload_type_9,upload_type_10,upload_type_11,upload_type_12,upload_type_13,upload_type_14,upload_type_15,upload_type_16,upload_type_17,visible_status_0,visible_status_1,visible_status_2
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343336,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1

In [15]:
item_daily_features_processd = pd.concat([item_daily_features[['video_id','date']+item_sparse_feature_2+item_dense_feature],item_daily_features_onehot],axis=1)
item_daily_features_processd

,video_id,date,video_type,video_duration,video_width,video_height,show_cnt,show_user_num,play_cnt,play_user_num,play_duration,complete_play_cnt,complete_play_user_num,valid_play_cnt,valid_play_user_num,long_time_play_cnt,long_time_play_user_num,short_time_play_cnt,short_time_play_user_num,play_progress,comment_stay_duration,like_cnt,like_user_num,click_like_cnt,double_click_cnt,cancel_like_cnt,cancel_like_user_num,comment_cnt,comment_user_num,direct_comment_cnt,reply_comment_cnt,delete_comment_cnt,delete_comment_user_num,comment_like_cnt,comment_like_user_num,follow_cnt,follow_user_num,cancel_follow_cnt,cancel_follow_user_num,share_cnt,share_user_num,download_cnt,download_user_num,report_cnt,report_user_num,reduce_similar_cnt,reduce_similar_user_num,video_tag_id_0,video_tag_id_1,video_tag_id_2,video_tag_id_3,video_tag_id_4,video_tag_id_5,video_tag_id_6,video_tag_id_7,video_tag_id_8,video_tag_id_9,video_tag_id_10,video_tag_id_11,video_tag_id_12,video_tag_id_13,video_tag_id_14,video_tag_id_15,video_tag_id_16,video_tag_id_17,video_tag_id_18,video_tag_id_19,video_tag_id_20,video_tag_id_21,video_tag_id_22,video_tag_id_23,video_tag_id_24,video_tag_id_25,video_tag_id_26,video_tag_id_27,video_tag_id_28,video_tag_id_29,video_tag_id_30,video_tag_id_31,video_tag_id_32,video_tag_id_33,video_tag_id_34,video_tag_id_35,video_tag_id_36,video_tag_id_37,video_tag_id_38,video_tag_id_39,video_tag_id_40,video_tag_id_41,video_tag_id_42,video_tag_id_43,video_tag_id_44,video_tag_id_45,video_tag_id_46,video_tag_id_47,video_tag_id_48,video_tag_id_49,video_tag_id_50,video_tag_id_51,video_tag_id_52,video_tag_id_53,video_tag_id_54,video_tag_id_55,video_tag_id_56,video_tag_id_57,video_tag_id_58,video_tag_id_59,video_tag_id_60,video_tag_id_61,video_tag_id_62,video_tag_id_63,video_tag_id_64,video_tag_id_65,video_tag_id_66,video_tag_id_67,video_tag_id_68,video_tag_id_69,video_tag_id_70,video_tag_id_71,video_tag_id_72,video_tag_id_73,video_tag_id_74,video_tag_id_75,video_tag_id_76,video_tag_id_77,video_tag_id_78,video_tag_id_79,video_tag_id_80,video_tag_id_81,video_tag_id_82,video_tag_id_83,video_tag_id_84,video_tag_id_85,video_tag_id_86,video_tag_id_87,video_tag_id_88,video_tag_id_89,video_tag_id_90,video_tag_id_91,video_tag_id_92,video_tag_id_93,video_tag_id_94,video_tag_id_95,video_tag_id_96,video_tag_id_97,video_tag_id_98,video_tag_id_99,video_tag_id_100,video_tag_id_101,video_tag_id_102,video_tag_id_103,video_tag_id_104,video_tag_id_105,video_tag_id_106,video_tag_id_107,video_tag_id_108,video_tag_id_109,video_tag_id_110,video_tag_id_111,video_tag_id_112,video_tag_id_113,video_tag_id_114,video_tag_id_115,video_tag_id_116,video_tag_id_117,video_tag_id_118,video_tag_id_119,video_tag_id_120,video_tag_id_121,video_tag_id_122,video_tag_id_123,video_tag_id_124,video_tag_id_125,video_tag_id_126,video_tag_id_127,video_tag_id_128,video_tag_id_129,video_tag_id_130,video_tag_id_131,video_tag_id_132,video_tag_id_133,video_tag_id_134,video_tag_id_135,video_tag_id_136,video_tag_id_137,video_tag_id_138,video_tag_id_139,video_tag_id_140,video_tag_id_141,video_tag_id_142,video_tag_id_143,video_tag_id_144,video_tag_id_145,video_tag_id_146,video_tag_id_147,video_tag_id_148,video_tag_id_149,video_tag_id_150,video_tag_id_151,video_tag_id_152,video_tag_id_153,video_tag_id_154,video_tag_id_155,video_tag_id_156,video_tag_id_157,video_tag_id_158,video_tag_id_159,video_tag_id_160,video_tag_id_161,video_tag_id_162,video_tag_id_163,video_tag_id_164,video_tag_id_165,video_tag_id_166,video_tag_id_167,video_tag_id_168,video_tag_id_169,video_tag_id_170,video_tag_id_171,video_tag_id_172,video_tag_id_173,video_tag_id_174,video_tag_id_175,video_tag_id_176,video_tag_id_177,video_tag_id_178,video_tag_id_179,video_tag_id_180,video_tag_id_181,video_tag_id_182,video_tag_id_183,video_tag_id_184,video_tag_id_185,video_tag_id_186,video_tag_id_187,video_tag_id_188,video_tag_id_189,video_tag_id_190,video_tag_id_191,video_tag_id_192,video_tag_id_193,video_tag_id_194,video_tag_id_195,video_tag_id_196,video_tag_id_197,video_tag_id_198,video_tag_id_199,video_tag_id_200,video_tag_id_201,video_tag_id_202,video_tag_id_203,video_tag_id_204,video_tag_id_205,video_tag_id_206,video_tag_id_207,video_tag_id_208,video_tag_id_209,video_tag_id_210,video_tag_id_211,video_tag_id_212,video_tag_id_213,video_tag_id_214,video_tag_id_215,video_tag_id_216,video_tag_id_217,video_tag_id_218,video_tag_id_219,video_tag_id_220,video_tag_id_221,video_tag_id_222,video_tag_id_223,video_tag_id_224,video_tag_id_225,video_tag_id_226,video_tag_id_227,video_tag_id_228,video_tag_id_229,video_tag_id_230,video_tag_id_231,video_tag_id_232,video_tag_id_233,video_tag_id_234,video_tag_id_235,video_tag_id_236,video_tag_id_237,video_tag_id_238,video_tag_id_239,video_tag_id_240,video_tag_id_241,video_tag_id_242,video_tag_id_243,video_tag_id_244,video_tag_id_245,video_tag_id_246,video_tag_id_247,video_tag_id_248,video_tag_id_249,video_tag_id_250,video_tag_id_251,video_tag_id_252,video_tag_id_253,video_tag_id_254,video_tag_id_255,video_tag_id_256,video_tag_id_257,video_tag_id_258,video_tag_id_259,video_tag_id_260,video_tag_id_261,video_tag_id_262,video_tag_id_263,video_tag_id_264,video_tag_id_265,video_tag_id_266,video_tag_id_267,video_tag_id_268,video_tag_id_269,video_tag_id_270,video_tag_id_271,video_tag_id_272,video_tag_id_273,video_tag_id_274,video_tag_id_275,video_tag_id_276,video_tag_id_277,video_tag_id_278,video_tag_id_279,video_tag_id_280,video_tag_id_281,video_tag_id_282,video_tag_id_283,video_tag_id_284,video_tag_id_285,video_tag_id_286,video_tag_id_287,video_tag_id_288,video_tag_id_289,video_tag_id_290,video_tag_id_291,video_tag_id_292,video_tag_id_293,video_tag_id_294,video_tag_id_295,video_tag_id_296,video_tag_id_297,video_tag_id_298,video_tag_id_299,video_tag_id_300,video_tag_id_301,video_tag_id_302,video_tag_id_303,video_tag_id_304,video_tag_id_305,video_tag_id_306,video_tag_id_307,video_tag_id_308,video_tag_id_309,video_tag_id_310,video_tag_id_311,video_tag_id_312,video_tag_id_313,video_tag_id_314,video_tag_id_315,video_tag_id_316,video_tag_id_317,video_tag_id_318,video_tag_id_319,video_tag_id_320,video_tag_id_321,video_tag_id_322,video_tag_id_323,video_tag_id_324,video_tag_id_325,video_tag_id_326,video_tag_id_327,video_tag_id_328,video_tag_id_329,video_tag_id_330,video_tag_id_331,video_tag_id_332,video_tag_id_333,video_tag_id_334,video_tag_id_335,video_tag_id_336,video_tag_id_337,video_tag_id_338,video_tag_id_339,video_tag_id_340,video_tag_id_341,video_tag_id_342,video_tag_id_343,video_tag_id_344,video_tag_id_345,video_tag_id_346,video_tag_id_347,video_tag_id_348,video_tag_id_349,video_tag_id_350,video_tag_id_351,video_tag_id_352,video_tag_id_353,video_tag_id_354,video_tag_id_355,video_tag_id_356,video_tag_id_357,video_tag_id_358,video_tag_id_359,video_tag_id_360,video_tag_id_361,video_tag_id_362,video_tag_id_363,video_tag_id_364,video_tag_id_365,video_tag_id_366,video_tag_id_367,video_tag_id_368,video_tag_id_369,video_tag_id_370,video_tag_id_371,video_tag_id_372,video_tag_id_373,video_tag_id_374,video_tag_id_375,video_tag_id_376,video_tag_id_377,video_tag_id_378,video_tag_id_379,video_tag_id_380,video_tag_id_381,video_tag_id_382,video_tag_id_383,video_tag_id_384,video_tag_id_385,video_tag_id_386,video_tag_id_387,video_tag_id_388,video_tag_id_389,video_tag_id_390,video_tag_id_391,video_tag_id_392,video_tag_id_393,video_tag_id_394,video_tag_id_395,video_tag_id_396,video_tag_id_397,video_tag_id_398,video_tag_id_399,video_tag_id_400,video_tag_id_401,video_tag_id_402,video_tag_id_403,video_tag_id_404,video_tag_id_405,video_tag_id_406,video_tag_id_407,video_tag_id_408,video_tag_id_409,video_tag_id_410,video_tag_id_411,video_tag_id_412,video_tag_id_413,video_tag_id_414,video_tag_id_415,video_tag_id_416,video_tag_id_417,video_tag_id_418,video_tag_id_419,video_tag_id_420,video_tag_id_421,video_tag_id_422,video_tag_id_423,video_tag_id_424,video_tag_id_425,video_tag_id_426,video_tag_id_427,video_tag_id_428,video_tag_id_429,video_tag_id_430,video_tag_id_431,video_tag_id_432,video_tag_id_433,video_tag_id_434,video_tag_id_435,video_tag_id_436,video_tag_id_437,video_tag_id_438,video_tag_id_439,video_tag_id_440,video_tag_id_441,video_tag_id_442,video_tag_id_443,video_tag_id_444,video_tag_id_445,video_tag_id_446,video_tag_id_447,video_tag_id_448,video_tag_id_449,video_tag_id_450,video_tag_id_451,video_tag_id_452,video_tag_id_453,video_tag_id_454,video_tag_id_455,video_tag_id_456,video_tag_id_457,video_tag_id_458,video_tag_id_459,video_tag_id_460,video_tag_id_461,video_tag_id_462,video_tag_id_463,video_tag_id_464,video_tag_id_465,video_tag_id_466,video_tag_id_467,video_tag_id_468,video_tag_id_469,video_tag_id_470,video_tag_id_471,video_tag_id_472,video_tag_id_473,video_tag_id_474,video_tag_id_475,video_tag_id_476,video_tag_id_477,video_tag_id_478,video_tag_id_479,video_tag_id_480,video_tag_id_481,video_tag_id_482,video_tag_id_483,video_tag_id_484,video_tag_id_485,video_tag_id_486,video_tag_id_487,video_tag_id_488,video_tag_id_489,video_tag_id_490,video_tag_id_491,video_tag_id_492,video_tag_id_493,video_tag_id_494,video_tag_id_495,video_tag_id_496,video_tag_id_497,video_tag_id_498,video_tag_id_499,video_tag_id_500,video_tag_id_501,video_tag_id_502,video_tag_id_503,video_tag_id_504,video_tag_id_505,video_tag_id_506,video_tag_id_507,video_tag_id_508,video_tag_id_509,video_tag_id_510,video_tag_id_511,video_tag_id_512,video_tag_id_513,video_tag_id_514,video_tag_id_515,video_tag_id_516,video_tag_id_517,video_tag_id_518,video_tag_id_519,video_tag_id_520,video_tag_id_521,video_tag_id_522,video_tag_id_523,video_tag_id_524,video_tag_id_525,video_tag_id_526,video_tag_id_527,video_tag_id_528,video_tag_id_529,video_tag_id_530,video_tag_id_531,video_tag_id_532,video_tag_id_533,video_tag_id_534,video_tag_id_535,video_tag_id_536,video_tag_id_537,video_tag_id_538,video_tag_id_539,video_tag_id_540,video_tag_id_541,video_tag_id_542,video_tag_id_543,video_tag_id_544,video_tag_id_545,video_tag_id_546,video_tag_id_547,video_tag_id_548,video_tag_id_549,video_tag_id_550,video_tag_id_551,video_tag_id_552,video_tag_id_553,video_tag_id_554,video_tag_id_555,video_tag_id_556,video_tag_id_557,video_tag_id_558,video_tag_id_559,video_tag_id_560,video_tag_id_561,upload_type_0,upload_type_1,upload_type_2,upload_type_3,upload_type_4,upload_type_5,upload_type_6,upload_type_7,upload_type_8,upload_type_9,upload_type_10,upload_type_11,upload_type_12,upload_type_13,upload_type_14,upload_type_15,upload_type_16,upload_type_17,visible_status_0,visible_status_1,visible_status_2
0,0,20200705,1,0.018813,0.163399,0.355030,0.000348,0.000292,0.000246,0.000201,4.467997e-05,0.000224,0.000199,0.000189,0.000169,0.000208,0.000185,0.000186,0.000162,0.799860,3.179897e-05,0.000214,0.000215,1.850155e-04,0.000266,0.000372,0.000407,0.000060,0.000064,0.000046,0.00003,0.0,0.0,0.000164,0.000199,0.000575,0.000576,0.0,0.0,0.000007,0.000007,0.000060,0.000060,0.000000,0.000000,0.000087,0.000089,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
1,0,20200706,1,0.018813,0.163399,0.355030,0.000258,0.000219,0.000178,0.000147,3.236061e-05,0.000165,0.000145,0.000138,0.000123,0.000152,0.000134,0.000128,0.000114,0.805253,1.917529e-05,0.000113,0.000114,9.338878e-05,0.000147,0.000201,0.000225,0.000038,0.000041,0.000034,0.00001,0.0,0.0,0.000088,0.000104,0.000407,0.000406,0.0,0.0,0.000003,0.000004,0.000015,0.000015,0.000000,0.000000,0.000145,0.000148,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
2,0,20200707,1,0.018813,0.163399,0.355030,0.000186,0.000161,0.000116,0.000100,2.081623e-05,0.000108,0.000099,0.000090,0.000084,0.000100,0.000092,0.000083,0.000075,0.808821,1.589822e-05,0.000077,0.000077,7.106945e-05,0.000087,0.000223,0.000239,0.000022,0.000017,0.000017,0.00001,0.0,0.0,0.000086,0.000085,0.000265,0.000266,0.0,0.0,0.000003,0.000004,0.000015,0.000015,0.000000,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3,0,20200708,1,0.018813,0.163399,0.355030,0.000211,0.000186,0.000126,0.000106,2.280150e-05,0.000117,0.000104,0.000098,0.000088,0.000108,0.000097,0.000094,0.000084,0.801680,2.031732e-05,0.000111,0.000110,1.045484e-04,0.000123,0.000257,0.000282,0.000022,0.000023,0.000011,0.00002,0.0,0.0,0.000133,0.000150,0.000363,0.000363,0.0,0.0,0.000007,0.000007,0.000022,0.000022,0.000000,0.000000,0.000087,0.000089,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
4,0,20200709,1,0.018813,0.163399,0.355030,0.000202,0.000171,0.000131,0.000106,2.364318e-05,0.000121,0.000106,0.000101,0.000090,0.000111,0.000098,0.000100,0.000082,0.805359,1.852579e-05,0.000115,0.000115,9.750023e-05,0.000146,0.000244,0.000268,0.000027,0.000012,0.000000,0.00005,0.0,0.0,0.000111,0.000153,0.000377,0.000377,0.0,0.0,0.000000,0.000000,0.000015,0.000015,0.010101,0.005682,0.000029,0.000030,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1

In [22]:
# item daily feature 特征是统计了每个item每天的特征，这个其实就对应了分布的漂移

In [16]:
item_features_columns = item_daily_features_processd.columns.tolist()
item_features_columns

['video_id',
 'date',
 'video_type',
 'video_duration',
 'video_width',
 'video_height',
 'show_cnt',
 'show_user_num',
 'play_cnt',
 'play_user_num',
 'play_duration',
 'complete_play_cnt',
 'complete_play_user_num',
 'valid_play_cnt',
 'valid_play_user_num',
 'long_time_play_cnt',
 'long_time_play_user_num',
 'short_time_play_cnt',
 'short_time_play_user_num',
 'play_progress',
 'comment_stay_duration',
 'like_cnt',
 'like_user_num',
 'click_like_cnt',
 'double_click_cnt',
 'cancel_like_cnt',
 'cancel_like_user_num',
 'comment_cnt',
 'comment_user_num',
 'direct_comment_cnt',
 'reply_comment_cnt',
 'delete_comment_cnt',
 'delete_comment_user_num',
 'comment_like_cnt',
 'comment_like_user_num',
 'follow_cnt',
 'follow_user_num',
 'cancel_follow_cnt',
 'cancel_follow_user_num',
 'share_cnt',
 'share_user_num',
 'download_cnt',
 'download_user_num',
 'report_cnt',
 'report_user_num',
 'reduce_similar_cnt',
 'reduce_similar_user_num',
 'video_tag_id_0',
 'video_tag_id_1',
 'video_tag_id_2',
 'video_tag_id_3',
 'video_tag_id_4',
 'video_tag_id_5',
 'video_tag_id_6',
 'video_tag_id_7',
 'video_tag_id_8',
 'video_tag_id_9',
 'video_tag_id_10',
 'video_tag_id_11',
 'video_tag_id_12',
 'video_tag_id_13',
 'video_tag_id_14',
 'video_tag_id_15',
 'video_tag_id_16',
 'video_tag_id_17',
 'video_tag_id_18',
 'video_tag_id_19',
 'video_tag_id_20',
 'video_tag_id_21',
 'video_tag_id_22',
 'video_tag_id_23',
 'video_tag_id_24',
 'video_tag_id_25',
 'video_tag_id_26',
 'video_tag_id_27',
 'video_tag_id_28',
 'video_tag_id_29',
 'video_tag_id_30',
 'video_tag_id_31',
 'video_tag_id_32',
 'video_tag_id_33',
 'video_tag_id_34',
 'video_tag_id_35',
 'video_tag_id_36',
 'video_tag_id_37',
 'video_tag_id_38',
 'video_tag_id_39',
 'video_tag_id_40',
 'video_tag_id_41',
 'video_tag_id_42',
 'video_tag_id_43',
 'video_tag_id_44',
 'video_tag_id_45',
 'video_tag_id_46',
 'video_tag_id_47',
 'video_tag_id_48',
 'video_tag_id_49',
 'video_tag_id_50',
 'video_tag_id_51',
 'video_tag_id_52',
 'video_tag_id_53',
 'video_tag_id_54',
 'video_tag_id_55',
 'video_tag_id_56',
 'video_tag_id_57',
 'video_tag_id_58',
 'video_tag_id_59',
 'video_tag_id_60',
 'video_tag_id_61',
 'video_tag_id_62',
 'video_tag_id_63',
 'video_tag_id_64',
 'video_tag_id_65',
 'video_tag_id_66',
 'video_tag_id_67',
 'video_tag_id_68',
 'video_tag_id_69',
 'video_tag_id_70',
 'video_tag_id_71',
 'video_tag_id_72',
 'video_tag_id_73',
 'video_tag_id_74',
 'video_tag_id_75',
 'video_tag_id_76',
 'video_tag_id_77',
 'video_tag_id_78',
 'video_tag_id_79',
 'video_tag_id_80',
 'video_tag_id_81',
 'video_tag_id_82',
 'video_tag_id_83',
 'video_tag_id_84',
 'video_tag_id_85',
 'video_tag_id_86',
 'video_tag_id_87',
 'video_tag_id_88',
 'video_tag_id_89',
 'video_tag_id_90',
 'video_tag_id_91',
 'video_tag_id_92',
 'video_tag_id_93',
 'video_tag_id_94',
 'video_tag_id_95',
 'video_tag_id_96',
 'video_tag_id_97',
 'video_tag_id_98',
 'video_tag_id_99',
 'video_tag_id_100',
 'video_tag_id_101',
 'video_tag_id_102',
 'video_tag_id_103',
 'video_tag_id_104',
 'video_tag_id_105',
 'video_tag_id_106',
 'video_tag_id_107',
 'video_tag_id_108',
 'video_tag_id_109',
 'video_tag_id_110',
 'video_tag_id_111',
 'video_tag_id_112',
 'video_tag_id_113',
 'video_tag_id_114',
 'video_tag_id_115',
 'video_tag_id_116',
 'video_tag_id_117',
 'video_tag_id_118',
 'video_tag_id_119',
 'video_tag_id_120',
 'video_tag_id_121',
 'video_tag_id_122',
 'video_tag_id_123',
 'video_tag_id_124',
 'video_tag_id_125',
 'video_tag_id_126',
 'video_tag_id_127',
 'video_tag_id_128',
 'video_tag_id_129',
 'video_tag_id_130',
 'video_tag_id_131',
 'video_tag_id_132',
 'video_tag_id_133',
 'video_tag_id_134',
 'video_tag_id_135',
 'video_tag_id_136',
 'video_tag_id_137',
 'video_tag_id_138',
 'video_tag_id_139',
 'video_tag_id_140',
 'video_tag_id_141',
 'video_tag_id_142',
 'video_tag_id_143',
 'video_tag_id_144',
 'video_tag_id_145',
 'video_tag_id_146',
 'video_tag_id_147',
 'video_tag_id_148',
 'video_tag_id_149',
 'video_tag_id_150',
 'video_tag_id_151',
 'video_tag_id_152',
 'video_tag_id_153',
 'video_tag_id_154',
 'video_tag_id_155',
 'video_tag_id_156',
 'video_tag_id_157',
 'video_tag_id_158',
 'video_tag_id_159',
 'video_tag_id_160',
 'video_tag_id_161',
 'video_tag_id_162',
 'video_tag_id_163',
 'video_tag_id_164',
 'video_tag_id_165',
 'video_tag_id_166',
 'video_tag_id_167',
 'video_tag_id_168',
 'video_tag_id_169',
 'video_tag_id_170',
 'video_tag_id_171',
 'video_tag_id_172',
 'video_tag_id_173',
 'video_tag_id_174',
 'video_tag_id_175',
 'video_tag_id_176',
 'video_tag_id_177',
 'video_tag_id_178',
 'video_tag_id_179',
 'video_tag_id_180',
 'video_tag_id_181',
 'video_tag_id_182',
 'video_tag_id_183',
 'video_tag_id_184',
 'video_tag_id_185',
 'video_tag_id_186',
 'video_tag_id_187',
 'video_tag_id_188',
 'video_tag_id_189',
 'video_tag_id_190',
 'video_tag_id_191',
 'video_tag_id_192',
 'video_tag_id_193',
 'video_tag_id_194',
 'video_tag_id_195',
 'video_tag_id_196',
 'video_tag_id_197',
 'video_tag_id_198',
 'video_tag_id_199',
 'video_tag_id_200',
 'video_tag_id_201',
 'video_tag_id_202',
 'video_tag_id_203',
 'video_tag_id_204',
 'video_tag_id_205',
 'video_tag_id_206',
 'video_tag_id_207',
 'video_tag_id_208',
 'video_tag_id_209',
 'video_tag_id_210',
 'video_tag_id_211',
 'video_tag_id_212',
 'video_tag_id_213',
 'video_tag_id_214',
 'video_tag_id_215',
 'video_tag_id_216',
 'video_tag_id_217',
 'video_tag_id_218',
 'video_tag_id_219',
 'video_tag_id_220',
 'video_tag_id_221',
 'video_tag_id_222',
 'video_tag_id_223',
 'video_tag_id_224',
 'video_tag_id_225',
 'video_tag_id_226',
 'video_tag_id_227',
 'video_tag_id_228',
 'video_tag_id_229',
 'video_tag_id_230',
 'video_tag_id_231',
 'video_tag_id_232',
 'video_tag_id_233',
 'video_tag_id_234',
 'video_tag_id_235',
 'video_tag_id_236',
 'video_tag_id_237',
 'video_tag_id_238',
 'video_tag_id_239',
 'video_tag_id_240',
 'video_tag_id_241',
 'video_tag_id_242',
 'video_tag_id_243',
 'video_tag_id_244',
 'video_tag_id_245',
 'video_tag_id_246',
 'video_tag_id_247',
 'video_tag_id_248',
 'video_tag_id_249',
 'video_tag_id_250',
 'video_tag_id_251',
 'video_tag_id_252',
 'video_tag_id_253',
 'video_tag_id_254',
 'video_tag_id_255',
 'video_tag_id_256',
 'video_tag_id_257',
 'video_tag_id_258',
 'video_tag_id_259',
 'video_tag_id_260',
 'video_tag_id_261',
 'video_tag_id_262',
 'video_tag_id_263',
 'video_tag_id_264',
 'video_tag_id_265',
 'video_tag_id_266',
 'video_tag_id_267',
 'video_tag_id_268',
 'video_tag_id_269',
 'video_tag_id_270',
 'video_tag_id_271',
 'video_tag_id_272',
 'video_tag_id_273',
 'video_tag_id_274',
 'video_tag_id_275',
 'video_tag_id_276',
 'video_tag_id_277',
 'video_tag_id_278',
 'video_tag_id_279',
 'video_tag_id_280',
 'video_tag_id_281',
 'video_tag_id_282',
 'video_tag_id_283',
 'video_tag_id_284',
 'video_tag_id_285',
 'video_tag_id_286',
 'video_tag_id_287',
 'video_tag_id_288',
 'video_tag_id_289',
 'video_tag_id_290',
 'video_tag_id_291',
 'video_tag_id_292',
 'video_tag_id_293',
 'video_tag_id_294',
 'video_tag_id_295',
 'video_tag_id_296',
 'video_tag_id_297',
 'video_tag_id_298',
 'video_tag_id_299',
 'video_tag_id_300',
 'video_tag_id_301',
 'video_tag_id_302',
 'video_tag_id_303',
 'video_tag_id_304',
 'video_tag_id_305',
 'video_tag_id_306',
 'video_tag_id_307',
 'video_tag_id_308',
 'video_tag_id_309',
 'video_tag_id_310',
 'video_tag_id_311',
 'video_tag_id_312',
 'video_tag_id_313',
 'video_tag_id_314',
 'video_tag_id_315',
 'video_tag_id_316',
 'video_tag_id_317',
 'video_tag_id_318',
 'video_tag_id_319',
 'video_tag_id_320',
 'video_tag_id_321',
 'video_tag_id_322',
 'video_tag_id_323',
 'video_tag_id_324',
 'video_tag_id_325',
 'video_tag_id_326',
 'video_tag_id_327',
 'video_tag_id_328',
 'video_tag_id_329',
 'video_tag_id_330',
 'video_tag_id_331',
 'video_tag_id_332',
 'video_tag_id_333',
 'video_tag_id_334',
 'video_tag_id_335',
 'video_tag_id_336',
 'video_tag_id_337',
 'video_tag_id_338',
 'video_tag_id_339',
 'video_tag_id_340',
 'video_tag_id_341',
 'video_tag_id_342',
 'video_tag_id_343',
 'video_tag_id_344',
 'video_tag_id_345',
 'video_tag_id_346',
 'video_tag_id_347',
 'video_tag_id_348',
 'video_tag_id_349',
 'video_tag_id_350',
 'video_tag_id_351',
 'video_tag_id_352',
 'video_tag_id_353',
 'video_tag_id_354',
 'video_tag_id_355',
 'video_tag_id_356',
 'video_tag_id_357',
 'video_tag_id_358',
 'video_tag_id_359',
 'video_tag_id_360',
 'video_tag_id_361',
 'video_tag_id_362',
 'video_tag_id_363',
 'video_tag_id_364',
 'video_tag_id_365',
 'video_tag_id_366',
 'video_tag_id_367',
 'video_tag_id_368',
 'video_tag_id_369',
 'video_tag_id_370',
 'video_tag_id_371',
 'video_tag_id_372',
 'video_tag_id_373',
 'video_tag_id_374',
 'video_tag_id_375',
 'video_tag_id_376',
 'video_tag_id_377',
 'video_tag_id_378',
 'video_tag_id_379',
 'video_tag_id_380',
 'video_tag_id_381',
 'video_tag_id_382',
 'video_tag_id_383',
 'video_tag_id_384',
 'video_tag_id_385',
 'video_tag_id_386',
 'video_tag_id_387',
 'video_tag_id_388',
 'video_tag_id_389',
 'video_tag_id_390',
 'video_tag_id_391',
 'video_tag_id_392',
 'video_tag_id_393',
 'video_tag_id_394',
 'video_tag_id_395',
 'video_tag_id_396',
 'video_tag_id_397',
 'video_tag_id_398',
 'video_tag_id_399',
 'video_tag_id_400',
 'video_tag_id_401',
 'video_tag_id_402',
 'video_tag_id_403',
 'video_tag_id_404',
 'video_tag_id_405',
 'video_tag_id_406',
 'video_tag_id_407',
 'video_tag_id_408',
 'video_tag_id_409',
 'video_tag_id_410',
 'video_tag_id_411',
 'video_tag_id_412',
 'video_tag_id_413',
 'video_tag_id_414',
 'video_tag_id_415',
 'video_tag_id_416',
 'video_tag_id_417',
 'video_tag_id_418',
 'video_tag_id_419',
 'video_tag_id_420',
 'video_tag_id_421',
 'video_tag_id_422',
 'video_tag_id_423',
 'video_tag_id_424',
 'video_tag_id_425',
 'video_tag_id_426',
 'video_tag_id_427',
 'video_tag_id_428',
 'video_tag_id_429',
 'video_tag_id_430',
 'video_tag_id_431',
 'video_tag_id_432',
 'video_tag_id_433',
 'video_tag_id_434',
 'video_tag_id_435',
 'video_tag_id_436',
 'video_tag_id_437',
 'video_tag_id_438',
 'video_tag_id_439',
 'video_tag_id_440',
 'video_tag_id_441',
 'video_tag_id_442',
 'video_tag_id_443',
 'video_tag_id_444',
 'video_tag_id_445',
 'video_tag_id_446',
 'video_tag_id_447',
 'video_tag_id_448',
 'video_tag_id_449',
 'video_tag_id_450',
 'video_tag_id_451',
 'video_tag_id_452',
 'video_tag_id_453',
 'video_tag_id_454',
 'video_tag_id_455',
 'video_tag_id_456',
 'video_tag_id_457',
 'video_tag_id_458',
 'video_tag_id_459',
 'video_tag_id_460',
 'video_tag_id_461',
 'video_tag_id_462',
 'video_tag_id_463',
 'video_tag_id_464',
 'video_tag_id_465',
 'video_tag_id_466',
 'video_tag_id_467',
 'video_tag_id_468',
 'video_tag_id_469',
 'video_tag_id_470',
 'video_tag_id_471',
 'video_tag_id_472',
 'video_tag_id_473',
 'video_tag_id_474',
 'video_tag_id_475',
 'video_tag_id_476',
 'video_tag_id_477',
 'video_tag_id_478',
 'video_tag_id_479',
 'video_tag_id_480',
 'video_tag_id_481',
 'video_tag_id_482',
 'video_tag_id_483',
 'video_tag_id_484',
 'video_tag_id_485',
 'video_tag_id_486',
 'video_tag_id_487',
 'video_tag_id_488',
 'video_tag_id_489',
 'video_tag_id_490',
 'video_tag_id_491',
 'video_tag_id_492',
 'video_tag_id_493',
 'video_tag_id_494',
 'video_tag_id_495',
 'video_tag_id_496',
 'video_tag_id_497',
 'video_tag_id_498',
 'video_tag_id_499',
 'video_tag_id_500',
 'video_tag_id_501',
 'video_tag_id_502',
 'video_tag_id_503',
 'video_tag_id_504',
 'video_tag_id_505',
 'video_tag_id_506',
 'video_tag_id_507',
 'video_tag_id_508',
 'video_tag_id_509',
 'video_tag_id_510',
 'video_tag_id_511',
 'video_tag_id_512',
 'video_tag_id_513',
 'video_tag_id_514',
 'video_tag_id_515',
 'video_tag_id_516',
 'video_tag_id_517',
 'video_tag_id_518',
 'video_tag_id_519',
 'video_tag_id_520',
 'video_tag_id_521',
 'video_tag_id_522',
 'video_tag_id_523',
 'video_tag_id_524',
 'video_tag_id_525',
 'video_tag_id_526',
 'video_tag_id_527',
 'video_tag_id_528',
 'video_tag_id_529',
 'video_tag_id_530',
 'video_tag_id_531',
 'video_tag_id_532',
 'video_tag_id_533',
 'video_tag_id_534',
 'video_tag_id_535',
 'video_tag_id_536',
 'video_tag_id_537',
 'video_tag_id_538',
 'video_tag_id_539',
 'video_tag_id_540',
 'video_tag_id_541',
 'video_tag_id_542',
 'video_tag_id_543',
 'video_tag_id_544',
 'video_tag_id_545',
 'video_tag_id_546',
 'video_tag_id_547',
 'video_tag_id_548',
 'video_tag_id_549',
 'video_tag_id_550',
 'video_tag_id_551',
 'video_tag_id_552',
 'video_tag_id_553',
 'video_tag_id_554',
 'video_tag_id_555',
 'video_tag_id_556',
 'video_tag_id_557',
 'video_tag_id_558',
 'video_tag_id_559',
 'video_tag_id_560',
 'video_tag_id_561',
 'upload_type_0',
 'upload_type_1',
 'upload_type_2',
 'upload_type_3',
 'upload_type_4',
 'upload_type_5',
 'upload_type_6',
 'upload_type_7',
 'upload_type_8',
 'upload_type_9',
 'upload_type_10',
 'upload_type_11',
 'upload_type_12',
 'upload_type_13',
 'upload_type_14',
 'upload_type_15',
 'upload_type_16',
 'upload_type_17',
 'visible_status_0',
 'visible_status_1',
 'visible_status_2']

### PCA降维 到25维

In [17]:
from sklearn.decomposition import PCA
item_daily_features_processd_for_pca = item_daily_features_processd[item_features_columns[2:]]
item_daily_features_processd_for_pca
pca = PCA(n_components=25)
pca.fit(item_daily_features_processd_for_pca)
item_daily_features_processd_pca = pca.transform(item_daily_features_processd_for_pca)
item_daily_features_processd_for_pca.shape
item_daily_features_processd_pca.shape

,video_type,video_duration,video_width,video_height,show_cnt,show_user_num,play_cnt,play_user_num,play_duration,complete_play_cnt,complete_play_user_num,valid_play_cnt,valid_play_user_num,long_time_play_cnt,long_time_play_user_num,short_time_play_cnt,short_time_play_user_num,play_progress,comment_stay_duration,like_cnt,like_user_num,click_like_cnt,double_click_cnt,cancel_like_cnt,cancel_like_user_num,comment_cnt,comment_user_num,direct_comment_cnt,reply_comment_cnt,delete_comment_cnt,delete_comment_user_num,comment_like_cnt,comment_like_user_num,follow_cnt,follow_user_num,cancel_follow_cnt,cancel_follow_user_num,share_cnt,share_user_num,download_cnt,download_user_num,report_cnt,report_user_num,reduce_similar_cnt,reduce_similar_user_num,video_tag_id_0,video_tag_id_1,video_tag_id_2,video_tag_id_3,video_tag_id_4,video_tag_id_5,video_tag_id_6,video_tag_id_7,video_tag_id_8,video_tag_id_9,video_tag_id_10,video_tag_id_11,video_tag_id_12,video_tag_id_13,video_tag_id_14,video_tag_id_15,video_tag_id_16,video_tag_id_17,video_tag_id_18,video_tag_id_19,video_tag_id_20,video_tag_id_21,video_tag_id_22,video_tag_id_23,video_tag_id_24,video_tag_id_25,video_tag_id_26,video_tag_id_27,video_tag_id_28,video_tag_id_29,video_tag_id_30,video_tag_id_31,video_tag_id_32,video_tag_id_33,video_tag_id_34,video_tag_id_35,video_tag_id_36,video_tag_id_37,video_tag_id_38,video_tag_id_39,video_tag_id_40,video_tag_id_41,video_tag_id_42,video_tag_id_43,video_tag_id_44,video_tag_id_45,video_tag_id_46,video_tag_id_47,video_tag_id_48,video_tag_id_49,video_tag_id_50,video_tag_id_51,video_tag_id_52,video_tag_id_53,video_tag_id_54,video_tag_id_55,video_tag_id_56,video_tag_id_57,video_tag_id_58,video_tag_id_59,video_tag_id_60,video_tag_id_61,video_tag_id_62,video_tag_id_63,video_tag_id_64,video_tag_id_65,video_tag_id_66,video_tag_id_67,video_tag_id_68,video_tag_id_69,video_tag_id_70,video_tag_id_71,video_tag_id_72,video_tag_id_73,video_tag_id_74,video_tag_id_75,video_tag_id_76,video_tag_id_77,video_tag_id_78,video_tag_id_79,video_tag_id_80,video_tag_id_81,video_tag_id_82,video_tag_id_83,video_tag_id_84,video_tag_id_85,video_tag_id_86,video_tag_id_87,video_tag_id_88,video_tag_id_89,video_tag_id_90,video_tag_id_91,video_tag_id_92,video_tag_id_93,video_tag_id_94,video_tag_id_95,video_tag_id_96,video_tag_id_97,video_tag_id_98,video_tag_id_99,video_tag_id_100,video_tag_id_101,video_tag_id_102,video_tag_id_103,video_tag_id_104,video_tag_id_105,video_tag_id_106,video_tag_id_107,video_tag_id_108,video_tag_id_109,video_tag_id_110,video_tag_id_111,video_tag_id_112,video_tag_id_113,video_tag_id_114,video_tag_id_115,video_tag_id_116,video_tag_id_117,video_tag_id_118,video_tag_id_119,video_tag_id_120,video_tag_id_121,video_tag_id_122,video_tag_id_123,video_tag_id_124,video_tag_id_125,video_tag_id_126,video_tag_id_127,video_tag_id_128,video_tag_id_129,video_tag_id_130,video_tag_id_131,video_tag_id_132,video_tag_id_133,video_tag_id_134,video_tag_id_135,video_tag_id_136,video_tag_id_137,video_tag_id_138,video_tag_id_139,video_tag_id_140,video_tag_id_141,video_tag_id_142,video_tag_id_143,video_tag_id_144,video_tag_id_145,video_tag_id_146,video_tag_id_147,video_tag_id_148,video_tag_id_149,video_tag_id_150,video_tag_id_151,video_tag_id_152,video_tag_id_153,video_tag_id_154,video_tag_id_155,video_tag_id_156,video_tag_id_157,video_tag_id_158,video_tag_id_159,video_tag_id_160,video_tag_id_161,video_tag_id_162,video_tag_id_163,video_tag_id_164,video_tag_id_165,video_tag_id_166,video_tag_id_167,video_tag_id_168,video_tag_id_169,video_tag_id_170,video_tag_id_171,video_tag_id_172,video_tag_id_173,video_tag_id_174,video_tag_id_175,video_tag_id_176,video_tag_id_177,video_tag_id_178,video_tag_id_179,video_tag_id_180,video_tag_id_181,video_tag_id_182,video_tag_id_183,video_tag_id_184,video_tag_id_185,video_tag_id_186,video_tag_id_187,video_tag_id_188,video_tag_id_189,video_tag_id_190,video_tag_id_191,video_tag_id_192,video_tag_id_193,video_tag_id_194,video_tag_id_195,video_tag_id_196,video_tag_id_197,video_tag_id_198,video_tag_id_199,video_tag_id_200,video_tag_id_201,video_tag_id_202,video_tag_id_203,video_tag_id_204,video_tag_id_205,video_tag_id_206,video_tag_id_207,video_tag_id_208,video_tag_id_209,video_tag_id_210,video_tag_id_211,video_tag_id_212,video_tag_id_213,video_tag_id_214,video_tag_id_215,video_tag_id_216,video_tag_id_217,video_tag_id_218,video_tag_id_219,video_tag_id_220,video_tag_id_221,video_tag_id_222,video_tag_id_223,video_tag_id_224,video_tag_id_225,video_tag_id_226,video_tag_id_227,video_tag_id_228,video_tag_id_229,video_tag_id_230,video_tag_id_231,video_tag_id_232,video_tag_id_233,video_tag_id_234,video_tag_id_235,video_tag_id_236,video_tag_id_237,video_tag_id_238,video_tag_id_239,video_tag_id_240,video_tag_id_241,video_tag_id_242,video_tag_id_243,video_tag_id_244,video_tag_id_245,video_tag_id_246,video_tag_id_247,video_tag_id_248,video_tag_id_249,video_tag_id_250,video_tag_id_251,video_tag_id_252,video_tag_id_253,video_tag_id_254,video_tag_id_255,video_tag_id_256,video_tag_id_257,video_tag_id_258,video_tag_id_259,video_tag_id_260,video_tag_id_261,video_tag_id_262,video_tag_id_263,video_tag_id_264,video_tag_id_265,video_tag_id_266,video_tag_id_267,video_tag_id_268,video_tag_id_269,video_tag_id_270,video_tag_id_271,video_tag_id_272,video_tag_id_273,video_tag_id_274,video_tag_id_275,video_tag_id_276,video_tag_id_277,video_tag_id_278,video_tag_id_279,video_tag_id_280,video_tag_id_281,video_tag_id_282,video_tag_id_283,video_tag_id_284,video_tag_id_285,video_tag_id_286,video_tag_id_287,video_tag_id_288,video_tag_id_289,video_tag_id_290,video_tag_id_291,video_tag_id_292,video_tag_id_293,video_tag_id_294,video_tag_id_295,video_tag_id_296,video_tag_id_297,video_tag_id_298,video_tag_id_299,video_tag_id_300,video_tag_id_301,video_tag_id_302,video_tag_id_303,video_tag_id_304,video_tag_id_305,video_tag_id_306,video_tag_id_307,video_tag_id_308,video_tag_id_309,video_tag_id_310,video_tag_id_311,video_tag_id_312,video_tag_id_313,video_tag_id_314,video_tag_id_315,video_tag_id_316,video_tag_id_317,video_tag_id_318,video_tag_id_319,video_tag_id_320,video_tag_id_321,video_tag_id_322,video_tag_id_323,video_tag_id_324,video_tag_id_325,video_tag_id_326,video_tag_id_327,video_tag_id_328,video_tag_id_329,video_tag_id_330,video_tag_id_331,video_tag_id_332,video_tag_id_333,video_tag_id_334,video_tag_id_335,video_tag_id_336,video_tag_id_337,video_tag_id_338,video_tag_id_339,video_tag_id_340,video_tag_id_341,video_tag_id_342,video_tag_id_343,video_tag_id_344,video_tag_id_345,video_tag_id_346,video_tag_id_347,video_tag_id_348,video_tag_id_349,video_tag_id_350,video_tag_id_351,video_tag_id_352,video_tag_id_353,video_tag_id_354,video_tag_id_355,video_tag_id_356,video_tag_id_357,video_tag_id_358,video_tag_id_359,video_tag_id_360,video_tag_id_361,video_tag_id_362,video_tag_id_363,video_tag_id_364,video_tag_id_365,video_tag_id_366,video_tag_id_367,video_tag_id_368,video_tag_id_369,video_tag_id_370,video_tag_id_371,video_tag_id_372,video_tag_id_373,video_tag_id_374,video_tag_id_375,video_tag_id_376,video_tag_id_377,video_tag_id_378,video_tag_id_379,video_tag_id_380,video_tag_id_381,video_tag_id_382,video_tag_id_383,video_tag_id_384,video_tag_id_385,video_tag_id_386,video_tag_id_387,video_tag_id_388,video_tag_id_389,video_tag_id_390,video_tag_id_391,video_tag_id_392,video_tag_id_393,video_tag_id_394,video_tag_id_395,video_tag_id_396,video_tag_id_397,video_tag_id_398,video_tag_id_399,video_tag_id_400,video_tag_id_401,video_tag_id_402,video_tag_id_403,video_tag_id_404,video_tag_id_405,video_tag_id_406,video_tag_id_407,video_tag_id_408,video_tag_id_409,video_tag_id_410,video_tag_id_411,video_tag_id_412,video_tag_id_413,video_tag_id_414,video_tag_id_415,video_tag_id_416,video_tag_id_417,video_tag_id_418,video_tag_id_419,video_tag_id_420,video_tag_id_421,video_tag_id_422,video_tag_id_423,video_tag_id_424,video_tag_id_425,video_tag_id_426,video_tag_id_427,video_tag_id_428,video_tag_id_429,video_tag_id_430,video_tag_id_431,video_tag_id_432,video_tag_id_433,video_tag_id_434,video_tag_id_435,video_tag_id_436,video_tag_id_437,video_tag_id_438,video_tag_id_439,video_tag_id_440,video_tag_id_441,video_tag_id_442,video_tag_id_443,video_tag_id_444,video_tag_id_445,video_tag_id_446,video_tag_id_447,video_tag_id_448,video_tag_id_449,video_tag_id_450,video_tag_id_451,video_tag_id_452,video_tag_id_453,video_tag_id_454,video_tag_id_455,video_tag_id_456,video_tag_id_457,video_tag_id_458,video_tag_id_459,video_tag_id_460,video_tag_id_461,video_tag_id_462,video_tag_id_463,video_tag_id_464,video_tag_id_465,video_tag_id_466,video_tag_id_467,video_tag_id_468,video_tag_id_469,video_tag_id_470,video_tag_id_471,video_tag_id_472,video_tag_id_473,video_tag_id_474,video_tag_id_475,video_tag_id_476,video_tag_id_477,video_tag_id_478,video_tag_id_479,video_tag_id_480,video_tag_id_481,video_tag_id_482,video_tag_id_483,video_tag_id_484,video_tag_id_485,video_tag_id_486,video_tag_id_487,video_tag_id_488,video_tag_id_489,video_tag_id_490,video_tag_id_491,video_tag_id_492,video_tag_id_493,video_tag_id_494,video_tag_id_495,video_tag_id_496,video_tag_id_497,video_tag_id_498,video_tag_id_499,video_tag_id_500,video_tag_id_501,video_tag_id_502,video_tag_id_503,video_tag_id_504,video_tag_id_505,video_tag_id_506,video_tag_id_507,video_tag_id_508,video_tag_id_509,video_tag_id_510,video_tag_id_511,video_tag_id_512,video_tag_id_513,video_tag_id_514,video_tag_id_515,video_tag_id_516,video_tag_id_517,video_tag_id_518,video_tag_id_519,video_tag_id_520,video_tag_id_521,video_tag_id_522,video_tag_id_523,video_tag_id_524,video_tag_id_525,video_tag_id_526,video_tag_id_527,video_tag_id_528,video_tag_id_529,video_tag_id_530,video_tag_id_531,video_tag_id_532,video_tag_id_533,video_tag_id_534,video_tag_id_535,video_tag_id_536,video_tag_id_537,video_tag_id_538,video_tag_id_539,video_tag_id_540,video_tag_id_541,video_tag_id_542,video_tag_id_543,video_tag_id_544,video_tag_id_545,video_tag_id_546,video_tag_id_547,video_tag_id_548,video_tag_id_549,video_tag_id_550,video_tag_id_551,video_tag_id_552,video_tag_id_553,video_tag_id_554,video_tag_id_555,video_tag_id_556,video_tag_id_557,video_tag_id_558,video_tag_id_559,video_tag_id_560,video_tag_id_561,upload_type_0,upload_type_1,upload_type_2,upload_type_3,upload_type_4,upload_type_5,upload_type_6,upload_type_7,upload_type_8,upload_type_9,upload_type_10,upload_type_11,upload_type_12,upload_type_13,upload_type_14,upload_type_15,upload_type_16,upload_type_17,visible_status_0,visible_status_1,visible_status_2
0,1,0.018813,0.163399,0.355030,0.000348,0.000292,0.000246,0.000201,4.467997e-05,0.000224,0.000199,0.000189,0.000169,0.000208,0.000185,0.000186,0.000162,0.799860,3.179897e-05,0.000214,0.000215,1.850155e-04,0.000266,0.000372,0.000407,0.000060,0.000064,0.000046,0.00003,0.0,0.0,0.000164,0.000199,0.000575,0.000576,0.0,0.0,0.000007,0.000007,0.000060,0.000060,0.000000,0.000000,0.000087,0.000089,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
1,1,0.018813,0.163399,0.355030,0.000258,0.000219,0.000178,0.000147,3.236061e-05,0.000165,0.000145,0.000138,0.000123,0.000152,0.000134,0.000128,0.000114,0.805253,1.917529e-05,0.000113,0.000114,9.338878e-05,0.000147,0.000201,0.000225,0.000038,0.000041,0.000034,0.00001,0.0,0.0,0.000088,0.000104,0.000407,0.000406,0.0,0.0,0.000003,0.000004,0.000015,0.000015,0.000000,0.000000,0.000145,0.000148,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
2,1,0.018813,0.163399,0.355030,0.000186,0.000161,0.000116,0.000100,2.081623e-05,0.000108,0.000099,0.000090,0.000084,0.000100,0.000092,0.000083,0.000075,0.808821,1.589822e-05,0.000077,0.000077,7.106945e-05,0.000087,0.000223,0.000239,0.000022,0.000017,0.000017,0.00001,0.0,0.0,0.000086,0.000085,0.000265,0.000266,0.0,0.0,0.000003,0.000004,0.000015,0.000015,0.000000,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3,1,0.018813,0.163399,0.355030,0.000211,0.000186,0.000126,0.000106,2.280150e-05,0.000117,0.000104,0.000098,0.000088,0.000108,0.000097,0.000094,0.000084,0.801680,2.031732e-05,0.000111,0.000110,1.045484e-04,0.000123,0.000257,0.000282,0.000022,0.000023,0.000011,0.00002,0.0,0.0,0.000133,0.000150,0.000363,0.000363,0.0,0.0,0.000007,0.000007,0.000022,0.000022,0.000000,0.000000,0.000087,0.000089,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
4,1,0.018813,0.163399,0.355030,0.000202,0.000171,0.000131,0.000106,2.364318e-05,0.000121,0.000106,0.000101,0.000090,0.000111,0.000098,0.000100,0.000082,0.805359,1.852579e-05,0.000115,0.000115,9.750023e-05,0.000146,0.000244,0.000268,0.000027,0.000012,0.000000,0.00005,0.0,0.0,0.000111,0.000153,0.000377,0.000377,0.0,0.0,0.000000,0.000000,0.000015,0.000015,0.010101,0.005682,0.000029,0.000030,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1

PCA(n_components=25)

(343341, 628)

(343341, 25)

In [25]:
new_item_daily_data = pd.concat([item_daily_features_processd[['video_id', 'date']], pd.DataFrame(item_daily_features_processd_pca)], axis=1)
new_item_daily_data.columns = ['video_id', 'date'] + ["v"+str(i) for i in range(25)]
new_item_daily_data

,video_id,date,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18,v19,v20,v21,v22,v23,v24
0,0,20200705,-0.500783,-0.021146,-0.020828,-0.042827,0.372269,-0.064526,-0.030237,0.020533,-0.029087,-0.048127,-0.040939,-0.007408,0.019336,0.003283,-0.005352,0.007167,0.046009,0.004024,0.008336,0.004438,-0.029383,-0.019759,-0.013523,-0.005138,-0.016134
1,0,20200706,-0.501539,-0.020626,-0.020729,-0.041565,0.377308,-0.065137,-0.030695,0.020893,-0.029217,-0.048340,-0.041060,-0.007169,0.019291,0.003180,-0.005134,0.007255,0.046192,0.004068,0.008484,0.004562,-0.029379,-0.019794,-0.013505,-0.005053,-0.015991
2,0,20200707,-0.502039,-0.020282,-0.020663,-0.040730,0.380641,-0.065541,-0.030998,0.021131,-0.029303,-0.048481,-0.041140,-0.007011,0.019260,0.003112,-0.004990,0.007314,0.046314,0.004096,0.008581,0.004643,-0.029376,-0.019817,-0.013493,-0.004997,-0.015896
3,0,20200708,-0.501037,-0.020974,-0.020795,-0.042404,0.373959,-0.064735,-0.030389,0.020656,-0.029132,-0.048200,-0.040980,-0.007327,0.019318,0.003250,-0.005280,0.007198,0.046070,0.004039,0.008387,0.004479,-0.029382,-0.019771,-0.013516,-0.005109,-0.016086
4,0,20200709,-0.501555,-0.020614,-0.020728,-0.041539,0.377414,-0.065147,-0.030705,0.020899,-0.029222,-0.048345,-0.041063,-0.007165,0.019290,0.003177,-0.005129,0.007252,0.046196,0.004062,0.008486,0.004569,-0.029373,-0.019795,-0.013505,-0.005051,-0.015989
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343336,10723,20200905,-0.465774,-0.055610,-0.024956,-0.105090,0.165705,-0.048879,-0.016089,0.007375,-0.023988,-0.046700,-0.057562,-0.028377,0.053476,0.018432,-0.031130,-0.010534,0.034007,0.012055,0.154109,-0.045631,-0.103917,-0.208501,0.868223,0.327005,0.103507
343337,10724,20200905,0.500469,0.411354,-0.034175,-0.122323,0.308176,0.722221,-0.538309,-0.015460,0.010847,-0.015498,0.004712,-0.069660,0.012788,-0.003021,-0.003505,-0.017585,0.026633,-0.008742,0.014137,0.020369,-0.016574,-0.009541,-0.001919,0.001508,0.006376
343338,10725,20200905,-0.467286,-0.040927,-0.024133,-0.093091,0.154675,-0.042287,-0.022417,0.010091,-0.017508,-0.035756,-0.030167,-0.019687,0.025565,0.007009,-0.010850,-0.000016,0.021330,0.000719,0.000865,-0.000723,-0.025053,-0.013035,-0.007597,-0.006607,-0.011819
343339,10726,20200905,-0.501116,-0.007233,-0.020317,-0.043395,0.373312,-0.074838,-0.047855,0.018475,-0.022043,-0.048364,-0.034996,-0.020018,0.011682,-0.002065,-0.010802,0.005939,0.040718,0.002515,0.019991,0.008303,-0.029658,-0.023036,-0.010797,-0.000659,-0.014694
343340,10727,20200905,0.892802,-0.595622,0.031484,-0.086790,0.015264,-0.115009,-0.060937,-0.009056,0.021771,-0.001982,-0.111530,-0.058979,0.025147,0.030762,-0.078669,-0.036978,0.108960,0.773373,-0.174617,0.087950,0.505266,0.048736,0.021906,0.035159,0.020271

In [34]:
grouped_feature = new_item_daily_data.groupby('video_id').mean().drop(columns=['date']).reset_index(level='video_id')
# grouped_feature = grouped_feature.set_index('video_id')
grouped_feature

,video_id,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18,v19,v20,v21,v22,v23,v24
0,0,-0.455352,-0.052904,-0.026822,-0.118887,0.069964,-0.028110,-0.003444,-0.000546,-0.021418,-0.035601,-0.034397,-0.021394,0.020917,0.008985,-0.018723,0.002238,0.036022,0.001595,0.000404,-0.002589,-0.031476,-0.018988,-0.015324,-0.012125,-0.026828
1,1,0.454934,0.262099,0.699175,0.365964,-0.350615,0.245838,0.207768,0.027996,-0.138357,-0.030480,-0.087534,0.388678,-0.309821,-0.262420,0.100628,0.175469,0.579621,-0.176704,-0.030858,-0.252804,0.247271,-0.023172,0.013505,0.020148,0.029147
2,2,0.604627,0.720926,-0.021720,-0.153536,-0.137626,-0.557654,-0.129066,-0.012974,0.035596,-0.021431,-0.006578,-0.041843,0.017866,-0.004676,-0.058936,-0.005695,0.009307,-0.009252,-0.004495,0.004702,-0.029311,-0.020927,-0.007265,-0.009223,-0.002814
3,3,0.498918,0.205528,-0.025525,-0.203114,-0.234439,0.206369,0.264937,0.034318,-0.148255,-0.054614,-0.110811,0.339339,-0.301285,-0.258513,0.075641,0.176351,0.604505,-0.177518,-0.029936,-0.253649,0.224146,-0.036904,0.005818,0.010317,0.014105
4,4,0.904818,-0.615313,0.032611,-0.092350,-0.041057,-0.106685,-0.048657,-0.011760,0.031350,0.015990,-0.088411,-0.062222,0.024511,0.004944,-0.020048,-0.017518,0.003193,-0.003834,-0.032433,-0.079712,-0.139315,-0.098892,-0.403811,0.754125,0.081312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10723,10723,-0.465774,-0.055610,-0.024956,-0.105090,0.165705,-0.048879,-0.016089,0.007375,-0.023988,-0.046700,-0.057562,-0.028377,0.053476,0.018432,-0.031130,-0.010534,0.034007,0.012055,0.154109,-0.045631,-0.103917,-0.208501,0.868223,0.327005,0.103507
10724,10724,0.500469,0.411354,-0.034175,-0.122323,0.308176,0.722221,-0.538309,-0.015460,0.010847,-0.015498,0.004712,-0.069660,0.012788,-0.003021,-0.003505,-0.017585,0.026633,-0.008742,0.014137,0.020369,-0.016574,-0.009541,-0.001919,0.001508,0.006376
10725,10725,-0.467286,-0.040927,-0.024133,-0.093091,0.154675,-0.042287,-0.022417,0.010091,-0.017508,-0.035756,-0.030167,-0.019687,0.025565,0.007009,-0.010850,-0.000016,0.021330,0.000719,0.000865,-0.000723,-0.025053,-0.013035,-0.007597,-0.006607,-0.011819
10726,10726,-0.501116,-0.007233,-0.020317,-0.043395,0.373312,-0.074838,-0.047855,0.018475,-0.022043,-0.048364,-0.034996,-0.020018,0.011682,-0.002065,-0.010802,0.005939,0.040718,0.002515,0.019991,0.008303,-0.029658,-0.023036,-0.010797,-0.000659,-0.014694
10727,10727,0.892802,-0.595622,0.031484,-0.086790,0.015264,-0.115009,-0.060937,-0.009056,0.021771,-0.001982,-0.111530,-0.058979,0.025147,0.030762,-0.078669,-0.036978,0.108960,0.773373,-0.174617,0.087950,0.505266,0.048736,0.021906,0.035159,0.020271

In [36]:
grouped_feature.to_csv("./item_feature_pca_meanday.csv", sep=" ", index=False)