# 将User_FeatureVectors聚成40类

### 读取所有用户向量

In [2]:
import pandas as pd
import numpy as np
# Path of the file to read
User_filepath = "./user_feature_pca.csv"#可以选择
FeatureVectors = {}
Userfeatures_noid = []
User_id = []
data = pd.read_csv(User_filepath, header=0,sep=' ')
data_user = data.iloc[:,0]
print(data_user)
data_feature = data.iloc[:,1:]
data_feature
# with open(User_filepath, "r") as f:
#     # f.readline() # skip the header
#     for line in f:
#         line = line.split("\t")
#         vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
#         FeatureVectors[int(line[0])] = np.array(vec).astype(float)
#         Userfeatures_noid.append(np.array(vec).astype(float))
#         User_id.append(int(line[0]))
# Userfeatures_noid = pd.DataFrame(Userfeatures_noid)
# Userfeatures_noid

0          0
1          1
2          2
3          3
4          4
        ...
7171    7171
7172    7172
7173    7173
7174    7174
7175    7175
Name: user_id, Length: 7176, dtype: int64

,u0,u1,u2,u3,u4,u5,u6,u7,u8,u9,...,u15,u16,u17,u18,u19,u20,u21,u22,u23,u24
0,-1.674993,0.152371,-0.554478,0.847241,-0.487899,0.379005,0.038020,0.683137,-0.043919,0.463972,...,0.025993,-0.487937,-0.513339,-0.060585,0.092976,0.162210,-0.263889,-0.347352,0.251206,0.208874
1,0.353917,-1.110304,1.185043,0.134926,-0.119457,0.115978,-0.387008,0.258563,-0.518948,-0.095652,...,0.734863,0.624212,-0.383560,-0.332877,-0.399949,0.062644,-0.418552,0.275639,0.188519,0.255468
2,-0.333553,1.103801,0.204809,0.232690,0.007381,0.132940,0.401279,-1.488611,-0.436226,0.569142,...,0.290853,0.251065,-0.164117,-0.360368,-0.423455,0.713594,0.097480,-0.051655,0.547016,0.350105
3,-0.658980,1.172114,0.762873,-0.289276,0.313181,-0.195914,-0.190670,-1.212718,-0.201246,0.093425,...,-0.352097,0.541714,0.023365,-0.017354,0.213095,-0.118452,-0.016572,0.376097,-0.159158,-0.124515
4,-0.263066,-0.781668,-0.032065,-1.030237,-0.041411,-0.860592,-0.677270,-0.097401,-0.318732,0.046551,...,0.197960,-0.430306,0.372218,0.136370,0.498894,-0.193749,-0.210194,-0.270706,0.178125,-0.176187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7171,0.404764,-0.846309,-0.645774,-0.188909,-0.138761,-0.583587,0.241269,-0.113076,-0.145269,0.295969,...,0.117326,-0.257680,-0.230332,0.268963,-0.653390,-0.647309,-0.405664,-0.040272,-0.325261,0.631514
7172,0.138108,-0.873551,0.685209,0.142144,-0.605445,1.214768,0.451691,-0.694564,-0.120286,-0.455424,...,0.429813,0.601006,-0.507452,-0.075559,-0.744555,0.350266,-0.340947,-0.065165,0.382320,0.235505
7173,1.334196,0.262405,-0.146614,-1.131377,0.207926,0.824497,-0.787195,-0.134796,-0.132404,0.463317,...,0.033094,0.299075,-0.276668,0.104060,-0.676064,0.904495,0.089272,-0.141311,0.509480,0.112142
7174,-0.423911,-0.368874,0.673537,0.627725,1.059992,-0.631193,-0.119376,0.054937,0.098089,-0.610454,...,0.313102,0.809837,0.353500,0.113543,-0.264847,0.908311,0.635354,0.354454,-0.537803,-0.327043
7175,0.382793,-0.503213,-0.848771,-0.150371,1.014602,0.563848,-1.034925,-0.713395,-0.231569,0.193781,...,0.051566,0.178112,0.117024,0.219552,0.146996,0.222483,0.134586,0.070334,-0.041519,-0.160424

### 生成聚类向量

In [9]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
# 假设 user_vectors 是用户向量的集合，每个向量形状为 (n_features,)
Userfeatures_noid = data_feature
n_clusters = 40# 指定聚类的数量
kmeans = KMeans(n_clusters=n_clusters)
kmeans.fit(Userfeatures_noid)
centers = kmeans.cluster_centers_
for i in range(len(centers)):
    print("Class {}: {}".format(i+1, centers[i]))


# 计算轮廓系数
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")

Class 1: [ 0.26980467  0.70477468  0.23289483 -0.32200755  0.05255877  0.05830713
  0.80390654  0.22424225 -0.26453395  0.05505236 -0.14835931 -0.33798561
  0.15682744  0.47383648  0.11481233 -0.24745323 -0.25475637  0.01439714
  0.17790276  0.02869209 -0.09388317  0.14461081 -0.21132311  0.1789968
 -0.10626195]
Class 2: [-0.87355543 -0.33216121  0.33625185  0.49720494  0.40442158 -0.30393143
  0.33436943 -0.60832493 -0.08443697 -0.11935009 -0.08470055 -0.07702747
 -0.04926703 -0.06409124 -0.13478327  0.1292627   0.04319332 -0.16886024
 -0.18662851  0.13691916  0.07359246  0.15224965  0.15113492 -0.16750195
  0.06162921]
Class 3: [ 0.5229867  -0.6931007  -0.06182285  0.80889794  0.81661345 -0.00739741
 -0.59107942 -0.12074632 -0.0728757  -0.17664728 -0.03932805  0.25743818
  0.26535801  0.02280797  0.14708486  0.14803379  0.02758783  0.35462689
  0.28964916 -0.11169486  0.19674492  0.10937112 -0.04400464 -0.07311399
 -0.15049191]
Class 4: [-0.67884724 -0.37187739 -0.73229035 -0.31202796  0.53946728 -0.38563549
  0.13145622 -0.51559377  0.07781006  0.08693178  0.01297852 -0.06383069
 -0.05170897 -0.00557024 -0.14586726  0.02250591  0.11423969 -0.23092169
 -0.14180601  0.02207051  0.05786103  0.10760341 -0.0125625  -0.1230918
  0.03334072]
Class 5: [-0.22814124 -0.72834716 -0.14152473 -0.84885029  0.07106661 -0.29720139
 -0.07233209 -0.02174448  0.21387662  0.10198144  0.04364109 -0.32072641
  0.0736999  -0.0165875   0.25587585 -0.03689184  0.01653678  0.29994181
  0.02763817 -0.02391826 -0.0596363  -0.12734738  0.03329827 -0.02823014
 -0.0703459 ]
Class 6: [ 1.25029829  0.72282675 -0.92483787  0.85494675  0.19695624 -0.15365228
 -0.12178844 -0.18063079 -0.00675587 -0.12849542  0.02385253  0.03507247
  0.09133996  0.03331294  0.28008458  0.01993505 -0.22805747  0.27079681
 -0.0574471  -0.04050701  0.08116103 -0.09629277  0.02001856  0.17968785
  0.0308823 ]
Class 7: [ 9.12931755e-01  7.15487959e-01  4.48621832e-01  1.10949056e+00
  5.55916795e-01  5.95969384e-02 -6.23543152e-03 -3.11058921e-01
  5.64246260e-02  4.60157431e-02  9.98393968e-02  1.09242903e-01
 -1.05500831e-01 -9.22833991e-02  1.60118520e-01  1.42341054e-01
 -4.33109815e-02  2.47960652e-01  1.37337364e-02 -1.04799611e-03
 -1.74539118e-01 -9.42196493e-02 -4.37716638e-02 -2.71505011e-02
  8.68024785e-02]
Class 8: [-0.59822009  1.28203428 -0.54868651 -0.29585124 -0.00332721 -0.22762608
 -0.31199259  0.25391625  0.11917791 -0.07779172 -0.07666527 -0.1198916
 -0.08494596  0.08371422 -0.1006794  -0.05569735  0.0053495  -0.21337327
 -0.07599478  0.07019579 -0.04003577 -0.00881594 -0.02813176  0.05111616
  0.01948325]
Class 9: [-9.90817129e-01 -3.18823565e-01  5.68384076e-01 -1.04704572e-02
 -3.17868356e-01  4.11057340e-01 -2.22242825e-01 -6.83466826e-01
 -1.22217998e-01  5.38974647e-02 -1.79019202e-02 -2.01797200e-01
  2.77495537e-04 -1.22077269e-01  1.02024460e-01 -5.16142720e-02
 -8.40902655e-02  2.53293649e-01  2.29275762e-01 -1.63443296e-01
  7.12005420e-03  3.61593031e-02  2.69862440e-02 -3.02753457e-02
  9.00489511e-02]
Class 10: [ 1.19787477  0.32187376  0.29542868  0.01612309 -0.23873088  0.40234447
  0.41164525  0.38129345 -0.38545463  0.00513738  0.05459423  0.0079426
 -0.04718011  0.47644052 -0.2154081  -0.20759134 -0.0461798  -0.4085681
  0.20585421  0.0025502   0.05197035  0.14161974 -0.14068474  0.25263217
 -0.18530139]
Class 11: [-0.16412363 -0.64126321 -0.56156798 -0.09075874 -0.65045039 -0.54082026
  0.17736454 -0.10120179  0.16595787  0.06465038 -0.15302368 -0.31093241
  0.01194226 -0.16213996  0.25314055 -0.00198622 -0.04579066  0.19815462
  0.15311751  0.03880223 -0.06072823 -0.08212133 -0.01393045 -0.02247905
 -0.0353388 ]
Class 12: [-0.43037719 -0.7047964   0.90512071  0.17946158 -0.17074148 -0.45692632
  0.05569766 -0.00097866  0.06932621  0.03478942 -0.18928662 -0.21883447
  0.05614606 -0.16419576  0.19310185 -0.04396652 -0.12193612  0.31811474
  0.05442119  0.05511232 -0.11505998  0.01861247  0.09086282 -0.14094302
  0.074544  ]
Class 13: [-1.49276585 -0.00991885  0.04528252  0.29260551  0.22654287  0.17791145
 -0.20613333  0.3547175   0.60876075  0.04597553 -0.08264215  0.40343402
  0.18340722  0.41082711  0.09376808  0.27587341 -0.15269491 -0.35939702
 -0.04617095 -0.16485144  0.05169344  0.07077843 -0.02671619 -0.03226374
  0.04570039]
Class 14: [-0.92481445  1.30463485  0.64430984  0.3278887   0.18778946 -0.04227078
 -0.12997767  0.0845703   0.02317508  0.02589812  0.04233529 -0.07273618
 -0.02811328 -0.15338785 -0.20785458  0.07354885  0.06206437 -0.26391399
 -0.02902736  0.06275906  0.04857953  0.01820886  0.03744349 -0.00391702
 -0.07598197]
Class 15: [ 0.91826992  0.5897984  -0.33402144 -0.40255657 -0.86672953  0.12676268
 -0.3043082  -0.0896965   0.01997688 -0.2407946   0.26250043  0.04519531
 -0.28100866 -0.03381588 -0.06164552 -0.08236479 -0.22701475 -0.19434214
 -0.02849406 -0.26802623 -0.09213371  0.02374909  0.13248765 -0.030374
  0.0087475 ]
Class 16: [ 0.24994564 -0.95738025  1.02402312  0.07752738 -0.06695704  0.33627801
 -0.56106063 -0.09522772 -0.07884162 -0.12520224  0.16452545  0.15695234
 -0.17967825  0.03247955 -0.12578054 -0.00494692  0.05168688 -0.12501548
 -0.20034573 -0.03561092 -0.03509576  0.00591458  0.04758853 -0.04691527
  0.13282732]
Class 17: [-1.18023422 -0.25790069  0.02674933 -0.02500322  0.69657849  0.23110138
  0.04814433  0.2366023   0.08120975 -0.25226455  0.0263664  -0.40372678
 -0.12375738  0.07229907 -0.0952834  -0.27198408  0.28694259 -0.14776106
 -0.04538745 -0.48545428  0.02669396 -0.33677084 -0.1495622   0.540071
  0.05120893]
Class 18: [ 0.75154667 -1.12952324 -0.070481   -0.32221787  0.16304827  0.07734827
 -0.30716752  0.11387631 -0.24619045 -0.2064718  -0.22262885  0.10115345
 -0.10175578 -0.01264698 -0.42377738  0.40197694 -0.4516501  -0.25342023
  0.00732073  0.43139948  0.10255377 -0.07311874 -0.0227121   0.06550972
 -0.13221916]
Class 19: [ 0.30856764  0.70439321 -0.1743396  -0.96259976 -0.21391     0.14693802
  0.18739299 -0.24994658  0.44011831  0.21343548 -0.09301337 -0.22488119
 -0.00946885 -0.15807564  0.20629042  0.06154224 -0.00386079  0.20710715
  0.16320527  0.04292333 -0.02223631 -0.02716734 -0.05685568  0.01660042
 -0.00758224]
Class 20: [ 0.68264442 -0.85023342 -0.67576225  0.36593911 -0.81237234 -0.00921528
 -0.38082566  0.01133858  0.08402714 -0.06086333 -0.08768635 -0.05817898
  0.10648141  0.08073325 -0.12104587 -0.03609289  0.15453127 -0.13255246
 -0.38236252  0.15479147  0.04640166  0.0487681  -0.13976656  0.05128383
 -0.05931302]
Class 21: [ 0.89434255  0.3873908   1.06186436  0.13041655 -0.47661263  0.23628155
 -0.19968117 -0.08841373 -0.08264786 -0.0653243  -0.01114975  0.14297533
 -0.19733038 -0.05860189 -0.22398377  0.04381095  0.14754473 -0.25332798
 -0.14487279 -0.01192834 -0.02475415  0.03966967  0.03962738 -0.06751897
  0.13312742]
Class 22: [ 1.44788202  0.3603852   0.01033381 -0.152545    0.36710079 -0.14491454
 -0.47360535  0.23132428 -0.29111091 -0.06860743 -0.18477811  0.1435808
  0.12827322 -0.01926248 -0.04368794  0.06861655  0.02601709 -0.07831023
  0.17281994 -0.22772456  0.61159698  0.18283296  0.20917234 -0.08167117
 -0.11832303]
Class 23: [-0.24708011  0.97406424 -0.07207146 -0.36079861  0.4056072  -0.41211746
  0.35477114 -0.61942199 -0.02752341  0.00946838  0.0911787   0.12842394
  0.00875153 -0.02394048 -0.22416732 -0.00651321  0.11236274 -0.23875337
 -0.12580141 -0.05825753  0.07445441  0.13217931  0.01090146  0.00312231
 -0.00176575]
Class 24: [ 0.01164979 -0.33751701 -0.0494587  -0.32040335 -0.30116268  0.62914299
  0.76012429  0.70675371 -0.53244982 -0.10023849  0.16359397  0.76579792
 -0.02253585 -0.39102319 -0.00318528 -0.03985419  0.2039978   0.61934799
 -0.15249568  0.06302208  0.01256602 -0.14454004  0.06022825 -0.12554035
  0.06906588]
Class 25: [ 1.30119738  0.22280777  0.05739613 -0.66706353  0.0271312  -0.04509853
 -0.19484579  0.17697943  0.07433209  0.14754913  0.25553986  0.15831134
 -0.11921254 -0.04874797 -0.22064583  0.02603579  0.2046537  -0.36970746
 -0.14406524  0.05643481 -0.10261169 -0.0357215  -0.1547154  -0.03088747
  0.06068807]
Class 26: [ 0.75578068 -1.09036816 -0.15524151 -0.24273445 -0.0661602  -0.13171739
 -0.31675519  0.34221216  0.10242842  0.04039234  0.28395825  0.05424645
 -0.17425863 -0.0465145  -0.13737958 -0.09198826  0.19216813 -0.30122412
 -0.03875654 -0.20736944  0.02424594  0.03992437  0.05543835 -0.1063168
 -0.06771014]
Class 27: [ 0.52290868  0.54033213 -0.08100217 -0.63960723 -0.28367073 -0.86049302
  0.265121    0.12315549  0.13279932 -0.0965201  -0.11740824 -0.07137663
  0.12305393 -0.0880032   0.19562766  0.07739079  0.05207989  0.17517525
  0.15478337 -0.04698821 -0.07851528 -0.04052742 -0.01120825  0.04934069
  0.09756778]
Class 28: [-1.25889115  0.25298153 -0.70897659  0.04952842 -0.02421078  0.44599224
  0.59433748  0.61309253 -0.64616564  0.0290832   0.12977313  0.77407434
 -0.09479407 -0.40214894 -0.1821024   0.12337722  0.28175243  0.45170238
 -0.27070506  0.02355751  0.14074314 -0.00878745  0.02828868 -0.21374483
  0.04680505]
Class 29: [ 0.42393259 -0.86563048 -0.31128127 -0.55667238 -0.24855384  0.82631938
 -0.49541015 -0.19537319  0.02178987 -0.07785405  0.08054166 -0.0495585
 -0.19143552  0.01395077 -0.0965023  -0.01530154  0.07457251 -0.22249481
  0.04454546 -0.1459075   0.06477106  0.06403067 -0.07027884  0.05740718
 -0.01815225]
Class 30: [-0.46819299 -0.54327088 -0.11767163 -0.07775677 -0.5455655   0.03092522
  0.12875541  0.14903908  0.92617989  0.16101916 -0.03981325  0.36209311
  0.37809189  0.3261443   0.32520997  0.40149415 -0.28950526  0.03953365
  0.08157446 -0.08126866  0.00842122  0.0610634  -0.03684447 -0.01749589
  0.0133682 ]
Class 31: [ 0.05552612 -0.84965001  0.15604207 -0.16253145  0.18193879  0.13064431
  0.6696633   0.17938759 -0.25563654 -0.09991632 -0.10561766 -0.30803592
  0.21177753  0.42399112  0.16751909 -0.28033216 -0.2050829  -0.08028602
  0.28727563  0.03984001 -0.05183314  0.02397427 -0.105965    0.11766057
 -0.18904002]
Class 32: [-1.03969313  0.02213038 -0.47900734  0.33746371  0.08083605  0.29555865
  0.44596677  0.12143245 -0.46728328  0.02522489 -0.06972375 -0.47109776
  0.01635038  0.61807669 -0.09518406 -0.24436512 -0.23030793 -0.35499409
  0.13915565  0.0963483   0.09072743  0.09098003 -0.08969161  0.06109323
 -0.08216962]
Class 33: [ 2.83390451e-01  6.00722764e-01  9.95407961e-01 -1.39385167e-01
 -1.73807458e-01 -2.44432493e-01  3.01103887e-01 -3.33834101e-01
 -9.97414842e-03  1.63591779e-01 -2.20514408e-01 -1.76434482e-01
  1.12846601e-01 -2.21111167e-01  1.73983196e-01  2.77652491e-04
 -1.41958590e-02  2.57078942e-01  6.08224036e-02  4.00017738e-02
 -3.38175962e-02 -2.55797723e-02  1.45947727e-01 -1.23751457e-02
  1.33388257e-01]
Class 34: [ 0.37204372 -0.87358102  0.45756749  0.75152078 -0.777926    0.28349905
 -0.08013829 -0.21520464 -0.07942345  0.10109692 -0.03958473 -0.00775807
 -0.05416189  0.01016025 -0.13733681 -0.04922745  0.08101011 -0.21025717
 -0.27880508 -0.02674296  0.00766765  0.02596805  0.03421624  0.04291408
 -0.02316692]
Class 35: [ 0.43389052 -0.62742472 -0.60604812  0.90475412  0.59390445  0.30528383
 -0.14086215 -0.18665322  0.16089333 -0.01300674  0.34274338  0.02817591
 -0.00692538  0.00899785  0.26856786 -0.05190651 -0.106493    0.23989533
  0.16693758  0.04723755 -0.31014651 -0.20947098 -0.11966991  0.14734831
  0.05255678]
Class 36: [ 1.2125132   0.66527    -0.47221255  0.20500646  1.02418726  0.21587246
 -0.20677554 -0.0763875   0.04784388 -0.03365747  0.27647267  0.06222082
  0.11632651  0.03155845  0.17729418 -0.10278034 -0.12757163  0.30015836
  0.21405464  0.04496451 -0.2291769  -0.1908715  -0.03658131 -0.02264824
 -0.00227121]
Class 37: [-1.49533601  0.00406583  0.36017782  0.52073413  0.20283303 -0.04276165
 -0.48483823 -0.01010649 -0.19466977  0.10617398 -0.133565   -0.24357822
 -0.08388368 -0.10146136 -0.13785482 -0.09838951  0.02315098 -0.12991387
 -0.15999694  0.08220383  0.01127799  0.03407244  0.12589312 -0.13747362
 -0.03242872]
Class 38: [-1.25044194 -0.02262766 -0.85077653 -0.0736279  -0.04126282 -0.27792392
 -0.52991862 -0.01728658  0.01242482 -0.11490066  0.00508352 -0.11657632
 -0.14823242 -0.02677723 -0.15414705 -0.13300101  0.04654644 -0.14184294
  0.05847134 -0.02199537 -0.09657456  0.04902755  0.0345962   0.05521583
 -0.04828828]
Class 39: [-0.32802506  0.90859044  0.93854491 -0.12493065 -0.43581676  0.09350461
 -0.10567243  0.44321469  0.42766486  0.13227915 -0.13390333 -0.05726097
  0.12475581 -0.08740923  0.28384067  0.22830304 -0.14587212  0.16168985
  0.16629575  0.08614559 -0.03564921 -0.10960562  0.01593433  0.07313052
 -0.0441823 ]
Class 40: [ 1.30007393  0.44605551 -0.44156755  0.21679207 -0.7401175   0.19679893
 -0.05399991  0.04574966  0.33152033  0.17771687 -0.13248388 -0.09522875
 -0.03740273  0.04556412 -0.27922275 -0.11265605  0.30794602 -0.12849073
 -0.25322784  0.28293549  0.01019674 -0.01621271  0.02633626  0.139991
  0.08511718]
轮廓系数：0.06381194952702242

### 生成用户聚类结果信息

In [10]:
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")
print("label",  kmeans.labels_)
print("num_label",  len(kmeans.labels_))
print(kmeans.labels_[1])

轮廓系数：0.06381194952702242
label [31 15 22 ... 21  1  2]
num_label 7176
15

### 同步存储聚类后的用户向量 和 映射关系

In [11]:
# 因为聚类了所以不用考虑原来用户id，类别顺序就是新的id
filename = "./{}clusters_FeatureVectors.dat".format(n_clusters)
with open(filename, 'w', newline='') as f:
    for i in range(centers.shape[0]):
        new_line = str(i) + '\t' + ';'.join(str(centers[i, :]).strip('[').strip(']').split()) + '\n'
        f.write(new_line)
print("done")

#label需要类别顺序与用户id对应，而不是与用户向量的index对应
label_dict = {}
for i in range(len(kmeans.labels_)):
    label_dict[str(data_user[i])] = int(kmeans.labels_[i])
import json
filename = "./{}clusters_labels.json".format(n_clusters)
with open(filename, 'w') as f:
    json.dump(label_dict, f)
print("done")

done
done

## 生成关系矩阵

### 读取聚类向量

In [12]:
import numpy as np
import pandas as pd

In [13]:
classfeatures = []
n_clusters=40
filename = "./{}clusters_FeatureVectors.dat".format(n_clusters)
with open(filename, "r") as f:
    # f.readline()# 跳过第一行
    for line in f:
        line = line.split("\t")
        vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
        classfeatures.append(np.array(vec).astype(float))
classfeatures = pd.DataFrame(classfeatures)
classfeatures

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.269805,0.704775,0.232895,-0.322008,0.052559,0.058307,0.803907,0.224242,-0.264534,0.055052,...,-0.247453,-0.254756,0.014397,0.177903,0.028692,-0.093883,0.144611,-0.211323,0.178997,-0.106262
1,-0.873555,-0.332161,0.336252,0.497205,0.404422,-0.303931,0.334369,-0.608325,-0.084437,-0.119350,...,0.129263,0.043193,-0.168860,-0.186629,0.136919,0.073592,0.152250,0.151135,-0.167502,0.061629
2,0.522987,-0.693101,-0.061823,0.808898,0.816613,-0.007397,-0.591079,-0.120746,-0.072876,-0.176647,...,0.148034,0.027588,0.354627,0.289649,-0.111695,0.196745,0.109371,-0.044005,-0.073114,-0.150492
3,-0.678847,-0.371877,-0.732290,-0.312028,0.539467,-0.385635,0.131456,-0.515594,0.077810,0.086932,...,0.022506,0.114240,-0.230922,-0.141806,0.022071,0.057861,0.107603,-0.012563,-0.123092,0.033341
4,-0.228141,-0.728347,-0.141525,-0.848850,0.071067,-0.297201,-0.072332,-0.021744,0.213877,0.101981,...,-0.036892,0.016537,0.299942,0.027638,-0.023918,-0.059636,-0.127347,0.033298,-0.028230,-0.070346
5,1.250298,0.722827,-0.924838,0.854947,0.196956,-0.153652,-0.121788,-0.180631,-0.006756,-0.128495,...,0.019935,-0.228057,0.270797,-0.057447,-0.040507,0.081161,-0.096293,0.020019,0.179688,0.030882
6,0.912932,0.715488,0.448622,1.109491,0.555917,0.059597,-0.006235,-0.311059,0.056425,0.046016,...,0.142341,-0.043311,0.247961,0.013734,-0.001048,-0.174539,-0.094220,-0.043772,-0.027151,0.086802
7,-0.598220,1.282034,-0.548687,-0.295851,-0.003327,-0.227626,-0.311993,0.253916,0.119178,-0.077792,...,-0.055697,0.005350,-0.213373,-0.075995,0.070196,-0.040036,-0.008816,-0.028132,0.051116,0.019483
8,-0.990817,-0.318824,0.568384,-0.010470,-0.317868,0.411057,-0.222243,-0.683467,-0.122218,0.053897,...,-0.051614,-0.084090,0.253294,0.229276,-0.163443,0.007120,0.036159,0.026986,-0.030275,0.090049
9,1.197875,0.321874,0.295429,0.016123,-0.238731,0.402344,0.411645,0.381293,-0.385455,0.005137,...,-0.207591,-0.046180,-0.408568,0.205854,0.002550,0.051970,0.141620,-0.140685,0.252632,-0.185301
10,-0.164124,-0.641263,-0.561568,-0.090759,-0.650450,-0.540820,0.177365,-0.101202,0.165958,0.064650,...,-0.001986,-0.045791,0.198155,0.153118,0.038802,-0.060728,-0.082121,-0.013930,-0.022479,-0.035339
11,-0.430377,-0.704796,0.905121,0.179462,-0.170741,-0.456926,0.055698,-0.000979,0.069326,0.034789,...,-0.043967,-0.121936,0.318115,0.054421,0.055112,-0.115060,0.018612,0.090863,-0.140943,0.074544
12,-1.492766,-0.009919,0.045283,0.292606,0.226543,0.177911,-0.206133,0.354718,0.608761,0.045976,...,0.275873,-0.152695,-0.359397,-0.046171,-0.164851,0.051693,0.070778,-0.026716,-0.032264,0.045700
13,-0.924814,1.304635,0.644310,0.327889,0.187789,-0.042271,-0.129978,0.084570,0.023175,0.025898,...,0.073549,0.062064,-0.263914,-0.029027,0.062759,0.048580,0.018209,0.037443,-0.003917,-0.075982
14,0.918270,0.589798,-0.334021,-0.402557,-0.866730,0.126763,-0.304308,-0.089696,0.019977,-0.240795,...,-0.082365,-0.227015,-0.194342,-0.028494,-0.268026,-0.092134,0.023749,0.132488,-0.030374,0.008748
15,0.249946,-0.957380,1.024023,0.077527,-0.066957,0.336278,-0.561061,-0.095228,-0.078842,-0.125202,...,-0.004947,0.051687,-0.125015,-0.200346,-0.035611,-0.035096,0.005915,0.047589,-0.046915,0.132827
16,-1.180234,-0.257901,0.026749,-0.025003,0.696578,0.231101,0.048144,0.236602,0.081210,-0.252265,...,-0.271984,0.286943,-0.147761,-0.045387,-0.485454,0.026694,-0.336771,-0.149562,0.540071,0.051209
17,0.751547,-1.129523,-0.070481,-0.322218,0.163048,0.077348,-0.307168,0.113876,-0.246190,-0.206472,...,0.401977,-0.451650,-0.253420,0.007321,0.431399,0.102554,-0.073119,-0.022712,0.065510,-0.132219
18,0.308568,0.704393,-0.174340,-0.962600,-0.213910,0.146938,0.187393,-0.249947,0.440118,0.213435,...,0.061542,-0.003861,0.207107,0.163205,0.042923,-0.022236,-0.027167,-0.056856,0.016600,-0.007582
19,0.682644,-0.850233,-0.675762,0.365939,-0.812372,-0.009215,-0.380826,0.011339,0.084027,-0.060863,...,-0.036093,0.154531,-0.132552,-0.382363,0.154791,0.046402,0.048768,-0.139767,0.051284,-0.059313
20,0.894343,0.387391,1.061864,0.130417,-0.476613,0.236282,-0.199681,-0.088414,-0.082648,-0.065324,...,0.043811,0.147545,-0.253328,-0.144873,-0.011928,-0.024754,0.039670,0.039627,-0.067519,0.133127
21,1.447882,0.360385,0.010334,-0.152545,0.367101,-0.144915,-0.473605,0.231324,-0.291111,-0.068607,...,0.068617,0.026017,-0.078310,0.172820,-0.227725,0.611597,0.182833,0.209172,-0.081671,-0.118323
22,-0.247080,0.974064,-0.072071,-0.360799,0.405607,-0.412117,0.354771,-0.619422,-0.027523,0.009468,...,-0.006513,0.112363,-0.238753,-0.125801,-0.058258,0.074454,0.132179,0.010901,0.003122,-0.001766
23,0.011650,-0.337517,-0.049459,-0.320403,-0.301163,0.629143,0.760124,0.706754,-0.532450,-0.100238,...,-0.039854,0.203998,0.619348,-0.152496,0.063022,0.012566,-0.144540,0.060228,-0.125540,0.069066
24,1.301197,0.222808,0.057396,-0.667064,0.027131,-0.045099,-0.194846,0.176979,0.074332,0.147549,...,0.026036,0.204654,-0.369707,-0.144065,0.056435,-0.102612,-0.035722,-0.154715,-0.030887,0.060688
25,0.755781,-1.090368,-0.155242,-0.242734,-0.066160,-0.131717,-0.316755,0.342212,0.102428,0.040392,...,-0.091988,0.192168,-0.301224,-0.038757,-0.207369,0.024246,0.039924,0.055438,-0.106317,-0.067710
26,0.522909,0.540332,-0.081002,-0.639607,-0.283671,-0.860493,0.265121,0.123155,0.132799,-0.096520,...,0.077391,0.052080,0.175175,0.154783,-0.046988,-0.078515,-0.040527,-0.011208,0.049341,0.097568
27,-1.258891,0.252982,-0.708977,0.049528,-0.024211,0.445992,0.594337,0.613093,-0.646166,0.029083,...,0.123377,0.281752,0.451702,-0.270705,0.023558,0.140743,-0.008787,0.028289,-0.213745,0.046805
28,0.423933,-0.865630,-0.311281,-0.556672,-0.248554,0.826319,-0.495410,-0.195373,0.021790,-0.077854,...,-0.015302,0.074573,-0.222495,0.044545,-0.145907,0.064771,0.064031,-0.070279,0.057407,-0.018152
29,-0.468193,-0.543271,-0.117672,-0.077757,-0.545566,0.030925,0.128755,0.149039,0.926180,0.161019,...,0.401494,-0.289505,0.039534,0.081574,-0.081269,0.008421,0.061063,-0.036844,-0.017496,0.013368
30,0.055526,-0.849650,0.156042,-0.162531,0.181939,0.130644,0.669663,0.179388,-0.255637,-0.099916,...,-0.280332,-0.205083,-0.080286,0.287276,0.039840,-0.051833,0.023974,-0.105965,0.117661,-0.189040
31,-1.039693,0.022130,-0.479007,0.337464,0.080836,0.295559,0.445967,0.121432,-0.467283,0.025225,...,-0.244365,-0.230308,-0.354994,0.139156,0.096348,0.090727,0.090980,-0.089692,0.061093,-0.082170
32,0.283390,0.600723,0.995408,-0.139385,-0.173807,-0.244432,0.301104,-0.333834,-0.009974,0.163592,...,0.000278,-0.014196,0.257079,0.060822,0.040002,-0.033818,-0.025580,0.145948,-0.012375,0.133388
33,0.372044,-0.873581,0.457567,0.751521,-0.777926,0.283499,-0.080138,-0.215205,-0.079423,0.101097,...,-0.049227,0.081010,-0.210257,-0.278805,-0.026743,0.007668,0.025968,0.034216,0.042914,-0.023167
34,0.433891,-0.627425,-0.606048,0.904754,0.593904,0.305284,-0.140862,-0.186653,0.160893,-0.013007,...,-0.051907,-0.106493,0.239895,0.166938,0.047238,-0.310147,-0.209471,-0.119670,0.147348,0.052557
35,1.212513,0.665270,-0.472213,0.205006,1.024187,0.215872,-0.206776,-0.076387,0.047844,-0.033657,...,-0.102780,-0.127572,0.300158,0.214055,0.044965,-0.229177,-0.190871,-0.036581,-0.022648,-0.002271
36,-1.495336,0.004066,0.360178,0.520734,0.202833,-0.042762,-0.484838,-0.010106,-0.194670,0.106174,...,-0.098390,0.023151,-0.129914,-0.159997,0.082204,0.011278,0.034072,0.125893,-0.137474,-0.032429
37,-1.250442,-0.022628,-0.850777,-0.073628,-0.041263,-0.277924,-0.529919,-0.017287,0.012425,-0.114901,...,-0.133001,0.046546,-0.141843,0.058471,-0.021995,-0.096575,0.049028,0.034596,0.055216,-0.048288
38,-0.328025,0.908590,0.938545,-0.124931,-0.435817,0.093505,-0.105672,0.443215,0.427665,0.132279,...,0.228303,-0.145872,0.161690,0.166296,0.086146,-0.035649,-0.109606,0.015934,0.073131,-0.044182
39,1.300074,0.446056,-0.441568,0.216792,-0.740117,0.196799,-0.054000,0.045750,0.331520,0.177717,...,-0.112656,0.307946,-0.128491,-0.253228,0.282935,0.010197,-0.016213,0.026336,0.139991,0.085117

### 生成W

In [14]:
import numpy as np
import json
classfeatures = np.array(classfeatures)
n = len(classfeatures)
sparsityLevel = int(n/2)
W = np.zeros(shape=(n, n))

for i in range(n):
    sSim = 0
    for j in range(n):
        sim = np.dot(classfeatures[i], classfeatures[j])
        W[i][j] = sim
        sSim += sim
    W[i] /= sSim
SparseW = W

#小于阈值的置为0
if sparsityLevel > 0 and sparsityLevel < n:
    for i in range(n):
        similarity = sorted(W[i], reverse=False)
        threshold = similarity[sparsityLevel]
        for j in range(n):
            if W[i][j] <= threshold:
                SparseW[i][j] = 0
        SparseW[i] /= sum(SparseW[i])
# for i in range(len(SparseW)):
    
#     print(sum(SparseW[i]))

for i in range(n):
    # SparseW[i][i] = 0
    # if sum(SparseW[i]) != 0:
    #     SparseW[i][i] = np.linalg.norm(SparseW[i]) ** 2 / sum(SparseW[i])
    # else:
    SparseW[i][i] = 1
    SparseW[i] /= sum(SparseW[i])
print("SparseW --Opt", SparseW)

# for i in range(len(SparseW)):
    
#     print(sum(SparseW[i]))
#存储为json格式
# import json
filename = "./SparseW.json"
with open(filename, 'w') as f:
    json.dump(SparseW.T.tolist(), f)
print("save SparseW.json")
# W = np.load('./NYC/SparseW.npy')

SparseW --Opt [[0.54444415 0.         0.         ... 0.         0.03136945 0.01253992]
 [0.01566038 0.5        0.         ... 0.         0.01158294 0.04710812]
 [0.         0.00919118 0.55281636 ... 0.         0.         0.        ]
 ...
 [0.0239095  0.         0.0125164  ... 0.5        0.01186966 0.03030717]
 [0.         0.01375447 0.04082607 ... 0.01611961 0.5        0.        ]
 [0.00723051 0.         0.         ... 0.         0.         0.53845123]]
save SparseW.json