# 将User_FeatureVectors聚成40类

### 读取所有用户向量

In [12]:
import pandas as pd
import numpy as np
# Path of the file to read
User_filepath = "./TKY/User_Glovemean_FeatureVectors.csv"#可以选择
FeatureVectors = {}
Userfeatures_noid = []
User_id = []
data = pd.read_csv(User_filepath, header=0,sep=' ')
data_user = data.iloc[:,0]
print(data_user)
data_feature = data.iloc[:,1:]
data_feature
# with open(User_filepath, "r") as f:
#     # f.readline() # skip the header
#     for line in f:
#         line = line.split("\t")
#         vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
#         FeatureVectors[int(line[0])] = np.array(vec).astype(float)
#         Userfeatures_noid.append(np.array(vec).astype(float))
#         User_id.append(int(line[0]))
# Userfeatures_noid = pd.DataFrame(Userfeatures_noid)
# Userfeatures_noid

0        868
1        114
2       1458
3       1541
4       1635
        ...
1587     902
1588    1997
1589    1626
1590    1257
1591    1184
Name: uid, Length: 1592, dtype: int64

,u0,u1,u2,u3,u4,u5,u6,u7,u8,u9,...,u20,u21,u22,u23,u24,u25,u26,u27,u28,u29
0,0.769533,-0.584054,0.033698,0.615681,0.616085,-0.113057,-0.286729,-0.122116,0.108261,-0.483004,...,-0.011484,-0.192883,0.242007,-0.202697,0.155682,0.173926,0.106891,0.214119,0.101837,-0.226468
1,-0.406192,-0.277822,1.644915,-0.310860,-0.180669,-0.281364,-0.953587,0.167760,0.033061,-0.120212,...,-0.516856,0.010219,0.712776,-0.321756,-0.266093,0.284349,0.414463,-0.451735,0.114916,-0.271819
2,-1.182736,0.310900,0.544380,-0.876621,-0.101550,-1.087947,-0.943926,-0.251927,-0.334852,0.166630,...,0.222816,-0.246735,0.161517,-0.173870,-0.450140,0.086370,0.176904,0.080288,0.044055,-0.200206
3,-0.062119,-0.362071,0.062043,-0.134294,0.222651,0.123801,-0.277163,0.182900,0.157453,-0.154677,...,0.109930,0.012128,0.226406,0.049729,0.011248,-0.057104,0.065104,-0.126770,0.097899,0.051079
4,-0.008183,0.158957,0.758697,0.242165,-1.188651,-0.053958,-0.416525,-0.167453,-0.193359,0.063420,...,-0.712486,-0.190245,0.471916,0.026797,0.133422,0.364891,0.232172,-0.215924,-0.084001,-0.163277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1587,-0.462251,0.745678,2.081868,-0.397688,-0.135593,-0.928747,-1.525605,-0.000869,-0.631042,-0.164639,...,-0.600546,0.081528,0.943777,-0.228986,-0.442254,0.369199,0.328832,-1.093267,0.249341,-0.593085
1588,-0.462251,0.745678,2.081868,-0.397688,-0.135593,-0.928747,-1.525605,-0.000869,-0.631042,-0.164639,...,-0.600546,0.081528,0.943777,-0.228986,-0.442254,0.369199,0.328832,-1.093267,0.249341,-0.593085
1589,0.901381,-0.165725,0.276448,0.221292,-1.378187,-0.430944,-0.451907,-0.189746,-0.075593,-0.664455,...,-0.161894,1.053431,-0.344790,0.489834,-0.986503,-0.523239,-0.808056,0.508041,-0.257871,0.249288
1590,0.305584,0.578995,1.523103,-0.047897,-0.869017,-0.971269,-1.283481,0.526309,-0.154042,0.005040,...,-0.488286,-0.008049,0.863411,0.524327,-0.254041,0.380667,0.021030,-0.803806,-0.134098,-0.861228
1591,-0.462251,0.745678,2.081868,-0.397688,-0.135593,-0.928747,-1.525605,-0.000869,-0.631042,-0.164639,...,-0.600546,0.081528,0.943777,-0.228986,-0.442254,0.369199,0.328832,-1.093267,0.249341,-0.593085

### 生成聚类向量

In [5]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
# 假设 user_vectors 是用户向量的集合，每个向量形状为 (n_features,)
Userfeatures_noid = data_feature
n_clusters = 40# 指定聚类的数量
kmeans = KMeans(n_clusters=n_clusters)
kmeans.fit(Userfeatures_noid)
centers = kmeans.cluster_centers_
for i in range(len(centers)):
    print("Class {}: {}".format(i+1, centers[i]))


# 计算轮廓系数
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")

Class 1: [ 3.00394234  0.81438037 -0.72708562  0.39009536 -0.67583075  0.4444716
 -0.08515836  0.4965227   0.22745405 -0.13064827  0.13944716 -0.59697138
 -0.07320415  0.32509957 -0.15623376 -0.54240138  0.14353929  0.04022725
 -0.05339776 -0.23575316  0.10639359  0.14972095  0.06057895 -0.02209607
 -0.23731775  0.00308784 -0.13826887 -0.23280169 -0.0896591   0.27579373]
Class 2: [-0.56128469  0.09106583  0.23870411 -0.80254269  0.42660933 -0.53056176
 -0.88411789  0.22835386  0.28896402  0.38936651 -0.05444667 -0.07137078
 -0.59365665 -0.04863802 -0.00295512 -0.25602327 -0.19831605  0.90847961
  0.11993861 -0.05739729 -0.10379232  0.08920995  0.33608322  0.04856147
 -0.14283084  0.23932233  0.13051537 -0.21276302  0.00172837 -0.09281086]
Class 3: [ 1.00611642  0.04022787 -0.06798614 -0.08385871 -0.29383474  0.22076056
 -0.11857543  0.26451998  0.21137085 -0.03718325  0.00839816 -0.0962153
 -0.17795668  0.06673675 -0.12270405 -0.10058088  0.22274962  0.34603119
 -0.02555221 -0.14170925 -0.03626456  0.09928623  0.25058504  0.00504812
 -0.05316588  0.10035875  0.04903778 -0.16228227  0.02001433 -0.01042509]
Class 4: [-0.12963622  0.23941589  1.2542495  -0.24491939 -0.14213892 -0.55715757
 -0.96942114  0.0597645  -0.2414396  -0.11336343  0.5235298   0.40320583
 -0.34283641  0.32423532 -0.66587251  0.04127713  0.14924496  1.33240548
 -0.0752552   0.0329743  -0.33457111  0.05479374  0.61517263 -0.09775617
 -0.23679155  0.2668923   0.22330968 -0.61310496  0.12588115 -0.32085757]
Class 5: [-0.44301744  0.73780442  2.04382029 -0.39303651 -0.14436942 -0.93745307
 -1.5087128   0.01388355 -0.59844424 -0.16000171  0.96988397  0.65385641
 -0.50847793  0.48172334 -1.09734313  0.10407706  0.23625886  2.23172103
 -0.14398772  0.18698098 -0.58966974  0.06041931  0.92649575 -0.19995741
 -0.43189248  0.36510252  0.31285976 -1.0525078   0.23469513 -0.57507984]
Class 6: [-0.3997197   0.21044523  0.48017021 -0.23786128 -0.29633334 -0.40993342
 -0.60726    -0.07281648 -0.07932066 -0.07514458  0.26181815  0.2530012
 -0.18316543  0.21522399 -0.42262378  0.04177237  0.15295295  0.78544136
 -0.06065263 -0.08767421 -0.1395591   0.08173479  0.34396859 -0.04530371
 -0.10963462  0.17381569  0.1570586  -0.33082235  0.07851061 -0.21919395]
Class 7: [-0.48920666  0.95265384  1.09072698  0.42087861 -0.29078676 -0.17579917
 -0.4981703  -0.19497692 -0.17469705 -0.83301738 -0.43313813  0.35150705
 -0.71232793 -0.59267521 -0.12676748 -0.49909786  0.35036783  0.31860614
  0.12600548 -0.35578097  0.47924301 -0.25326622  0.3554294   0.06856845
 -0.24829716  0.77168877 -0.02039969 -0.0660211  -0.26979246 -0.2263792 ]
Class 8: [ 0.91892624  0.35520211  0.89216161  0.22129842 -1.36204165 -0.86958151
 -0.92032104  0.86292809  0.26026323  0.10375266  0.43547373 -0.07500122
 -0.56589839  1.37005687 -0.66008616  0.00676783  0.24343527  1.39826373
  0.24755221 -0.80962169 -0.31966596 -0.07414061  0.69643116  1.02403323
 -0.0926467   0.36478445 -0.21059311 -0.45567596 -0.41772664 -0.9485465 ]
Class 9: [-0.40845463 -0.16128447  0.3040518   0.75496165 -0.0358277   1.47066089
 -0.65430152 -0.28343058 -0.31324904  1.24327166  0.42610781  0.41689307
 -0.54811434  0.26870695 -0.20129088  0.25486902 -0.05557513 -0.32983134
  0.18324896  0.45185569  0.32121848  0.14969053  0.452376   -0.23637754
 -0.34404035  0.17223751  0.06720555  0.18560338  0.17913958 -0.09728334]
Class 10: [ 0.25747321 -0.58667717  0.94628504  0.75314945 -0.39401363  0.48294666
 -0.76740359 -0.684067    0.13907292  0.52530052 -0.28408172 -0.21888691
 -0.40671351  1.06502067 -0.3299555   0.31858174  0.09418924  0.44208676
 -0.52300981 -1.12234982  1.21940822 -0.04486365  1.31821316 -0.54951751
  0.82013317  0.76332979  0.3779762   0.23911887  0.0906008   1.00094621]
Class 11: [ 1.87915222  0.36228696 -0.60232892 -0.09140217 -1.10061823 -0.05205028
  0.01873341  0.18213695 -0.02351961 -0.05314335 -0.15948886  0.17867159
 -0.39698764  0.17281018  0.11992243  0.23414941  0.03993593  0.48743782
  0.03926879 -0.37664205  0.16349147  0.15260364 -0.05213511 -0.24335969
 -0.04998234  0.25121766  0.21519381  0.30974133  0.14628011 -0.23983209]
Class 12: [-3.78015624e-03 -1.63139549e+00  6.98584736e-01 -3.86413066e-01
  1.27090929e-01  1.78345440e-01 -8.47713580e-02  2.89773404e-01
  6.17260499e-01 -2.33174549e-02  8.18262752e-02 -1.86130846e-01
 -4.18219507e-02  3.56371214e-02 -2.80939989e-01 -1.16281541e-01
  6.91583166e-02 -1.81372241e-02 -1.92655139e-01 -2.38430724e-01
 -1.10101024e-01  1.13589244e-01  3.05724356e-01 -9.10504438e-02
 -6.68563163e-02 -8.13224806e-03  1.00960141e-01  1.31344632e-03
 -6.55380720e-02 -1.11773562e-01]
Class 13: [ 0.23055958  0.40173794  1.29328586 -0.06126659 -0.67599751 -0.77446628
 -1.09180434  0.4169893  -0.06258949 -0.05021697  0.60573588  0.22625828
 -0.47245847  0.83952527 -0.776248    0.03835107  0.22356211  1.56205682
  0.04396591 -0.31251956 -0.39096764  0.00459393  0.73906185  0.39373631
 -0.2165429   0.3472773   0.05682945 -0.63359394 -0.09840623 -0.65211397]
Class 14: [ 3.06186126  0.36306805 -1.83881474  1.58703983  2.65564287 -0.98437658
 -1.44522111 -0.7352186   0.22135263 -0.2998796   0.27793013  0.19565911
  0.34351623 -0.26535081 -0.00978552  0.18982788  0.09374844 -0.32342629
 -0.00744647 -0.19916383 -0.24785122 -0.01895289  0.12366006  0.0576089
  0.09537976  0.01559469  0.09809714  0.1096861  -0.11091926 -0.12030194]
Class 15: [-1.46189137 -0.46703527 -0.96389174 -1.80302196  1.27585526 -0.63113873
 -0.99255928  0.49951838  1.04714411  1.28349809 -0.69312952 -0.72772476
 -1.21541927 -0.41397751  0.86641295 -0.76948702 -1.05405276  0.93010916
  0.30418099 -0.06512894  0.05025683  0.12575833  0.24291341  0.17340233
 -0.06877114  0.12432851  0.0508878   0.06854337  0.02115466  0.15072176]
Class 16: [ 0.35362404  1.52934152  1.41392513 -0.8306944   0.07784554 -0.99052439
 -0.54906883  0.79091867 -0.04756039  0.31197781  0.95137077  0.33560356
 -0.05830571  0.18284734  0.40609691 -0.03109307  0.1155474   0.14308289
  0.4124355  -0.48965285  0.03521612  0.15760016 -0.16272241 -0.07420768
 -0.00323247  0.28959718  0.14413233  0.01018174  0.14067083 -0.16843819]
Class 17: [ 0.06175512 -0.54722872  1.08176994 -0.21626235 -0.0978016  -0.23131851
 -0.60225763  0.16951339  0.07790807 -0.12742676  0.37199156  0.23471367
 -0.21069197  0.31077481 -0.51784378 -0.06916943  0.13383627  0.84073532
 -0.06877184 -0.04980012 -0.25485619  0.04160228  0.48975475 -0.03343717
 -0.14367039  0.18734697  0.1345311  -0.4202927   0.04117428 -0.23159044]
Class 18: [ 0.28875257 -0.68073623  0.19146643 -0.09398279 -0.13571644 -0.08058981
  0.08245923  0.01157643  0.00115718 -0.07282477 -0.230904    0.1136841
 -0.16543373  0.05217197  0.03614103 -0.04932155  0.01255538  0.01618019
 -0.0249572  -0.11512102 -0.04417439  0.00470996  0.12172061  0.01324764
  0.0712422   0.06135436  0.05037568 -0.06613988  0.04510981 -0.08123759]
Class 19: [-0.33291219  2.15357913  2.76075651 -1.25260195  0.44860079 -1.35721798
 -0.92653315  0.97246606 -0.2604221   0.41161345  1.79587815  0.58206793
  0.10396705  0.35223623  0.03438031 -0.07769516  0.33395257  0.58922491
  0.34517481 -0.28054243 -0.34733033  0.09473633  0.15931571 -0.07773432
 -0.15150754  0.21967382  0.14010002 -0.521679    0.20612926 -0.11996397]
Class 20: [-0.25827888  0.56066565  1.55015086 -0.27170521 -0.15548423 -0.71707122
 -1.20444208  0.05929277 -0.38604474 -0.15658795  0.70308384  0.49740336
 -0.43805036  0.36132966 -0.85983909  0.05072346  0.20876105  1.72940649
 -0.0935968   0.0814879  -0.42829892  0.05636347  0.7516596  -0.13808098
 -0.34380083  0.33037264  0.25706749 -0.80801863  0.14798828 -0.46329415]
Class 21: [ 2.12585674e+00  3.41670802e-01 -8.74568067e-01  6.48004035e-01
  8.11428955e-01 -2.58816136e-01 -4.75216525e-01 -1.38035681e-01
  1.38931672e-01 -9.58974529e-02  5.71145374e-02  8.54892548e-02
 -6.19765776e-02 -1.95005367e-01  1.71944288e-02  5.21811694e-02
  2.13608136e-01  2.63802481e-02 -5.91334008e-02 -1.48425254e-01
  8.67422613e-03 -1.69052286e-02  1.44373495e-01 -3.68882924e-04
  5.94921276e-03  1.43904808e-01  1.31502756e-01  7.57753271e-02
 -6.87912306e-02 -9.95353876e-02]
Class 22: [-1.94959542e+00  3.84814841e-01 -1.16787058e+00 -1.27808670e-01
 -2.02849544e-01  1.48556170e-01  1.73346097e-01 -1.11539400e-01
  3.19146806e-01 -5.14796900e-01  6.62083506e-01  2.63977454e-02
  6.89291330e-02  2.43983632e-01  7.58772110e-02 -1.40984819e-01
  6.04588916e-04  1.57689365e-01 -3.85064710e-01 -2.42031988e-01
 -3.98490963e-02  9.34272664e-02  1.44863312e-01  1.08426827e-02
  7.51380329e-02  1.31264435e-01  4.45914964e-04  3.84293053e-02
  1.51015790e-01 -4.32345821e-02]
Class 23: [-1.78000568  0.50798325 -0.42216066 -0.38826772  0.73542507  0.69726823
 -0.35838162  2.00429952 -0.50028069 -0.94552797 -0.78172377  0.1925063
  0.30913134 -0.29986448 -0.45321675  0.14881245 -0.24860289 -0.28309627
 -0.22310089 -0.04415547 -0.13097372  0.11776854  0.1754352   0.03300241
 -0.14685819  0.3338808   0.09914766  0.13563978 -0.20342372  0.07928066]
Class 24: [ 0.14699299  0.96703859  1.11880903 -0.15264488 -0.13906687 -0.23338587
 -0.65258313  0.10677008  0.00987814 -0.28220534  0.15547864  0.26612215
 -0.37358498  0.26113046 -0.55611849 -0.06847211  0.21616997  0.99824856
  0.06872647 -0.15735779 -0.18647736 -0.00601622  0.52423954  0.09502158
 -0.18538718  0.35427041  0.12650535 -0.4224747  -0.04740264 -0.31143418]
Class 25: [ 1.66144588 -1.36087875 -0.15153859 -0.11833779 -0.25794739  0.01233366
  0.19588979  0.33647988  0.43463979 -0.3494898   0.04569475  0.68516828
 -0.02583902  0.13820716  0.01410455 -0.36734685 -0.11726706  0.13464276
  0.21723303  0.16013949 -0.01848197 -0.04530892  0.09801786  0.02017316
  0.16924     0.00451108 -0.1730522  -0.32493029  0.03184756  0.16659387]
Class 26: [ 2.41644821e+00  6.42758309e-01 -1.14863415e+00 -4.82667870e-01
 -9.06230041e-01  1.82182651e-01  5.90492956e-01  5.16850030e-01
  7.84777291e-02  3.82057443e-01  5.99999068e-02 -1.76714470e-02
 -3.20294315e-01 -7.55743222e-01 -1.29880814e-02  2.00096333e-01
  6.19204099e-01  5.47702244e-01 -2.52102258e-01 -2.22923733e-01
 -4.89956000e-02  6.52756450e-02  2.54877300e-01 -1.15265418e-01
 -7.45672416e-02  2.43061383e-01  4.84560976e-01  4.36774926e-02
 -7.28761253e-04 -1.83715538e-01]
Class 27: [ 1.19295196  0.04195137 -0.17801241  0.25931287 -1.31281509 -0.3243923
 -0.58437231 -0.172392   -0.05245008 -0.21752243 -0.25173274  0.25672946
 -0.56436531  1.07397679  0.1384638   0.56528519 -0.56398671  0.63260789
  0.33689281 -0.68018531  0.31837382  0.39661784 -0.37118746 -0.44228257
  0.05194239  0.27935505  0.03124383  0.51966728  0.39917487 -0.57106348]
Class 28: [-0.4026193   3.7307873   3.7880287  -2.219128    1.0685385  -1.9574175
 -0.42564085  2.1185503  -0.10900071  1.0996467   2.8701248   0.6261308
  0.87648815  0.09567191  1.3680744  -0.23752147  0.45698613 -1.1451323
  1.0015677  -0.8026506  -0.12202984  0.3172773  -0.72145057 -0.09105949
  0.15244351  0.10512513  0.07270241 -0.12739539  0.24677314  0.35902685]
Class 29: [-0.85873499  0.94748526  0.64239744  0.44229821 -1.19967906  0.37407474
 -1.06478289 -0.74949206 -0.09835806 -0.88368982 -0.24779021 -1.06127844
  0.26710825 -0.23276979  0.30078864  1.49369305 -0.37452588  0.02107396
  0.68057108  0.19340126 -0.82958392 -0.50959743  0.45849945 -0.65498664
  0.21170836  0.86705397  0.08308985  0.1330689   0.3551006   0.33837731]
Class 30: [ 0.71056969 -0.16551881  0.53784146 -0.06192864 -0.67688638 -0.41391664
 -0.51927693  0.49087701  0.33667483 -0.00427173  0.13082157  0.02338881
 -0.36481768  0.66381557 -0.38885809 -0.10794752  0.19935033  0.73917938
  0.1361927  -0.3939181  -0.18768635 -0.01683464  0.42790522  0.45587369
 -0.05900173  0.22007029 -0.05279119 -0.25584918 -0.17999596 -0.41925375]
Class 31: [-0.94513923  0.16538257 -0.20147491 -0.91421721 -0.35932535 -0.59694262
 -0.44619608 -0.70979067  0.58085893  0.09786686 -0.79532985  0.48936695
  0.42663268  0.5926387  -0.46904083 -0.265144    0.9450448   0.49350296
  0.38697944 -0.11411063 -0.17126247  0.17195287 -0.18992878 -0.25482312
 -0.1890921   0.06709743  0.13800036 -0.07364292 -0.2228993   0.01806901]
Class 32: [-0.78318724  0.88766149  1.34217389 -0.17812764 -0.49090507 -1.1941326
 -0.75408745 -0.9797622   0.06003251 -1.4570884  -0.15608481  0.08564038
 -1.32174586 -0.74123137 -1.10241193 -0.90419954  0.14848775  0.28152472
  0.6357024  -0.13031791 -0.39559958  0.05071679  0.17504646  0.56870358
 -0.57758989  1.43126738  0.62851477  0.3473764  -0.18111286  0.85700342]
Class 33: [ 0.76238316  0.41508279  0.64646283 -0.11697858 -0.43800033 -0.39108578
 -0.74089812  0.14134093 -0.17809587 -0.0259202   0.45573126  0.30776462
 -0.3951271   0.34910612 -0.51938923  0.08468943  0.16475464  1.20693102
 -0.05507125 -0.09722325 -0.19683681  0.09440677  0.52265375 -0.09816791
 -0.21924972  0.24654168  0.19306954 -0.42178014  0.11548427 -0.33573182]
Class 34: [ 0.16624019 -0.03713965  0.96121514  0.19079994 -0.50496533  0.73908324
 -0.13750536 -0.5357376  -0.23537031 -0.95711041 -1.41931     1.11158549
  0.2418553  -0.48524186  2.0116177  -0.01835565  0.94103806  0.8792937
 -0.08710205 -0.13626232 -0.34831457 -0.15787999 -0.29174845 -0.45552462
  0.45957319  0.20492992  0.10638412  0.56270444  0.83635518  0.42542944]
Class 35: [-0.65507298 -0.16642976 -0.3087425   0.5037187   1.28283316  0.2392552
  0.86048935  0.99239081 -1.2454938  -0.46832024 -0.82702528 -0.25552526
 -0.20552594  0.758125    0.10080041 -0.2019993   0.74927433  0.3367665
  0.79698085 -0.0200862   0.04242389  0.29994128  0.33490941 -0.00787916
  0.06615626 -0.28543202  0.36090274 -0.48384961  0.4881469   0.05953767]
Class 36: [-1.5929755   0.4477229  -0.23713315  0.33839183 -0.74602618  1.82073045
 -0.7502551  -0.3365947  -0.36800403 -0.17190829  0.57991812  0.50913724
  2.34131275 -1.3735828   0.63398537 -0.2833796   0.0803549   1.5698006
 -0.28715123 -0.8553483   0.5735824   0.22969698  0.21129884  0.42198284
 -0.35899562 -0.59017955 -0.61463773 -0.00910686 -0.20815997 -0.10206603]
Class 37: [-0.28726775  0.47330881  1.23734069  0.14791414 -0.13739108  0.49076416
 -0.54308542  0.75926693  0.78860412 -0.6011894  -0.37216136 -0.04178604
 -0.17945923  0.17398427 -0.42948845 -0.36537662  0.63054455 -0.19852137
  0.55236287 -0.68655826 -0.03046746  0.17368327  0.42419479  0.8710904
  0.33386995  0.58387541  0.3467073  -0.13718747 -0.43347739  0.15648103]
Class 38: [-0.27863788  0.57798469  1.09503945 -0.09000375 -0.40511745 -0.7264534
 -0.96106503 -0.57609088 -0.10273284 -0.6241474   0.14452851  0.09656715
 -0.5377128  -0.14770505 -0.71769143 -0.27177204  0.27428751  0.64424855
  0.16083029 -0.12524903 -0.22355818  0.2807581   0.25374605  0.16978777
 -0.14294716  0.49141987  0.3427875  -0.19119049 -0.09269625  0.27033832]
Class 39: [-0.08559814  0.41883931  0.1501372   0.14221429 -0.50462091  0.09471939
 -0.47395113 -0.13254347  0.02882008 -0.14215692 -0.17095158 -0.06884156
 -0.10887516  0.05417641  0.05227863  0.20359984  0.13738998  0.25079214
  0.14727084 -0.21750552 -0.02866682 -0.03641914  0.24055367 -0.15863545
  0.01503246  0.31542245  0.06512083 -0.017198    0.05439462 -0.01339793]
Class 40: [ 1.05389781e+00  3.25905334e-01  1.49588768e-01  4.78723327e-01
  6.45557793e-01 -5.78438858e-01 -1.06615977e+00 -2.08061797e-01
 -1.23963050e-01 -2.04736298e-01  3.65106111e-01  3.44121993e-01
 -1.36462243e-01  9.59142311e-02 -3.96220869e-01  7.58298057e-02
  8.99454082e-02  6.87068663e-01  5.52549731e-04 -5.53900748e-02
 -2.16526106e-01  4.61186222e-03  4.13270682e-01 -6.69230022e-02
 -1.37125647e-01  2.42351331e-01  1.05264625e-01 -3.21547381e-01
  1.61686225e-02 -2.73806680e-01]
轮廓系数：0.20434547869887437

### 生成用户聚类结果信息

In [6]:
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")
print("label",  kmeans.labels_)
print("num_label",  len(kmeans.labels_))
print(kmeans.labels_[1])

轮廓系数：0.20434547869887437
label [17  3  5 ... 26 12  4]
num_label 1592
3

### 同步存储聚类后的用户向量 和 映射关系

In [11]:
# 因为聚类了所以不用考虑原来用户id，类别顺序就是新的id
filename = "./TKY/{}clusters_FeatureVectors.dat".format(n_clusters)
with open(filename, 'w', newline='') as f:
    for i in range(centers.shape[0]):
        new_line = str(i) + '\t' + ';'.join(str(centers[i, :]).strip('[').strip(']').split()) + '\n'
        f.write(new_line)
print("done")

#label需要类别顺序与用户id对应，而不是与用户向量的index对应
label_dict = {}
for i in range(len(kmeans.labels_)):
    label_dict[str(data_user[i])] = int(kmeans.labels_[i])
import json
filename = "./TKY/{}clusters_labels.json".format(n_clusters)
with open(filename, 'w') as f:
    json.dump(label_dict, f)
print("done")

done
done

## 生成关系矩阵

### 读取聚类向量

In [13]:
classfeatures = []
filename = "./TKY/{}clusters_FeatureVectors.dat".format(n_clusters)
with open(filename, "r") as f:
    # f.readline()# 跳过第一行
    for line in f:
        line = line.split("\t")
        vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
        classfeatures.append(np.array(vec).astype(float))
classfeatures = pd.DataFrame(classfeatures)
classfeatures

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,3.003942,0.814380,-0.727086,0.390095,-0.675831,0.444472,-0.085158,0.496523,0.227454,-0.130648,...,0.106394,0.149721,0.060579,-0.022096,-0.237318,0.003088,-0.138269,-0.232802,-0.089659,0.275794
1,-0.561285,0.091066,0.238704,-0.802543,0.426609,-0.530562,-0.884118,0.228354,0.288964,0.389367,...,-0.103792,0.089210,0.336083,0.048561,-0.142831,0.239322,0.130515,-0.212763,0.001728,-0.092811
2,1.006116,0.040228,-0.067986,-0.083859,-0.293835,0.220761,-0.118575,0.264520,0.211371,-0.037183,...,-0.036265,0.099286,0.250585,0.005048,-0.053166,0.100359,0.049038,-0.162282,0.020014,-0.010425
3,-0.129636,0.239416,1.254250,-0.244919,-0.142139,-0.557158,-0.969421,0.059764,-0.241440,-0.113363,...,-0.334571,0.054794,0.615173,-0.097756,-0.236792,0.266892,0.223310,-0.613105,0.125881,-0.320858
4,-0.443017,0.737804,2.043820,-0.393037,-0.144369,-0.937453,-1.508713,0.013884,-0.598444,-0.160002,...,-0.589670,0.060419,0.926496,-0.199957,-0.431892,0.365103,0.312860,-1.052508,0.234695,-0.575080
5,-0.399720,0.210445,0.480170,-0.237861,-0.296333,-0.409933,-0.607260,-0.072816,-0.079321,-0.075145,...,-0.139559,0.081735,0.343969,-0.045304,-0.109635,0.173816,0.157059,-0.330822,0.078511,-0.219194
6,-0.489207,0.952654,1.090727,0.420879,-0.290787,-0.175799,-0.498170,-0.194977,-0.174697,-0.833017,...,0.479243,-0.253266,0.355429,0.068568,-0.248297,0.771689,-0.020400,-0.066021,-0.269792,-0.226379
7,0.918926,0.355202,0.892162,0.221298,-1.362042,-0.869582,-0.920321,0.862928,0.260263,0.103753,...,-0.319666,-0.074141,0.696431,1.024033,-0.092647,0.364784,-0.210593,-0.455676,-0.417727,-0.948546
8,-0.408455,-0.161284,0.304052,0.754962,-0.035828,1.470661,-0.654302,-0.283431,-0.313249,1.243272,...,0.321218,0.149691,0.452376,-0.236378,-0.344040,0.172238,0.067206,0.185603,0.179140,-0.097283
9,0.257473,-0.586677,0.946285,0.753149,-0.394014,0.482947,-0.767404,-0.684067,0.139073,0.525301,...,1.219408,-0.044864,1.318213,-0.549518,0.820133,0.763330,0.377976,0.239119,0.090601,1.000946
10,1.879152,0.362287,-0.602329,-0.091402,-1.100618,-0.052050,0.018733,0.182137,-0.023520,-0.053143,...,0.163491,0.152604,-0.052135,-0.243360,-0.049982,0.251218,0.215194,0.309741,0.146280,-0.239832
11,-0.003780,-1.631395,0.698585,-0.386413,0.127091,0.178345,-0.084771,0.289773,0.617260,-0.023317,...,-0.110101,0.113589,0.305724,-0.091050,-0.066856,-0.008132,0.100960,0.001313,-0.065538,-0.111774
12,0.230560,0.401738,1.293286,-0.061267,-0.675998,-0.774466,-1.091804,0.416989,-0.062589,-0.050217,...,-0.390968,0.004594,0.739062,0.393736,-0.216543,0.347277,0.056829,-0.633594,-0.098406,-0.652114
13,3.061861,0.363068,-1.838815,1.587040,2.655643,-0.984377,-1.445221,-0.735219,0.221353,-0.299880,...,-0.247851,-0.018953,0.123660,0.057609,0.095380,0.015595,0.098097,0.109686,-0.110919,-0.120302
14,-1.461891,-0.467035,-0.963892,-1.803022,1.275855,-0.631139,-0.992559,0.499518,1.047144,1.283498,...,0.050257,0.125758,0.242913,0.173402,-0.068771,0.124329,0.050888,0.068543,0.021155,0.150722
15,0.353624,1.529342,1.413925,-0.830694,0.077846,-0.990524,-0.549069,0.790919,-0.047560,0.311978,...,0.035216,0.157600,-0.162722,-0.074208,-0.003232,0.289597,0.144132,0.010182,0.140671,-0.168438
16,0.061755,-0.547229,1.081770,-0.216262,-0.097802,-0.231319,-0.602258,0.169513,0.077908,-0.127427,...,-0.254856,0.041602,0.489755,-0.033437,-0.143670,0.187347,0.134531,-0.420293,0.041174,-0.231590
17,0.288753,-0.680736,0.191466,-0.093983,-0.135716,-0.080590,0.082459,0.011576,0.001157,-0.072825,...,-0.044174,0.004710,0.121721,0.013248,0.071242,0.061354,0.050376,-0.066140,0.045110,-0.081238
18,-0.332912,2.153579,2.760757,-1.252602,0.448601,-1.357218,-0.926533,0.972466,-0.260422,0.411613,...,-0.347330,0.094736,0.159316,-0.077734,-0.151508,0.219674,0.140100,-0.521679,0.206129,-0.119964
19,-0.258279,0.560666,1.550151,-0.271705,-0.155484,-0.717071,-1.204442,0.059293,-0.386045,-0.156588,...,-0.428299,0.056363,0.751660,-0.138081,-0.343801,0.330373,0.257067,-0.808019,0.147988,-0.463294
20,2.125857,0.341671,-0.874568,0.648004,0.811429,-0.258816,-0.475217,-0.138036,0.138932,-0.095897,...,0.008674,-0.016905,0.144373,-0.000369,0.005949,0.143905,0.131503,0.075775,-0.068791,-0.099535
21,-1.949595,0.384815,-1.167871,-0.127809,-0.202850,0.148556,0.173346,-0.111539,0.319147,-0.514797,...,-0.039849,0.093427,0.144863,0.010843,0.075138,0.131264,0.000446,0.038429,0.151016,-0.043235
22,-1.780006,0.507983,-0.422161,-0.388268,0.735425,0.697268,-0.358382,2.004300,-0.500281,-0.945528,...,-0.130974,0.117769,0.175435,0.033002,-0.146858,0.333881,0.099148,0.135640,-0.203424,0.079281
23,0.146993,0.967039,1.118809,-0.152645,-0.139067,-0.233386,-0.652583,0.106770,0.009878,-0.282205,...,-0.186477,-0.006016,0.524240,0.095022,-0.185387,0.354270,0.126505,-0.422475,-0.047403,-0.311434
24,1.661446,-1.360879,-0.151539,-0.118338,-0.257947,0.012334,0.195890,0.336480,0.434640,-0.349490,...,-0.018482,-0.045309,0.098018,0.020173,0.169240,0.004511,-0.173052,-0.324930,0.031848,0.166594
25,2.416448,0.642758,-1.148634,-0.482668,-0.906230,0.182183,0.590493,0.516850,0.078478,0.382057,...,-0.048996,0.065276,0.254877,-0.115265,-0.074567,0.243061,0.484561,0.043677,-0.000729,-0.183716
26,1.192952,0.041951,-0.178012,0.259313,-1.312815,-0.324392,-0.584372,-0.172392,-0.052450,-0.217522,...,0.318374,0.396618,-0.371187,-0.442283,0.051942,0.279355,0.031244,0.519667,0.399175,-0.571063
27,-0.402619,3.730787,3.788029,-2.219128,1.068539,-1.957418,-0.425641,2.118550,-0.109001,1.099647,...,-0.122030,0.317277,-0.721451,-0.091059,0.152444,0.105125,0.072702,-0.127395,0.246773,0.359027
28,-0.858735,0.947485,0.642397,0.442298,-1.199679,0.374075,-1.064783,-0.749492,-0.098358,-0.883690,...,-0.829584,-0.509597,0.458499,-0.654987,0.211708,0.867054,0.083090,0.133069,0.355101,0.338377
29,0.710570,-0.165519,0.537841,-0.061929,-0.676886,-0.413917,-0.519277,0.490877,0.336675,-0.004272,...,-0.187686,-0.016835,0.427905,0.455874,-0.059002,0.220070,-0.052791,-0.255849,-0.179996,-0.419254
30,-0.945139,0.165383,-0.201475,-0.914217,-0.359325,-0.596943,-0.446196,-0.709791,0.580859,0.097867,...,-0.171262,0.171953,-0.189929,-0.254823,-0.189092,0.067097,0.138000,-0.073643,-0.222899,0.018069
31,-0.783187,0.887661,1.342174,-0.178128,-0.490905,-1.194133,-0.754087,-0.979762,0.060033,-1.457088,...,-0.395600,0.050717,0.175046,0.568704,-0.577590,1.431267,0.628515,0.347376,-0.181113,0.857003
32,0.762383,0.415083,0.646463,-0.116979,-0.438000,-0.391086,-0.740898,0.141341,-0.178096,-0.025920,...,-0.196837,0.094407,0.522654,-0.098168,-0.219250,0.246542,0.193070,-0.421780,0.115484,-0.335732
33,0.166240,-0.037140,0.961215,0.190800,-0.504965,0.739083,-0.137505,-0.535738,-0.235370,-0.957110,...,-0.348315,-0.157880,-0.291748,-0.455525,0.459573,0.204930,0.106384,0.562704,0.836355,0.425429
34,-0.655073,-0.166430,-0.308742,0.503719,1.282833,0.239255,0.860489,0.992391,-1.245494,-0.468320,...,0.042424,0.299941,0.334909,-0.007879,0.066156,-0.285432,0.360903,-0.483850,0.488147,0.059538
35,-1.592976,0.447723,-0.237133,0.338392,-0.746026,1.820730,-0.750255,-0.336595,-0.368004,-0.171908,...,0.573582,0.229697,0.211299,0.421983,-0.358996,-0.590180,-0.614638,-0.009107,-0.208160,-0.102066
36,-0.287268,0.473309,1.237341,0.147914,-0.137391,0.490764,-0.543085,0.759267,0.788604,-0.601189,...,-0.030467,0.173683,0.424195,0.871090,0.333870,0.583875,0.346707,-0.137187,-0.433477,0.156481
37,-0.278638,0.577985,1.095039,-0.090004,-0.405117,-0.726453,-0.961065,-0.576091,-0.102733,-0.624147,...,-0.223558,0.280758,0.253746,0.169788,-0.142947,0.491420,0.342788,-0.191190,-0.092696,0.270338
38,-0.085598,0.418839,0.150137,0.142214,-0.504621,0.094719,-0.473951,-0.132543,0.028820,-0.142157,...,-0.028667,-0.036419,0.240554,-0.158635,0.015032,0.315422,0.065121,-0.017198,0.054395,-0.013398
39,1.053898,0.325905,0.149589,0.478723,0.645558,-0.578439,-1.066160,-0.208062,-0.123963,-0.204736,...,-0.216526,0.004612,0.413271,-0.066923,-0.137126,0.242351,0.105265,-0.321547,0.016169,-0.273807

### 生成W

In [14]:
import numpy as np
classfeatures = np.array(classfeatures)
n = len(classfeatures)
sparsityLevel = int(n/3)
W = np.zeros(shape=(n, n))

for i in range(n):
    sSim = 0
    for j in range(n):
        sim = np.dot(classfeatures[i], classfeatures[j])
        W[i][j] = sim
        sSim += sim
    W[i] /= sSim
SparseW = W

#小于阈值的置为0
if sparsityLevel > 0 and sparsityLevel < n:
    for i in range(n):
        similarity = sorted(W[i], reverse=True)
        threshold = similarity[sparsityLevel]
        for j in range(n):
            if W[i][j] <= threshold:
                SparseW[i][j] = 0
        SparseW[i] /= sum(SparseW[i])

for i in range(n):
    SparseW[i][i] = 0
    if sum(SparseW[i]) != 0:
        SparseW[i][i] = np.linalg.norm(SparseW[i]) ** 2 / sum(SparseW[i])
    else:
        SparseW[i][i] = 1
    SparseW[i] /= sum(SparseW[i])
print("SparseW --Opt", SparseW)

#存储为json格式
import json
filename = "./TKY/SparseW.json"
with open(filename, 'w') as f:
    json.dump(SparseW.T.tolist(), f)
print("save SparseW.json")
# W = np.load('./NYC/SparseW.npy')

SparseW --Opt [[0.09506242 0.         0.06103886 ... 0.         0.         0.04383814]
 [0.         0.08538909 0.         ... 0.04930578 0.         0.        ]
 [0.13388194 0.         0.08501163 ... 0.         0.         0.04384977]
 ...
 [0.         0.         0.         ... 0.08360825 0.         0.        ]
 [0.         0.         0.         ... 0.06214998 0.07490589 0.        ]
 [0.05043199 0.         0.         ... 0.04794453 0.         0.08457262]]
save SparseW.json