# 将User_FeatureVectors聚成40类

### 读取所有用户向量

In [29]:
import pandas as pd
import numpy as np
import json
# Path of the file to read
User_filepath = "../.././embedding/user_embedding_mean_item_embedding_kuai_bert_pca.json"#可以选择
FeatureVectors = {}
Userfeatures_noid = []
User_id = []

data  = json.load(open(User_filepath))
data_feature = pd.DataFrame.from_dict(data, orient='index')# key做行
# data_feature

data_user = data_feature.index.map(int)
# data = pd.read_csv(User_filepath, header=0,sep=' ')
# data_user = data.iloc[:,0]
print(data_user)
# data_feature = data.iloc[:,1:]
data_feature

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            746, 747, 748, 749, 750, 751, 752, 753, 754, 755],
           dtype='int64', length=756)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.055778,-0.004260,-0.543154,0.011912,0.550761,0.665190,-0.198090,-0.525569,-0.218940,0.530473,...,0.203203,0.178421,0.349624,0.152232,0.405377,0.175397,-0.462310,0.256250,-0.085351,-0.139623
1,-0.130531,0.298797,-1.202305,0.143772,0.162620,1.794285,-0.492618,0.089423,0.680131,-0.194859,...,0.588957,-0.681649,-0.206050,0.272554,-0.309101,0.158834,0.552252,0.623566,-0.066721,-0.175987
2,0.095703,0.343003,-1.358350,-0.612148,-0.491443,0.779505,0.546732,-0.363866,0.509214,0.769084,...,-0.374190,-0.011673,0.606274,0.101038,-0.347400,0.057754,0.267272,0.143260,-0.117476,0.246479
3,-0.121898,-0.467775,-0.520354,0.408927,0.038953,1.256314,-0.178155,-0.187658,-0.052879,0.053930,...,-0.120471,-0.596459,0.276139,-0.002929,0.179866,-0.457990,-0.186962,-0.298792,0.022062,-0.162113
4,-1.693005,-2.162507,0.303364,0.952798,0.849447,1.080894,-0.072290,-0.624038,-0.325451,0.846594,...,0.922316,0.083252,0.487495,0.486847,0.287418,0.268967,0.144333,-0.406940,0.134905,0.116450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,0.144804,-0.940896,-0.023352,-0.313586,-0.240376,-0.206074,-0.164099,0.030046,-0.975229,1.636943,...,-0.415202,-0.247425,0.190301,-0.003990,0.350972,-0.360472,-0.320369,0.767319,0.318488,-0.064361
752,-1.482752,1.576602,0.022620,-0.290203,-0.755853,0.414710,0.185143,-0.216621,0.421432,-0.073595,...,-0.353763,0.026744,0.433820,0.489268,-0.062839,-0.578113,0.121655,-0.202832,-0.239410,0.205304
753,-0.571152,-1.670242,-0.292592,-0.537910,-0.208133,0.353444,0.346924,-0.801536,-0.241938,0.298466,...,-0.188008,0.421338,0.771740,0.039427,0.332831,-0.269444,-0.029664,0.777093,-0.176209,0.307791
754,1.105206,0.255727,-0.694170,0.872498,-0.257677,0.472825,0.009907,0.034836,0.487274,0.213721,...,-0.139388,0.340989,0.549747,0.192929,0.178698,-0.092919,-0.011986,0.182345,-0.576782,0.011101
755,0.525181,0.213847,0.603917,0.113836,-0.686404,0.971693,-0.532336,-0.422768,0.345195,-0.183100,...,-0.208771,-0.627409,0.597080,0.219529,0.148385,-0.070853,-0.240837,-0.018520,0.399412,0.433456

In [12]:
# import pandas as pd
# import numpy as np
# # Path of the file to read
# User_filepath = "./NYC/User_Glovemean_FeatureVectors.csv"#可以选择
# FeatureVectors = {}
# Userfeatures_noid = []
# User_id = []
# data = pd.read_csv(User_filepath, header=0,sep=' ')
# data_user = data.iloc[:,0]
# print(data_user)
# data_feature = data.iloc[:,1:]
# data_feature

0        868
1        114
2       1458
3       1541
4       1635
        ...
1587     902
1588    1997
1589    1626
1590    1257
1591    1184
Name: uid, Length: 1592, dtype: int64

,u0,u1,u2,u3,u4,u5,u6,u7,u8,u9,...,u20,u21,u22,u23,u24,u25,u26,u27,u28,u29
0,0.769533,-0.584054,0.033698,0.615681,0.616085,-0.113057,-0.286729,-0.122116,0.108261,-0.483004,...,-0.011484,-0.192883,0.242007,-0.202697,0.155682,0.173926,0.106891,0.214119,0.101837,-0.226468
1,-0.406192,-0.277822,1.644915,-0.310860,-0.180669,-0.281364,-0.953587,0.167760,0.033061,-0.120212,...,-0.516856,0.010219,0.712776,-0.321756,-0.266093,0.284349,0.414463,-0.451735,0.114916,-0.271819
2,-1.182736,0.310900,0.544380,-0.876621,-0.101550,-1.087947,-0.943926,-0.251927,-0.334852,0.166630,...,0.222816,-0.246735,0.161517,-0.173870,-0.450140,0.086370,0.176904,0.080288,0.044055,-0.200206
3,-0.062119,-0.362071,0.062043,-0.134294,0.222651,0.123801,-0.277163,0.182900,0.157453,-0.154677,...,0.109930,0.012128,0.226406,0.049729,0.011248,-0.057104,0.065104,-0.126770,0.097899,0.051079
4,-0.008183,0.158957,0.758697,0.242165,-1.188651,-0.053958,-0.416525,-0.167453,-0.193359,0.063420,...,-0.712486,-0.190245,0.471916,0.026797,0.133422,0.364891,0.232172,-0.215924,-0.084001,-0.163277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1587,-0.462251,0.745678,2.081868,-0.397688,-0.135593,-0.928747,-1.525605,-0.000869,-0.631042,-0.164639,...,-0.600546,0.081528,0.943777,-0.228986,-0.442254,0.369199,0.328832,-1.093267,0.249341,-0.593085
1588,-0.462251,0.745678,2.081868,-0.397688,-0.135593,-0.928747,-1.525605,-0.000869,-0.631042,-0.164639,...,-0.600546,0.081528,0.943777,-0.228986,-0.442254,0.369199,0.328832,-1.093267,0.249341,-0.593085
1589,0.901381,-0.165725,0.276448,0.221292,-1.378187,-0.430944,-0.451907,-0.189746,-0.075593,-0.664455,...,-0.161894,1.053431,-0.344790,0.489834,-0.986503,-0.523239,-0.808056,0.508041,-0.257871,0.249288
1590,0.305584,0.578995,1.523103,-0.047897,-0.869017,-0.971269,-1.283481,0.526309,-0.154042,0.005040,...,-0.488286,-0.008049,0.863411,0.524327,-0.254041,0.380667,0.021030,-0.803806,-0.134098,-0.861228
1591,-0.462251,0.745678,2.081868,-0.397688,-0.135593,-0.928747,-1.525605,-0.000869,-0.631042,-0.164639,...,-0.600546,0.081528,0.943777,-0.228986,-0.442254,0.369199,0.328832,-1.093267,0.249341,-0.593085

### 生成聚类向量

In [30]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
# 假设 user_vectors 是用户向量的集合，每个向量形状为 (n_features,)
Userfeatures_noid = data_feature
n_clusters = 40# 指定聚类的数量
kmeans = KMeans(n_clusters=n_clusters)
kmeans.fit(Userfeatures_noid)
centers = kmeans.cluster_centers_
for i in range(len(centers)):
    print("Class {}: {}".format(i+1, centers[i]))


# 计算轮廓系数
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")

Class 1: [ 1.23451406 -1.13447865 -2.13924087  0.08165954  0.08818188  1.59603684
 -0.53410109  0.2646318  -0.36815839  0.4082755  -1.72942088 -1.24627099
  0.25727237 -1.01016759  0.15647886  0.63157284  0.28693244  0.72481967
  1.04006449  0.20289594  0.63949792 -0.62396263 -0.00505955 -0.29817705
  0.17402124]
Class 2: [ 0.61990957  0.62866244 -0.47890896  0.39706816 -0.17441006  0.61046622
 -0.14817127 -0.21709132  0.00287358  0.13030951  0.1483796   0.80922804
  0.03096663 -0.17698023  0.27169899 -0.07087537 -0.06739901  0.73885272
  0.2868925   0.16884547 -0.22331718 -0.09467316  0.21002829 -0.19418303
  0.03765525]
Class 3: [-0.93304603 -2.66536475 -0.63504312  0.50607746  0.47321781  1.13850689
  0.38484944 -0.27562184 -0.30890009  0.43167622 -0.78446508 -0.18429469
 -0.05981587 -0.48500964 -0.15695437  0.45701633  0.04876571  0.43778817
  0.15713261  0.15240209  0.16680155 -0.07716888 -0.38455947 -0.1375576
 -0.07694131]
Class 4: [-0.21323294  0.97637875 -0.55520708 -1.17211076 -1.07262637  0.99769376
 -0.43102676 -0.18159018  0.56896294  0.53868514  0.12203988  0.89405347
 -0.3694632  -0.22524865  0.2788435  -0.18776504  0.3019844   0.05530702
  0.19613303 -0.11198127 -0.3227239   0.47109317 -0.2923888  -0.24436516
  0.02039206]
Class 5: [-1.09389009 -0.43412273 -0.4786264  -0.2494743  -0.61994371  0.9525555
 -0.16011015 -0.16766035  0.04736255  0.18393209 -0.17217143  0.44245363
 -0.37600651 -0.37230055  0.32806958  0.04986676 -0.04488545  0.44995784
  0.18052181  0.11671774 -0.07075152 -0.01665694 -0.00309478 -0.18288983
  0.11600672]
Class 6: [-1.89084715 -0.6786536  -0.35695341  0.16886009  0.26166385  0.67657319
 -0.38825658 -0.82678886 -0.38642466  0.39047437 -0.5321156  -0.17965381
 -0.18197164 -0.17950301  0.03814454  0.18459641  0.15902897  0.23725494
  0.17242814  0.1666075   0.19555567 -0.0193501  -0.11927831 -0.0113951
 -0.09141618]
Class 7: [-0.57888659  0.10390646 -0.61641952 -0.07709455 -0.17227085  0.61450316
  0.15192426 -0.21286517  0.06292976  0.22615237  0.05594278  0.45892963
  0.0568683  -0.0941711   0.22606166 -0.0451498  -0.08925837  0.41160417
  0.11395863  0.10126274 -0.08540967  0.06980494  0.07476028 -0.13181162
  0.0194584 ]
Class 8: [-0.86938641 -0.96669085 -0.81891321 -0.01885084 -0.10750634  0.77761978
  0.25563373 -0.14218836  0.12093585  0.15472712 -0.19635046  0.17557174
  0.10141699 -0.1259783   0.20677437 -0.02446993 -0.19723316  0.36510831
  0.04160656  0.01830161 -0.09089396  0.15258337 -0.00108957 -0.15608332
 -0.02340282]
Class 9: [ 1.72713005 -1.46732716 -0.11411721  0.13366812  0.0019945   0.86223108
 -0.31399655 -0.25273656 -0.50450397  0.33619493  0.02539769  0.8201721
 -0.13877807  0.06345509  0.74127288 -0.179039   -0.55821215  0.31005221
  0.18262885  0.63831775 -0.74867728 -0.55501126 -0.15771053  0.4847932
 -0.36120929]
Class 10: [ 1.94569552  0.49537701  1.40636412  1.59201232 -0.58313572  1.42176448
 -0.38189613  0.35508432  0.75126291  0.39865482  1.01792954  1.27060621
  0.55251224 -0.41145852 -0.87308889  0.51160387 -0.41200569  0.70531389
  0.15403151  0.53869904 -0.75471144 -0.27241146  0.10213688  0.27832243
 -0.10325824]
Class 11: [-0.53609262  4.28955775  1.21701836  1.21262504 -0.51589848  0.4701073
  0.82370293 -0.05811307  0.6501685   0.44530641  1.09524194  0.48612811
  0.16869617  0.45674404 -0.36554457 -0.16846482  0.33319997  0.8756507
  0.29300871  0.69679468  0.1556446   0.06332529  0.94852248  0.54927311
  0.31765861]
Class 12: [-1.61617761  2.00250445 -0.6922741   0.30355889 -0.1630139   0.68276119
  0.21658361 -0.2993707  -0.03903541 -0.01822461  0.14166582 -0.01535434
 -0.39632787  0.31649228 -0.16762457  0.03831351 -0.20390567  0.13788212
  0.19429782  0.04318032 -0.22261921  0.20188508  0.22142549 -0.02546279
 -0.0052091 ]
Class 13: [-0.49146568 -1.15870032 -0.00717798  0.30183634 -0.06546541  0.55350192
  0.0597468  -0.33129535 -0.16049876  0.49264657 -0.2291297   0.2505274
 -0.12780074 -0.05260794  0.13260646  0.18801857  0.03578154  0.40782723
  0.23113332  0.16193691 -0.27530759 -0.04132214 -0.06229756 -0.05138831
 -0.03475473]
Class 14: [ 1.21778032 -0.48812164 -1.23289292 -0.35019478 -0.32229756  0.54821643
  0.66785031  0.77668295 -0.31790068 -0.23100651 -0.28059906  0.74812695
 -0.51957357 -0.56553484  0.02301564  0.27928848 -0.41878185  0.31653271
  0.50348356 -0.41204725 -0.13651984 -0.06003403 -0.14175353  0.05814505
 -0.01954042]
Class 15: [-0.71333475  1.27893841  0.56756928  0.4767258  -0.97072035  1.36277003
 -0.59878793 -0.08126197  0.52883321  0.20368522  0.52193654  0.69571369
  0.2128332  -0.34719597 -0.65468647  0.28564532 -0.10579274  0.62748434
  0.27923586  0.22102556 -0.19243671  0.22384561  0.26201016  0.00460641
  0.18535028]
Class 16: [ 2.46525031 -1.10292006  0.24614127  2.03242898  0.38956296  1.56387578
 -0.59015623 -0.12885211 -0.15434021  0.1789033  -0.4213615   0.40036719
 -0.0660893  -0.58705902 -0.14922247  0.24949847 -0.09029226  0.44388034
  0.05330868  0.79458925 -0.28621933 -1.04727257 -0.25871397  0.28161763
 -0.6447733 ]
Class 17: [ 0.62178026 -0.98053791  0.24133001 -0.15047235  0.0704207   0.58096828
 -0.22013093 -0.46379299 -0.74659687  1.07756373 -0.42832461 -0.00558617
  0.10630822 -0.37018383  0.38248465 -0.09945184 -0.25808416 -0.0355259
  0.1589684   0.44291321 -0.40025316 -0.28640326  0.16019762  0.07531267
 -0.04951658]
Class 18: [-0.43438542  0.17577169 -0.95269176  0.42411771 -0.0868763   1.00600981
 -0.4809165  -0.15059448 -0.11767152 -0.19385756 -0.40304332  0.19494417
  0.10788006 -0.38994734  0.24764634 -0.05607822 -0.22723577  0.42380162
  0.28793937  0.09410142  0.04153237 -0.02512016  0.1821232  -0.20147614
 -0.00297668]
Class 19: [-3.63730280e+00  8.62338642e+00 -1.37582884e-01  1.08949512e+00
  1.61349162e-01  5.69083191e-01  1.25647851e+00 -3.78296452e-01
  1.26847559e-01  5.15919677e-01  3.66012235e-01 -1.31368122e+00
 -4.03018929e-01  1.17371448e+00 -1.11078324e+00 -1.14606018e+00
  8.18298996e-02 -6.30847006e-01  6.21323398e-01 -6.01972229e-03
  2.85823295e-01 -4.92378506e-01  1.64741310e-01  7.60239705e-01
 -6.01189783e-02]
Class 20: [-1.81034239  1.07240339 -0.76617131 -0.6589975  -0.8084523   0.40310004
  0.05655223 -0.33290867  0.0507904  -0.10565676  0.04543874  0.52656413
 -0.04078826 -0.10597422  0.32791466 -0.18544755  0.02971281  0.37607944
  0.19778121  0.06809578 -0.00722147  0.12558383 -0.07810442 -0.13616333
 -0.00211817]
Class 21: [ 0.45044381 -0.44798239  0.54375813  0.83564152 -0.33230268  0.88999657
 -0.22408851 -0.07852756  0.20788497  0.42146517  0.11608369  0.70807716
  0.24868704 -0.3132135  -0.31249474  0.25603171 -0.1517431   0.50381188
  0.10346305  0.41561428 -0.3775667  -0.29579816  0.07193889  0.05918896
 -0.1041877 ]
Class 22: [-1.68677322 -1.62440447 -0.94530974  0.02731726 -0.24578507  0.73255767
  0.1772405   0.02510754  0.05935094  0.41765043 -0.37610694  0.02625176
  0.04293021 -0.25303739  0.4005212   0.0484969  -0.27814507  0.17749781
  0.06863322  0.02896842 -0.14868023  0.0049989   0.05055071  0.06712956
  0.06108268]
Class 23: [ 3.03147983 -0.41202762  0.41428804 -0.00928511  0.05440056  0.99566133
 -0.93810457 -0.27030441 -1.08920445  1.50414794  0.01898279  0.21561558
  0.45317426 -0.68415546  0.68744173 -0.95592487 -0.79757373 -0.41089365
  0.02710822  0.83774644 -1.11149063 -0.79217682  0.45269385  0.44389798
 -0.39700913]
Class 24: [ 0.42605423 -1.88095182 -0.43786157  0.60255132  0.14728565  1.03664539
  0.1735683   0.29816696  0.25568573  0.57897392 -0.37924367  0.0122312
  0.58751499 -0.58796685 -0.19309537 -0.01142857 -0.56968967  0.33507204
 -0.07417352  0.1243679  -0.1938398   0.09814666  0.04878462  0.06750757
 -0.17692363]
Class 25: [-0.32283001 -0.48581155 -0.72245802  0.87913978 -0.18620298  0.58518265
 -0.36206293  0.0038548  -0.07505077  0.2537107  -0.15922864  0.83564173
 -0.27757654 -0.15197904  0.12188668 -0.01356159 -0.1899419   0.47544404
  0.0732666   0.16498115 -0.35296035 -0.24479425  0.01344726  0.23600722
 -0.0309637 ]
Class 26: [ 0.51099613 -1.00964094 -0.92261504 -0.16252338  0.25567396  0.85922162
  0.7420572   0.09453615  0.07866816  0.27770222 -0.02655356  0.76990026
  0.48063149 -0.17483604  0.1687165  -0.20186446 -0.50081779  0.35254999
 -0.13079503  0.05348261 -0.08022306  0.16403553  0.00124313 -0.01729922
 -0.21430698]
Class 27: [-0.3760388  -1.13642724 -1.12277878  0.32184057 -0.01912368  0.43136628
 -0.01326618 -0.25781556 -0.28041677  0.50092951  0.01428675  0.56231112
 -0.21967383 -0.01321346  0.60456813 -0.20546826  0.06431425  0.7953683
  0.1846837   0.03610272 -0.29937965 -0.10309268  0.58952135 -0.27341891
  0.34873902]
Class 28: [ 0.7096781  -0.75480145 -1.28263073  0.33386768  0.95327426  0.82839627
  0.5118626  -0.60959515  0.46748383  1.24198022  0.40705065  0.21046794
  0.00801599  0.56035139  1.23859126  0.37779147 -0.2773506   1.96341453
  0.49439999  0.08335302 -0.24470188  0.84399588  0.62834665 -1.26836705
  0.6619848 ]
Class 29: [-0.26757934  0.58564443 -0.34886956 -0.6530447  -0.74534752  0.50033942
  0.4896108  -0.23341491  0.54149102 -0.24387578 -0.23133944  0.16261121
 -0.11243111 -0.07420697  0.00479619  0.13671202  0.21763526  0.74675703
 -0.26620435  0.42101957  0.14781391 -0.21861957 -0.05319555 -0.79853045
 -0.23035306]
Class 30: [ 1.70056636  0.29827065 -0.1662086   0.71962378 -0.18550103  1.06124776
 -0.34387187  0.03585557 -0.08022801  0.34930965  0.30185911  1.19567713
 -0.00276178 -0.29883309  0.38575933 -0.07114262 -0.49995409  0.56146578
 -0.15318896  0.53939486 -0.70030589 -0.65457745  0.10345982  0.46422848
 -0.40308804]
Class 31: [-1.31696503 -0.6026509   0.82804165  0.84703628 -0.02333136  1.1258117
 -0.13290856 -0.21855866  0.32063317  0.58650121  0.04638109  0.06518725
  0.48016292 -0.35426255 -1.09901797  0.91480131  0.24858792  0.90049833
  0.54131794  0.38509802  0.09693672  0.0958069  -0.05840537 -0.08371955
  0.25553051]
Class 32: [-0.29358711  0.02037593 -0.08583692  2.45521026 -0.34271736 -0.52027451
  0.67657942 -0.08867713  0.69690845  0.45256064 -0.11553055 -0.72454655
 -0.2561259   0.24031922  0.43281457  0.21382248  0.1644317  -0.33263004
  0.24027772 -0.04285781 -0.05349453  0.02685727  0.05920381  0.18416781
 -0.01057244]
Class 33: [ 2.26159934e+00  1.06358121e+00  3.85823203e-01 -1.12626753e+00
 -9.71933428e-01  9.73989346e-01  9.43806340e-01  1.87624994e-01
  4.57648665e-01 -1.73956814e-01  4.39350327e-02  6.20882128e-01
  1.57398988e-01 -4.40369376e-01 -6.57748737e-01  4.25753831e-01
 -3.57751410e-01  9.40795205e-01 -6.65178526e-03  1.86758126e-03
 -7.40918455e-02 -1.99853726e-01 -5.62995626e-01 -4.50878511e-01
 -1.05158989e-01]
Class 34: [-0.95743126 -1.23270826 -0.83775542 -0.12851444  0.10350699  1.12210438
  0.68328512  0.33522932  0.5287466   0.39328274 -0.53827813  0.16293601
  0.8602955  -0.27948038 -0.17232798  0.18442416 -0.61190012  0.35509078
 -0.3061914  -0.11780217  0.33653009  0.68818624 -0.15389082 -0.11718952
 -0.14179153]
Class 35: [-1.81090962  0.70804736 -0.27983091  0.66087425  0.06181513  0.96968761
 -0.56791987 -0.2472782   0.07915406 -0.0700963  -0.18372376  0.39895423
  0.04035822 -0.11804777  0.43087587 -0.07548231 -0.58995265  0.39415821
  0.15947342  0.02161861 -0.225761    0.14913145  0.00435905  0.05668412
  0.16757844]
Class 36: [ 0.15840644 -0.42968134 -0.43087779 -0.12746423 -0.20093785  0.68932816
  0.09163    -0.16100372  0.06012609  0.44377833 -0.11662749  0.35574613
  0.04629104 -0.15133077  0.25397322 -0.10436368 -0.09263685  0.38323144
  0.10839278  0.16688686 -0.22437419 -0.04015929  0.05952897 -0.16535985
 -0.01067816]
Class 37: [ 0.98428517 -0.85870839 -1.26275767  0.06535957  0.30979875  0.63615598
  0.34029067 -0.32875577  0.00495437 -0.14975197 -0.46547855  0.14036711
  0.04733189 -0.07591569  0.16454756 -0.00458055  0.17325614  1.01813666
  0.2217279   0.08578021  0.02043579 -0.10855968  0.36714363 -0.88941859
  0.20531278]
Class 38: [ 1.67755037 -0.16257222 -0.66597022 -0.24652082 -0.13372514  0.74720694
  0.38683197 -0.10760878  0.17364271 -0.00702265 -0.15875786  0.43333187
  0.02994669 -0.16491332  0.33961098 -0.16610414 -0.22309025  0.62310485
 -0.23575352  0.33208656 -0.3052788  -0.29582593 -0.02242013 -0.44468684
 -0.31793753]
Class 39: [-2.19002039 -0.04155251 -0.48916435  0.33377434 -0.17249692  0.57650767
  0.25062419 -0.30398888  0.20282691  0.24237614 -0.3217737   0.22205166
  0.17750541 -0.10901672  0.09604637  0.20386431 -0.0425186   0.28021845
 -0.10085875  0.1723301   0.04213816  0.11486077 -0.05571898  0.04319586
 -0.08882753]
Class 40: [-1.28937112  1.33071081  0.06762451 -0.68195681 -0.77169999  0.22687475
 -0.59744393 -0.03156332 -0.41709547  0.65037129  0.21225973  0.59789353
  0.52466565  0.06589658  0.03513684 -0.03935262 -0.17660299  0.44033291
  0.31144484  0.17798682  0.14529434 -0.04264758  0.30133852 -0.18661393
  0.2910152 ]
轮廓系数：0.042967527097460705

### 生成用户聚类结果信息

In [31]:
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")
print("label",  kmeans.labels_)
print("num_label",  len(kmeans.labels_))
print(kmeans.labels_[1])# test

轮廓系数：0.042967527097460705
label [35 17  6 17  2 14 25 17 26 12 21 37 26 35 37 20  1 35 36 35 36 35 23 36
 13 12 33 27 20 28  6  1  6 24 26  5  6  4 24  2  7 13 13  7 12 16 29 12
 16 25 21 35 28 37 24  6 24 33  1  6 19  6  5 14 14  6 24  5 26 11 12  9
 21  7 23 23  6  4 29 20 25  6  6 38  1  6 16  7  6  3 20  4 38  0 14 35
 11 33  5  7 12 21 31 28  7 16  1 37  6 22 34  7 35 33 13 37 38  6  6  8
 12 13 35 22 23 13 14 38 29  6  1 17 34  6 34 16 35 12 17 25  7  4  5 10
  7 36 35 26 28 35  6  9  4 17 12 33 17  3 35 11 13 12  1 24 37 11 17 19
 33 24 21 12 15  2  1 23  5 21 13  6 23  7 35 38  6 39  3  6 35 29 15  4
 17  7 26  1  4 12 21  7 14 37 16 30  3  7  9 35 38 13 19 12 32  7  4  3
 17 17 36  2 17 39 23  9  7 16 35  6 36 25 17 25 21 11 35 26  6 21 30  4
 24 28 38  3 12  7  6  1  6  7 19  3 24 24 24 12  2 11  6 17  3 24  1 22
 34 38 12  1 12  6 14  6 35 39  6 21  1 12 25  2 23 24  6 28  5 21  7 12
  4 14 14  7  8  7  8 20  4 19 38 19 12  6  7 20  1 16 24  5 16 35  7  2
 35 34 35 12  5 31 12 21 38  4 17 26  1  6  7 17  5 12 37 19 17 25 14  2
 29 16  4 24  6 33  2 21  6  4 21 11 21 38  6 20  7  7  4  7  7  5 28  6
 37 37 20  4 38 20 21  3 28 16 35 19 26 12 38  7 19 22 38  4  7 36 39 37
  5  8  7 39 30 35 21  7 35 37 12  6  6  7  6  3 24 16  6 26  7 34 25 37
 30  5  7 20  6 30 20 35 21 29 16 21 34  1 30 35 14 33 38  4 35 35  1  4
 15 25 37 19 39 19  7 23 19 38 32  2 17  6 29 20 25 17  1 39  4  4 14 10
 35  4  6 30  4  7  4  1  6  4 31 34  6 14 12 36  6  7 35  9  6 26 23 38
 12  6  7  1 12 16  2  5 25  9 20 33 12  4  6  7 35 38 38 28 20  4 26 12
  6  6  1  9  8  2  0  4 39 34 12 38 12  7 32 35 20 17 17 29 29  7  5 35
 35  7  3 21 37  4 29 35 37  5 36  2  5 35  7 35 23 34  7 16 24 37 17 11
  4 38  7  6 22  7 35 21 20  1  7 37 37 33 35 12 26 16  4 23  4 35 25 34
 24  6 14 19 21  7 25 12  7 20  7 23 18 26 14 12  5  7  9  7 35  4 35 28
  4 35 37 33  5 16 24 21  4  2 11 22  7 34 38  7  4 36  6 35  3 16  2  2
 21 35 35 21 12 20 39  6 12 38  6  1 38 33  7  6 38  4  6  7 34  4 24  5
 20  1 32 21 21 28 29 35 11 26 33 36 23 23 23 26 34  6  5 26 35 35 26  1
 33 20  3  3 13 27  2 35  1 17  8 35  7  4  7 11 17  5 14 35 17 21 14 25
  6  6  4  6 20  1 20 24 25 19 15  6  2 12 24 35 24 12 38 37 33  4 12 17
  1 29  3 14 17 39 14 15 37 15 21  6  2 34  7 34 12  7 30 30 29 20 20 37
  6  6  3 33 37  6  7 16 19 26  1  1]
num_label 756
17

### 同步存储聚类后的用户向量 和 映射关系

In [33]:
# 因为聚类了所以不用考虑原来用户id，类别顺序就是新的id
filename = "../kuairec/{}clusters_FeatureVectors.dat".format(n_clusters)
with open(filename, 'w', newline='') as f:
    for i in range(centers.shape[0]):
        new_line = str(i) + '\t' + ';'.join(str(centers[i, :]).strip('[').strip(']').split()) + '\n'
        f.write(new_line)
print("done")

#label需要类别顺序与用户id对应，而不是与用户向量的index对应
label_dict = {}
for i in range(len(kmeans.labels_)):
    label_dict[str(data_user[i])] = int(kmeans.labels_[i])

print(label_dict)
import json
filename = "../kuairec/{}clusters_labels.json".format(n_clusters)
with open(filename, 'w') as f:
    json.dump(label_dict, f)
print("done")

done
{'0': 35, '1': 17, '2': 6, '3': 17, '4': 2, '5': 14, '6': 25, '7': 17, '8': 26, '9': 12, '10': 21, '11': 37, '12': 26, '13': 35, '14': 37, '15': 20, '16': 1, '17': 35, '18': 36, '19': 35, '20': 36, '21': 35, '22': 23, '23': 36, '24': 13, '25': 12, '26': 33, '27': 27, '28': 20, '29': 28, '30': 6, '31': 1, '32': 6, '33': 24, '34': 26, '35': 5, '36': 6, '37': 4, '38': 24, '39': 2, '40': 7, '41': 13, '42': 13, '43': 7, '44': 12, '45': 16, '46': 29, '47': 12, '48': 16, '49': 25, '50': 21, '51': 35, '52': 28, '53': 37, '54': 24, '55': 6, '56': 24, '57': 33, '58': 1, '59': 6, '60': 19, '61': 6, '62': 5, '63': 14, '64': 14, '65': 6, '66': 24, '67': 5, '68': 26, '69': 11, '70': 12, '71': 9, '72': 21, '73': 7, '74': 23, '75': 23, '76': 6, '77': 4, '78': 29, '79': 20, '80': 25, '81': 6, '82': 6, '83': 38, '84': 1, '85': 6, '86': 16, '87': 7, '88': 6, '89': 3, '90': 20, '91': 4, '92': 38, '93': 0, '94': 14, '95': 35, '96': 11, '97': 33, '98': 5, '99': 7, '100': 12, '101': 21, '102': 31, '103': 28, '104': 7, '105': 16, '106': 1, '107': 37, '108': 6, '109': 22, '110': 34, '111': 7, '112': 35, '113': 33, '114': 13, '115': 37, '116': 38, '117': 6, '118': 6, '119': 8, '120': 12, '121': 13, '122': 35, '123': 22, '124': 23, '125': 13, '126': 14, '127': 38, '128': 29, '129': 6, '130': 1, '131': 17, '132': 34, '133': 6, '134': 34, '135': 16, '136': 35, '137': 12, '138': 17, '139': 25, '140': 7, '141': 4, '142': 5, '143': 10, '144': 7, '145': 36, '146': 35, '147': 26, '148': 28, '149': 35, '150': 6, '151': 9, '152': 4, '153': 17, '154': 12, '155': 33, '156': 17, '157': 3, '158': 35, '159': 11, '160': 13, '161': 12, '162': 1, '163': 24, '164': 37, '165': 11, '166': 17, '167': 19, '168': 33, '169': 24, '170': 21, '171': 12, '172': 15, '173': 2, '174': 1, '175': 23, '176': 5, '177': 21, '178': 13, '179': 6, '180': 23, '181': 7, '182': 35, '183': 38, '184': 6, '185': 39, '186': 3, '187': 6, '188': 35, '189': 29, '190': 15, '191': 4, '192': 17, '193': 7, '194': 26, '195': 1, '196': 4, '197': 12, '198': 21, '199': 7, '200': 14, '201': 37, '202': 16, '203': 30, '204': 3, '205': 7, '206': 9, '207': 35, '208': 38, '209': 13, '210': 19, '211': 12, '212': 32, '213': 7, '214': 4, '215': 3, '216': 17, '217': 17, '218': 36, '219': 2, '220': 17, '221': 39, '222': 23, '223': 9, '224': 7, '225': 16, '226': 35, '227': 6, '228': 36, '229': 25, '230': 17, '231': 25, '232': 21, '233': 11, '234': 35, '235': 26, '236': 6, '237': 21, '238': 30, '239': 4, '240': 24, '241': 28, '242': 38, '243': 3, '244': 12, '245': 7, '246': 6, '247': 1, '248': 6, '249': 7, '250': 19, '251': 3, '252': 24, '253': 24, '254': 24, '255': 12, '256': 2, '257': 11, '258': 6, '259': 17, '260': 3, '261': 24, '262': 1, '263': 22, '264': 34, '265': 38, '266': 12, '267': 1, '268': 12, '269': 6, '270': 14, '271': 6, '272': 35, '273': 39, '274': 6, '275': 21, '276': 1, '277': 12, '278': 25, '279': 2, '280': 23, '281': 24, '282': 6, '283': 28, '284': 5, '285': 21, '286': 7, '287': 12, '288': 4, '289': 14, '290': 14, '291': 7, '292': 8, '293': 7, '294': 8, '295': 20, '296': 4, '297': 19, '298': 38, '299': 19, '300': 12, '301': 6, '302': 7, '303': 20, '304': 1, '305': 16, '306': 24, '307': 5, '308': 16, '309': 35, '310': 7, '311': 2, '312': 35, '313': 34, '314': 35, '315': 12, '316': 5, '317': 31, '318': 12, '319': 21, '320': 38, '321': 4, '322': 17, '323': 26, '324': 1, '325': 6, '326': 7, '327': 17, '328': 5, '329': 12, '330': 37, '331': 19, '332': 17, '333': 25, '334': 14, '335': 2, '336': 29, '337': 16, '338': 4, '339': 24, '340': 6, '341': 33, '342': 2, '343': 21, '344': 6, '345': 4, '346': 21, '347': 11, '348': 21, '349': 38, '350': 6, '351': 20, '352': 7, '353': 7, '354': 4, '355': 7, '356': 7, '357': 5, '358': 28, '359': 6, '360': 37, '361': 37, '362': 20, '363': 4, '364': 38, '365': 20, '366': 21, '367': 3, '368': 28, '369': 16, '370': 35, '371': 19, '372': 26, '373': 12, '374': 38, '375': 7, '376': 19, '377': 22, '378': 38, '379': 4, '380': 7, '381': 36, '382': 39, '383': 37, '384': 5, '385': 8, '386': 7, '387': 39, '388': 30, '389': 35, '390': 21, '391': 7, '392': 35, '393': 37, '394': 12, '395': 6, '396': 6, '397': 7, '398': 6, '399': 3, '400': 24, '401': 16, '402': 6, '403': 26, '404': 7, '405': 34, '406': 25, '407': 37, '408': 30, '409': 5, '410': 7, '411': 20, '412': 6, '413': 30, '414': 20, '415': 35, '416': 21, '417': 29, '418': 16, '419': 21, '420': 34, '421': 1, '422': 30, '423': 35, '424': 14, '425': 33, '426': 38, '427': 4, '428': 35, '429': 35, '430': 1, '431': 4, '432': 15, '433': 25, '434': 37, '435': 19, '436': 39, '437': 19, '438': 7, '439': 23, '440': 19, '441': 38, '442': 32, '443': 2, '444': 17, '445': 6, '446': 29, '447': 20, '448': 25, '449': 17, '450': 1, '451': 39, '452': 4, '453': 4, '454': 14, '455': 10, '456': 35, '457': 4, '458': 6, '459': 30, '460': 4, '461': 7, '462': 4, '463': 1, '464': 6, '465': 4, '466': 31, '467': 34, '468': 6, '469': 14, '470': 12, '471': 36, '472': 6, '473': 7, '474': 35, '475': 9, '476': 6, '477': 26, '478': 23, '479': 38, '480': 12, '481': 6, '482': 7, '483': 1, '484': 12, '485': 16, '486': 2, '487': 5, '488': 25, '489': 9, '490': 20, '491': 33, '492': 12, '493': 4, '494': 6, '495': 7, '496': 35, '497': 38, '498': 38, '499': 28, '500': 20, '501': 4, '502': 26, '503': 12, '504': 6, '505': 6, '506': 1, '507': 9, '508': 8, '509': 2, '510': 0, '511': 4, '512': 39, '513': 34, '514': 12, '515': 38, '516': 12, '517': 7, '518': 32, '519': 35, '520': 20, '521': 17, '522': 17, '523': 29, '524': 29, '525': 7, '526': 5, '527': 35, '528': 35, '529': 7, '530': 3, '531': 21, '532': 37, '533': 4, '534': 29, '535': 35, '536': 37, '537': 5, '538': 36, '539': 2, '540': 5, '541': 35, '542': 7, '543': 35, '544': 23, '545': 34, '546': 7, '547': 16, '548': 24, '549': 37, '550': 17, '551': 11, '552': 4, '553': 38, '554': 7, '555': 6, '556': 22, '557': 7, '558': 35, '559': 21, '560': 20, '561': 1, '562': 7, '563': 37, '564': 37, '565': 33, '566': 35, '567': 12, '568': 26, '569': 16, '570': 4, '571': 23, '572': 4, '573': 35, '574': 25, '575': 34, '576': 24, '577': 6, '578': 14, '579': 19, '580': 21, '581': 7, '582': 25, '583': 12, '584': 7, '585': 20, '586': 7, '587': 23, '588': 18, '589': 26, '590': 14, '591': 12, '592': 5, '593': 7, '594': 9, '595': 7, '596': 35, '597': 4, '598': 35, '599': 28, '600': 4, '601': 35, '602': 37, '603': 33, '604': 5, '605': 16, '606': 24, '607': 21, '608': 4, '609': 2, '610': 11, '611': 22, '612': 7, '613': 34, '614': 38, '615': 7, '616': 4, '617': 36, '618': 6, '619': 35, '620': 3, '621': 16, '622': 2, '623': 2, '624': 21, '625': 35, '626': 35, '627': 21, '628': 12, '629': 20, '630': 39, '631': 6, '632': 12, '633': 38, '634': 6, '635': 1, '636': 38, '637': 33, '638': 7, '639': 6, '640': 38, '641': 4, '642': 6, '643': 7, '644': 34, '645': 4, '646': 24, '647': 5, '648': 20, '649': 1, '650': 32, '651': 21, '652': 21, '653': 28, '654': 29, '655': 35, '656': 11, '657': 26, '658': 33, '659': 36, '660': 23, '661': 23, '662': 23, '663': 26, '664': 34, '665': 6, '666': 5, '667': 26, '668': 35, '669': 35, '670': 26, '671': 1, '672': 33, '673': 20, '674': 3, '675': 3, '676': 13, '677': 27, '678': 2, '679': 35, '680': 1, '681': 17, '682': 8, '683': 35, '684': 7, '685': 4, '686': 7, '687': 11, '688': 17, '689': 5, '690': 14, '691': 35, '692': 17, '693': 21, '694': 14, '695': 25, '696': 6, '697': 6, '698': 4, '699': 6, '700': 20, '701': 1, '702': 20, '703': 24, '704': 25, '705': 19, '706': 15, '707': 6, '708': 2, '709': 12, '710': 24, '711': 35, '712': 24, '713': 12, '714': 38, '715': 37, '716': 33, '717': 4, '718': 12, '719': 17, '720': 1, '721': 29, '722': 3, '723': 14, '724': 17, '725': 39, '726': 14, '727': 15, '728': 37, '729': 15, '730': 21, '731': 6, '732': 2, '733': 34, '734': 7, '735': 34, '736': 12, '737': 7, '738': 30, '739': 30, '740': 29, '741': 20, '742': 20, '743': 37, '744': 6, '745': 6, '746': 3, '747': 33, '748': 37, '749': 6, '750': 7, '751': 16, '752': 19, '753': 26, '754': 1, '755': 1}
done

## 生成关系矩阵

### 读取聚类向量

In [34]:
import numpy as np
import pandas as pd

In [35]:
classfeatures = []
n_clusters=40
filename = "../kuairec/{}clusters_FeatureVectors.dat".format(n_clusters)
with open(filename, "r") as f:
    # f.readline()# 跳过第一行
    for line in f:
        line = line.split("\t")
        vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
        classfeatures.append(np.array(vec).astype(float))
classfeatures = pd.DataFrame(classfeatures)
classfeatures

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,1.234514,-1.134479,-2.139241,0.081660,0.088182,1.596037,-0.534101,0.264632,-0.368158,0.408276,...,0.631573,0.286932,0.724820,1.040064,0.202896,0.639498,-0.623963,-0.005060,-0.298177,0.174021
1,0.619910,0.628662,-0.478909,0.397068,-0.174410,0.610466,-0.148171,-0.217091,0.002874,0.130310,...,-0.070875,-0.067399,0.738853,0.286892,0.168845,-0.223317,-0.094673,0.210028,-0.194183,0.037655
2,-0.933046,-2.665365,-0.635043,0.506077,0.473218,1.138507,0.384849,-0.275622,-0.308900,0.431676,...,0.457016,0.048766,0.437788,0.157133,0.152402,0.166802,-0.077169,-0.384559,-0.137558,-0.076941
3,-0.213233,0.976379,-0.555207,-1.172111,-1.072626,0.997694,-0.431027,-0.181590,0.568963,0.538685,...,-0.187765,0.301984,0.055307,0.196133,-0.111981,-0.322724,0.471093,-0.292389,-0.244365,0.020392
4,-1.093890,-0.434123,-0.478626,-0.249474,-0.619944,0.952555,-0.160110,-0.167660,0.047363,0.183932,...,0.049867,-0.044885,0.449958,0.180522,0.116718,-0.070752,-0.016657,-0.003095,-0.182890,0.116007
5,-1.890847,-0.678654,-0.356953,0.168860,0.261664,0.676573,-0.388257,-0.826789,-0.386425,0.390474,...,0.184596,0.159029,0.237255,0.172428,0.166607,0.195556,-0.019350,-0.119278,-0.011395,-0.091416
6,-0.578887,0.103906,-0.616420,-0.077095,-0.172271,0.614503,0.151924,-0.212865,0.062930,0.226152,...,-0.045150,-0.089258,0.411604,0.113959,0.101263,-0.085410,0.069805,0.074760,-0.131812,0.019458
7,-0.869386,-0.966691,-0.818913,-0.018851,-0.107506,0.777620,0.255634,-0.142188,0.120936,0.154727,...,-0.024470,-0.197233,0.365108,0.041607,0.018302,-0.090894,0.152583,-0.001090,-0.156083,-0.023403
8,1.727130,-1.467327,-0.114117,0.133668,0.001995,0.862231,-0.313997,-0.252737,-0.504504,0.336195,...,-0.179039,-0.558212,0.310052,0.182629,0.638318,-0.748677,-0.555011,-0.157711,0.484793,-0.361209
9,1.945696,0.495377,1.406364,1.592012,-0.583136,1.421764,-0.381896,0.355084,0.751263,0.398655,...,0.511604,-0.412006,0.705314,0.154032,0.538699,-0.754711,-0.272411,0.102137,0.278322,-0.103258
10,-0.536093,4.289558,1.217018,1.212625,-0.515898,0.470107,0.823703,-0.058113,0.650169,0.445306,...,-0.168465,0.333200,0.875651,0.293009,0.696795,0.155645,0.063325,0.948522,0.549273,0.317659
11,-1.616178,2.002504,-0.692274,0.303559,-0.163014,0.682761,0.216584,-0.299371,-0.039035,-0.018225,...,0.038314,-0.203906,0.137882,0.194298,0.043180,-0.222619,0.201885,0.221425,-0.025463,-0.005209
12,-0.491466,-1.158700,-0.007178,0.301836,-0.065465,0.553502,0.059747,-0.331295,-0.160499,0.492647,...,0.188019,0.035782,0.407827,0.231133,0.161937,-0.275308,-0.041322,-0.062298,-0.051388,-0.034755
13,1.217780,-0.488122,-1.232893,-0.350195,-0.322298,0.548216,0.667850,0.776683,-0.317901,-0.231007,...,0.279288,-0.418782,0.316533,0.503484,-0.412047,-0.136520,-0.060034,-0.141754,0.058145,-0.019540
14,-0.713335,1.278938,0.567569,0.476726,-0.970720,1.362770,-0.598788,-0.081262,0.528833,0.203685,...,0.285645,-0.105793,0.627484,0.279236,0.221026,-0.192437,0.223846,0.262010,0.004606,0.185350
15,2.465250,-1.102920,0.246141,2.032429,0.389563,1.563876,-0.590156,-0.128852,-0.154340,0.178903,...,0.249498,-0.090292,0.443880,0.053309,0.794589,-0.286219,-1.047273,-0.258714,0.281618,-0.644773
16,0.621780,-0.980538,0.241330,-0.150472,0.070421,0.580968,-0.220131,-0.463793,-0.746597,1.077564,...,-0.099452,-0.258084,-0.035526,0.158968,0.442913,-0.400253,-0.286403,0.160198,0.075313,-0.049517
17,-0.434385,0.175772,-0.952692,0.424118,-0.086876,1.006010,-0.480917,-0.150594,-0.117672,-0.193858,...,-0.056078,-0.227236,0.423802,0.287939,0.094101,0.041532,-0.025120,0.182123,-0.201476,-0.002977
18,-3.637303,8.623386,-0.137583,1.089495,0.161349,0.569083,1.256479,-0.378296,0.126848,0.515920,...,-1.146060,0.081830,-0.630847,0.621323,-0.006020,0.285823,-0.492379,0.164741,0.760240,-0.060119
19,-1.810342,1.072403,-0.766171,-0.658998,-0.808452,0.403100,0.056552,-0.332909,0.050790,-0.105657,...,-0.185448,0.029713,0.376079,0.197781,0.068096,-0.007221,0.125584,-0.078104,-0.136163,-0.002118
20,0.450444,-0.447982,0.543758,0.835642,-0.332303,0.889997,-0.224089,-0.078528,0.207885,0.421465,...,0.256032,-0.151743,0.503812,0.103463,0.415614,-0.377567,-0.295798,0.071939,0.059189,-0.104188
21,-1.686773,-1.624404,-0.945310,0.027317,-0.245785,0.732558,0.177240,0.025108,0.059351,0.417650,...,0.048497,-0.278145,0.177498,0.068633,0.028968,-0.148680,0.004999,0.050551,0.067130,0.061083
22,3.031480,-0.412028,0.414288,-0.009285,0.054401,0.995661,-0.938105,-0.270304,-1.089204,1.504148,...,-0.955925,-0.797574,-0.410894,0.027108,0.837746,-1.111491,-0.792177,0.452694,0.443898,-0.397009
23,0.426054,-1.880952,-0.437862,0.602551,0.147286,1.036645,0.173568,0.298167,0.255686,0.578974,...,-0.011429,-0.569690,0.335072,-0.074174,0.124368,-0.193840,0.098147,0.048785,0.067508,-0.176924
24,-0.322830,-0.485812,-0.722458,0.879140,-0.186203,0.585183,-0.362063,0.003855,-0.075051,0.253711,...,-0.013562,-0.189942,0.475444,0.073267,0.164981,-0.352960,-0.244794,0.013447,0.236007,-0.030964
25,0.510996,-1.009641,-0.922615,-0.162523,0.255674,0.859222,0.742057,0.094536,0.078668,0.277702,...,-0.201864,-0.500818,0.352550,-0.130795,0.053483,-0.080223,0.164036,0.001243,-0.017299,-0.214307
26,-0.376039,-1.136427,-1.122779,0.321841,-0.019124,0.431366,-0.013266,-0.257816,-0.280417,0.500930,...,-0.205468,0.064314,0.795368,0.184684,0.036103,-0.299380,-0.103093,0.589521,-0.273419,0.348739
27,0.709678,-0.754801,-1.282631,0.333868,0.953274,0.828396,0.511863,-0.609595,0.467484,1.241980,...,0.377791,-0.277351,1.963415,0.494400,0.083353,-0.244702,0.843996,0.628347,-1.268367,0.661985
28,-0.267579,0.585644,-0.348870,-0.653045,-0.745348,0.500339,0.489611,-0.233415,0.541491,-0.243876,...,0.136712,0.217635,0.746757,-0.266204,0.421020,0.147814,-0.218620,-0.053196,-0.798530,-0.230353
29,1.700566,0.298271,-0.166209,0.719624,-0.185501,1.061248,-0.343872,0.035856,-0.080228,0.349310,...,-0.071143,-0.499954,0.561466,-0.153189,0.539395,-0.700306,-0.654577,0.103460,0.464228,-0.403088
30,-1.316965,-0.602651,0.828042,0.847036,-0.023331,1.125812,-0.132909,-0.218559,0.320633,0.586501,...,0.914801,0.248588,0.900498,0.541318,0.385098,0.096937,0.095807,-0.058405,-0.083720,0.255531
31,-0.293587,0.020376,-0.085837,2.455210,-0.342717,-0.520275,0.676579,-0.088677,0.696908,0.452561,...,0.213822,0.164432,-0.332630,0.240278,-0.042858,-0.053495,0.026857,0.059204,0.184168,-0.010572
32,2.261599,1.063581,0.385823,-1.126268,-0.971933,0.973989,0.943806,0.187625,0.457649,-0.173957,...,0.425754,-0.357751,0.940795,-0.006652,0.001868,-0.074092,-0.199854,-0.562996,-0.450879,-0.105159
33,-0.957431,-1.232708,-0.837755,-0.128514,0.103507,1.122104,0.683285,0.335229,0.528747,0.393283,...,0.184424,-0.611900,0.355091,-0.306191,-0.117802,0.336530,0.688186,-0.153891,-0.117190,-0.141792
34,-1.810910,0.708047,-0.279831,0.660874,0.061815,0.969688,-0.567920,-0.247278,0.079154,-0.070096,...,-0.075482,-0.589953,0.394158,0.159473,0.021619,-0.225761,0.149131,0.004359,0.056684,0.167578
35,0.158406,-0.429681,-0.430878,-0.127464,-0.200938,0.689328,0.091630,-0.161004,0.060126,0.443778,...,-0.104364,-0.092637,0.383231,0.108393,0.166887,-0.224374,-0.040159,0.059529,-0.165360,-0.010678
36,0.984285,-0.858708,-1.262758,0.065360,0.309799,0.636156,0.340291,-0.328756,0.004954,-0.149752,...,-0.004581,0.173256,1.018137,0.221728,0.085780,0.020436,-0.108560,0.367144,-0.889419,0.205313
37,1.677550,-0.162572,-0.665970,-0.246521,-0.133725,0.747207,0.386832,-0.107609,0.173643,-0.007023,...,-0.166104,-0.223090,0.623105,-0.235754,0.332087,-0.305279,-0.295826,-0.022420,-0.444687,-0.317938
38,-2.190020,-0.041553,-0.489164,0.333774,-0.172497,0.576508,0.250624,-0.303989,0.202827,0.242376,...,0.203864,-0.042519,0.280218,-0.100859,0.172330,0.042138,0.114861,-0.055719,0.043196,-0.088828
39,-1.289371,1.330711,0.067625,-0.681957,-0.771700,0.226875,-0.597444,-0.031563,-0.417095,0.650371,...,-0.039353,-0.176603,0.440333,0.311445,0.177987,0.145294,-0.042648,0.301339,-0.186614,0.291015

### 生成W

In [36]:
import numpy as np
import json
classfeatures = np.array(classfeatures)
n = len(classfeatures)
sparsityLevel = int(n/2)
W = np.zeros(shape=(n, n))

for i in range(n):
    sSim = 0
    for j in range(n):
        sim = np.dot(classfeatures[i], classfeatures[j])
        W[i][j] = sim
        sSim += sim
    W[i] /= sSim
SparseW = W

#小于阈值的置为0
if sparsityLevel > 0 and sparsityLevel < n:
    for i in range(n):
        similarity = sorted(W[i], reverse=False)
        threshold = similarity[sparsityLevel]
        for j in range(n):
            if W[i][j] <= threshold:
                SparseW[i][j] = 0
        SparseW[i] /= sum(SparseW[i])
# for i in range(len(SparseW)):
    
#     print(sum(SparseW[i]))

for i in range(n):
    # SparseW[i][i] = 0
    # if sum(SparseW[i]) != 0:
    #     SparseW[i][i] = np.linalg.norm(SparseW[i]) ** 2 / sum(SparseW[i])
    # else:
    SparseW[i][i] = 1
    SparseW[i] /= sum(SparseW[i])
print("SparseW --Opt", SparseW)

# for i in range(len(SparseW)):
    
#     print(sum(SparseW[i]))
#存储为json格式
# import json
filename = "../kuairec/SparseW.json"
with open(filename, 'w') as f:
    json.dump(SparseW.T.tolist(), f)
print("save SparseW.json")
# W = np.load('./NYC/SparseW.npy')

SparseW --Opt [[0.54715101 0.         0.03993592 ... 0.02281945 0.         0.        ]
 [0.01854066 0.51592928 0.         ... 0.02644095 0.         0.        ]
 [0.04164865 0.         0.53114621 ... 0.         0.01993519 0.        ]
 ...
 [0.03315854 0.01912439 0.         ... 0.51980124 0.         0.        ]
 [0.         0.         0.02773319 ... 0.         0.52182692 0.0207681 ]
 [0.         0.00989012 0.         ... 0.         0.02305954 0.52665775]]
save SparseW.json